### ISSUE TITLE
IndexedDB: unnecessary "app" index

### ISSUE THREAD

**Issue by nolanlawson** [techfort/LokiJS#103]
Hey, cool library. :) I was looking through your IndexedDB implementation, and I have a suggestion.

You're storing an `appkey` as well as an `app` and a `key`, with the `appkey` being [a composite of the two](https://github.com/techfort/LokiJS/blob/b399d08a0de8059005e20960fd6e6cfa5a2bbca2/src/lokiIndexedAdapter.js#L409-L421). That's a good strategy, especially since IE/Safari don't support complex keys, but that means you can actually get rid of the `app` index altogether. To search by app, you would just need to do a range query like so:

```js
IDBKeyRange.bound(app, app + ',\uffff'); 
```

(The `'\uffff'` is to guard against any apps with commas in their name.)

Then you would just use the `appkey` index instead. Saves you the time of creating/updating an unnecessary index!

**Comment by obeliskos** [comment]
Interesting idea... thanks!  I am sure you are familiar with the metal behind this so I trust this works.

In order to implement it I would have to do an indexeddb version upgrade so I may add this to list and when I need to break compatibility try this out along with any other changes.

Hopefully I will clean that adapter up soon, possibly after we refine our adapter interface more.

Thanks again,
Dave

**Comment by nolanlawson** [comment]
No need for a version upgrade. :) Since you're subtracting an index rather than adding one, all you have to do is just remove the `createIndex()` and stop using the old index. You can also stop storing the `app` value in the doc (just store `appkey`) and save a bit of space that way.

Older clients will never know the difference. Their databases may be slightly larger than newer clients, but you can still treat them the same way because they just have "more" information than what you need. We have used this trick many times in PouchDB to avoid migrations!

**Comment by obeliskos** [comment]
Even better... I'll definitely have a look at this the next time I am working on that adapter.  And yes, avoiding having to do an idb database upgrade makes it much easier :)

Great work on pouchdb... you have some very informative blog posts as well!

Dave

**Comment by nolanlawson** [comment]
Thanks a lot! :D
