### ISSUE TITLE
Asynchronous Collection Loading and Searching

### ISSUE THREAD

**Issue by robhicks** [techfort/LokiJS#104]
I'm having problems searching. 
I am using promises to search a collection which is asynchronously loaded. In my controller have the following function which is called to build a list of projects, which is injected into my view using controllerAs:
```javascript
function getProjects() {
    var searchParams = angular.extend({}, $scope.search);
    if (!searchParams.title) delete searchParams.title;
    if (searchParams.state === 'ANY') delete searchParams.state;
    dbs.getProjects().then(function(projects) {
      Projects.list = projects.find(searchParams);
      Projects.count = Projects.list.length;
      console.log('list',Projects.list);
    });
  }
```
The controller uses a service (dbs) to get or load the projects collection:
```javascript
var db = new loki('admin.json');
var projects = db.getCollection('projects') || db.addCollection('projects', {indices: ['id','access','type','state','title']});
this.getProjects = function() {
    return $q(function(resolve, reject) {
      if (projects.data.length > 0) return resolve(projects);
      ps.getProjects({page: 1, pagesize: 1000})
        .then(function(projectsAtomFeed) {
          var projectEntries = projectsAtomFeed.getEntriesByType('relations/project');
          projectEntries.forEach(function(entry) {
            projects.insert({
              id: entry.id.replace('urn:rel+uuid:project/',''),
              title: entry.title,
              description: entry.summary.projectDescription,
              access: entry.summary.projectAccess,
              type: entry.summary.projectType,
              state: entry.summary.state
            });
          });
          return resolve(projects);
        });
    });
  };
```
So if the projects collection is already loaded, it returns immediately and is available for searching.
My problem is the find method does not always work. For example, I never get correct results for "type". I suspect this has to do with the asynchronous nature of my code. 
What is the right way to asynchronously populate and then search a collection?

**Comment by obeliskos** [comment]
Without a sample I can attach a browser debugger to, the first thing I would recommend testing is removing some or all of your indices to see if it is a problem with index generation / usage.  Functionally your find operations should work the same whether indexed or not.  If it works without any indexes, you can add them back and see if it functions differently when indexed.

**Comment by techfort** [comment]
Hi, would you be able to create a plunker for this so i can give it a go?

**Comment by robhicks** [comment]
@techfort and @obeliskos Thanks for looking at this. 
I'll try to create  plunkr but I'll probably have to mock the data. I won't be able to get to it for a few hours.

**Comment by robhicks** [comment]
I haven't been able to get a plunkr working but I have discovered that find works for the first parameter of the search query only. Does LokiJs support compound filters? From the code, it appears so. However, if I find using a single filter, it works:
```javascript
projects.find({'access': 'OPEN'}) //works
```
But if I search based upon compound filters, it ignores everything after the first filter:
```javascript
projects.find({'access': 'OPEN', 'type': 'INDEXING'}) //ignores type filter.
```
On a hunch, I removed the indices. That didn't help. It still ignores all but the first filter.

My conclusion. I must be doing something wrong. Can you enlighten me?

**Comment by obeliskos** [comment]
Not implemented that notation yet but this should work : 

```javascript
projects.find({'$and' : [
  {'access' : 'open'},
  {'type' : 'INDEXING'}
]);
```
Will look into adding your (mongo) syntax above as comma separated implicit 'and' op.

We also support chaining if you don't need strict mongo compatibility, that might look like : 

```javascript
projects.chain().find({'access': 'open'}).find({'type': 'INDEXING'}).data();
```
Only one index is used for $and ops so make the first query expression the most likely to filter out records.

**Comment by robhicks** [comment]
@obeliskos Thanks for pointing me in the right direction! Do you want me to close this?

**Comment by obeliskos** [comment]
Since implementing the $and op, it seems the syntax you were attempting is probably the most common.  I will probably be adding support for that syntax soon if performance is not impacted severely.

Sure you can close this and/or create an issue for request of feature.  Otherwise I will close in a bit.
