### ISSUE TITLE
ReferenceError when linking to src/lokijs.js

### ISSUE THREAD

**Issue by miketahani** [techfort/LokiJS#105]
When I try to instantiate a new Loki database in the browser, I get a `ReferenceError: loki is not defined`.

Also breaks the example:

![screen shot 2015-03-17 at 5 10 10 pm](https://cloud.githubusercontent.com/assets/1015032/6700249/93bb1d5e-ccc8-11e4-91a3-5a07c1317729.png)

**Comment by obeliskos** [comment]
Waiting on Techfort to review this error. 

I can confirm I also get this on normal html script include (such as our example.html you mentioned).

**Comment by techfort** [comment]
OK i reverted some changes that were applied very recently which moved loki to an object called `thirdParty` preoperty of `window`. Works for me now, let me know if this is the case.

**Comment by obeliskos** [comment]
Seems to work good for me now

**Comment by techfort** [comment]
Closing this, @miketahani feel free to re-open if this does not work for you.

**Comment by miketahani** [comment]
Thanks!

**Comment by joegillon** [comment]
On Windows 7, I install via npm, then in js 

var db = new loki('loki.json')

gets ReferenceError: loki is not defined. Is there a trick to using this with Windows?

**Comment by techfort** [comment]
@joegillon  is there code you can share so i can help? i just want to rule out something trivial.

**Comment by joegillon** [comment]
Duh. Turns out it was trivial. Just needed to require it. Might want to 
put that step in your documentation between the npm install and the var 
instantiation. Keep you from being bothered by nitwits like me.

**Comment by techfort** [comment]
So I will! Closing this in the meantime. Happy Loki-ing!
