### ISSUE TITLE
Enhancement: Browser compatibility badge/tests.

### ISSUE THREAD

**Issue by tecfu** [techfort/LokiJS#107]
Hey Joe - love your project and really hope you succeed big.

I've just come across Loki in the last hour or so. A couple ideas:

- Browser compatibility badges would help new users get a sense of how well supported Loki is in the browser. https://ci.testling.com/ might be a good option. Its a bit hypocritical for me to mention this, because I haven't done it for my own projects. But I think it would benefit you.

- Add an "onChange" event for the Changes API

- I bet all the cool hipster kids in Nothern California would love you if you created a Loki/Flux Store object.

Just some thoughts. Hope this blows up.

**Comment by techfort** [comment]
Hey there, thanks a lot for the kind words! I was not aware of testling.com  i will definitely look into getting browser compatibility badges. 
Adding that "onChange" should be a straight forward and brilliant idea, will get on it asap.
I also admit my complete ignorance of Flux. I know what it is but never worked with it. I will take this opportunity to expand my knowledge on the subject!
Thanks a lot again for the very constructive feedback!

**Comment by jrhicks** [comment]
@tecfu @techfort - I've been thinking about how replication and lokijs could fit into the flux pattern quite a bit lately.  After my first implimentation I can say that flux slows down replicating 30,000 records .... I'm looking into some "almost flux" patterns and after facebook release their relay diagram today https://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html ... I'm guessing that they don't mind breaking pure-flux.

Its a bit of a work in progress, but here is the diagram I have so far - http://screencast.com/t/r0B2XYtSZx

**Comment by techfort** [comment]
@tecfu  @jrhicks I am going to spend the next few days familiarizing with flux. I suppose i dodged it all along because i was otherwise occupied but i definitely need to face the beast now. Nonetheless, if you feel like keeping this going with further information I will very much appreciate it.
