### ISSUE TITLE
React Flux Store

### ISSUE THREAD

**Issue by techfort** [techfort/LokiJS#109]
Create a flux store that utilises LokiJS.

**Comment by ArnoBuschmann** [comment]
I guess you mean a flux store for Reactjs? That would be interesting! Actually I just stumbled over LokiJS after reading http://jrhicks.github.io/replicate_architecture_ideas_for_react_flux_apps/index.html from @jrhicks.

As facebook points out, that reactjs is being used best with immutable data, so I wondered, if there is a meaningful way (I'm not sure if it even makes sense?) to combine LokiJS and Immutablejs https://github.com/facebook/immutable-js/ or similiar libraries for Reactjs such as Freezer https://github.com/arqex/freezer or Baobab https://github.com/Yomguithereal/baobab?

Also as I didn't got deeper into LokiJS yet, what is the preferred way to synchronise a LokiJS db between the browsers local storage and the server?

**Comment by techfort** [comment]
Hi Arno, the question makes sense, and i too have been wondering about data immutability as I like the concept. So for now I don't have an answer for that other than "I'm going to investigate this asap". 

As for remote syncing, there are a number of possibilities, mainly:
* use LokiJS's Changes API to post deltas to your server
* write your own PersistenceAdapter which persists to a remote server (look at [this](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters) )
* use Collection events to post calls to the server updating in real-time

If you have better ideas by all means I'm all ears, and thanks for the feedback!

**Comment by ArnoBuschmann** [comment]
Basically the other libraries I mentioned are mostly based on keeping the entire appstate in one JS and/or immutable object and provide cursors. These cursors are passed to Reactjs components, together with event emitters, so if the data changes, the React component rerenders. Here I see similarities to your views in LokiJS.

Now these libraries are not meant to persist data on the server, just to handle the appstate. But as everyone (including me:) is thinking about isomorphic apps these days, LokiJS seems to be a great fit as it runs in both environments the same way already.

I will have to play a bit more with LokiJS though to get a more detailed idea. Immutability was just the first thing that came to mind.

**Comment by jrhicks** [comment]
@ArnoBuschmann Keep us posted on what you come up with!  I'm thinking about making the case that writing to a database is NOT mutating state.  Its something different, its writing to a database!  The database in turn has listeners that can trigger actions, the actions can dispatch to stores, and the stores can update state and pass immutable state to the views for their re-rendering pleasure.

**Comment by ArnoBuschmann** [comment]
@jrhicks Thanks for joining and clarification. I completely agree, that writing to a DB is not mutating state.
> The database in turn has listeners that can trigger actions

I just saw that collections emit events on change, does that apply for views too? That would be neat indeed to update stores on LokiJS-view-changes.

**Comment by jrhicks** [comment]
I'm not 100% on the LokiJS events, thats question is best for @techfort.  I would like to clarify that the LokiJS-view-changes would update the stores through the typical action->dispatch->store flux pattern.

<img src="http://jrhicks.github.io/replicate_architecture_ideas_for_react_flux_apps/rd.png">

**Comment by techfort** [comment]
@ArnoBuschmann @jrhicks here's my problem. I appreciate the value of immutability and i am a fan of it. In fact, i will admit that if LokiJS had been developed today from scratch it would contain a lot more functional programming /FRP code than it does now AND it would definitely make use of immutable structures.

Today on twitter I asked a user what he would think of using LokiJS as a store and the answer was that he thought Loki was too complicated, that a JS map object + some helpers would do for a flux store, and also that he was pro-immutability (implying LokiJS breaks immutability). I did not want to continue that discussion at 140 characters chunks, but I thought to myself that where LokiJS shines is in performance, handling hundreds of thousands, sometimes millions of records and being fast at manipulating them. I actually shivered at the prospect of handling 200k records with a big JS object. Obviously the person in question never had a case for maintaining large data sets.
All of this to confirm what you two have just agreed upon: writing to a DB is not the same as mutating state.

As for dynamicview events: DynamicView reacts to Collection events more than it emits events. However, dynamicview can re-materialize the data contained in it lazily or eagerly. When the view is recomputed (and the data is now available) it emits a 'rebuild' event, to which you can react.
Other than that, DynamicView reacts to insert/update/delete events in the underlying collection and recomputes the indexes, but doesn't necessarily rematerialize the view. This can be done explicitly by calling the data() method on it. Either way, if LokiJS doesn't already 100% do what you want it to, it's at the very least only a few lines of code away from it. Hope this helps!

**Comment by jrhicks** [comment]
@techfort I've been studying the full-stack link that the twitter user links to: https://blog.rotenberg.io/million-user-webchat-with-full-stack-flux-react-redis-and-postgresql/ ... Its hard to tell from his diagram at first glance, but the components are actually initiating actions by writing to PostgreSQL and the actions are being triggered through PostgreSQL triggers!  Its almost identical to what we have come up with, but without the round trip to the server.

**Comment by techfort** [comment]
@jrhicks exactly, thank you for making me feel less stupid :) I think LokiJS can break new ground towards a solid architecture. We avail of the changes API: it means we can keep trying to get the client-side store and the server in sync until it's successful (which in most cases it's upwards of 99.9% of comms) and given LokiJS's meta object contained in each record you can even implement a "last write wins" type-of-logic on the server to avoid re-applying deltas. Lastly as you pointed out, redis is involved.
As far as I'm concerned, LokiJS is ready to be a redis replacement. It installs with npm, you don't need external binaries and you can use the same monitoring node.js tools you're accustomed to as a sys admin. It's isomorphic with the client-side db you're going to put in place. It uses nosql jargon, with a natural flow to anybody who uses JS daily. It guarantees fantastic peroformance on JS standards, I doubt it would stack up to redis but neither it would represent a bottleneck, and the advantages far outweigh the cons.
I wish I had these kind of tools to develop a solid scalable web app years ago instead of having to swear at LAMP stacks on rusty boxes.

**Comment by tecfu** [comment]
+1

**Comment by ArnoBuschmann** [comment]
@jrhicks Yes, that got clear in your first comment indeed and describes nicely how to "connect" LokiJS to the React infrastructure (including  for example Immutable/Freezer/Baobab).

@techfort The views rebuild event sounds very interesting then because I could kind of "observe" the db with my custom criteria (view) and use that event to initiate an action, that triggers the store to update from the view. It's nicely reactive and I wouldn't have to query the DB randomly to check for changes. It makes a big difference to collection change events.

How could I access the views rebuild event specifically?

**Comment by techfort** [comment]
DynamicView - like Collection and Loki itself - is a LokiEventEmitter. Which is nothing but a streamlined minimalist implementation of EventEmitter. So you access a view rebuild event by doing:
```javascript
var dv = myColl.addDynamicView('myDv');
// apply finds etc.
dv.on('rebuild', callback)
```
Hope this helps!

**Comment by ArnoBuschmann** [comment]
@techfort Yup, thx! *heads off to play with it* :)

**Comment by techfort** [comment]
good luck! I'm on GMT so i'm off to bed soon, feel free to drop create
issues if you encounter problems.

**Comment by jrhicks** [comment]
@techfort I'm definately still working on trying to figure out how to fit LokiJS into flux.   Admittedly, I'm all over the place on my ideas.  I've implimented it a few different ways, if this latest way works out well ... I'm going to share it.

**Comment by jrhicks** [comment]
@techfort tha latest incarnation looks like this <img src="http://content.screencast.com/users/jrhickscteh/folders/Jing/media/11cf0bdf-09c0-4fb1-bb62-16b62d168390/2015-03-23_1321.png">

The LokiDB lives inside a flux store, and replicate is best described as a "worker" that creates actions in the background.

**Comment by techfort** [comment]
That's awesome. I'm getting more and more into Flux, I have quite a few off
the walls ideas for Loki in this respect but I'm going to hold back till i
have gathered an intimate knowledge of the architecture. Meanwhile, thanks
a lot for your efforts!

**Comment by techfort** [comment]
@jrhicks that's great, you materialized where my mind was going. The Store would provided the equivalent of an interface to Loki, possibly with that architecture you may be able to satisfy immutability too - am I wrong?

**Comment by jrhicks** [comment]
@techfort - Yes, the convention is for stores to wrap their returned data in immutability.  So if you constrained the components access to db throught the store ... then your good.

**Comment by techfort** [comment]
@jrhicks well then it seems to me like we're flying!

**Comment by jrhicks** [comment]
@techfort - I may not actually undertand this part of flux well enough though.  I need to study more.

**Comment by arqex** [comment]
Hi guys,

Freezer author here, you are having a really interesting conversation :)

Using a replica of the server db in your app can transform how flux applications store work, but it is tricky to make it work with immutable structures. 

If you listen to the view 'rebuild' method I suppose you are thinking to reset your store with the updated data. That would make a completely new immutable store, and all the reactjs components will re-render even if the data is the same, because the immutable store has been re-created and it is different from the previous one.

We should either only update the part of the store that has changed or create a something that compares the db data and the store data before updating the store.

Thinking from the freezer point of view, maybe it is possible to save what is the source of the data inside the store. On a db view rebuild, we check if the new data is different from the source freezer has saved and, if they are not, don't rebuild. This would work if the db reuses the JS objects for the unchanged data on view rebuild. Is it that way?

**Comment by techfort** [comment]
@arqex cool lib Freezer - got my star some time ago :) I think the last part of your post makes perfect sense. I'm not an expert in the Flux architecture so I may be a bit inaccurate here, but if I understand the use case correctly (and especially following the model illustrated by @jrhicks ) then Loki would sit "inside" the store (so basically Freezer would provide exposure to LokiJS data). Looking at the docs for Freezer, would this sound completely crazy:
```javascript
/* assuming a dynamicview called lokiView, 
   a store called freezerStore containing an object called lokiView
   and a function notDeepEqual which returns if two objects are not deepEqual
  */
lokiView.on('rebuild', function () {
  if (notDeepEqual(lokiView.data(), freezerStore.get().toJS)) {
    freezerStore.get().lokiView.update(lokiView.data());
  }
})
```

**Comment by arqex** [comment]
Interesting thoughts! Well, after thinking a bit I wouldnt include Loki's view inside a freezer store.

First, deep comparision is too expensive when talking about performance, and second and more important, It is not needed because in my opinion a Loki's view is already can act like an immutable store without the help of an external library. You need to use Loki's methods to access and update its data, so you can use it directly with `on('rebuild')` to re-render react components like if it was the flux store. Basically it is the same way that freezer works.

What I was thinking about is, since freezer or baobab make really easy to track changes in deep data nodes, convert the data of the view to freezer data ( db should be outside the store ) and any modification on that data should trigger also the db update. Maybe I am thinking too much and making things overcomplex, but since you were talking about that I need to push all those thoughts out of me :D

**Comment by ArnoBuschmann** [comment]
A current problem of realizing some sort of "advanced" isomorphism is to have the same state available both, on client and server side. Right now most solutions are like providing just an "initial state" server side to render the first page and then handing over to the client to process the ongoing state.

Now the guys from Netflix described a use case, where they need the ongoing state on the server side, namely then, when the mobile connection got lost, the client reconnects and wants to proceed where he/she left.

Also we can think about the "offline first approach", where an app could proceed running offline during temporary mobile connection loss.

That's the moment, I think, where @arqex 's suggestion fits in. Kepping track of ongoing changes and update/sync the database on both (client/server) sides.

Following the Javascript Jabber about GraphQL and Relay http://devchat.tv/js-jabber/152-jsj-graphql-and-relay-with-nick-schrock-and-joe-savona- they introduce a new dimension of flexibility when they say: "It doesn't matter if you are on the server or the client, you can always define from where you want to render."

**Comment by techfort** [comment]
@arqex good points about performance of deep-equal scans, however I wonder if loki's meta object wouldn't come to the rescue here? each record has a `meta { created, updated, revision }` which means you'd only need to check if the two `revision` attributes are equal to establish that they still are. Surely that would save a lot of time? Plus you won't always be so unlucky that the last record in the view is the changed one, you can break the loop at the first difference encountered and just freeze the new `view.data()` array. How does it sound?

@ArnoBuschmann you know the concept sounds really interesting, futuristic even. I'd be lying though if i said i really understand how to implement this. I imagine client and server containing two parallel streams of states and the client being able to keep going on its own or referring to the server for data. But this is all a bit fuzzy still, so maybe i'll listen to that javascript jabber first and revert. Thanks for the contributions so far everybody. Anybody has any concrete ideas how to go about implementing this store in the real world so :) ? @jrhicks @assafweinberg @obeliskos @tecfu @seriousme

**Comment by Bessonov** [comment]
I want to use LokiJS for holding a bunch of data to provide offline and filtering capability for a cordova app, because LokiJS seem to be great for this task. It would be nice if I could use LokiJS as a redux store to get common pattern to manage the state and filterable data in it. Is there any progress on this feature? Thanks!

**Comment by jrhicks** [comment]
Bessonv,

I think redux offers something called redux-saga that you can use to sync data between a store and an API.  Similarly it can be used to sync data between a redux-store and a large persistent store such as LokiJS.  So for example, when you navigate to a work order page it could pull the relevant data out of lokiJS and put it in the redux store.  This way redux store can remain relatively small and use all of its immutable features.

We built a mobile app with this pattern.  We eventually re-designed it to not use a large persistent store and sagas.  We found it better to design our application to provide domain features to limit what data a particular mobile user needed to work on.  This decreased sync times, it reduced mobile app complexity, and the increased mobile app usability (less data to navigate).

Good Luck

**Comment by Bessonov** [comment]
Hey, @jrhicks, we use currently `redux-persist` with LocalStorage. Can you please elaborate how it can help to replace a database? Sure, I can iterate trough data, but it's very limited.
