### ISSUE TITLE
collection.ensureIndex()

### ISSUE THREAD

**Issue by baseio** [techfort/LokiJS#111]
Hi,

A collection.ensureIndex(propertyName) method is mentioned in at the [Indexing-and-Query-Performance](https://github.com/techfort/LokiJS/wiki/Indexing-and-Query-Performance) page, but I see no documentation for it.
Experimenting a bit, this seems to be working:

```
var db = new loki();
var data = db.addCollection("data");
data.insert({name:"test", group:{id:1,name:"groupname"}});
(...)
data.ensureIndex({'group.id':true});
```

Correct?

Thanks!

j.

**Comment by techfort** [comment]
Yeah that seems fine. Ultimately we wanted to keep ensureIndex shielded from users in case we change its implementation, you can initialize the index by declaring the collection as:
```javascript
var data = db.addCollection('data', { indices: ['group.id'] });
```
Hope this helps!

**Comment by baseio** [comment]
super! Thanks!

**Comment by rob-baker** [comment]
Hi, is it possible to create an index after the collection has been created. I'm persisting that data using autosave and getting the collection by:

    db.getCollection('collection_name')

Thanks

**Comment by obeliskos** [comment]
If your index is binary index, you should be able to call : 
```javascript
  coll.ensureIndex("columnName");
```

**Comment by rob-baker** [comment]
Thanks
