### ISSUE TITLE
Cannot resolve module 'fs'

### ISSUE THREAD

**Issue by ArnoBuschmann** [techfort/LokiJS#112]
Just a hint, I stumbled over:

ERROR in ./~/lokijs/src/lokijs.js
Module not found: Error: Cannot resolve module 'fs' in /node_modules/lokijs/src
 @ ./~/lokijs/src/lokijs.js 179:45-58 723:16-29

Installing fs via
npm install fs
fixes it of course

**Comment by techfort** [comment]
That's weird, fs is built-in. what OS/node version are you using?

**Comment by ArnoBuschmann** [comment]
Ubuntu 14.04 LTS and Node v0.10.25 It's probably the Node version as I just saw 0.12.0 is the current one, that's a bit ahead.

**Comment by techfort** [comment]
Hey Arno,
i just installed 0.10.25 using nvm on a Ubuntu 14.04 LTS machine and all works ok - if i run npm test all tests are passed. I actually would stick to 0.10.33-35 because 0.11 and 0.12 use an unsupported version of v8 and performance is slower, so your set up is fine. It's probably down to the way you installed it, maybe you passed some config during the build that did not build/install fs?

**Comment by ArnoBuschmann** [comment]
Hey Joe, thanks for your hints on different Node versions! It's good news all your tests passed :) so I'll close this issue now. Actually I don't really know why fs is missing on my system but it's pretty ok this way, no problem.

I'm already curious on the next LokiJS developments/commits, the "full blown standalone server" sounds interesting :) And you, keep thinking about the React flux store idea! Saying that "mutating state is not writing to the server" might be admittedly just "current thinking". There are still serious problems all around handling state in React when it comes to "isomorphic" as that's tricky. You might want to have a closer look at what Relay/Graphql tries to accomplish, maybe you could apply some ideas to LokiJS. I'm sure you already know the relevant links, if not, I have them at hand, so you don't have to search:

Video, data fetching for React applications at Facebook: https://www.youtube.com/watch?v=9sc8Pyc51uU&index=5&list=PLb0IAmt7-GS1cbw4qonlQztYV1TAW0sCr
Blogpost Introducing Relay and GraphQL: http://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html
Blogpost Building The Facebook News Feed With Relay: http://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html

Cheers, Arno.

**Comment by techfort** [comment]
@ArnoBuschmann thanks for the links! Actually I'm pretty ignorant of the whole react business, so those links are going to be precious resources. I'll keep you posted on future developments, for now my eye is on replacing rediswith Loki  in node.js environments, taking over in-browser dbs, replacing sqlite in cordova/phonegap with Loki, and I'm developing a RESTful wrapper for Loki called snaptun which you can find in my github profile if you are interested. Keep the ideas coming!

**Comment by ArnoBuschmann** [comment]
Talking about REST, you will see in the video, that Facebook is going to eliminate REST endpoints with GraphQL. A so called GraphQL-Server is going to serve exactly that JSON structure the app needs. Now there has to be some sort of mapping between server side database models and the exact JSON structure the app wants. They promise, that this mapping process of setting up a GraphQL server and connecting it to the database should be "relatively simple". I have no idea how that will be done but the advantage would be huge.

Would be interesting to hear your opinion on the video :)

**Comment by techfort** [comment]
That is a very interesting concept. I will be watching the video today. In
the meantime i can see graphql is quite a bit away from being released ...
it makes me want to write my own alternative solution to that. I'm a very
impatient type :)

**Comment by ArnoBuschmann** [comment]
I even had the hope, that something such as graphql complements LokiJS so much, it would trigger you to come up with an own solution ;)

Netflix developed a similiar thing for themselves but it's not open yet either:
"Binding to the Cloud with Falcor Jafar Husain" -> https://www.youtube.com/watch?v=WiO1f6h15c8
