### ISSUE TITLE
LokiJS as Node module via Webpack in Browser environment.

### ISSUE THREAD

**Issue by ArnoBuschmann** [techfort/LokiJS#113]
When I require LokiJS as Node module on the server (isomorphic app approach) and bundle it via Webpack (http://webpack.github.io/) for the client (browser) then:

- the db gets written correctly on the server
- but on the client it tries also to use 'fs' instead of localStorage

I also tried to generally define for the client:
```javascript
var db = new loki('Test', { adapter: 'localStorage' });
```
But this is not working either.

Any idea how I can fix this?

**Comment by obeliskos** [comment]
I think the correct option is : 
 
```javascript
var db = new loki('Test', { persistenceMethod: 'localStorage' });
```

**Comment by ArnoBuschmann** [comment]
Thanks @obeliskos I tried your suggestion but in the browser is says
"undefined" and points to lines 749 and 750:
```javascript
    LokiFsAdapter.prototype.saveDatabase = function saveDatabase(dbname, dbstring, callback) {
      this.fs.writeFile(dbname, dbstring, callback);
```
Which makes sense because 'fs' isn't available in the browser?

**Comment by obeliskos** [comment]
A bug must have been introduced which I think I have fixed.  Let me know if you still have issues.

**Comment by ArnoBuschmann** [comment]
Perfect, works now, thank you!

**Comment by gblok** [comment]
webpack.config.js
..
`node: {fs: 'empty'},`

**Comment by sertaconay** [comment]
It gives "Uncaught TypeError: fs.readFile is not a function" error on src/loki-crypted-file-adapter.js file.

```
	lokiCryptedFileAdapter.prototype.loadDatabase = function loadDatabase(dbname, callback) {
	  var secret = this.secret;
	  var cFun = callback || console.log;
	  
	  fs.readFile(dbname,'utf8',function(err,data){
	    var decrypted = err || decrypt(data, secret);
	    cFun(decrypted);
	  });
	};
```

I imported lokiCryptedFileAdapter. Node config in webpack didn't solve the issue.

`import lokiCryptedFileAdapter from 'lokijs/src/loki-crypted-file-adapter';`

Any advice?

**Comment by sertaconay** [comment]
I was using Electron, so this package solved my problem:

https://github.com/chentsulin/webpack-target-electron-renderer

**Comment by mnasyrov** [comment]
Having the same issue with webpack because it parses all requires on a build time.

While @gblok's workaround does the job, it will be great to move `LokiFsAdapter` to a separate file. IMO, a user should explicitly import the adapter for using because it is not cross platform.
