### ISSUE TITLE
DB gets overwritten.

### ISSUE THREAD

**Issue by ArnoBuschmann** [techfort/LokiJS#115]
This is embarrassing but seems I'm getting something wrong. Given this code:
```javascript
import loki from 'lokijs'
const db = new loki('test.json', {autoload: true});
const users = db.addCollection('users');

const stan = users.insert( { name : 'stan', email : 'stan.soap@lokijs.org', age: 29 } );
const odin = users.insert( { name : 'odin', email: 'odin.soap@lokijs.org', age: 38 } );
const thor = users.insert( { name : 'thor', email : 'thor.soap@lokijs.org', age: 25 } );
const oliver = users.insert( { name : 'oliver', email : 'oliver.soap@lokijs.org', age: 31 } );
const hector = users.insert( { name : 'hector', email : 'hector.soap@lokijs.org', age: 15} );

db.saveDatabase()
```
The DB gets persisted as it should in Node as file 'test.json'. Thereafter I manually remove the last 4 entries in the code, so just the first one (stan) stays:
```javascript
const stan = users.insert( { name : 'stan', email : 'stan.soap@lokijs.org', age: 29 } );
```
Now when re-executing the code, I would think, that
```javascript
const db = new loki('test.json', {autoload: true});
```
would load the existing file with the stored 5 entries and put stan either as 6th entry (duplicate) or just keeping the stan entry unchanged.

But what happens is, that the existing file with 5 entries gets overwritten and just one stan record remains.

What do I get wrong here?

**Comment by obeliskos** [comment]
You can try visiting the Wiki page at : https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters 

What you should probably do is set up an autoload callback such as : 
```javascript
var db = new loki('test.json', {autoload: true, autoloadCallback: loadHandler});

function loadHandler() {
  var users = db.getCollection('users');
  if (!users) {
    db.addCollection('users');
  }

  var stan = users.insert( { name : 'stan', email : 'stan.soap@lokijs.org', age: 29 } );
  var odin = users.insert( { name : 'odin', email: 'odin.soap@lokijs.org', age: 38 } );
  var thor = users.insert( { name : 'thor', email : 'thor.soap@lokijs.org', age: 25 } );
  var oliver = users.insert( { name : 'oliver', email : 'oliver.soap@lokijs.org', age: 31 } );
  var hector = users.insert( { name : 'hector', email : 'hector.soap@lokijs.org', age: 15} );

  db.saveDatabase()
}
```

**Comment by ArnoBuschmann** [comment]
@obeliskos Thanks for the Wiki page hint. Still having problems though :( When I try your code I get
```javascript
error given was: ReferenceError: users is not defined
```
It seemed as if the loadHandler would not be executed. So I thought I have to add an adapter declaration for fs. After I tried this:
```javascript
const db = new loki('test.json', {adapter: 'fs', autoload: true, autoloadCallback: loadHandler});
```
I got this error:
```javascript
this.persistenceAdapter.loadDatabase(this.filename, function loadDatab
                                ^
TypeError: Object fs has no method 'loadDatabase'
```
That made me wonder, if  'autoload' is maybe not compatible with the 'fs' adapter? Declaring the adapter was only for testing purposes anyway as I normally would like to load the database from file system in Node but local storage or indexed db in the browser.

**Comment by obeliskos** [comment]
not sure why you need to use const but try these options instead : 
```javascript
var db = new loki('test.json', {persistenceMethod:'fs', autoload: true, autoloadCallback: loadHandler});
```

**Comment by techfort** [comment]
@ArnoBuschmann If you are still experiencing problems could you send over your full code so I can try to reproduce it?

**Comment by ArnoBuschmann** [comment]
@obeliskos Thanks for your suggestion. const was just an ES6 thing, tried with var, same result.

Hello Joe, thanks for having a look. This is the current code:

```javascript
var db = new loki('test.json', {persistenceMethod:'fs', autoload: true, autoloadCallback: loadHandler});

function loadHandler() {
  var users = db.getCollection('users');
  if (!users) {
    db.addCollection('users');
  }

  var odin = users.insert( { name : 'odin', email: 'odin.soap@lokijs.org', age: 38 } );
  var thor = users.insert( { name : 'thor', email : 'thor.soap@lokijs.org', age: 25 } );
  var oliver = users.insert( { name : 'oliver', email : 'oliver.soap@lokijs.org', age: 31 } );
  var hector = users.insert( { name : 'hector', email : 'hector.soap@lokijs.org', age: 15} );

  db.saveDatabase()
};

var users = db.addCollection('users');
var stan = users.insert( { name : 'stan', email : 'stan.soap@lokijs.org', age: 29 } );
var victor = users.insert( { name : 'victor', email : 'victor.soap@lokijs.org', age: 29 } );
```
First of all I'm confused, that I have to add the collection a 2nd time out of the loadHandler. If I don't, 'users is not defined'.

But the thing I wonder about most is, that having all these 6 users in the db file, this should load them, shoulnd't it?
```javascript
function loadHandler() {
  var users = db.getCollection('users')...
```
But it seems not. Then, when I delete one or more users in the code, they disappear from the database file although I haven't deleted them via remove( obj ) but just eliminated the users.insert line of code. Given all this, I think the db file gets always entirely overwritten.

The thing is, I'm pretty sure that everything is correct without mistakes in the Loki code base but I am doing some silly stuff which has to be done differently.

**Comment by techfort** [comment]
@ArnoBuschmann a bit up the walls busy with stuff, it may be tomorrow before i manage to take a look at it, hope you can wait till then.

**Comment by obeliskos** [comment]
Yea you need to figure out how javascript asynchronous works.  All your code after the loadHandler is global code that won't wait for the db to load before it runs.

This is sample code I don't understand the use case for so I would just say put your last two inserts into the loadhandler after the savedatabase.

I will look into seeing if we can provide a synchronous filesystem adapter to make it easier to learn 'hello loki' type examples.

**Comment by ArnoBuschmann** [comment]
@techfort wouldn't have been any problem at all :) but phew, yeah @obeliskos, you are right, it was all about async behaviour that tricked me. I had a db.saveDatabase() statement not within the loadHandler, which did the overriding. After eliminating that, everything works as expected.

Thanks for your help! :) Closing this issue now.
