### ISSUE TITLE
insert problem

### ISSUE THREAD

**Issue by kristdev** [techfort/LokiJS#124]
Hello, i'm tryng to use loki and i'm new.
The problem I have is, after the insert  and page reloading, my collection is empty. How do I correct this? thank you

**Comment by techfort** [comment]
Hi Franck, could you create a jsfiddle / plunker so that i can analyze the code? At first glance it looked like you're not specifying the use of IndexedDB adapter and/or not saving the database by calling saveDatabase().

**Comment by kristdev** [comment]
(function(){
    // Déclaration de la base de données
    db= new loki('localdb.json');

    // Déclaration de quelques collections
    // ------ Utilisateurs --------
    users=db.addCollection('users');

    //Insertion des données statiques dans la collection users
    users.insert([
        {
            name: "Pambe Aba Franck Serge",
            tel: "237 6 99 92 57 40",
            adresse: "Bonamoussadi Afrique Du Sud"
        },
        {
            name: "Aubin Njuimo",
            tel: "237 6 51 74 97 52",
            adresse: "Deido Bonateki"
        },
        {
            name: "Sam Nganji",
            tel: "237 6 87 56 74 23",
            adresse: "Eido Street"
        },
        {
            name: "Alex Dipita",
            tel: "237 6 56 47 86 23",
            adresse: "Nlongkak valley"
        },
        {
            name: "Blek le bun",
            tel: "237 6 97 52 65 78",
            adresse: "Allalout Street"
        }
    ]);

    var usersarray=users.data;
    if(usersarray.length!=0){
        console.log(usersarray[0].name+usersarray[0].tel);
    }else console.log('Rien');
    })();

**Comment by kristdev** [comment]
my problem is, after the first page loading, i comment query insert and my collection is empty.
Another problem is, i don't know how to stringify collections result

**Comment by obeliskos** [comment]
Easiest way is to use local storage which is default for browser and is synchronous.

Just do a db.saveDatabase() and use db.loadDatabase() at the beginning.

**Comment by kristdev** [comment]
Hey i got an error:

      Error: persistenceAdapter not configured                                lokijs.js:810:13

**Comment by kristdev** [comment]
this is my new code:

	<script>
	(function(){
		// Déclaration de la base de données
		db= new loki('localdb.json');

		db.loadDatabase();

		// Déclaration de quelques collections
		// ------ Utilisateurs --------
		users=db.addCollection('users');

		//Insertion des données statiques dans la collection users
		users.insert([
			{
				name: "Pambe Aba Franck Serge",
				tel: "237 6 99 92 57 40",
				adresse: "Bonamoussadi Afrique Du Sud"
			},
			{
				name: "Aubin Njuimo",
				tel: "237 6 51 74 97 52",
				adresse: "Deido Bonateki"
			},
			{
				name: "Sam Nganji",
				tel: "237 6 87 56 74 23",
				adresse: "Eido Street"
			},
			{
				name: "Alex Dipita",
				tel: "237 6 56 47 86 23",
				adresse: "Nlongkak valley"
			},
			{
				name: "Blek le bun",
				tel: "237 6 97 52 65 78",
				adresse: "Allalout Street"
			}
		]);
		
		db.saveDatabase();

		var usersarray=users.data;
		if(usersarray.length!=0){
			alert(usersarray[0].name+usersarray[0].tel);
		}else alert('Rien');


	})();
	</script>

**Comment by obeliskos** [comment]
My guess is you are running off local filesystem, as I was trying to reproduce this.  Loki was detecting that as cordova environment which had no default adapter defined.

I fixed this issue in the lastest commit, you can either download or make the simple change to your copy.

You will probably want to put your addCollection and collection inserts into a helper function and only run them if there is not already a 'users' collection.  You should be able to test db.getCollection('user') == null for that.

**Comment by kristdev** [comment]
hello
