### ISSUE TITLE
insert persistance

### ISSUE THREAD

**Issue by kristdev** [techfort/LokiJS#126]
Hello, i recently post an issue about insert problem, but i have not been satisfied.
Now, i've create a plunkr copy of my project, [http://embed.plnkr.co/tLm5s0WI884T7Yn3krur/](http://embed.plnkr.co/tLm5s0WI884T7Yn3krur/ "plunkr")

My problem is the data doest not persist in the database.
How do i fix the problem?
I would like to run the project in node webkit or in the browser.
Thanks!

**Comment by techfort** [comment]
Hi Franck,

I edited your plunkr: http://embed.plnkr.co/4RalPOAeZA1xYyT3gpeB/preview
I think you were overcomplicating your life by supplying autoload and autosave and then calling load and save.
Either approach is good but not both :)
Let me know if this solves your problem.

**Comment by kristdev** [comment]
Thanks, solved
