### ISSUE TITLE
find() to return only certain fields

### ISSUE THREAD

**Issue by techfort** [techfort/LokiJS#128]
Support mongo-style field filtering, instead of returning the entire object.
Ideally this happens within the find method, so to avoid adding further filtering when returning a ResultSet.

**Comment by dropfen** [comment]
+1

**Comment by dropfen** [comment]
mmh.. you wrote that ideally the find method should care about filtering this would mean you have to pass the fileds param somehow there.. now find looks like this `function (query, firstOnly)` 
so you have to pass a third parameter or use an `options` object wich is simpler to extend and use like:

`.find = function (query, {firstOnly: false, fields: ["name", "favorite.food"] }) ` 

what do you think?

**Comment by obeliskos** [comment]
Your syntax seems good.  At some point in the future this might be good option to add.  For now you could utilize a chained map() call to achieve similar functionality.

**Comment by hy9be** [comment]
@techfort Why this tick is closed? Is the proposal of @dropfen  already supported?

**Comment by techfort** [comment]
@hy9be my bad, this should not have been closed.

**Comment by DaelDe** [comment]
Can this be achieved with current version somehow? I need this to get an array of one field that is passed to a statistics library.

I tried to use Resultet.Map for this, to return only the one field I need, but it throws. Any other options?

**Comment by jrichardsz** [comment]
Please, @obeliskos could you share us an example of how to pick some fields using **chained map()**?
