### ISSUE TITLE
development flow

### ISSUE THREAD

**Issue by seriousme** [techfort/LokiJS#136]
A few days ago I reworked the task runner to use npm.
(more info see: http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/ )

This enables a number of new options, e.g.:
- always run lint (currently jshint) before(or after) testing, this will enforce coding standards, but at the same time will take time and break Travis-CI builds on code which is not passing lint. (the latter might actually be a good thing ;-))
- always minify src/lokijs.js before running browser tests
- minify, do browser test and bump the npm version before doing an npm publish
etc..

A lot is possible, automating flows will improve repeatability (and possibly quality ;-)) but it also forces people into a certain flow which some might find annoying. (e.g. "Darn, I always have to fix my lint errors first before testing, I'd rather fix them after testing")

So what should be automated/enforced, and what should be left to the individual developer ?

**Comment by techfort** [comment]
I'm actually ok with breaking travis on lint-errors. If something is really annoying it can always be annotated as a skip (e.g. `/* jshint -W101 */` skips lines that are too long - or whatever, can't remember right now)

I would probably create a "publish" task that lints, minifies the source, runs tests against the minified, bumps the npm version, tags the version on git for bower, pushes to the repo and publishes on npm.

And after that probably even a "npm run pour:beer" :D

**Comment by seriousme** [comment]
Landed in PR  https://github.com/techfort/LokiJS/pull/138
