### ISSUE TITLE
Indexed Expressions

### ISSUE THREAD

**Issue by PseudoCorps** [techfort/LokiJS#141]
I think it would be a mind blowing feature to add Indexed expressions to the indexing functionality.

Im not completely sure how it works, but I imagine it just like [Postgres's Implementation](http://www.postgresql.org/docs/9.4/static/indexes-expressional.html).

In psql

``` sql
CREATE INDEX user_names ON users ((first_name || ' ' || last_name));
```

Possibly In JS

``` js
function user_names(obj){
    return object.first +' ' + obj.last;
}
var users = db.addCollection('users', { indices: ['email', name_index] });
```

Possibly just a string?

``` js
var users = db.addCollection('users', { indices: ['email','this.first + " " + this.last'] });
```

The way that they implement it makes it so you can index child properties as well 
'{"name":"Frank Doe","city":"Pittsburgh"}'::json->'name'

``` sql
CREATE TABLE users(id INT, info JSON); 
CREATE INDEX ON users((info->>'name'));
```

(example of this seems pretty straight forward)

I think this would be crazy! (probably because I didn't imagine this before today...) So it might not be as cool as I'm imagining. It seems like something they should implement within the indexeddb spec. Maybe it already is implemented? I know the planning and architecture design they use is way beyond my understanding, so if this sounds wrong/dumb let me know.

**Comment by techfort** [comment]
if i got the concept correctly then i believe this is entirely feasible but let me look into this. We are already in the process of working on indexes so your issue is quite well timed.
@PseudoCorps on and i did not forget #125 don't worry :)
