### ISSUE TITLE
db.toJson/.loadJSON and Dates

### ISSUE THREAD

**Issue by jeffryan** [techfort/LokiJS#145]
Loki's json adapter methods can be handy for exporting and importing data with other systems. However I've noticed that saving the database to JSON and later reloading it results in all Date objects being converted to Strings. This is a common JSON.parse problem as JSON does not support Dates as it does normal primitive types.  The JSON.parse() function does however offer an optional reviver parameter that the caller can provide to handle deserializing of additional types.

It'd be nice if Loki would provide a reviver that handled common date formats - or allowed the calling application to provide one on the loadJSON call.

**Comment by techfort** [comment]
that's a very good point Jeff. If I get you correctly then maybe [this](http://lokijs.org/#/docs#load) should help. Basically you can provide an `inflate` helper to loadDatabase that specifies how to translate the raw json object into the record. Let me know if this is not what you're trying to achieve, and we'll define the functionality a bit better.

**Comment by jeffryan** [comment]
I think that'd be an excellent option @techfort. 

Today I am walking behind the loadJSON and doing this sort of thing manually via update. Your proposal would be a good way to do any sort of custom initialization required.

**Comment by techfort** [comment]
hey @jeffryan - sorry for not explaining this in a better way. You can already provide the inflater helper to specify a behaviour. Quoting from the docs: 
```
{
	shapes: {
		proto: Shape,
		inflate: function (src, dst) {
			dst.name = src.name;
			dst.width = src.width;
			dst.height = src.height;
			dst.area = src.width * src.height;
		}
	}
}
```

in this example, a `shape` specifies the name of the collection, `proto` is the constructor you want to use, and `inflate` is the custom behaviour to revive objects: `src` is the raw record coming form JSON and `dst` is the way the record as it's going to be in the collection (in this example, the record will have an `area` which is the product of the raw json width and height, just to show a simplistic implementation of custom logic).
So you could do something like
```
{
   'event': 
     inflate: function (src, dst) {
         dst.timestamp = new Date(src.timestamp);
       }
   }
}
```

Apologies if I misunderstand or am missing something!

**Comment by jeffryan** [comment]
Thats awesome. Thanks very much for your reply. I should have recognized that but I guess I'm running a little slow today ;)

Thanks too for sharing all you've done with Lokijs.

Jeff

PS I am looking to do some distributed collection mapping similar to what the meteor folks are doing with mongo/minimongo. It seems your collection listeners would be good hooks into this. I'd couple this with socketio and some sort of DDP-like protocol to keep the collections synched. Like meteor i'd control the data exchange via some sort of publish/subscribe rules scoped to the user. Do you know of anyone working on such a thing using Loki?



On Apr 27, 2015, at 4:06 PM, Techfort <notifications@github.com<mailto:notifications@github.com>> wrote:


hey @jeffryan<https://github.com/jeffryan> - sorry for not explaining this in a better way. You can already provide the inflater helper to specify a behaviour. Quoting from the docs:

{
    shapes: {
        proto: Shape,
        inflate: function (src, dst) {
            dst.name = src.name;
            dst.width = src.width;
            dst.height = src.height;
            dst.area = src.width * src.height;
        }
    }
}


in this example, a shape specifies the name of the collection, proto is the constructor you want to use, and inflate is the custom behaviour to revive objects: src is the raw record coming form JSON and dst is the way the record as it's going to be in the collection (in this example, the record will have an area which is the product of the raw json width and height, just to show a simplistic implementation of custom logic).
So you could do something like

{
   'event':
     inflate: function (src, dst) {
         dst.timestamp = new Date(src.timestamp);
       }
   }
}


Apologies if I misunderstand or am missing something!

�

**Comment by techfort** [comment]
@jeffryan glad to be of help! As for your request, I am not very familiar with meteor or minimongo, but i know that LokiJS has attracted a lot of interest in the area of syncing/replication, hence why we introduced the Changes API a couple of versions ago (btw, that should help you keep things in sync).  While there's definitely developers in the wild doing what you describe unfortunately I couldn't name you one. However, it does sound pretty similar to something I'm working on - if you feel like doing a bit of code "perusing": https://github.com/techfort/streamlog 
It's only a start but I'm going to develop this fully, maybe there's something in there you may find interesting? Meanwhile I'm closing the JSON issue, feel free to open a RFC to satisfy the behaviour you're asking about!
Also I'm working on a standalone server-side LokiJS which would work as a centralized database for all LokiJS clients, most likely implementing pub/sub so changes applied to one collection by a client are propagated to all clients. Feel free to drop me a mail if you have a specific use case.

**Comment by retorquere** [comment]
I'm having a little difficulty understanding the docs on this issue. Should I pass something like this as the `options` object to the database:

```
{
  inflate: {
    shapes: {
      proto: Shape,
      inflate: function(src, dst) {
        dst.name = src.name;
        dst.width = src.width;
        dst.height = src.height;
        dst.area = src.width * src.height;
      }
    }
  }
}
```
Or should I pass

```
{
  shapes: {
    proto: Shape,
    inflate: function(src, dst) {
      dst.name = src.name;
      dst.width = src.width;
      dst.height = src.height;
      dst.area = src.width * src.height;
    }
  }
}
```

and LokiJS will assume that any top-level property that matches a collection name (in this case `shapes`) are collection options? Does that mean it's not safe to have a collection named `autosave` for example (I'm going through the code and I think that's the case)

Is it correct that the inflater will only be called when `proto` is also set? Is it OK to pass `Object` as the proto?
