### ISSUE TITLE
Apply Simple Sort

### ISSUE THREAD

**Issue by hutch120** [techfort/LokiJS#146]
Hi Joe,

Love your work... hoping you can help.

I think I'm missing something obvious... I'm simply trying to sort a collection before filtering... that is, I have a bunch of names and I want them sorted before applying a filter so I get the A's first.

I've tried a lot of variations... here is an extract from my code that doesn't work but looks like it should???

```javascript
var myView = myCollection.addDynamicView('myView');
myView.applySimpleSort('lastname', false);
myView.applyWhere(function (obj) {
	if (obj.language != '') {
		return false;
	}
	return true;
});
var people = myView.data();
// ... Do something with sorted and filtered data
```

Thanks in advance!

**Comment by obeliskos** [comment]
Your example seems to work for me.  Can you provide a more complete example?  For dynamic views, sorting always occurs after filtering.   For your example it would not make a difference which is done first... only if you wanted to do something like 'grab first 100 docs, then sort'... for that you might just use resultset chaining.

Also your 'where' filter can be easily expressed as a 'find' filter which may be faster and can be saved within the database.  Your filter creates a result of all documents with a blank language.  This can be expressed as : 
```javascript
myView.applyFind({ 'language': '' });
```
or
```javascript
myView.applyFind({ 'language': { '$eq': '' } });
```

Feel free to clarify problem and I will look into it.

**Comment by techfort** [comment]
hey @hutch120 any luck with this? I have a 30 days policy on inactivity for an issue before I close it, so if you need further help let me know.

**Comment by hutch120** [comment]
Sorry for the late response.... I did get it going by using a resultset.

```javascript
var resultSet = this.collection
  .chain()
  .find()
  .simplesort("lastname")
  .where(function (obj) {
    return (obj.language == '');
}).data();
```

**Comment by techfort** [comment]
Cool, thank you for the feedback. I'm closing this, feel free to re-open if you have any more issues.
