### ISSUE TITLE
how can i use lokijs in electron?

### ISSUE THREAD

**Issue by tcdona** [techfort/LokiJS#147]
https://github.com/atom/electron/

the code db.js
```
var loki = require('lokijs')
var db =  new loki('./loki.json')
db.save()
```
worked by cmd node db.js and by node-webkit[nwjs.io]

but didn't work [electron] neither main.js [main process] or page.js required by main.html [render process] 
and i have try require('remote').require('lokijs') from page.js [render process]

**Comment by techfort** [comment]
I've looked at electron but never used it. If you give me a bit to explore it i may able to get back to you.

**Comment by tcdona** [comment]
that very nice of you, I am looking forward to it

**Comment by techfort** [comment]
Hi there,
I took a look at electron. Documentation is pretty vast so I could only skim it. 
I am yet to familiarize with the concept of `renderer` which is where all the html action happens (I *think*), in any case i created a gist of a mini-app that loads lokijs correctly: https://gist.github.com/techfort/509b95190b226519c07c

Bear in mind I created a skeleton app as described in the documentation, then I did `npm install lokijs`

This is my `main.js` file in the skeleton app i created. When I run `electron .` I get the correct output.

**Comment by tcdona** [comment]
you are so nice, and i have seen your code.

i just find why i can't get my data "loki.json". 
that's all because the path! "./loki.json" is some where else i run the electron app
```
new loki(require('path').resolve(__dirname, './loki.json'))
```
this is all i need .

and thank you very much !

**Comment by techfort** [comment]
You're welcome!
