### ISSUE TITLE
npm and bower versions update?

### ISSUE THREAD

**Issue by aesqe** [techfort/LokiJS#148]
It seems that both bower and npm version contain lokiIndexedAdapter.js with that onsuccess bug present. I don't know if they pull data directly from the github repo or you need to update them manually, just thought best to let you know.

**Comment by techfort** [comment]
thanks a lot for flagging this, I am preparing to release 1.3 so this is good to know!

**Comment by janober** [comment]
Any updates or timeframe on this? Because there is still no 1.3.0 in bower.

**Comment by techfort** [comment]
@Jan A few days at most, life got in the way of this release which got
delayed a bit

Any updates or timeframe on this? Because there is still no 1.3.0 in bower.

—
Reply to this email directly or view it on GitHub
<https://github.com/techfort/LokiJS/issues/148#issuecomment-103578230>.

**Comment by janober** [comment]
Great, thanks a lot for the fast answer!

Great product btw.!

**Comment by tomByrer** [comment]
semi-blocking: https://github.com/techfort/LokiJS/issues/151

**Comment by janober** [comment]
Just checked. Version 1.3.0 is there. So I guess it can be closed.
