### ISSUE TITLE
lowercase filenames names please

### ISSUE THREAD

**Issue by tomByrer** [techfort/LokiJS#151]
Mixed case filenames can cause issues with `require`, bower, & other AMD/CJS.  Also better Netiquette.
https://groups.google.com/forum/#!topic/ractive-js/lR7_Gz1zwJw
http://unix.stackexchange.com/a/197999

& better to change this early; more pain when needed to change later on.

**Comment by techfort** [comment]
I suppose you're right. I'll make it a point to change file names before 1.3 and put a disclaimer on the website. Thanks for the feedback!

**Comment by tomByrer** [comment]
cheers

**Comment by techfort** [comment]
This is done, closing.
