### ISSUE TITLE
minified files need @copyright & @license

### ISSUE THREAD

**Issue by tomByrer** [techfort/LokiJS#152]
Several good [reasons](https://github.com/tomByrer/web-engeneering-notes/blob/master/banner-tips.md#mini-banner) why to include in each .js file atleast a project name & license, but my near-immediate is for automated collating (eg on [jsDelivr CDN ](https://github.com/jsdelivr/jsdelivr#load-multiple-files-with-single-http-request)).  Also, one of your files has foreign code, so you need to mention that.  Example:
`lokiCryptedFileAdapter.js`

``` js
/** @see {@link https://github.com/techfort/LokiJS}
@file lokiCryptedFileAdapter.js: encrypt/decrypt routines from github.com/meltmedia/krypt
@author Hans Klunder <Hans.Klunder@bigfoot.com>
@copyright Mike Moulton 2014, Hans Klunder 2015
@license MIT, BSD
*/
```

I made the comment without extra spacing, since I think `uglifyjs --comments src/lokijs.js > build/lokijs.min.js` will carry over the comment block, want to save a few bytes.

I was about to make a PR, but found the mixedCase filename issue.

BTW, I found this project via [jsDelivr API source](https://github.com/jsdelivr/api/blob/v2/db/index.js#L8).

**Comment by techfort** [comment]
Thanks again for flagging this, i should be able to get round to changing filenames tonight, will that enable you to submit the PR afterward? 
Also, feel free to drop a mail with general feedback, happiness of developers is a very high priority for me.
