### ISSUE TITLE
The update doesnt work

### ISSUE THREAD

**Issue by estvmachine** [techfort/LokiJS#154]
Im trying this.

```javascript

exports.update= function(lokidb){
  
   return function(req, res){
           
          var advance = {};
           advance= _.extend(advance, req.body);

           var advances= lokidb.getCollection('advances');
           var advance_old=  advances.find({$loki : advance.id });
           
          advance_old= advance;
  
           advances.update(advance_old);

          console.log(advances.find());
          console.log(advance_old);

   }

}
```

The logs thrown differents things, the 'advances.find()'  indicate the document dont updated :(.

**Comment by techfort** [comment]
Hey there,
LokiJS checks for `$loki` and `meta` properties in an object before updating. Is it possible that in your 
```advance_old = advance;``` you're copying over an object which has no `$loki` and `meta` properties?

**Comment by estvmachine** [comment]
I corrected but there seems odd . I'm making an query from an angular-view to my server nodejs, the server returns an object that the user edit. You are telling me that 'object' never should lose their 'meta' attribute.

I thought each time to do this operation:
```javascript
 var findObject = objects.find ($ loki : whatever_id )
```
returns the object with the 'meta' inside, so only i need to edit the attribute i want to change, but this doesnt work:

    exports.update= function(lokidb){

   return function(req, res){

          var advance = {};
           advance= _.extend(advance, req.body);

           var advances= lokidb.getCollection('advances');
           var advance_old=  advances.find({$loki : advance.id });

          advance_old.thingsDone= advance.thingsDone;

           advances.update(advance_old);

          console.log(advances.find());
          console.log(advance_old);

   }

}

**Comment by techfort** [comment]
are you getting an error or does it simply not work as it's supposed?
What's the output of the two log statements?
If you can create a plunkr/fiddle i could take a deeper look at the problem. Cheers

**Comment by estvmachine** [comment]
I works, but only if i used the same object with 'meta' and '$loki', that seems weird because the object travel from server to client and back again, only the '$loki' looks necessary to find the same document.

**Comment by techfort** [comment]
You don't have to necessarily use the same object but you need to ensure
that $loki and meta properties are retained. Without those LokiJS will
think that you're trying to update an object that is not in the collection
(and strictly speaking the object coming from server was not in the
collection). Think of $loki as the $id property in mongodb.
Let me know if i can close this.

**Comment by estvmachine** [comment]
Yes, you can close this issue. Maybe that information its necessary in docs. Thanks for the help.

**Comment by techfort** [comment]
Noted! Created the issue here: https://github.com/techfort/lokijs.org/issues/3
