### ISSUE TITLE
Make simplesort case-insensitive?

### ISSUE THREAD

**Issue by countermeasure** [techfort/LokiJS#157]
`simplesort` appears to be case-sensitive when sorting strings.

Can I suggest that an appropriate default for `simplesort` would be case-insensitive for strings? I can't speak for anyone else, but when I'm sorting by string, I always need a case-insensitive sort.

It's not a big deal, and I implemented a case-insensitive sort with `sort` without too much trouble, but I just thought I'd mention it in case it's quick and easy to implement.

Cheers!

**Comment by techfort** [comment]
That's a good point, as it is unlikely people will create two fields with the only difference being a letter case. Should be straight forward enough. Might not make into 1.3 which is due this week though. Thanks!

**Comment by countermeasure** [comment]
No drama.

Thank you for a nice lightweight database. I think it only added 38Kb to my minified browser bundle!

**Comment by techfort** [comment]
cheers!
