### ISSUE TITLE
Multiple params in find doesnt work

### ISSUE THREAD

**Issue by estvmachine** [techfort/LokiJS#160]
Hi, i have one problem with the **find**, its just works with the first parameter. Im trying this:

```javascript
   var tasks= lokidb.getCollection('tasks');

  var listTasks= tasks.find({  day:'23', hour: '10' });
```

This retrieved all task in day '23', doesnt filter with second parameter.

**Comment by techfort** [comment]
This has been a recurring issue because the documentation isn't 100% clear on this (this is being corrected). The correct syntax for that is:
`var listTasks = tasks.find({ $and: [ { day:'23'},{ hour: '10' }]});

**Comment by estvmachine** [comment]
Thanks!, sorry for ask xD

**Comment by techfort** [comment]
Hey - no problem! Hope loki makes your life easier.
