### ISSUE TITLE
Are pre-insert and pre-update allowed to modify the objects?

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#161]
I'm using LokiJS as a cache between my code and an sqlite backend. My code works against a framework (Zotero) that allows interchangeable use of lookalike-values in most places -- strings consisting of numbers work where a number is expected, any falsish value will do instead of `null`, etc. Sort of good from a robustness POV ("be liberal in what you accept" and all) but not so good for storing things in LokiJS, which takes the javascript standard behaviour for identity in searches, and rightly so.

Unfortunately for me, that means I need to do object cleanup before nearly any call to LokiJS, to make sure numbers are actually numbers, bools are actually bools, etc. I was wondering whether I could centralise this to the pre-insert/pre-update event emitters, to change `obj` before it would actually be sent to the store. It would do wonders for robustness. From the code it looks like it, but I'd rather not go with that level of insight.

In extension to that, I think that `insert` returns the object(s) inserted, so I could use the return value of that to make sure I was using the objects as they were cleansed in `pre-insert`. `update` does not seem to return the updated object, but if I'm interpreting the code right it acts on the same `obj` through-out, and if `pre-update` acts on the object in-situ, the object passed into `update` will have been changed as a side effect of calling `update` on it. Correct? Can I rely on these behaviours?

**Comment by retorquere** [comment]
And on that same track, I could use a `pre-find` :)

**Comment by techfort** [comment]
Hi,
well I never, `update` doesn't return the object. That's wrong, it should. As for all the events supported, see: https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L2558
pre-insert and pre-update are there, is there something additional to those that you need?
And regarding pre-find, what would you pass to the listener, the query itself?

**Comment by retorquere** [comment]
I've found those pre-X events, but I'm wondering whether it is specced
behavior that they're allowed to modify the objects they're passed. As far
as I can tell that's the current behavior, but that could be an accidental
side effect rather than expected behavior, and if it is, it could go away.

Regarding pre-find, I hadn't thought ahead that far. Hmm. Perhaps better to
just create a wrapper function for that.

**Comment by retorquere** [comment]
Do pre-insert and pre-update run synchronously? I'm looking to auto-add a composite key generated from multiple fields to enforce multi-field uniqueness.

**Comment by retorquere** [comment]
I'll have to retest then - I do not have async listeners, but I didn't manage to change the object in earlier tests. It doesn't matter whether I have clone objects on?

**Comment by obeliskos** [comment]
That's how it 'should' work and I think that is how it 'does' work... 

I'll look through our unit tests or add some to verify that this weekend

**Comment by retorquere** [comment]
An MWE shows that it does. I'll dive into my own code.
