### ISSUE TITLE
Can a build (as present in the "build" directory) also host the non-minified version?

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#162]
Easier for debugging purposes.

How did you get the "Please review the guidelines for contributing to this repository." banner above this BTW?

**Comment by techfort** [comment]
Sounds good, will try to stick it into 1.3 as it's only a matter of copying the file over to the build dir. As for the banner, i don't see it, but I'm assuming it's the presence of a CONTRIBUTING.md file triggers that?

**Comment by retorquere** [comment]
Awesome -- that's it.
