### ISSUE TITLE
Searching for with nulls triggers exception

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#163]
Script to reproduce it at https://gist.github.com/950f4445a5ed43819321

**Comment by retorquere** [comment]
The problem looks to be a little more involved than just search, see https://gist.github.com/a880d1db13687c9d0968. It looks like if you search for any column that has a null or boolean value in *any* of its entries, the query bombs out. The actual search value doesn't seem to have a causal effect.

**Comment by retorquere** [comment]
Even using the full query syntax `col.findOne( {'$and': [ {citekey: {'$eq': "xsheehan2010heidegger"}}, {libraryID:{'$eq': 3}} ] } );` doesn't help -- it's really triggered by DB values, not query values.

**Comment by obeliskos** [comment]
Slow down please I realize you are in the middle of a lot of tests but it is difficult to trace through your errors and respond.

When I look at the bash generated output scripts the findOne is missing the $and operator.  Could this be bash related string delineation?

**Comment by retorquere** [comment]
Ugh, you're right. The error was there, but this test set doesn't trigger it anymore. I'll reinstate the full set -- be back later.

**Comment by retorquere** [comment]
OK, sorry for the panic -- it really was a panic. The commit you made earlier does fix the problem.

Should it be safe to use https://raw.githubusercontent.com/techfort/LokiJS/master/src/lokijs.js rather than https://raw.githubusercontent.com/techfort/LokiJS/master/build/lokijs.min.js ? I really need to put a fix out for this soon.

**Comment by obeliskos** [comment]
No problem, glad we finally figured it out.  And yes, your original reporting of this bug helped me to figure out what needed to be fixed.  I'm glad you reported that.

I have regenerated the minified version so should be able to use either. src/lokijs.js or build/lokijs.min.js.

Let me know if you run into any issues with the minified version, techfort or others have modified build scripts.  @Techfort can decide if this needs version bump or not.

**Comment by retorquere** [comment]
That's good enough for me -- I've picked up the new minified version, my tests are running now.

**Comment by obeliskos** [comment]
Great... let me know if you find anything else.

**Comment by techfort** [comment]
I will be doing a little cleanup and version bump and publish this. I published 1.3.4 last night but it did not contain this fix. I will be publishing for npm and bower today, announcement and docs in the next couple of days (but it will be available on npm and bower from tonight GMT)
