### ISSUE TITLE
Update documentation on site for AngularJs integration

### ISSUE THREAD

**Issue by MarkAPhillips** [techfort/LokiJS#165]
Hi - I recently updated to version 1.3.4 and noticed that the js file name has changed from lokiAngular.js to loki-angular.js - this initially broke my application but easily resolved it my renaming the file.

Please could you update the documentation at http://lokijs.org/#/docs

which currently reads: 
```
LokiJS is made available to Angular through a 'lokijs' module. Include lokiAngular.js and the following should suffice to have a Loki constructor available as a factory:
```

Thanks! :+1:

**Comment by techfort** [comment]
Will do - currently working on that!

**Comment by obeliskos** [comment]
This adapter has been rewritten and expanded, with wiki documentation [here](https://github.com/techfort/LokiJS/wiki/Lokiwork---LokiJS-Angular-Service).  

It would appear that @techfort did update the lokijs.org documentation, so I will close this.
