### ISSUE TITLE
CommonJS (NodeJS) examples of lokiIndexedAdapter references

### ISSUE THREAD

**Issue by toddpi314** [techfort/LokiJS#166]
Document the general surface api for accessing the lokiIndexed adapter within a node process.
Note: the browser include is clearly communicated

**Comment by toddpi314** [comment]
For example, the indexedDbAdapter use-case at https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#full-examples-of-using-loki-indexed-adapter is not possible in the NPM module  as is.

**Comment by techfort** [comment]
Thanks Todd, I'll make sure to correct this asap.

**Comment by obeliskos** [comment]
indexedDB is not available under node right?  You could use for webkit.  Not sure I understand the question/suggestion.

**Comment by techfort** [comment]
@obeliskos the way i interpreted the issue was to specify in the wiki that the adapter is only available in the browser, but now that I re-read... @toddpi314 could you elaborate a little more on this? IndexedDB is only available in the browser, for node.js/commonjs environments you would either use LokiFsAdapter (for which you don't need to do anything but specify the name of the file to save the serialized db in, should probably appear more clearly in the wiki) or src/loki-crypted-file-adapter.js which stores the encrypted db in the file system.

**Comment by toddpi314** [comment]
Good point @obeliskos. This can be clarified with more context.

There is a fair number of projects using CommonJS in multiple environments. 
That is, NPM based require injection of dependencies that can run in Node process (typically for Server and Unit test), then Browersify over into the client world.

A hard reference to the IndexDB adapter is required for browserify to serialize the adapter for browser consumption. Otherwise, you end up packaging your project source and having to maintain the IndexDB adapter as a separate vendor library.

Possible mitigation:
- Expose the IndexDB adapter on the Loki surface api - this would allow client consumers in the above use-case to reference and assure it is available on non-nodejs export
- Add a strategy (in the module itself) that accelerates storage based on existence of nodejs process context - if missing, assume browser context and favor indexdb

The biggest issue is that we can't find a direct handle to the indexDB adapter without doing a gnarly require('node_modules/lokijs/src/loki-indexed-adapter'). This is pretty vulnerable since not all NPM packages are maintained in the root project dir.

Thanks for the quick feedback!

**Comment by obeliskos** [comment]
Ah, ok.. thanks for your explanation.  I think I understand your request now (cool project btw).

So do I understand correctly that the only options are either include indexed adapter in main lokijs.js or put indexed adapter in its own npm project for browserify to be happy?  

Thanks

**Comment by toddpi314** [comment]
either would be acceptable. Not sure if the they are the only options, but they both seem reasonable.
Thanks!

**Comment by chasm** [comment]
+10

**Comment by obeliskos** [comment]
I will do some testing of adding a javascript getter property which returns a relative require of the adapter to see if that would suffice.

**Comment by obeliskos** [comment]
No feedback, so closing as stale.  An arbitrary method getIndexedAdapter was added which does its own relative require, which browserify should pick up in an ast scan but I am not able to test this out at the moment.  

Feel free to reopen if you are able to test or offer workarounds other than a separate npm repo.

**Comment by G-Rath** [comment]
@obeliskos the `getIndexedAdapter` method works perfectly. The only issue seems to be that it's not static, meaning I have to create a new database to get the indexed adapter.

I've also had some typing problems, but that's another story/issue ;)
