### ISSUE TITLE
TypeScript Definition Done!

### ISSUE THREAD

**Issue by TeamworkGuy2** [techfort/LokiJS#167]
Wasn't sure where to post this, it's not an issue, just wanted to let those who use LokiJS know. 

For those of you who use or might be interested in TypeScript, there's a newly added TypeScript definition for LokiJS over at the DefinitelyTyped repository: https://github.com/borisyankov/DefinitelyTyped/tree/master/lokijs.

**Comment by techfort** [comment]
Excellent! Thank you!

**Comment by obeliskos** [comment]
Yea thanks!  I wonder if this could be used in an editor like Visual Studio Code to get intellisense.

**Comment by obeliskos** [comment]
We may need to revisit this in the future as our api surface evolves, but this seems a closed issue, thanks!

**Comment by TeamworkGuy2** [comment]
I was thinking about that recently, I was wondering if you guys would be interested in upgrading Loki to typescript and pros/cons from your viewpoint? 

My viewpoint after writing the definition file for LokiJS is that there's no obvious downsides to TypeScript for an OOP JS library like LokiJS, the code doesn't doing anything crazy with prototypes or function argument and makes an excellent target for TypeScript. 
Since typescript is just javascript with types and there's a dozen tools and IDEs to compile .ts to .js when you save a file or as part of the build process, keeping side-by-side .ts and .js files in the '/src' directory wouldn't take much effort, thoughts?

(based on my experience over the last 6 months working on a large business web app using VS2015 + TypeScript + LokiJS + lokijs.d.ts file linked in the OP)

**Comment by OzzieOrca** [comment]
How should I go about importing and using `Loki` with the `LokiIndexedAdapter` in Typescript using this definition?

I've imported Loki using:
```
import * as Loki from 'lokijs';

//Usage
var db = new Loki('my-app', {});
```
which compiles but is looking for the module `fs` which isn't available in the browser.

I'd like to be able to do something like:
```
import {Loki, LokiIndexedAdapter} from 'lokijs';

export class LokiJSService {
  constructor() {
    var iDBAdapter = new LokiIndexedAdapter('my-app-db');
    var db = new Loki('my-app',
      {
        adapter: iDBAdapter
      }
    );
  }
}
```
but can't seem to get the imports/exports right. I tried modifying the type definition file too. I'm new at using TypeScript and I know I haven't changed some of the code to use TypeScript features or the class fully. I'm just trying to get the imports to work first. If there are any docs you guys could point me to that would be helpful too. Thanks!

**Comment by obeliskos** [comment]
I have not yet had the time to experiment that much with typescript or the definitions which @TeamworkGuy2 created for us, so I unfortunately can't provide any immediate help on this issue.

The typescript definitions appear 9 months old so it is quite possible they are outdated.  I would like at some point in the future to revisit this but have not had time.  

I'm not certain if he wants dissemination of this (and I just found so i'm not sure if its ready), but it would appear @TeamworkGuy2 is actively working on typescript wrapper for loki collections here : 

https://github.com/TeamworkGuy2/lokijs-collections

(TWG2 if you would prefer I not link to that project, let me know and I will remove.)

If anything it may give you some ideas while you are learning typescript with loki.

**Comment by TeamworkGuy2** [comment]
I'm happy to have you link to it!  Yes, the definition is somewhat out of date and I haven't had the interest in updating it since I've been working on the lokijs-collections project you linked to. 
Lokijs-collections is a work in progress that is closely aligned with the requirements of another project I'm working on outside of the open source domain. 

Lokijs-collections is designed around meta-data schemas for each collection.  These schemas containing primary key column names, non-nullable column names, data types, and a few other optional pieces that are used by new functions like DataCollection.addOrUpdate().  We use this meta-data to add constraints (such as uniqueness and auto-generated columns) to lokijs-collections without adding any additional API complexity to the developer besides setting up the initial schemas. 

The purpose of the library may not match your needs @OzzieOrca, but it does have some unit tests which contain code that uses the loki TypeScript definition file.  You might be able to use it as a guide for using the typescript definition file in your project. 

You are right, Lokijs does require('fs') for the optional LokiFsAdapter (https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L1068). 
If you're running in the browser, I'd comment out or remove lines 1058 (https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L1058) through 1112 (https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L1112) and any other references to LokiFsAdapter.  That should fix the missing 'fs' issue you mentioned.

**Comment by TeamworkGuy2** [comment]
Fyi, @obeliskos and @OzzieOrca, I updated [lokijs.d.ts] (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/lokijs) type definition over on DefinitelyTyped to latest loki.js v1.3.16.

**Comment by obeliskos** [comment]
That's awesome, thank you!  Interesting project as well :)

**Comment by thasmo** [comment]
Typings are located [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lokijs/index.d.ts), although they don't seem to be up-to-date.
> Type definitions for lokijs v1.2.5

**Comment by nmocruz** [comment]
@thasmo  is not updated and is missing a few thing there.  I don't see  updateWhere and there's conflicts and a few methods

**Comment by TeamworkGuy2** [comment]
@thasmo, @nmocruz - lokijs@1.5.1 definition just got merged to definitely typed (pull: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21747, commit: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/766089f4e8107fd0fba147ed4543ae4b3cb0b3b8). Should auto update to npm in a day or two.
Took me ~10 hrs, documentation from lokijs source included, hope it works well for those of you using it.

**Comment by thasmo** [comment]
@TeamworkGuy2 Thanks for your work on this, spending so much time! I'll definitely have a look.

**Comment by Viatorus** [comment]
@TeamworkGuy2 Very good work!

Just one question:  Does the LokiQuery works with nested properties?

**Comment by TeamworkGuy2** [comment]
@Viatorus Not really, although I left it as a global interface type **so you can extend it in your own code**.
The problem is:
1. `LokiOps` properties like `$contains` can only be of type `any` because they can be nested (which I'm not knowledgeable enough to mimic in TypeScript's type system, and if I could, would lead un-intelligiblely long messages when compiling incorrect queries and impossible to read hover-over hints in IDEs) and because I can't restrict which `LokiOps` can be applied to which properties of a model (i.e. `$indexOf` can't be applied to a `number` property) so I don't even attempt to mimic one or two layers of nesting and just use `any`.
2. And it's not possible to extract the types of nested property using TypeScript's current type system.  
For example: `type E = { name: string; posts: { id: number; ... }[] }`
It's impossible to know whether `E["posts"]` is a primitive, null/undefined, or an object.  So my definition of `type PartialModel<E, T> = { [P in keyof E]?: T | E[P] }`
cannot make any type decisions about `E[P]` where `P = "posts"`

**Comment by nmocruz** [comment]
Also branchresultset is defining all parameters as optionals

Em 05/12/2017 12:41, "Viatorus" <notifications@github.com> escreveu:

**Comment by Viatorus** [comment]
@TeamworkGuy2 thank you for your explanation.

What you wanted can maybe implement this way:

```ts
type R<T> = {
    [P in keyof T]: R<T[P]>;
}

interface Foo {
    bar: {
        baz: {
            name: string;
        }
    }; 
}

let r: R<Foo>;
r.bar.baz.name = "123";
```

But this does not help here.
The real obstacle is: LokiJS (and MongoDB) accesses nested properties using the dot syntax:

```js
let query = {"bar.baz.name": 123}
```

Currently, typescript cannot handle this in an easy way. (There are some proposals [like this one](https://github.com/Microsoft/TypeScript/issues/20423)).

What I have done today is the following:

```ts
/**
 * E = the data type
 * N = the nested properties
 */
class Collection<E, N> {
    public data(): E[];

    public find(LokiQuery<E & N>); 
}

interface Foo {
    bar: {
        baz: {
            name: string;
        }
    }; 
}

let coll = new Collection<Foo, {"bar.baz.name": string}>
coll.find({"bar.baz.name": "test"});

```

**Comment by TeamworkGuy2** [comment]
@Viatorus good stuff, thanks for sharing!  That's why I made all the interfaces global so other people can extend them to work best in their own situations.
