### ISSUE TITLE
How to import data from csv or json?

### ISSUE THREAD

**Issue by megabait1212** [techfort/LokiJS#170]
Hello, 
what is best way to import data? I want to upload data to existing db and automatically create key-values pairs from my json file. Json file contain about 200 objects and each object contain about 30 properties. Is it possible to upload data straight from csv? Thank you

**Comment by techfort** [comment]
Hi! There's a demo project i've done which loads a csv and queries it. It's here: https://github.com/techfort/csv-loader let me know if it's of any help, it should be simple enough.

**Comment by megabait1212** [comment]
Thank you for your answer but in my case it's not suitable because it require nodejs. I decide to use library papa parse http://papaparse.com/. Here my piece of code
```
document.getElementById("upload").addEventListener('click', function () {
            parseMe(document.getElementById("file").files[0]);
        });

        function parseMe(file) {
            Papa.parse(file, {
                header: true,
                complete: function (results) {
                    renderDataset(results.data);
                }
            });
        }

        function renderDataset(dataset) {
            dataset.forEach(function (el) {
               users.insert(el);
            });
            db.saveDatabase();
        }
```

**Comment by techfort** [comment]
cool - thank you. Closing this so.
