### ISSUE TITLE
ensureUniqueIndex

### ISSUE THREAD

**Issue by kberryman** [techfort/LokiJS#172]
I am using ensureUniqueIndex to build an index on my uniqueId's that I have on records.  My issue is that I have records with null ID's.  This is valid behavior with in the system.  Is there a way to get the speed increase of ensureUniqueIndex and using the 'by' function to pull records but still allow multiple records with null if all other id's are unique.

I can make this change to code and send a pull request if you think this would not violate anything else Loki is doing.  My thought was to just update the UniqueIndex.set function to ignore any records with null id's.  This could also be added as an option to ensureUniqueIndex so this functionality can be turned on or off.

**Comment by techfort** [comment]
Sounds good!
Looking forward to that PR. I will ask you though to create a couple of tests in spec/generic/unique.spec.js to verify existing functionality is intact (travis ci will do that anyway but hey) and the new approach also holds well against tests. Once completed, I will include it in the next release and add proper docs so nobody gets caught by the null behaviour.
