### ISSUE TITLE
Searching by indexes

### ISSUE THREAD

**Issue by alex21** [techfort/LokiJS#174]
When I'm trying to find documents by indexed field, query returns not all documents, matching search criteria.
After removing indexes, it was fixed. Fortunately, It seems it didn't affect queries performance (in my case).

Example:

Collection:
collection = db.addCollection('name', {indicies: ['left', 'right']}) //Query returns only 1 entry
collection = db.addCollection('name') //Query returns 2 entries

Collection entries:
{'code': 'code1', 'left': 1, 'right': 4}
{'code': 'code2', 'left': 2, 'right': 3}

Query:
collection.find({'left': {'$lt': 3}})

**Comment by techfort** [comment]
so are you saying that when specifying indexes the query results are inaccurate? that would be a major bug. Will investigate asap, thanks for reporting!

**Comment by obeliskos** [comment]
Think I found the problem, thanks!  I will try to fix tonight and add this as test case.  Our calcseg utility function only seems to work when the target value ('3') is in the middle of total all possible values in the data.  If you added another record with left = 5 (just for diagnostic purposes) it would have worked.  I'll add a check for 'all values are in range' and handle correctly.

**Comment by alex21** [comment]
wow, such a quick feedback. thanks guys:)

**Comment by techfort** [comment]
thank @obeliskos really - i'm submerged in work ATM, he's like a saviour.

**Comment by obeliskos** [comment]
Thank you for finding that, i guess there was a gap in unit test coverage.

The release i just checked in should fix it, and I added units tests and rebuilt the minified version.  You should be able to get it from this github repo if you want to test it.

Let me know if you still have issues
