### ISSUE TITLE
LokiJS not able to write the data to the json db file after creating NSIS installer package.

### ISSUE THREAD

**Issue by saan1984** [techfort/LokiJS#175]
LokiJS works fine and able insert and update json db file.

But when i packaged the entire code using NSIS and ASAR it is not able to write into the db json file.
It is not throwing any error!!!.

when i have done a debug, i saw the data are getting added to collection however it is not persisting it to file!!!

Any help here??

**Comment by techfort** [comment]
do you mean that it works fine in development, but once you package it with an installer and use the installed app it can't write to file?
could there be some form of permission issue? Loki doesn't catch write file errors so you should definitely see if something goes wrong. I will investigate this asap.

**Comment by saan1984** [comment]
@techfort yup.
Let me know if you get any updates.O

[If you need i can share the code]

**Comment by saan1984** [comment]
It is able to read the db.json file. But when i am inserting new one and saving it, it is not getting persisted.

**Comment by techfort** [comment]
@saan1984 are you still stalled on this? I'm going to be pretty busy for the next week so i might not get time to investigate this before then, especially because i'm completely unfamiliar with nsis and asar. Code would be useful though!

**Comment by saan1984** [comment]
Hi,

I resolved this issue by providing FullAccess to Using NSIS script.

Thanks
Sandeep

On Wed, Jun 24, 2015 at 5:34 PM, Techfort <notifications@github.com> wrote:

> @saan1984 <https://github.com/saan1984> are you still stalled on this?
> I'm going to be pretty busy for the next week so i might not get time to
> investigate this before then, especially because i'm completely unfamiliar
> with nsis and asar. Code would be useful though!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/techfort/LokiJS/issues/175#issuecomment-114844901>.
>



-- 
Thanks
*Sandeep Kumar Patel*
www.tutorialsavvy.com
________________________

**Comment by techfort** [comment]
Awesome, so it was a permission issue? Will close this in the mean time. Good luck!
