### ISSUE TITLE
Failure to remove with unique index

### ISSUE THREAD

**Issue by Whoaa512** [techfort/LokiJS#177]
Repro: https://github.com/Whoaa512/loki-remove-repro

**Comment by kberryman** [comment]
@Whoaa512 did you have leads on this issue.  I am seeing the same error arise within the browser when I attempt to removeAllData from a collection with unique indexes.  I didn't realize that it had to do with the unique index though.

**Comment by Whoaa512** [comment]
I know the error comes from https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L3685
Which happens after it tries run: https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L3135-L3137

**Comment by kberryman** [comment]
I think I found the bug here.  Give me a little and I will submit a pull request to fix it.

**Comment by kberryman** [comment]
@Whoaa512 I just submitted a pull request that fixes this issue.  @techfort is usually pretty quick with excepting pull requests, so you should see it soon in master.

**Comment by techfort** [comment]
yep - closing this one, thanks @kberryman
