### ISSUE TITLE
Removing entries with unique indexes

### ISSUE THREAD

**Issue by alex21** [techfort/LokiJS#183]
When I'm trying to remove entries from collection, which has unique index, an error is thrown.

Example:
```
col = new loki.Collection('collection')
col.ensureUniqueIndex('a') // problem is here
col.insert({a: 11})
col.insert({a: 12})
col.insert({a: 13})
col.remove(col.find({a: 12})[0])
```

**Comment by techfort** [comment]
@alex21  the unique index and removal of objects was just modified in a PR, maybe that's what introduced the bug. I will look into this asap.

**Comment by alex21** [comment]
Yep, sorry. I think, it's here a9aee4ae7fb7bab6dd607e6a183bddf68b85ee3b.

**Comment by alex21** [comment]
Finally, I figured out my problem:) Bower cannot install latest version of LokiJS.
I think, it would be nice to release new version (tag?), when you fixing such kind of bug.

**Comment by techfort** [comment]
@alex21 I would except tests are failing, so i need to fix that first. As soon as that's done i will release 1.3.5

**Comment by alex21** [comment]
@techfort, thanks a lot. Waiting for new version:)
