### ISSUE TITLE
Performance of findOne

### ISSUE THREAD

**Issue by cosmith** [techfort/LokiJS#192]
Hi everyone, thanks for this great DB!

I'm running into a bit of a performance issue which I find very odd considering that my dataset only has about 1000 documents.

I'm using Loki in a Cordova app, testing is done on a Nexus 5.

This is the function that I'm using to update my data: 

```js
    function _upsertMarker(collection, marker) {
        let dbMarker = collection.findOne({"pk": marker.pk});
        if (dbMarker) {
            for (let key in marker) {
                dbMarker[key] = marker[key];
            }
            collection.update(dbMarker);
        }
        else {
            collection.insert(marker);
        }
    }
```

With time logs:

```js
    function _upsertMarker(collection, marker) {
        now = new Date();
        let dbMarker = collection.findOne({"pk": marker.pk});
        console.log("endfind", new Date() - now)

        if (dbMarker) {
            for (let key in marker) {
                dbMarker[key] = marker[key];
            }
            console.log("update", new Date() - now)
            collection.update(dbMarker);
        }
        else {
            console.log("insert", new Date() - now)
            collection.insert(marker);
        }
        console.log("end", new Date() - now)
    }
```

Which gives me:

```
>>> _upsertMarker(col, {"pk": 63000, "name": "TEST"})
endfind 107
insert 109
end 112

>>> _upsertMarker(col, {"pk": 63, "name": "TEST"})
endfind 110
update 111
end 112
```

Sometimes it goes up to 400ms (!) per `findOne` call. Which makes the whole app hang/crash when I'm loading a big JSON into my db...

I am using indices and `ensureUniqueIndex`, but maybe the wrong way:

```js
    static _createCollection() {
        let collection = Database.db().getCollection(COLLECTION_NAME);
        if (collection === null) {
            console.log("[Database]", "creating collection");
            Database.db().addCollection(COLLECTION_NAME, {indices: ["pk", "latitude", "longitude"]});
            collection = Database.db().getCollection(COLLECTION_NAME);
            collection.ensureUniqueIndex("pk");
        }
    }
```

Any thoughts?

**Comment by techfort** [comment]
Hey there @cosmith - glad you enjoy using Loki!
There may something up because 400ms is a huge amount of time for a dataset that small. However, when using uniqueIndex, the fastest way to retrieve records is `by`, e.g.
```javascript
collection.by('pk', value);
```
Meanwhile I'll inspect the code to see what's up with findOne.

**Comment by obeliskos** [comment]
Our unique indexes were added after our binary search indexes so you may be duplicating index types.

Try this : 
```javascript
let collection = Database.db().getCollection(COLLECTION_NAME);
if (collection === null) {
  console.log("[Database]", "creating collection");
  Database.db().addCollection(COLLECTION_NAME, {
    indices: ["latitude", "longitude"],
    unique: ['pk']    
  });
  collection = Database.db().getCollection(COLLECTION_NAME);
}
```

And then, when querying, as @techfort suggested, use collection.by()

**Comment by cosmith** [comment]
Awesome! It's super fast now (< 1ms) ;)

The 400ms was weird, but it might be related to some other code that's running on the app at the same time... not sure.

Thanks anyway!

**Comment by cosmith** [comment]
@obeliskos I'm having issues when removing `collection.ensureUniqueIndex("pk")`; taking a look at the code I would expect something similar to the `ensureIndex` call in the Collection constructor? 

Like here:
https://github.com/techfort/LokiJS/blob/9509ceea090634936e7ecec9b05db454bf4e5119/src/lokijs.js#L2658-L2660 
Is there any reason why there is not something like this?

```js
      for (var idx = 0; idx < unique.length; idx++) {
        this.ensureUniqueIndex(unique[idx]);
      }
```

Also I'm having issues when loading the database with the indexedAdapter, it looks like the ensureUniqueIndex is not persisted somehow. `collection.constraints` is empty when I load the db so `.by()` fails here: https://github.com/techfort/LokiJS/blob/9509ceea090634936e7ecec9b05db454bf4e5119/src/lokijs.js#L3269

What do you think? A solution is for me to call `collection.ensureUniqueIndex("pk")` every time I load the db.

**Comment by techfort** [comment]
@cosmith the behaviour you described will be supported in the future but for the moment calling `ensureUniqueIndex` after load is the only way. While not optimal, i tried to highlight this in the docs: "IMPORTANT: unique index are NOT serialized for persistence. As they use in memory references it is not practical to serialize them. Just explictly call the function after you create a collection or after you loaded a database.".
Serialization is coming too!

**Comment by cosmith** [comment]
@techfort Ok, sorry for not reading the docs! My fault entirely.

**Comment by techfort** [comment]
@cosmith no bother! The behaviour you describe is what we're aiming for.

**Comment by obeliskos** [comment]
I have made a commit which automatically regenerates unique constraints on database load.  Keep that in mind as you upgrade versions this workaround will need to be removed soon.

**Comment by adueck** [comment]
> when using uniqueIndex, the fastest way to retrieve records is `by`, e.g.
> 
> ```js
> collection.by('pk', value);
> ```

@techfort Is this still true now in 2020? And does that mean that `by` is faster than `findOne` always, or just if we're using a unique index on our `findOne` searches.

I have a field which is unique, but I don't care about enforcing the uniqueness... I often need to query for documents based on that field, and I'm wondering **which would be the fastest way**:

1. Using unique index and `by`

```js
const collection = lokidb.addCollection("myCol", {
    unique: ["f"],
});

// then make queries with
collection.by("f", "value");
```

2. Using regular index and `findOne`

```js
const collection = lokidb.addCollection("myCol", {
    indices: ["f"],
});

// then make queries with
collection.findOne({ f: "value" });
```

In my case, the f field is guaranteed to be unique, but I don't care about enforcing uniqueness on insert into lokijs.

Thank you so much!
