### ISSUE TITLE
Enhancement Request: $text query operator

### ISSUE THREAD

**Issue by toddpi314** [techfort/LokiJS#193]
LokiJS could use some intelligent search features.

The Mongo-like API for this is the [$text operator](http://docs.mongodb.org/manual/reference/operator/query/text/#op._S_text).
This approach is really similar to `like` matching but also employs stemming.

If you are new to stemming,  [natural](https://github.com/NaturalNode/natural) has a pretty solid implementation if your willing to take in a larger dependency.

**Comment by techfort** [comment]
sound - i like the idea. Let me look into it and see what can be done, meanwhile I'll include it in 1.4.0

**Comment by techfort** [comment]
@toddpi314 by the way - i'm writing a few experimental modules utilizing SVMs and ANNs for classification of records, using the Bag-Of-Words algorithm to vectorize text. At insert or update a record would get classified, and ideally a dynamicview per class would exist providing access to records that have been classified in a similar way.  Hopefully if i get more than one classification mechanism going i could also implement some kind of ground-truth algorithm to increase accuracy.

**Comment by toddpi314** [comment]
I have had luck using synonym nets to drive bounded k-means groups. That has a hard dependency on a fidelity language set for WordNet though. Otherwise, you are stuck with using 'meaningless patterns' alone to do your unsupervised training.

Combine a quick 'route' based on meaning to SVM (for outliers) and you could have some pretty intelligent lookup feature.

"We aim above the mark to hit the mark." - Emerson
