### ISSUE TITLE
this.filename in Loki.prototype.getName

### ISSUE THREAD

**Issue by AtomicAntimatter** [techfort/LokiJS#198]
As it currently is

```
Loki.prototype.getName = function () {
     return this.name;
};
```

As it should be?

```
Loki.prototype.getName = function () {
     return this.filename;
};
```

This would seem to make more sense since `this.name` is not saved in the Loki class.  
However, it is loaded in `Loki.prototype.loadJSON`.

```
this.name = obj.name;
```

Should it be changed to this?

```
this.filename = obj.filename;
```

**Comment by techfort** [comment]
@AtomicAntimatter sounds like you're right, I will definitely look into this. If you feel like a PR with a few tests to confirm the correctness of the fix go ahead so you get the credit for it.
