### ISSUE TITLE
Unexpected findOne Behavior  "lokijs": "^1.3.7",

### ISSUE THREAD

**Issue by jrhicks** [techfort/LokiJS#203]
When I search by last name and first name I get the expected matching object:

    resources.findOne({l:'Callahan', f:'Jason'})

    Object {id: 1693, updated_at: "2015-06-01T08:28:15.000-05:00", b: "7U2BBB3L", f: "Jason", l: "Callahan"…}

When I search by the id, I do not get a match.  Although I do sometimes.

    resources.findOne({id: 1693})
    null

When I search by first name and last name (changed order), I get the first object matching first name but doesn't match last name.

    resources.findOne({f: 'Jason', l:'Callahan'})
    Object {id: 10693, updated_at: "2015-06-17T08:44:15.000-05:00", b: "G2Z", f: "Jason", l: "Covington"…}

**Comment by Alex-Werner** [comment]
Wow ! Didn't saw that one coming during all my tests =O
Can you share a little gist with the code ? To repeat the same on my computer and try to see where the problem come from ?

**Comment by jrhicks** [comment]
But was on my end.... do not ... I repeat ... do not update a record to the wrong collection.

**Comment by techfort** [comment]
@jrhicks well... actually - having a mechanism to prevent that wouldn't be so bad! *takes notes*

**Comment by obeliskos** [comment]
It appears you may also be using an unsupported 'and' syntax?

I have started a long overdue wiki page to quickly describe the $and syntax.  (Will continue to fill out docs as time permits).

https://github.com/techfort/LokiJS/wiki/Query-Examples

**Comment by techfort** [comment]
that's awesome @obeliskos - thanks for that!

**Comment by jrhicks** [comment]
You all rock!
