### ISSUE TITLE
Loki.prototype.loadJSON does not save the database

### ISSUE THREAD

**Issue by tlkiong** [techfort/LokiJS#204]
I realize that once I execute this function by passing in a database string and then I restart my Cordova app, the data is not saved.

It is saved only after I call "saveDatabase" before I restart my app.

Is this by design?

**Comment by techfort** [comment]
if i understand you correctly then yes, this is the expected behaviour. If you want to share some code or illustrate the desired behaviour we can take a look?

**Comment by tlkiong** [comment]
Well, I expected when I were to call
    Loki.prototype.loadJSON
It will automatically save the database after finish loading the JSON into memory instead of manually calling saveDatabase.

If it is possible at all, can I know why is it designed in this manner?

**Comment by techfort** [comment]
I suppose the simplest answer would be that if you're just finished loading
the db then you had correctly saved data in the first place, so I didn't
think it needed to be re-saved immediately.
That said, you can pass a callback and save?

**Comment by tlkiong** [comment]
Yup. I can :)

Al right then. Thanks a lot for the clarification.
