### ISSUE TITLE
Unexpeted results when using the "$contains" operator

### ISSUE THREAD

**Issue by pignion** [techfort/LokiJS#205]
Unless I'm misunderstanding the usage, the '$contains' operator does not seem to produce expected results. 

In this example I add items all that have their "test" property set to various types, including some with a string that I want to search for:
```
var db = new loki('testdb');
db.addCollection('testcollection')
  .insert([
    {test:'zzz' },
    {test: ['zzz'] },
    {test: {aaa:'zzz'}},
    {test: null },
    {test: [null] },
    {test: false},
    {test: true},
    {test: 0 },
    {test: 123},
    {test: {}},
    {test: []}
  ]);

var results = db.getCollection('testcollection')
    .find({'test': {'$contains': 'zzz'}});

console.log(results);

```
After searching for items where the "test" property contains "zzz" I get the following result set:

```
[ 
    {"test":123, "meta":{"revision":0, "created":1438839466380, "version":0}, "$loki":9},
    {"test":0, "meta":{"revision":0, "created":1438839466380, "version":0}, "$loki":8},
    {"test":true, "meta":{"revision":0, "created":1438839466380, "version":0}, "$loki":7},
    {"test":false, "meta":{"revision":0, "created":1438839466380, "version":0}, "$loki":6},
    {"test":null, "meta":{"revision":0, "created":1438839466380, "version":0}, "$loki":4},
    {"test":["zzz"], "meta":{"revision":0, "created":1438839466380, "version":0}, "$loki":2},
    {"test":"zzz", "meta":{"revision":0, "created":1438839466380, "version":0}, "$loki":1}
]

```
That last two results seem reasonable since the value of foo "contains" the search string, but the rest don't make much sense to me.

**Comment by pignion** [comment]
My hope in using $contains in the first place was that it would allow me to search for values that were at times arrays containing the search term, so hopefully the fix preserves this functionality. In other words, the example would return the following:
```
[ 
    {"test":["zzz"], "meta":{"revision":0, "created":1438839466380, "version":0}, "$loki":2},
    {"test":"zzz", "meta":{"revision":0, "created":1438839466380, "version":0}, "$loki":1}
]
```

**Comment by obeliskos** [comment]
I believe @KimSchneider added the implementation for those ops, so ideally he might fix this but i'm not sure if he is monitoring this.  If not, I will take a look at it over the weekend to see if I can better understand what he was trying to do.  Your expectation of behavior sounds reasonable.

**Comment by KimSchneider** [comment]
I didn't change the default behaviour but that was a bug, you are right :)
https://github.com/techfort/LokiJS/pull/206

**Comment by obeliskos** [comment]
Thanks!  Looks great and I believe it performs exactly as mentioned.

**Comment by techfort** [comment]
@pignion i'll wait for you to confirm that `$contains` now works as expected.

**Comment by pignion** [comment]
:+1: 
Thanks @techfort and @KimSchneider, it works as exactly expected now.

**Comment by techfort** [comment]
cool!
