### ISSUE TITLE
removeWhere throws an error Object is not a document stored in the collection

### ISSUE THREAD

**Issue by shivambarsaley** [techfort/LokiJS#207]
I am able to find the objects using
 `this.surveyResponses.find({sid:surveyID}`

Though when I try deleting them via
`this.surveyResponses.removeWhere({sid: surveyID})`
 It throws the above error

**Comment by techfort** [comment]
Hi @shivambarsaley - the error thrown sounds strange. Are you sure you're not working with a copy of the object that does not contain the `$loki` and `meta` properties? if those properties are missing then the db will think the object is not in the collection.

**Comment by techfort** [comment]
@shivambarsaley have you any more feedback on this? I'll close the issue as tests show this is working correctly, however if you still experience problems let me know and i'll re-open.

**Comment by zakalibit** [comment]
I'm getting the same error, what do you mean under a copy? I do insert a document, then I see it in file, there is no meta assigned to it. Then I can find it but can not remove it with the same error as above.

**Comment by zakalibit** [comment]
had to use clone: false while creating the collection, without that the user in the database file has no meta, so there is no way to delete it.

**Comment by zakalibit** [comment]
then I removed clone from the collection creation and it still works, that is strange.

**Comment by obeliskos** [comment]
Can you provide an example of how you are using removeWhere()... are you passing function or query object?

**Comment by zakalibit** [comment]
actually I use find, then pass the result in to remove, as removeWhere returns no feedback if anything was removed.

var u = users.find({'name': user});
if (u && u.length) {
  users.remove(u);
}

it works now for some reason, I'll be doing more testing and will try to get a reproducible set of steps.
