### ISSUE TITLE
Hello world documentation missing right curly brace

### ISSUE THREAD

**Issue by gprimosch** [techfort/LokiJS#208]
on the home page http://lokijs.org:

> legs.applyFind( { legs: { '$gt' : 2 } )

should be:

> legs.applyFind( { legs: { '$gt' : 2 } } )

**Comment by gprimosch** [comment]
Would also be nice to have the require call added there for us newbs.

**Comment by techfort** [comment]
thanks @gprimosch - i'll open these as issues in the website repo.

**Comment by obeliskos** [comment]
this appears to have been already fixed

**Comment by obeliskos** [comment]
Hmm well it was fixed in repo but not migrated to website yet
