### ISSUE TITLE
Update bower tag

### ISSUE THREAD

**Issue by rgksugan** [techfort/LokiJS#209]
Hi,

The current version in bower is a bit outdated. The current bower version doesn't work with gulp plugins. This issue is fixed in the master branch, but not updated in the bower registry. Can you make an updated release tag.

It's not possible to add tag in a pull request, else I would have raised a pull request.

**Comment by techfort** [comment]
@rgksugan cheers -  i'll correct this as soon as possible.

**Comment by techfort** [comment]
@rgksugan I published 1.3.8, will update the website soon with the necessary docs about the transforms implemented by @obeliskos , meanwhile i'm closing this.
