### ISSUE TITLE
Dot notation

### ISSUE THREAD

**Issue by fusepilot** [techfort/LokiJS#210]
Is querying with dot notation not supported?

````
collection.findOne({property: 'value'}); // returns { property: 'value' }
```
````
collection.findOne({'nested.property': 'value'}); // returns null
```

Looked through the specs and docs and haven't seen how to do this or if it's supported.

**Comment by obeliskos** [comment]
Yes we support dot notation, your example should work fine.

I will try to add mention of it to Query Examples wiki page this weekend.

**Comment by Kanaye** [comment]
The dot notation is working in the collection.find() function,
but not in the findOne() function.
Here the [jsfiddle](http://jsfiddle.net/f7L9v5aw/4/)
Btw. LokiJS is awsome :+1:.

**Comment by techfort** [comment]
mmm - that's interesting. If that was the case then implementing it in findOne shouldn't be too difficult, what do you think @obeliskos ?
/cc @Kanaye @fusepilot

**Comment by obeliskos** [comment]
Yea, it should work the same for find() as for findOne() but I see now that it doesn't.

I've traced through and see where the fix needs to be made.  I'll fix it sometime this weekend and add a dot notation findOne test to our unit tests.

**Comment by obeliskos** [comment]
Ok I think I have fixed this as my tests pass now (with latest commit).  Let me know if you still have any problems with this.

**Comment by Kanaye** [comment]
Sorry, I just saw that this one is still open.
I have used the dot-notation with ``findOne`` quite often in the last weeks and didn't stumble across bugs with it. 
In my opinion you can close this issue.

**Comment by obeliskos** [comment]
Ah, great I had forgotten about this one as well.
