### ISSUE TITLE
Count() method

### ISSUE THREAD

**Issue by cosmith** [techfort/LokiJS#212]
Hello,

What is the fastest way of counting the number of results in a query?
The basic logic I want to achieve is something like:

```
if (query.count() < THRESHOLD) {
    get_query_results_and_display()
}
```

Of course if I'm doing the same amount of work in both lines it's not very useful... I'm wondering if I could get a way of counting that would be faster than getting the whole dataset like

```
collection.find({"$and": [
            {"latitude": {"$gte": -50}},
            {"latitude": {"$lte": 50}},
            {"longitude": {"$gte": -50}},
            {"longitude": {"$lte": 50}},
        ]}).length
```

I tried using `chain` and `.mapReduce(function (obj) {return 1}, function (arr) {return arr.length})` but it's not faster (I guess it is doing the same thing after all).

Any ideas?

**Comment by obeliskos** [comment]
Just as a test, try using the internal filteredrows variable of a chain resultset and let me know the results : 

```javascript
var docCount = collection.chain().find({"$and": [
            {"latitude": {"$gte": -50}},
            {"latitude": {"$lte": 50}},
            {"longitude": {"$gte": -50}},
            {"longitude": {"$lte": 50}},
        ]}).filteredrows.length;
```

**Comment by cosmith** [comment]
Hey @obeliskos, thanks for the tip! I'll try and I'll report the results here.

**Comment by cosmith** [comment]
So I tried it and I don't see any real difference in execution time with filteredrows. It's not really a big issue though so no worries. I'm going to close this for now.
