### ISSUE TITLE
Uncaught Error: Could not find module ./loki-indexed-adapter.js

### ISSUE THREAD

**Issue by null-null-null** [techfort/LokiJS#214]
Upgrading from 1.3.5 to 1.3.8, I now get this error:

    Uncaught Error: Could not find module ./loki-indexed-adapter.js

The relevant stack:

    indexedAdapter @ lokijs.js:369
    Loki.serialize @ lokijs.js:618
    Loki.saveDatabase @ lokijs.js:935

The problem seems to be that [here](https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L616), `this`'s `getters` key includes `indexedAdapters`.

UPDATE:

I should mention that I'm not trying to use `loki-indexed-adapter`. It's simply getting required in the background. Also, I'm not using require.js or common.js, but Ember CLI's [loader.js](https://github.com/ember-cli/loader.js). It also adds `require` to the global namespace, which is confusing loki [here](https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L434).

**Comment by obeliskos** [comment]
Yes, I encountered that issue myself... I fixed that about a week ago here : 
https://github.com/techfort/LokiJS/commit/183401caef26300f6690223d91671551b7069d95

It is a rather a nasty bug though, so maybe @techfort could expedite a revision patch.

**Comment by techfort** [comment]
Will check everything is in order and publish 1.3.9 tomorrow

**Comment by techfort** [comment]
1.3.9 released, closing this.
