### ISSUE TITLE
Data guarantees?

### ISSUE THREAD

**Issue by joepie91** [techfort/LokiJS#217]
Asking this here, since I was unable to find it in the documentation: What kind of guarantees does LokiJS provide with regards to data integrity, consistency, etc.?
- Are there any known data corruption issues? (eg. upon unexpected failure of the application)
- Is data persisted immediately, or is there a time window where data can be lost before it is written to disk?
- Is there any kind of transaction(-like) mechanism?
- How are non-primitive types (eg. JavaScript Date objects) handled? Is it possible to implement custom mappings?

**Comment by techfort** [comment]
@joepie91 hey Sven,
let me answer you to the best of my knowledge.

1. there are no known data corruption issues, there are also no fallback / backup / rescue mechanism. These are at the moment an onus of the developer, although they are on my to-do list.  At the moment the most LokiJS does in this respect is described below at answer number 3.
2. data is persisted when saveDatabase() is called, or every X ms (with X being the `autosaveInterval` value in milliseconds passed in the database constructor (see [here](http://lokijs.org/#/docs#db))
3. Short answer is no. Long answer is: there is an internal `commit` / `rollback` mechanism that prevents the db from wiping the data if anything went wrong during a write / update/ delete operation, by rolling back to the state the db was in before the operation itself and throwing an error.
4. default serialization is `JSON.stringify` at the moment you can't serialize in a custom fashion, but you can load objects into prototypes (see [here](http://lokijs.org/#/docs#load)). Ideas in this respect are welcome. I had started work on a custom serializer for fixed-schema objects in this [project](https://github.com/techfort/jumble) but I didn't get very far in terms of testing and my attention got derailed onto other projects.

LokiJS is regrettably still a bit immature in this respect, but then again, Loki remained a trickster till Ragnarok.

**Comment by obeliskos** [comment]
Everything @techfort said sounds spot on.  

I will just mention that the db can be flushed if you are shutting down by calling db.close(), however the success of a final flush (if changes are pending) depends on the adapter being synchronous.  Of all our adapters so far, only indexeddb is asynchronous, so issuing a db.close() in an onbeforeunload event of a web page if you have pending changes will not likely have an effect.
