### ISSUE TITLE
Error while clearing a collection

### ISSUE THREAD

**Issue by tonkonogov** [techfort/LokiJS#220]
I have a collection with 2 records that were inserted by `Collection.insert`. After that I try to clear the collection with `collection.chain().remove()` (as it was proposed in #75) and receive this:

    Uncaught Error: Parameter is not an object

I've investigated it and found that the issue happens here
https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L2026

`this.collection.data` is in fact an array. Thus `Object.keys` returns a set of numeric keys but casted to strings. After that `this.collection.remove` fails on using such key, because it is obviously not a number and not an object to delete as well. 

The core question is - is it a bug or I've missed something important?

**Comment by techfort** [comment]
@tonkonogov that seems to be a bug alright. Will look into this today - i'll cc @obeliskos as his understanding of resultsets internals is top notch.

**Comment by obeliskos** [comment]
I know it worked once, but i had no unit tests for resultset.remove, so yea... somehow that broke...

I believe i have fixed the error, let me know if that fixes for you.  Will add unit tests in a day or so.

**Comment by tonkonogov** [comment]
Just checked - it works well for me

**Comment by obeliskos** [comment]
Great... unit test has been added now so I will close this.
