### ISSUE TITLE
Possible bug: compoundsort

### ISSUE THREAD

**Issue by countermeasure** [techfort/LokiJS#222]
I'm using compoundsort like so:
```
.compoundsort(['theDate', 'theTime'])
```
`theDate` is a date object, `theTime` is a string representing a 24 hour time, such as "22:00".

I'm assuming that `compoundsort` should first sort by `theDate` in ascending order, and then sort records with identical `theDate` values by `theTime` in ascending order.

What happens though is that it sorts by `theDate` in ascending order, and then sorts by `theTime` in *descending* order.

If I switch the field order like so:
```
.compoundsort(['theTime', 'theDate'])
```
then sorting on both fields is done in ascending order, as expected.

If I set the sort order of `theTime` explicitly like:
```
.compoundsort(['theDate', ['theTime', true]])
```
or
```
.compoundsort(['theDate', ['theTime', false]])
```
it makes no difference and `theTime` is still sorted in descending order.

**Comment by obeliskos** [comment]
Could you give me some specific examples of test records to insert into a collection to reproduce this?  (Or a plunker or similar)

Sounds like the string time is not formatted in way that string comparisons do not necessary match the semantics you are reading into them?  Such as '9' > '11' in string terms?  Test documents should clear up if you can provide some.

**Comment by countermeasure** [comment]
The time string has a leading zero for single hour times, so we should still get correct sorting for all times, I think. eg. 3am is represented as "03:00".

You can try this data: 
```
var testData = [
  {id: 1, theDate: new Date(2015, 8, 18), theTime: "03:00"},
  {id: 2, theDate: new Date(2015, 8, 18), theTime: "22:00"},
  {id: 3, theDate: new Date(2015, 8, 18), theTime: "12:00"},
  {id: 4, theDate: new Date(2015, 8, 19), theTime: "23:00"},
  {id: 5, theDate: new Date(2015, 8, 19), theTime: "06:00"},
  {id: 6, theDate: new Date(2015, 8, 19), theTime: "14:00"},
  {id: 7, theDate: new Date(2015, 8, 20), theTime: "12:00"},
  {id: 8, theDate: new Date(2015, 8, 20), theTime: "11:00"},
  {id: 9, theDate: new Date(2015, 8, 20), theTime: "15:00"}
];
```
It's a simplified representation of what I'm doing, and should produce similar behaviour I described above (I hope!).

**Comment by obeliskos** [comment]
Thanks, this appears to be the same issue of dates never being equal.  Only if they are equal, do we bother to compare the next property in the list.  I was able to do a diagnostic fix which corrected this and produce the expected behavior.  

Since this is related to many instances where we use this compare logic, I am going to address this bug as part of your more general Date equality bug issue.   If you are on a time constraint, let me know and I can supply you a temp fix.

**Comment by countermeasure** [comment]
If it's easy to describe a temporary work-around strategy, I'd be interested to hear it, but only if it's no stress for you to explain it.

I can wait for the broader date comparison bug fix.

**Comment by obeliskos** [comment]
You could use the sort() method instead and pass it your own custom sort function.  It would probably look like : 

```javascript
function mysort(obj1, obj2) {
    if (obj1.theDate > obj2.theDate) return 1;
    if (obj1.theDate < obj2.theDate) return -1;    
    
    if (obj1.theTime > obj2.theTime) return 1;
    if (obj1.theTime < obj2.theTime) return -1;
    
    return 0;
}

var results = coll.chain().sort(mysort).data();
```

Or you could just pass that sort function as anonymous function.

**Comment by countermeasure** [comment]
@obeliskos, Thanks.
