### ISSUE TITLE
Dot notation error when a field has a value of null

### ISSUE THREAD

**Issue by countermeasure** [techfort/LokiJS#223]
When querying using dot notation like so

```
.find({'myField.id': id})
```

LokiJS seems to throw a

```
TypeError: root is null
```

error if any document in the collection has a `myField` with a value of null.

My workaround is to chain another `find` in front of my main `find` to exclude all records with a `myField` of null:

```
.find({'myField': {'$ne': null}}).find({'myField.id': id})
```

I find myself doing this frequently, and in places where I'm just doing a simple find and wouldn't otherwise need to chain filters together.

If a query using dot notation could ignore any documents with a null value for the field being queried on, that'd be pretty nice!

**Comment by obeliskos** [comment]
Should be fixed now, let me know if you still have issues.

**Comment by countermeasure** [comment]
@obeliskos, Fast! Thanks!

I'm using this as a Node module and am unsure how to install the latest code directly from Github, so will probably wait until the next release appears on npm.
