### ISSUE TITLE
Better error management and documentation

### ISSUE THREAD

**Issue by acanimal** [techfort/LokiJS#228]
Hi let me explain my problem so you can help me find a solution or consider this issue a future improvement to do.

Hi, I'm using loki with `try/catch` for managing errors. Right now errors seems a simple message, for example: `Duplicate key for property username...`.
My application needs to return different HTTP messages depending if the error is due a duplicated key, a key not found or a system error and, with the current loki error implementation it is hard to detect the type of error.

It would be great if Error objects contains a `status`, like in node style, with the error number or each error was a concrete subclass. I look for something I can compare quickly like: `error instanceof DuplicatedError` or `error.code === LokiJS.Errors.DUPLICATED_KEY`.

On the other hand I'm finding a bit complex to know the API documentation. The one existent at http://lokijs.org/#/docs is not enough and the project wiki seems not perfect too. For example I saw collections accept options, like `unique` not very well documented. Are there any other resources?

A side of criticism, I would like to contribute with my 5cents on the project and I think I can try to improve the doc using some kind of tool like jsdoc3. This way the docs could be synchronised with the code. What do you think?

**Comment by techfort** [comment]
@acanimal all good points. Yes defining the nature of an error definitely helps managing errors in a better / safer way.
Will see what i can come up with, it could be a case of breaking backward compatibility and a major version release.

**Comment by moshewe** [comment]
+1
Had to find out how some things in the library work from reading strings in the debugger...
