### ISSUE TITLE
Comparison Query not working

### ISSUE THREAD

**Issue by g21wadhwa** [techfort/LokiJS#229]
collection.find({$and:
[{ securityId: { '$in': [ '13063CJR2', '87638TAR4', '343136L62' ] },
  tradeTypeInd: 'S',
  price: { '$gte': 110 ,'$lte':120} }]})

Output: Price filter comparison not working.its only taking the last '$lte' filter phrase.

Please advise.

**Comment by obeliskos** [comment]
Your syntax looks a little off, try this format : 
```javascript
collection.find({
    $and: [
    { securityId: { '$in': [ '13063CJR2', '87638TAR4', '343136L62' ] } },
    { tradeTypeInd: 'S' },
    { price: { '$gte': 110 ,'$lte':120} }
]});
```
If that doesn't work perhaps post a plunker or work up a sample in our sandbox and post it as a gist.

**Comment by obeliskos** [comment]
actually your last 'and' clause probably needs expanding to another $and op such as : 

```javascript
collection.find({
    $and: [
    { securityId: { '$in': [ '13063CJR2', '87638TAR4', '343136L62' ] } },
    { tradeTypeInd: 'S' },
    { '$and': [ 
        { price: {'$gte': 110 } }, 
        { price: {'$lte':120 } }
    ]}
]});
```
Possibly in the future we will support simpler 'and' constructs as comma delimited expressions but for now, the above should do what you think it should.

**Comment by g21wadhwa** [comment]
That worked.Thanks for quick reply.

one more question:
 How to use $in in where options.

Ex:  collection.where(function(obj){
                       return obj.status $in ['M','S']
});

I hope my question is not confusing.

Thanks,
Gaurav

**Comment by obeliskos** [comment]
Using native javascript such as : 

```javascript
return (['m', 's'].indexOf(obj.status) !== -1);
```
javascript array provides the indexOf method and if result is -1 the item was not in it.

**Comment by g21wadhwa** [comment]
awesome.
Thanks a ton.
