### ISSUE TITLE
Loki constructor option `autoload` not checked in `Loki.prototype.configureOptions`

### ISSUE THREAD

**Issue by stefanosusini** [techfort/LokiJS#230]
It seams the `Loki.prototype.configureOptions` method doesn't check `autoload` option at all before triggering the database load:
```Javascript
        LINE: 884
        if (options.hasOwnProperty('autoload') && typeof (initialConfig) !== 'undefined' && initialConfig) {
          // for autoload, let the constructor complete before firing callback
          var self = this;
          setTimeout(function () {
            self.loadDatabase(options, options.autoloadCallback);
          }, 1);
        }
```

If `autoload` is set to `false`, it will trigger the `loadDatabase` function anyway.
Thanks :)

**Comment by techfort** [comment]
@stefanosusini good catch, grazie mille! @obeliskos i'm up the walls here, any chance you could fix this?

**Comment by obeliskos** [comment]
Thanks, should be fixed now

**Comment by stefanosusini** [comment]
Great! thanks!
