### ISSUE TITLE
Utilize Object.observe for automatic dirty checks

### ISSUE THREAD

**Issue by Cortys** [techfort/LokiJS#231]
It would be quite nice if Loki supported automatic dirty checks via `Object.observe` (if available), which would make it unnecessary to call `update()` manually.

Ideally an implementation of this feature could also check whether an indexed property was changed and unlike `update()` only mark the affected indexes as dirty.

This would make code easier and possibly even faster (since no unnecessary index rebuilds will be triggered).

**Comment by obeliskos** [comment]
I suppose feature detection is just checking if that method exists?  Quick search leads me to think maybe this is supported as of node.js version 12.0 (regular -and- harmony)? I suppose all objects could register the same callback and we could dig out the $loki id when it fires.  Would probably need throttling too.

Not sure what @techfort's thoughts on this are, so we'll see what he thinks.  Is this something you would be interested in contributing or just curious?

**Comment by Cortys** [comment]
Sure. I'd like to help with this feature. I would have already started sketching it out if I were more familiar with the codebase. Would you simply add the observers in `loadJSON` and `insert` or are there other ways for an object to get into Loki?

**Regarding Object.observe support:** Yes. As far as I know Object.observe is enabled without runtime flags in Node 0.12+, Chrome 36+ and Opera 30+.

**Comment by techfort** [comment]
@Cortys the idea is nice, however in the future i'd like object clones to be returned from insert/update/read operations, which means you'd be monitoring the wrong object with `observe()`. Or do I misunderstand what you're saying?

**Comment by Cortys** [comment]
@techfort You are right. When working with clones this feature would not be useful.

Now that you mention it, how would clones and the object inflation feature play together?

**Comment by techfort** [comment]
@Cortys the current default inflation pattern is already a clone of sorts, because inflating objects from serialized json effectively creates a new object from a constructor function then copies properties from the source object to the new destination object. So this would not change. If anything, leveraging ES2015 will make it easier to inflate json into a prototype by doing `Object.assign( (new MyObject()), srcObject)`

How does it sound?

**Comment by Cortys** [comment]
@techfort Right, that's when creating the objects. When reading however, do I get a newly inflated instance for each query or do I always get the same inflated object?

**Comment by techfort** [comment]
@Cortys I suppose this would really be optional. If the user needs a full prototype copy at each read he/she should be able to specify so. Probably by specifying a `clone` function? I mean it's all very much optional so it can go to any level of complexity.

**Comment by Cortys** [comment]
@techfort I see. So getting the actual objects instead of clones will still be possible, right?

**Regarding the `Object.observe` idea:** I think it would be useful with or without the clone feature. When clones are used, those could be observed as well and changes can then be reproduced at the corresponding DB internal object.

**Comment by techfort** [comment]
@Cortys absolutely! If you want to draft that up i'd be curious. And yes, getting the actual objects will be possible.

**Comment by Cortys** [comment]
@techfort Great! I'll take a look at it this weekend.

One question: Would you simply attach the observers in `loadJSON`/`loadDatabase` and `insert` or are there other ways for an object to get into Loki?

**Comment by techfort** [comment]
Those are the only ways. And of course insert()

**Comment by Cortys** [comment]
Implementation for this merged in #233.

**Comment by thomaschampagne** [comment]
Just for my own understanding...

What is the explanation behind "dirty" term in lokijs?

Thanks for your help

You can let this ticket closed :)

**Comment by techfort** [comment]
dirty is usually a flag to indicate that an object's state has changed and its cache representation is stale @thomaschampagne

**Comment by thomaschampagne** [comment]
@techfort Thanks for the clarification 👍
