### ISSUE TITLE
bug in save/load URL params in jquery sync adapter

### ISSUE THREAD

**Issue by antonioaguilar** [techfort/LokiJS#243]
I found a small bug/typo on the save/load URL params passed to the jquery sync adapter: 

File: LokiJS/src/jquery-sync-adapter.js
Line: 37
```javascript
if (!options.saveUrl || !options.loadUrl) {
```

should be:
```javascript
if (!options.save.url || !options.load.url) {
```
otherwise the adapter throws an error indicating that the load/save URLs are not specified.

**Comment by obeliskos** [comment]
I believe this was fixed with issue #244. 

Closing.
