### ISSUE TITLE
Uncaught TypeError: this.persistenceAdapter.saveDatabase when using jQuery Sync Adapter

### ISSUE THREAD

**Issue by antonioaguilar** [techfort/LokiJS#244]
I've been trying to use the jQuery Sync Adapter with the following code:

```javascript
var options = {
  ajaxLib: 'jquery',
  save: {
    url: 'http://requestb.in/1i6am5u1'
  },
  load: {
    url: 'http://requestb.in/1i6am5u1'
  }
};

var jqueryAdapter = new lokiJquerySyncAdapter(options);
var db = new loki('users', {adapter: jqueryAdapter});
var users = db.addCollection('users');

for (var i = 0; i < 5; i++) {
  users.insert({_id: i, name: 'user-' + i});
}

console.log(users);
db.saveDatabase();
```

but I'm getting the following error: 

```javascript
Uncaught TypeError: this.persistenceAdapter.saveDatabase is not a function
```
I'm unable to save the Loki database to a remote RequestBin. 

Any ideas or suggestions on what is causing the bug?

***Note: the code above assumes that the typo in the jquery-sync-adapter has been fixed, see issue #243***

**Comment by obeliskos** [comment]
Not sure this was ever tested fully so thanks for reporting.  @techfort wrote it a long time ago so normally I would let him fix but he may be out for a while, so I went ahead and did it.

Let me know if that works out for you.
