### ISSUE TITLE
DynamicView and limit number of results

### ISSUE THREAD

**Issue by awesomelin** [techfort/LokiJS#247]
Hey, 

Whats the best approach to limiting the number of results returned from a DynamicView.data() call?

I'm using a view together with ng-repeat, and want the capabilities of a ResultSet - limit, offset. Ideally I'd like to only return only X records to ng-repeat, and when user adds extra, or requests extra records, I would expand the result set limit.

Thanks for your help.

**Comment by obeliskos** [comment]
You can use the branchResultset() method, which will give you a copy of its current, internal resultset, which you can transform however you want.

Might look something like : 
```javascript
var someGridData = dv.branchResultset().offset(100).limit(10).data();
```

**Comment by awesomelin** [comment]
Thanks, that's what I was looking for.
