### ISSUE TITLE
Collection transform using $regex query converts Regex value to empty object on save

### ISSUE THREAD

**Issue by paddeee** [techfort/LokiJS#248]
When using saveDatabase with a persistent adapter, I'm losing collection transform state for regex values. I guess because the database is getting JSON.stringified leading to Regex values being converted to {}?

Should the full collection transform state be able to persisted?

**Comment by obeliskos** [comment]
Ok, so I had to read back through my implementation of this to remember... and i'm not that great with regular expressions so feel free to offer alternatives...

We are currently passing your regular expression and creating an instance of RegExp() with what you pass.  For most raw regular expressions, this compiles into the same thing.  You can however pass a string representation of your regular expression and it should work ok.  

The encoding may be different, requiring escaping for backslashes, or for my simple substring test of **/o/** this just needs a string of "o". 

Some of the other transform steps like 'where' also point to functions which cannot be persisted.  This is one reason why I added parameterization.  In those cases, after reloading a saved transform, you would pass parameters when running them to late bind those values.

So I think regex can be persisted if you use strings.  Feel free to experiment on your own and let me know if there are issues.

**Comment by paddeee** [comment]
Thanks @obeliskos for responding so quickly. LokiJS is absolutely fantastic, BTW!

I'm no expert myself on Regex unfortunately. Far from it. I've had a bit of a mess around and not been able to crack it so far. I think my issue may be due to wanting to use a Regex 'modifier' for case-insensitive searching .

The query I'm using for the transform is using something like this, using the 'i' modifier for case-insensitive searching. I've tried used a string representation below:

$regex = new RegExp('m', 'i').toString();

which outputs this:

"/m/i"

When this gets passed to the Regex in Loki, it becomes a Regex without a modifier and with the 'i' modifier as part of the string to match.

I'm off to read up on parameterisation as from your above post it looks like this may be the way to handle a modifier in a Regex.

**Comment by obeliskos** [comment]
Hmm, yes that would be an issue.  If it was a string, we were only using the 'pattern' part of the RegExp constructor.  I made a change to allow you to pass in array of two strings, for your example :  ['m', 'i'] to use as the $regex value part of a find expression.

Parameterization would have worked but if you use new array syntax it should persist as well.

Let me know if you have any issues with this.

**Comment by paddeee** [comment]
Brilliant! :-)

Thanks very much for the change @obeliskos

**Comment by obeliskos** [comment]
Great, i'll add a test case sometime this weekend to make sure it stays working like this.
