### ISSUE TITLE
"TypeError: undefined is not a function" in this.DynamicViews[dv].rematerialize()

### ISSUE THREAD

**Issue by RangerRick** [techfort/LokiJS#249]
I'm getting an error when attempting a removeWhere() in LokiJS 1.3.10:

```javascript
100   752891   error    TypeError: undefined is not a function
    at LokiEventEmitter.Collection.removeWhere (http://192.168.211.144:8100/lib/lokijs/src/lokijs.js:3331:31)
    at http://192.168.211.144:8100/scripts/opennms/services/Servers.js:244:9
    at processQueue (http://192.168.211.144:8100/lib/angular/angular.js:14745:28)
    at http://192.168.211.144:8100/lib/angular/angular.js:14761:27
    at Scope.$eval (http://192.168.211.144:8100/lib/angular/angular.js:15989:28)
    at Scope.$digest (http://192.168.211.144:8100/lib/angular/angular.js:15800:31)
    at Scope.$apply (http://192.168.211.144:8100/lib/angular/angular.js:16097:24)
    at HTMLElement.<anonymous> (http://192.168.211.144:8100/lib/ionic/release/js/ionic-angular.js:11656:13)
    at HTMLElement.n.event.dispatch (http://192.168.211.144:8100/lib/jquery/dist/jquery.min.js:3:6466)
    at HTMLElement.r.handle (http://192.168.211.144:8100/lib/jquery/dist/jquery.min.js:3:3241)
```

My database is set up like this (ish):

```javascript
var db = new Loki('foo', {
    autosave: true,
    autosaveInterval: 5000,
    autoload: true
});
var collection = db.addCollection('bar', { transactional: true });
```

And the general usage of the database is like so:

```javascript
collection.insert({id: '12345', name:'blah'});
collection.insert({id: '23456', name:'ergh'});

var serverNames = collection.chain().simplesort('name').data().map(function(obj) {
    return obj.name;
});
var server = collection.findObject({id: '12345'});
server = collection.findObject({name: 'ergh'});

collection.removeWhere({id:'12345'});

**Comment by RangerRick** [comment]
If I add some debugging to log 'dv' and the view, I get:

    dv=difference
    view=undefined

I don't grok LokiJS's internals very well, but I guess there's a dynamicview that's somehow set to undefined?

**Comment by obeliskos** [comment]
Yea, that call to rematerialize views is not needed in removeWhere... so i removed it.  

rematerialize should only be needed after inflating a serialized loki database in loadJSON().

Let me know if it works for you now.

**Comment by RangerRick** [comment]
Yup, works for me, thanks!

**Comment by RangerRick** [comment]
Sorry for bothering, but are there plans to make a new release with this fix?  Would love to not be using a patched version in production.  Thanks!

**Comment by obeliskos** [comment]
@techfort does all the releases and he has had a lot of things going on lately.  Hopefully he gets a few minutes here or there to do this soon.

**Comment by techfort** [comment]
hey @RangerRick @obeliskos i published 1.3.11 ! Docs will be outdated for a little while because i'm completely up the walls but at least the new version is up.

**Comment by obeliskos** [comment]
Thanks :)

**Comment by RangerRick** [comment]
Awesome, thank you so much!
