### ISSUE TITLE
EnsureUniqueIndex not working properly

### ISSUE THREAD

**Issue by tkambler** [techfort/LokiJS#250]
I am unable to use a collection's `ensureUniqueIndex()` method. Even when a single document exists, a `duplicate_key` error is thrown. Here is a [simple application](https://dl.dropboxusercontent.com/u/832215/loki-test.zip) that demonstrates the problem. Run it once (`$ node index`) - no problem. Run it twice - problems.

**Comment by tkambler** [comment]
After further investigation, it appears that the problem is due to my having called `ensureUniqueIndex()` each time the db is loaded. I am doing this as a result of the following statement in the documentation:

>> IMPORTANT: unique index are NOT serialized for persistence. As they use in memory references it is not practical to serialize them. Just explictly call the function after you create a collection or after you loaded a database.

Is this no longer the case? If not, the docs should be updated to indicate so.

**Comment by obeliskos** [comment]
Yea, we did add that functionality.  We can bug @techfort to fix that when he gets back :)

**Comment by joehui** [comment]
I went into the same problem too.  Sounds like it's a documentation issue.
