### ISSUE TITLE
question: which persistence method for incremental saves?

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#252]
I want to make sure changes are being flushed to disk regularly. Which backend is best geared to do incremental saves?

**Comment by obeliskos** [comment]
Depends on what platform you are on.  If you are on node I would guess the default filesystem.  If you are on web, localstorage is synchronous and probably faster but limited.  

All rely on autosave and you not bogging down the cpu 100% so that the thread yields and allows the save within the interval.

Elaborate if you need more.

**Comment by retorquere** [comment]
I'm in a Firefox extension, which is I guess halfway between node and web. I have access to the filesystem, but trough the FF chrome API, not node.

So you're saying the saying the filesystem API is fastest, even when that means (I guess) that the whole must be rewritten for each change I intend to save?

**Comment by obeliskos** [comment]
currently loki saves the entire database to disk no matter what adapter you use.  how large do you expect your database to grow to?

Not familiar with ff (chrome?) api but possibly an adapter could be written specifically for it.  otherwise, being browser based your choice is localstorage or indexeddb.

**Comment by retorquere** [comment]
Size will vary, ranging from 1MB to 30MB I think.

**Comment by obeliskos** [comment]
I am unfamiliar with the storage mechanisms available to Firefox extensions.  Local storage and indexed db are usually granted storage 'per-domain' and I don't know that an extension has a domain.  I would also be interested to know how easy it would be to do filesytem access but google is not yielding me a quick answer right now.

For all storage methods, we use a combination of a timer and a dirty flag to determine whether we need to flush the entire database.  So if no changes occur, we don't save.  I don't see saving 30mb of data taking very long to save but large databases might need higher interval than smaller databases.

We have talked in the past about persisting each collection in its own individual file but we have no timetable on this.  There is nothing preventing you from instantiating multiple loki databases, each configured for autosave and only a single collection each to optimize read and write data sizes and speeds.  You would probably need to estimate how big each collection is and its update frequency to determine if that would help.

**Comment by retorquere** [comment]
Filesystem access is super easy - single call atomic write.

**Comment by obeliskos** [comment]
Ah, great... it should be no problem then to create an adapter class which implements loadDatabase and saveDatabase interface methods and pass that in to loki constructor.

**Comment by retorquere** [comment]
I've done a little testing and a 70MB db takes about 4 seconds to save, of which about 2-2.5 seconds is spent in serialisation. That's a little much to do regularly on the UI thread. What I'm going to try:

* Load the DB at start
* Save the DB at shutdown
* Between those two, shuttle all DB activity to a web worker by echoing all activity in collection triggers, and save periodically from the worker

It's a little convoluted, and it seems a little fragile. I do have firefox indexeddb available -- but if I read the comment above correctly LokiJS also just saves the entire DB at save rather than just update changed records, so it doesn't appear there would be any benefit to using indexeddb when I have FS access available. Correct?

**Comment by retorquere** [comment]
BTW, if I call `db.save`, does that also only actually save if the DB is dirty? Or is that behaviour exclusive to auto-save?

**Comment by obeliskos** [comment]
Interesting, what class of hardware is that (cellphone, tablet, pc?).

Our indexeddb adapter is an enhanced 'key-value store' so yes... the whole database is saved.   Not sure what would be faster or more responsive for your environment.   Indexeddb adapter does support multiple databases and even multiple app contexts if you need to organize a myriad of databases within a single indexeddb store.

db.save (saveDatabase) doesn't check the dirty flags and will always save.  I added the dirty flags at the same time as autosave but they should be accurate if you manually use it like the following : 

```javascript
// if the database does not have autosave functionality turned on 
// you can use this for manual dirty checks
if (db.autosaveDirty()) {
  db.save(function(err) {
    if (err) {
      throw(err);
    }
    db.autosaveClearFlags();
  });
}

**Comment by retorquere** [comment]
Cool, I can use that. 

This is on a PC (a Macbook to be exact) with an SSD.

**Comment by retorquere** [comment]
BTW, please don't change the save behavior. It's great as it is, and I make use of the fact that it always saves out when called.

**Comment by obeliskos** [comment]
I think this issue was resolved, closing
