### ISSUE TITLE
Small vs Large Collections

### ISSUE THREAD

**Issue by awesomelin** [techfort/LokiJS#253]
Are there any benefits or detriments to having many small collections vs a few large ones?

I'm caching locally a set of private messages between users. I could store one conversation into one collection and create a new one for any new conversations. This would end up with many small collections. Second approach is to have a large collection with all conversations and filter the ones I need. Is there a good reason to use one approach or the other when working with LokiJS?

Thanks!

**Comment by obeliskos** [comment]
Personally, I would use single collection if the documents all have similar structure.

Depending on the performance you need you might need to add indexes as this get larger to keep this performant.

Although loki has no real limit, I would personally not split my collection over maybe 100 collections and then only with good reason.  If they are all within a single collection I have the ability to query against the entire dataset to find what I am looking for.  Also there is probably a small amount of overhead associated with each collection instance.  Each collection emits its own events so possibly this could get noisy with many collections.

**Comment by obeliskos** [comment]
Old issue so closing, we can revisit this in the future if necessary.
