### ISSUE TITLE
question: changing index on database upgrades

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#255]
I currently serialise my DB to disk, and I see that this includes the indexes on the collections contained in it. If at some point I need to update what I want indexed on a collection, how can I do this while retaining the data? The only place I see I can specify my index is in addCollection, but after DB load, the collections + indexes are already there.

**Comment by obeliskos** [comment]
Currently there is no api for this but you can manually do this after loading / before saving : 

```javascript
// remove all binary indexes
coll.binaryIndices = {};

// Unique indexes are not saved but their names are (to be rebuilt on every load)
// This will remove all unique indexes on the next save/load cycle
coll.uniqueNames = [];
```

We probably should add a few official api methods to this... maybe in next week or so.

**Comment by retorquere** [comment]
So those remove them, but how do I add new ones?

**Comment by retorquere** [comment]
Or can I just assign to those after load to have them be rebuilt?

**Comment by obeliskos** [comment]
```javascript
// add binary index
coll.ensureIndex("lastname");

// add unique index
coll.ensureUniqueIndex("userId");
```

**Comment by obeliskos** [comment]
Those methods are covered in docs on Techfort's website also : 
http://lokijs.org/#/docs

**Comment by retorquere** [comment]
Super -- thanks!

**Comment by retorquere** [comment]
Given that I have previously declared `addCollection('cache', { indices: ['itemID', 'exportCharset', 'getCollections', 'exportNotes', 'translatorID', 'useJournalAbbreviation', 'citekey'] })`

How do I detect that I still have an index on `getCollections` after load so I can remove it?

**Comment by obeliskos** [comment]
You can examine the collection.binaryIndices object.  Plug this into loki sandbox and run it so see example : 

```javascript
var db = new loki('test');
var coll = db.addCollection('cache', { indices: ['itemID', 'exportCharset', 'getCollections', 'exportNotes', 'translatorID', 'useJournalAbbreviation', 'citekey'] });

logObject(coll.binaryIndices);
```

or I think this will work : 
```javascript
if (collection.binaryIndices.hasOwnProperty("getCollections")) {
  delete collection.binaryIndices.getCollections;
}
```

**Comment by retorquere** [comment]
Super! But then simply

```
delete collection.binaryIndices.getCollections;
```

should also work
