### ISSUE TITLE
Updates reset indices?

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#258]
I'm running the script at the bottom in the playground. If I comment out the line that says `coll.update(item);`, it runs in approx 58ms. If I leave the line in, approx 5369ms. Does an update force the index to be rebuilt? Is there a way to prevent this? 

```
var junk, adapter, coll, db, i;

db = new loki('cache');
db.addCollection('cache', { indices: ['itemID', 'exportCharset', 'exportNotes', 'translatorID', 'useJournalAbbreviation', 'citekey'] })
coll = db.getCollection('cache');

junk = 'bibtex'
for (var i = 0; i < 14; i++) { junk += junk+junk; }

for (i = 0; i < 23000; i++) {
  coll.insert({
    itemID: i,
    exportCharset: 'UTF-8',
    exportNotes: false,
    translatorID: "f895aa0d-f28e-47fe-b247-2ea77c6ed583",
    useJournalAbbreviation: false,
    citekey: 'cite-' + i,
    bibtex: junk
  });
}

var attempts = 100;
var time = 0;
for (i = 0; i < attempts; i++) {
  var start = Date.now();
  var item = coll.findOne({ '$and': [ { itemID: 22000 + i }, { exportCharset: "UTF-8" }, { exportNotes: false }, { translatorID: "f895aa0d-f28e-47fe-b247-2ea77c6ed583" }, { useJournalAbbreviation: false } ] });
  item.accessed = Date.now()
  coll.update(item);
  var done = Date.now();
  time += (done - start);
}
logText(attempts + ' finds / ' + time + 'ms');
```

**Comment by retorquere** [comment]
Inserts do not appear to trigger an index drop BTW.

**Comment by obeliskos** [comment]
The update flags all indices as dirty which should not take much time.

The findOne in that loop causes both itemID and exportNotes indices to be rebuilt and then.

Is itemID unique?  Or would could you have multiple objects with same itemID?   At first glance I would think to make itemID a uniqueIndex instead of binary index... but then you also check exportNotes so don't know if you allow dups.

Your use case of update, find, update, find (when the find is on and indexed column) is worse case.

Instead of calling coll.update() within your loop you could modify objects and push to a temporary results array (without calling update).  When loop is over update them all with forEach loop.

You may have too many indexes. You should probably employ them on properties where that column is the most significant filter for your query since usually only the first find filter in a find object or resultset chain can utilize the index (unless it is an $or statement.

**Comment by retorquere** [comment]
The flagging is fast, but the consequent rebuild is not.

The itemID is not unique; the combination of the indices is. I could in principle just create a simple uniqueindex on the collection and then concatenate the search fields into a single string if you think that'll be faster. It's a little hackish, but I don't mind hackish.

But! You indicate an interesting solution. If I understand you correctly, I could just set `item.accessed`, and that data would still be in there when I save, I just can't search for it? That's perfectly fine for me.

The last part I don't understand, but I think you're saying I should just index itemID (it's the most selective), and that (I take it), findOne will use the index to find that fast, and then do a scan on the result from that. Right?

**Comment by obeliskos** [comment]
Yes an $and filter actually (internally) creates a resultset and performs the array of chained filters as chained find() statements.  The first statement is able to use the index to filter a (hopefully) majority of documents and then the second just does scan on just those results to further filter.  

So in your example it will only have advantage of itemID index.  So yea hopefully you dont have the following sequence : 

I modified previous message... probably best to find and store in temporary array first, then modify and update in forEach later.  If your updates do not affect find filters then this will work without flagging the index as dirty in between each find().

**Comment by retorquere** [comment]
OK, I've restricted indexing itemID, and remove the update. That speeds up things nicely.

I use the `accessed` field to occasionally reap the cache. I don't really search on it other than perhaps right after load of just before save. If the access date is reliably saved in saveDatabase then I don't need the update. Would that work? If I don't ever call `update` for the change to the `accessed` field, would it still be saved out?

**Comment by obeliskos** [comment]
Well what i would encourage is to do your finds and store objects into a temp array, then interate that array and update all of them in series with a forEach.

The option you suggest may work if you do not have 'clone' option on resultset and you are not updating an indexed property, and that property you are updating is not part of a dynamic view 'find' filter ... you should probably be ok.   

Without the 'clone' object we will give you actual object instance in our data array.  If you don't call update we still save your object changes but indexes might not be flagged dirty or dynamic view might get to evaluate changes to see if it should be in or out of view.

Not sure about accessed field, @techfort would know.

**Comment by retorquere** [comment]
I thought clone only cloned on insert, not on find? Clone on find would be quite useful for me.

From a little testing, it looks like the field is present when the DB is being saved. Since the field is not not an indexed prop, and it's not part if a view... I should probably be OK. If the field is lost or not updated, that's actually not that big of a deal; it will lead to aggressive cache reaping, but if it turns out to be the case later, it's easily corrected later.

**Comment by obeliskos** [comment]
It currently does only on insert, but i am planning to change that to also do that on find and data calls (if 'clone' option is set).

Feel free to review or suggest anything as i am thinking out how our object instancing  and referencing may change at this issue : 
https://github.com/techfort/LokiJS/issues/256

**Comment by obeliskos** [comment]
I will close this for inactivity for now, we did modify collection 'clone' option to close on finds now.  Feel free to open a new issue.  Perhaps in the future we can model more scenarios like this in our benchmarks to have common reference.
