### ISSUE TITLE
Support for increment save into indexdb

### ISSUE THREAD

**Issue by lygstate** [techfort/LokiJS#260]
At the current time, it's always serialize the whole database into a single JSON object and save into local database, that's would cause serious performance problem.
So I suggest to support for increment saving the changes into indexdb or other key/value based or relational locale storage database, by recording the changes between the last save time and the current save time and Applying all the changes in a single shot.

**Comment by obeliskos** [comment]
Yes this idea has been brought up before.  Long term maybe @techfort has some ideas on this.

This might be adapter specific.   We can easily support a 'lower-level' adapter interface which just passes a reference to the database.  A custom adapter might take that database reference and dump incremental changesets rather than entire database.  Since the lifecycle of the adapter instance is global it can maintain a state to help decide this.

This is currently beyond the scope of something I intend to work on, but I can extend the adapter interface to allow you to write your own custom adapter for this, if you are interested.

**Comment by lygstate** [comment]
Yeap, give me the adapter interface that would be able to increment save the changes.

**Comment by obeliskos** [comment]
Ok here's the initial extended interface : 
- implement a property on your adapter called 'mode' and set it equal to "reference"
- implement a method on your adapter called exportDatabase(dbname, dbref, callback);
- the dbref is loki providing you with a 'this' reference
- you should load the database with existing loadDatabase interface.  You should construct/reconstruct the database in memory and then serialize it and pass that string as result to callback.
- if you end up support both "reference" and "serialized" modes, you can test the mode in loadDatabase to see what method you should use to reconstruct.

**Comment by lygstate** [comment]
What's mode' and "reference" are stand for, is that stand for 'lokijs'
Still, I am not sure all these means, could please provide a
Interface to provide what's  the APIa the adapter  should be implemented?

**Comment by obeliskos** [comment]
```javascript
function YourAdapter() {
   this.mode = "reference";
}

YourAdapter.prototype.exportDatabase(dbname, dbref, callback) {
  // dbname will be passed in (same as dbref.filename)
  // database reference will be passed into dbref parameter

  // somewhere in here you can code your own adapter logic to save just the changes

  // when done, call the callback 
  callback(null);  // or pass in an error object to callback if there was an error
}
```

**Comment by lygstate** [comment]
@obeliskos  Thanks, but how the increment changes are exported?
I didn't see anything about how to fetch the increment changes and saving it into the permanent store.

**Comment by obeliskos** [comment]
Well, honestly I am not too familiar with the ChangesAPI which @techfort created, but you can read up on it in the wiki page here : 
https://github.com/techfort/LokiJS/wiki/Changes-API

Back when incremental save was last being discussed, I was thinking more along the lines of an (easier) approach where we would just save each collection in their own file (and only if dirty).  The benefit of this approach is more limited than full changesets but could have proven useful in some data situations where you have multiple large collections.

Feel free to ask @techfort for more information about the ChangesAPI, not sure when he will be back though... I would guess he should be available soon.

**Comment by obeliskos** [comment]
we still support persistence adapter model, we added partitioning adapter to save collections independently and only if dirty... changes api still separate but can be used manually

old thread so closing
