### ISSUE TITLE
Remove Console.warn call in LoadData

### ISSUE THREAD

**Issue by toddpi314** [techfort/LokiJS#261]
The console.warn call at https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L940 should be removed or conditional based on lokijs(..) options.

For environments attentive to logging activity (Test, Server) this isn't helpful.

Thanks!

**Comment by obeliskos** [comment]
Alright, this should be removed now.  

I modified it to properly bubble (potential) errors to the registered callback which it wasn't doing before.  

If you use the indexeddb adapter, you will need to grab that as well or this bubbling won't play well with it.

**Comment by obeliskos** [comment]
Old issue so closing, pr #270 implemented verbose flag (which is false by default) which should provide the functionality you were suggesting.
