### ISSUE TITLE
Ignore specific properties

### ISSUE THREAD

**Issue by Grafikart** [techfort/LokiJS#264]
Is it possible to have some ignored properties when a document is saved ? 
For instance lokijs doesn't save the `meta` and I would like to add more ignored properties. 

It's more a feature request than an issue, it would allow people to extend document easier without having to decorate them with a new level of object.

**Comment by obeliskos** [comment]
Lokijs does save the meta do I can't really compare this with that.

You could apply a map function to transform any given set of results to objects which look like what you expect?

**Comment by Grafikart** [comment]
@obeliskos is right, this can be handled by my own implementation.
