### ISSUE TITLE
question: has the "save" callback signature changed?

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#265]
I thought it took an "err" argument; but this code

```
db.save(function(err) {
  if (err) {
    console.log('error saving cache:' + err);
    throw err;
  }
});
```

has suddenly started failing (I think as of yesterday). The value of "err" is "true" when called.

**Comment by retorquere** [comment]
Or is it because I called the callback myself in my custom adapter? I passed `true` to the callback in saveDatabase; was I supposed `null` or an error there?

**Comment by obeliskos** [comment]
i modified this in lokijs.js and also loki-indexed-adapter.js.  If you are using indexeddb make sure you get latest of that file and lokijs.js at the same time.

Your code sample appears correct and you should not get false.

What database adapter are you using (fs, localstorage, indexeddb, other)?

**Comment by obeliskos** [comment]
Oh yea, after re-reading... you should pass null on success and an error object on failure if your using your own custom adapter.

**Comment by retorquere** [comment]
My tests pass again -- I do indeed use a custom adapter.
