### ISSUE TITLE
addDynamicView Documentation

### ISSUE THREAD

**Issue by ozum** [techfort/LokiJS#266]
Hi,

addDynamicView documentation refers wrong options. According to current documentation signature is as below:

    collection.addDynamicView(name [, persistent])

Per #195, it should be as below:

    collection.addDynamicView(name [{ persistent: boolean, sortPriority: 'active'|'passive' }])

Best Regards,

**Comment by obeliskos** [comment]
Old issue (so i am closing) but for now our most accurate documentation is our jsdocs documentation.  The jsdocs for this method should be correct here : 
https://rawgit.com/techfort/LokiJS/master/jsdoc/Collection.html#addDynamicView
