### ISSUE TITLE
PersistenceAdapter Serialization Issue

### ISSUE THREAD

**Issue by toddpi314** [techfort/LokiJS#267]
When saveDatabase is called, the persistence adapter is serialized in bulk.

This is a bit aggressive in situations that consumers will be implementing their own persistence adapter and injecting during instantiation of the LokiJS constructor. Custom adapters will have hooks to scopes that potentially aren't serializable (imagine it being backed by a bunch of web service apis that have request dependencies) 

It is possible to avoid calling serialize on the entire adapter?

Thanks!
Todd

**Comment by toddpi314** [comment]
Wanted to call out that adapter implementer can provide toJSON() method (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior)

But, wanted to keep the issue active to review if full serialization is actually necessary

**Comment by obeliskos** [comment]
Loki does not attempt to serialize the adapter reference itself.  We avoid this by using a serializeReplacer method and then passing that to JSON.serialize.

[Link to relevant lines of code in lokijs.js](https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L670-L688)

**Comment by bfcam** [comment]
I actually just ran into this as well. The problem is because Loki still serializes its options that were passed into the constructor. If you pass an adapter in using options, it still gets serialized.

You can avoid this by setting loki.persistenceAdapter = yourAdapterInstance; after you've created your loki instance.

However, loki does serialize a bunch of other stuff it does not need to as well...

**Comment by obeliskos** [comment]
Ok it does seem as though we were leaving this in options (even while copying this to a separate loki level variable which actually does get nulled out).

As per commit comment, we should probably create loki level object containing all volatile options... options we do not want serialized.

Please pass on any other options you think we should remove from serialization and we can refactor them all (including existing db.persistenceAdapater reference) into such a 'volatileOptions' object.

**Comment by obeliskos** [comment]
Old issue and I assume this has been fixed, if not feel free to reopen.
