### ISSUE TITLE
Remove all console logs/warnings

### ISSUE THREAD

**Issue by Cortys** [techfort/LokiJS#269]
Since Loki is usually included into other applications I think it should not log anything by default so that the developer has full control over the output of his/her application. This is especially relevant when developing CLI tools.

I think disabling all logs and offering a flag to reenable them would be an appropriate solution.

**Comment by obeliskos** [comment]
Sounds reasonable, perhaps an optional diagnostic flag on loki constructor.

**Comment by Cortys** [comment]
Yes. That would be fine.

**Comment by Cortys** [comment]
Do you need help with this?

If needed I could take a look at this at the weekend.

**Comment by obeliskos** [comment]
Sure, that would be great :) 

Thanks

**Comment by njurgens** [comment]
+1 for this.  I'd rather have the option to handle errors and warnings myself and not have them logged.
