### ISSUE TITLE
Question about database size and resource usage

### ISSUE THREAD

**Issue by dukedougal** [techfort/LokiJS#271]
I have created a very simple node.js express application.

It loads about 1 gig of JSON data into a memory only database. Eventually I plan for it to load about 4 gigabytes of JSON into RAM.

So I'm wondering what happens when I try to run this in production?

I don't know how express is deployed but presumably using some sort of web server that executes multiple express processes?

I am wondering if this means that each process will have its own 1-4 gigabyte database in memory?

Is there a way to configure such that the one database is shared amongst all the node.js express processes?  Or is there no way to avoid having a database-per-web-server-process?

**Comment by obeliskos** [comment]
This is more of a question for @techfort he may chime in whenever he gets back.

Obviously you should test this out in a non-production environment first to assess bottlenecks.  Your scenario could prove an interesting test case for loki performance testing.  I don't know that anyone else has tried to push a loki/node/express stack to the limits you are describing.  

I can only speak theoretically, and without knowing your usage patterns I can only offer some ideas.

- We do not yet have socket/socket synchronization component to loki (this was an interest of @techfort a while back), so for now if you wanted to go that route you would have to code that yourself.
- You might shard across collections, running each on their own loki/node/express stack
- In a light update or read only usage pattern you might use ramdisks with a master instance performing any updates and periodically saving to ramdisk.  Other 'cluster' instances might refresh from ramdisk periodically and assume some load the rest of the time.
- You might need to code your own coordinator to distribute load.

Before doing anything along those lines, I would be interesting in knowing what bottlenecks you encounter with a single loki/node/express server instance.

Yea assuming you configure node properly on a 64 bit system I believe you can increase the limit to 4gb.
