### ISSUE TITLE
Using LokiJS in a REST server

### ISSUE THREAD

**Issue by joehui** [techfort/LokiJS#274]
I am working on a project that uses Lokijs and node.js to implement a REST server.  The database will be persistent to the File System.  There will only be 1 in-memory database instance for handling all the potential requests.

Since the REST server can handle multiple HTTP requests at the same time, I am wondering when I "save" the database to the file system, if another REST request tries to "save" at approximately the same time, is there any chance of collision happening that would cause one of the "save()" calls to crash or to write incomplete data to the file system?

The documentation didn't mention anything about how this kind of concurrency should be handled.  Do I have to implement some kind of semaphore mechanism on my own to avoid any potential problem?  I can see that this would probably be related to how to the adaptor is written.  For my question, I am using the default FS adaptor for use with Nodejs.

Joseph

**Comment by obeliskos** [comment]
If you are keeping a global loki database instance, you'd probably be best served by using autosave option on the database.  That would save at periodic intervals and only if changes have been made.

**Comment by joehui** [comment]
Thanks for the quick response.  I guess I will use autosave as you suggested.

So, I suppose that if I use "save" to handle the saving on my own, it will be up to me to handle the potential concurrent saving problem.

**Comment by techfort** [comment]
hey @joehui - the main question here is about the stack you're using. If you're using plain node.js then concurrency is not a possibility as js is single-threaded. However, if you use something like nginx, it's possible that multiple threads (don't know about the internals of nginx, i assume it's multi-threaded) will try to access the same fs resource. However, LokiJS is designed with js single-thread approach in mind so we did not cater for concurrency that is introduced by other layers in the stack. Hope this helps!

**Comment by roblav96** [comment]
Excellent response! This helped me too. Thanks!

**Comment by joehui** [comment]
Even though js is single threaded, if the adaptor uses the async version of file system write function to save the json file, some other request make try to write to the same file while the file write us being executed.  This is what I m afraid of.

**Comment by techfort** [comment]
@joehui interesting point. let us know how you get on and if you resolved your problem. Meanwhile I'm closing this, feel free to re-open if you think work is needed on Loki's side to resolve this.
