### ISSUE TITLE
Large database on Mobile App

### ISSUE THREAD

**Issue by NgYueHong** [techfort/LokiJS#275]
Recently I come across with lokijs and I am planning to use it for my hybrid mobile app developed using Ionic. From my understanding, it is an in-memory database that will executes very fast. So, my questions is, will it work great with big database (maybe around 10-50MB or even more)? Does working with big database using lokijs will dramatically slow down the app?

**Comment by obeliskos** [comment]
Without knowing your usage patterns, yea it should.   Loki has many options for indexing your data if you need to optimize queries.  You can also create dynamic views for frequently used filters.

If you persist the data (potentially) to phone device storage, a larger (say 1mb) database might slow down a bit waiting on slow storage.
