### ISSUE TITLE
Load Database doesn't happen

### ISSUE THREAD

**Issue by dropfen** [techfort/LokiJS#277]
Hmm.. something strange is happening in my opinion.

I create a database the count is 0, insert an item.
Now when I reload the script, I expect that the count is 1.

```javascript
var loki = require('lokijs');

var db = new loki('db.json', {
    autoload: true,
    autosave: true,
    autoloadCallback: countItems
});

var Items = db.addCollection('items');

function countItems() {
    // Expected to see the first time 0,
    console.log(Items.count());
    // But then each more time the scripts executes, the items count should increase, not?
    Items.insert({label:'test', rand: Math.round(Math.random() * 100)});
}

// The result is always 0
```

https://github.com/dropfen/loki-test

**Comment by obeliskos** [comment]
Your assigning the items collection before it is asynchronously set, move that logic into autoload callback similar to here : 
https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#autosave-with-autoload-example

**Comment by dropfen** [comment]
Oh, thank you very much.. it worked!
