### ISSUE TITLE
Question: Why we don't have callbacks on ops like insert?

### ISSUE THREAD

**Issue by mariorodriguespt** [techfort/LokiJS#278]
I'm trying to understand how I can use lokijs with generators and promises.

My assumption is: When I do an insert this done on memory so it's stupid to wait on this. So I should wrap `saveDatabase` with a promise and I can happily yield it. This forces to create a wrapper that will always save the data, regardless of the autosave flag.

I noticed the emit event `insert` on the source code but it brings to the problem than I can't use a Promise. If I have a concurrent situation it's impossible to be sure I'm getting the right event.

What is the intended use from an architectural point of view and how can I wrap it the right way?

**Comment by techfort** [comment]
@mariorodriguespt  This is an interesting question which I think I am understanding correctly however a plunker or example would be awesome to understand exactly what you're trying to accomplish. It is my intention to promise-ify much of the code so this could be a good start.
