### ISSUE TITLE
i have issue in saveDatabaselokijs with ios 

### ISSUE THREAD

**Issue by NuruddinBadawi** [techfort/LokiJS#280]
show this error 

> QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
> setItemlokijs.js:867
> saveDatabaselokijs.js:867
> saveDatabaselokijs.js:933
> autosaveHandleIntervallokijs.js:996 "

this is a snippet code for initializing database 

```
.factory('Api', function($http , $q , Loki , ApiGetContentPost) {

        var _db;
        var _posts;

        var initDB = function() {

            var adapter = new LokiCordovaFSAdapter({"prefix": "loki"});
            _db = new Loki('khlidDB.json',
                {
                    autosave: true,
                    autosaveInterval: 1000, // 1 second
                    adapter: adapter
                });
        };

        var getAllPosts = function() {
            return $q(function (resolve, reject) {
                var options = { };

                if(_db){
                    _db.loadDatabase(options, function () {
                        _posts = _db.getCollection('posts');
                        if (!_posts) {
                            _posts = _db.addCollection('posts');
                        }
                        else if ( _posts.find().length == 0 ){
                            _posts.insert(posts);
                            _db.saveDatabase();
                        }
                        resolve(_posts.data);
                    });
                }

            });
        };
```

i need solution please and thanks for all

**Comment by obeliskos** [comment]
That would seem to be an error specific to a third party loki persistence adapter.

Perhaps you should open this issue at that Github project site? 
https://github.com/cosmith/loki-cordova-fs-adapter

**Comment by nuruddinbadawi** [comment]
the same error even i do not use adapter 
I think there is a problem in the data is stored in ios or programming way
If you have a full example will help me solve the problem because the error does not appear when someone else
and thank you .

**Comment by roblav96** [comment]
Use this here:
https://github.com/cosmith/loki-cordova-fs-adapter

Works flawless. Make sure you use a browserify bundle.

**Comment by shi11** [comment]
heads up, I contacted the developer with an issue of https://github.com/cosmith/loki-cordova-fs-adapter and he's no longer maintaining/using it...

**Comment by lfreneda** [comment]
news here?

**Comment by wendellpalazzo** [comment]
Hi guys, what's new?

I use CORD ... in the version of Android works ...
But in the ios version .. it shows this error "Error: quota exceeded".

![captura de tela 2017-06-08 as 17 50 50](https://user-images.githubusercontent.com/772896/26950139-08a7636c-4c73-11e7-9ef1-6b554c5756e1.png)
