### ISSUE TITLE
Group By

### ISSUE THREAD

**Issue by randdusing** [techfort/LokiJS#282]
Is it possible to group results into multi segments?

**Comment by obeliskos** [comment]
We have yet to add any Group By functionality, but this should not be too difficult to add once the feature is defined.  Possibly we could do this the same way as underscore implements their group by, accepting single property name or function (which returns single string per document).

We do -currently- have compound sort to sort by multiple columns which you could use for lesser but similar effect.  Also, if needed, we have map/reduce which might be set up (with your functions) to create list of groups.

**Comment by randdusing** [comment]
Thanks for the quick reply! Map reduce isn't quite as nice as a grouping function, but it works for my purposes.

**Comment by kerosin** [comment]
Would be great to have the functionality to define a groupBy function that returns the corresponding group for every item. 
Like:
```javascript
groupBy: function(item) {
                return item.lastname.substr(0, 1);
            }
```
Of course this is possible via MapReduce, but would be more developer-friendly to directly apply to a (dynamic) view :)
