### ISSUE TITLE
eqJoin Documentation joinData argument "type"

### ISSUE THREAD

**Issue by moshewe** [techfort/LokiJS#286]
Even though this JS isn't typed, I take type hints seriously.
In the documentation, it says joinData must be an array, see http://lokijs.org/#/docs#joins
Looking into the code, it can be a ResultSet or even another collection... A little confusing. 

I would have done this myself, but I couldn't find the lokijs.org sources here on github :(

**Comment by obeliskos** [comment]
If your up for it, you can submit a p.r. to lokijs.org repo here : 
https://github.com/techfort/lokijs.org

@techfort has to update the website so that might help him keep the site up to date.

**Comment by moshewe** [comment]
I think I've already submitted the PR for this... Please verify and if so close this issue :-)

**Comment by obeliskos** [comment]
great, thanks
