### ISSUE TITLE
eqJoin Documentation - not in DynamicView

### ISSUE THREAD

**Issue by moshewe** [techfort/LokiJS#288]
The current documentation for eqJoin declares this function as such:
`eqJoin(joinData, leftJoinKey, rightJoinKey, mapFun)`
which leaves quite some room for interpretation as to who implements it. So, I looked at the source code and saw that DynamicViews, although this entry in the docs is under that title, don't implement this function at all. ResultSets and Collections do implement it.

I'm trying to eqJoin two collections. Am I missing something?

Sorry to nag so much about the docs...

**Comment by moshewe** [comment]
Also - eqJoin doesn't create a dynamic view, although it's under Dynamic Views in the docs.

**Comment by obeliskos** [comment]
Old issue, but yes I think for now it would be best to refer to : 
https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html
