### ISSUE TITLE
Cannot set property 'filename' of undefined

### ISSUE THREAD

**Issue by friedemannsommer** [techfort/LokiJS#289]
/node_modules/lokijs/src/lokijs.js:346
      this.filename = filename || 'loki.db';
                    ^

TypeError: Cannot set property 'filename' of undefined
    at Loki (/node_modules/lokijs/src/lokijs.js:346:21)
    at Object.<anonymous> (/source/index.js:5:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

**Comment by techfort** [comment]
hey @friedemannsommer  can you show me an example of your code? looks like the loki object wasn't correctly instantiated.

**Comment by friedemannsommer** [comment]
/source/index.js
```javascript
var loki = require('lokijs'),
      db = loki('db.json', {
          autosave: true,
          autosaveInterval: 500,
          autoload: true
      });
```

**Comment by techfort** [comment]
if you omit the `new` operator then `loki` will be interpreted as a function not a constructor. Can that be the problem?

**Comment by friedemannsommer** [comment]
Yes the "new" operator solved the problem. Thank you for your fast response & help.

```javascript
var loki = require('lokijs'),
    database = new loki(path.join(__dirname, '..', 'data', 'db.json'), {
          autosave: true,
          autosaveInterval: 500,
          autoload: true
     });
```
