### ISSUE TITLE
LokiJS not allowing Json data to insert.

### ISSUE THREAD

**Issue by amitbrcmit** [techfort/LokiJS#291]
Hi i am using cordova/angularjs/lokijs while inserting records in db in json format it is showing typeerror("Document needs to be an object") but in case of simple array its working fine.I need to store as JSON as requirement.
Any help guys
Thanks

**Comment by roblav96** [comment]
try this:
```javascript
console.log( typeof data )
db.insert(data)
```

**Comment by techfort** [comment]
@amitbrcmit as @roblav96 pointed out, you need an object for a single-object insert, or an array of objects for a batch insert. Can you show me some code so i can check if something is not as it should be?

**Comment by amitbrcmit** [comment]
Thanks
it is working now perfectly.

**Comment by Mowso** [comment]
Hi, 

Is there somewhere an example of a batch insert in order to put an array of json data in loki ?

**Comment by obeliskos** [comment]
https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html
