### ISSUE TITLE
can i use lokijs  in PhantomJS 

### ISSUE THREAD

**Issue by sixihaoyue** [techfort/LokiJS#293]
can i use lokijs  in PhantomJS ? i see some code about PhantomJS, but i can't load database from file

**Comment by techfort** [comment]
hey @sixihaoyue the answer for now is "i don't know" because i'm not familiar with PhantomJS. Let me check it out and i'll revert.

**Comment by sixihaoyue** [comment]
thanks, PhantomJS can't use mostly db, i search for long time and i find lokijs

**Comment by techfort** [comment]
@sixihaoyue - i took a look at phantomjs. As loki is not specifically browser-based, you can use it no problem.
I'll close this, feel free to reopen if you have issues.
