### ISSUE TITLE
Minor doc issue

### ISSUE THREAD

**Issue by rmckeel** [techfort/LokiJS#294]
This is very minor, but at http://lokijs.org/#/docs, the following example is missing a right brace.  Apologies if this is not the proper place to notify you of a website doc change.

``` Example:
results.compoundsort(["legs", ["name", true]);

P.S. LokiJS rocks and is a delight to work with.  If I ever meet you in person I will need to buy you several beers as thanks :)
```

**Comment by techfort** [comment]
hey @rmckeel thanks for flagging that! There is a lokijs.org repo so maybe i'll close this here and reopen it there. Thanks for the compliments, glad you love Loki, if I ever am in Colorado i'll take you up on that beer offer :)
