### ISSUE TITLE
when i using Update ...

### ISSUE THREAD

**Issue by badawiZad** [techfort/LokiJS#297]
Update in document not work 
this Log :
Uncaught Trying to update unsynced document. Please save the document first by using insert() or addMany()

and the code :
```
if(newData.length > 0){
                    _posts.insert(newData)
                    newData = [];
                    if(updateData.length > 0){
                        _.each(updateData,function(x){
                            _posts.update(x)
                        })
                        updateData = [];
                    }
                    _db.saveDatabase();
                    resolve(newData);

                }
```

**Comment by obeliskos** [comment]
When you insert documents, we attach $loki and meta properties to your objects.  In order to call collection.update, your object needs those properties already attached.  

Are you trying to 'update' a changeset coming down from a server or some other external source?  If so, I am not sure if the changes api would apply but if not you would probably have to look up the object and either graft changes onto existing object or meta/$loki onto new one.  If you are able to define unique or binary key it would speed lookup.

**Comment by rgksugan** [comment]
@obeliskos Thanks. Had same issue. Your solution fixed it.

**Comment by obeliskos** [comment]
I believe this was resolved, so I will close for now

**Comment by nuruddinbadawi** [comment]
I did not understand how ??
if I have object and item id and I need to update data depend on this Id, should I do find() before the update to get meta/$loki properties or there is another way?

**Comment by obeliskos** [comment]
As I mentioned, any object inserted into loki gets assigned '$loki' and 'meta' properties.  If you attempt to pass an object to coll.update() without those properties you will get the error described in this issue.

Solution for this example (when refreshing objects in loki with 'fresher' versions of those objects from external source) would probably be : 
- to find those objects in loki using other properties
- copy their $loki and meta properties onto 'fresher' object
- call coll.update() passing the 'fresher' object with $loki and meta properties grafted onto them

**Comment by dasDaniel** [comment]
I've had this issue too.
The problem was that I made an assumption that the id was enough to identify the document. I was passing an object instead of passing the document

```
//this
info_col = db.getCollection('info');
var info_doc = info_col.get(1);
var num = info_doc.my_num + 1;
info_col.update({id:1, my_num:num});
```

```
// instead of
info_col = db.getCollection('info');
var info_doc = info_col.get(1);
var num = info_doc.my_num + 1;
info_doc.my_num = num;
info_col.update(info_doc);
```

maybe this will help somebody that sees the same error

**Comment by 7h3m4dS0u1** [comment]
Thanks @dasDaniel this was very helpful.

**Comment by shaojianyong** [comment]
My solution:
`let user = ...
let obj = coll.findObject({'id': user.id});
if (obj) {
  user['$loki'] = obj['$loki'];
  user['meta'] = obj['meta'];
  coll.update(user);
} else {
  coll.insert(user);
}`

**Comment by GabrielchenCN** [comment]
try this:
```
let doc = collection.chain().find(query);//query === your query conditions
 if(doc.data().length>0){
        //the properties your want to update in the koa
      doc.data().docDate= ctx.request.body.data;
      collection.update(doc.data())
      ctx.body = JSON.stringify({msg:"update",data:ctx.request.body});
  
      }else{
        //if not exist
        collection.insert(ctx.request.body);
        ctx.body = JSON.stringify({msg:"create",data:ctx.request.body});
      
      }

```
