### ISSUE TITLE
how do i get previously made database ?

### ISSUE THREAD

**Issue by harryy2510** [techfort/LokiJS#301]
I am using framework7 with lokijs. In my main.js file, I create a new database everytime var db = new loki(dbname); . while saving using db.saveDatabase(); it doesn't saves anywhere or either i am not able to use it properly.
I have a few questions:
1. does new loki(dbname) creates new database everytime and deletes the old one ?
2. if no then how to load previously saved database ?
3. how to save this database to any file on android using cordova and framework7 ?

**Comment by obeliskos** [comment]
You have to either call loadDatabase(), or set up autoload option as described in our : 
[Persistence and Adapters wiki page](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters)

Everytime loki saves a database, it overwrites any old one which has the same database name.

If your file is not saving properly it may be a cordova issue.

While I am not familiar with issues of loki on Cordova, @cosmith has created a loki database adapter specifically for Cordova, so you should probably use that.  His adapter github page is here : 
https://github.com/cosmith/loki-cordova-fs-adapter

**Comment by harryy2510** [comment]
thanks i got it working now using adapter and loadDatabase function :)
