### ISSUE TITLE
Feature: Loki as a db-cache for another database

### ISSUE THREAD

**Issue by moshewe** [techfort/LokiJS#302]
Hi,

For a project I'm working on I've been using Loki as a "front outpost" for a mysql server for lots of query-able configurations. Is this a feature you would be interested in? The codebase is maturing right now and has been in production on a real-time bidder for the past two months or so.

**Comment by techfort** [comment]
hey @moshewe ! that sounds awesome! Are you using loki as a kind of redis? I had a very simple prototype working of Loki writing to underlying dbs (i had mongodb and rethinkdb working) and an idea to use it as a redis-like key-value store.
Either way, i'd be really interested in seeing the code!

**Comment by moshewe** [comment]
Less like redis, more like "I wanna query this info but not with mysql latencies"... Hardly redis. No replication etc. I want to add a stale-data remover daemon though. I'm not even updating the "source", as I don't support making changes to the "outpost"

Part of the refactorings I'm doing to the code right now are about making it data-source agnostic.

After this iteration of work on it I'll make the code public on github. Might take a while to interface fully with the existing Loki codebase.

**Comment by techfort** [comment]
that sounds great - i'll greatly appreciate peeking at that project as it sounds really interesting and one of the uses i envisaged for Loki on the server side.

**Comment by techfort** [comment]
hey @moshewe would you be able to share a diagram that illustrates the flow of data? i'd really like to understand how you're using Loki and where in the infrastructure does loki fit in. Do you use Loki for reads and mysql for writes/updates or something like that?

**Comment by moshewe** [comment]
I just scribbled it down on a piece of paper, but it pretty much sums it up... 
I wrote query/1microsec but it's a real-time bidder, so this can be much, much more.
![loki-cache](https://cloud.githubusercontent.com/assets/7280505/12068016/59a6782e-b00d-11e5-852a-b1f4f45f9f3c.jpeg)

The architecture itself is simple, it's just the specific design that's been battle tested.

**Comment by moshewe** [comment]
other programs write to the mysql configurations for the app, but we tolerate a 5mins delay in config updates.

**Comment by techfort** [comment]
thanks a lot for that - it really looks clever. Looking forward to that
codebase when you can share!

**Comment by moshewe** [comment]
I've forked the repo and will add the code in the coming days/week. In my original implementation I use ES6 classes. I don't think that will fit in the current codebase...

**Comment by moshewe** [comment]
I'd like to be assigned to this issue. I'm working on making it public again...

**Comment by moshewe** [comment]
I just found out I wrote this for node only... How would you like to make it browser-friendly? Browserify?

**Comment by techfort** [comment]
Is this not really only relevant to node anyway?  Anxious to take a look BTW!  Thanks for the great work!

**Comment by moshewe** [comment]
Of course not.
I'm integrating it into the single lokijs file right now just to keep
things ordered.

I have no idea how to make it a node-only thing anyways :)
