### ISSUE TITLE
Collection.get function algorithm issue

### ISSUE THREAD

**Issue by shaderzak** [techfort/LokiJS#303]
Hello 
I use LokiJS verision 1.3.10 and I faced errors during document update/remove. After debugging I found out that the problem is with Collection.prototype.get function. So in my collection somehow there are documents which has no $loki property, and "get" function just returns null even if requested document exists. Main reason is in the condition of while statement.
```
while (data[min] < data[max]) {
        mid = Math.floor((min + max) / 2);
```
While exists when one of the IDs is undefined.
Thanks for help

**Comment by techfort** [comment]
Hey @shaderzak - the implementation of binary search algorithm is the standard optimized implementation , so errors are possible but unlikely. The problem i see is that some of your objects don't have a $loki property, which is weird. How do you get to have objects in a collection without $loki?

**Comment by shaderzak** [comment]
Thanks for reply. 
Yes actually the main problem is missing $loki property, the other problems are just effects. All over application modifications are made only by Collection.insert and Collection.remove functions. Although, as far as Collection.by function returns object itself with reference (not a copy), I believe some code just deleted this property, thus damaging collection.

**Comment by obeliskos** [comment]
If you have no control over user code overwriting variables on your loki objects, you should probably use the collection 'clone' option documented [here](https://rawgit.com/techfort/LokiJS/master/jsdoc/Collection.html).

Closing for now, pending 2.0 refactor which should address this more thoroughly.
