### ISSUE TITLE
Is it possible to load and store database in variable ?

### ISSUE THREAD

**Issue by harryy2510** [techfort/LokiJS#304]
```javascript
var db;
var adapter = new LokiIndexedAdapter( 'juliet' );
adapter.loadDatabase( 'nato' , loadDbCallback );

function loadDbCallback (data) {
    if (data == null) {
        db = new loki('nato', { persistenceMethod: 'adapter', autoload: true, autoloadCallback : checkTablesOrCreate, autosave: true, autosaveInterval: 5000, adapter: adapter }); 
    } else {
        checkTablesOrCreate();
    }
}

function checkTablesOrCreate() {
  var users = db.getCollection('users');
  if (users === null) {
    users = db.addCollection('users');
  }
}
```

I dont know where am I going wrong.
When this codes run for first time, then **db** is accessible
but for the second run it gives an error

Is it possible to access this variable **db** anywhere in my code ?
or do i have to everytime load database using adapter ?

if i use **new loki(dbname)** everytime then all my previous data will be overwritten

so is it like possible to load database when the prject runs and use this variable db anywhere in my code ?

**Comment by obeliskos** [comment]
You don't need to load twice... you don't need to call adapter.loadDatabase(), just test if collections exist in your autoloadCallback function.

The db variable is assigned by the time your autoload callback is called.  Outside your callback it won't be set until you yield the thread allowing the callback to fire.

Can you examine this example which demonstrates both autosave and autoload.
[Loki Sandbox Autoload/Autosave sample](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/c3d9574b61f7cb9ade55/raw/52bb24dec1e31950eedeefc350c579eb33919ab4/Loki%2520Autosave%2520Demo)

**Comment by harryy2510** [comment]
but autoloadCallback function works only when i create a new database ?
so like if database exists then how would i access functions ?
lets take an example
```javascript
var db;
var adapter = new LokiIndexedAdapter( 'juliet' );
adapter.loadDatabase( 'nato' , loadDbCallback );

function loadDbCallback (data) {
    
}

function insertData(data){
    var users = db.getCollection("users");
    users.insert(data);
}


$$('#button1').on('click',, function(event) {
   insertData(jsondata);
});

```
