### ISSUE TITLE
backbutton history issue

### ISSUE THREAD

**Issue by harryy2510** [techfort/LokiJS#305]
In my app, before getting onto dashboard there are two pages for authentication
pushstate is set to true since i need it on other pages.
i want to destroy history and action of back button as soon as user login and reaches the dashboard..
right now what is happening, when i login and reaches dashboard, i can still go back to login screen.
i tried deleting history but that doesnt work..
Any other way of doing it ?

**Comment by techfort** [comment]
hey @harryy2510 - maybe i misunderstand your issue but are you sure this is LokiJS related? if it is, in what way?
