### ISSUE TITLE
Problem remove after a fresh insert

### ISSUE THREAD

**Issue by MisterUlous** [techfort/LokiJS#307]
Hi everyone,
I build an angularJS application with LokiJS and I have a weird behaviour when I insert an object and for any reason I want to remove it just after.

I explain, how I proceed : 
in app.js I called a factory which init loki like that : 

in app.js : 

```javascript
dbGlobal.init();
```

in my dbGlobal Factory I have : 

```javascript
/**
       * Init the loki database.
       */
      factory.init = function(){
        var db = new Loki('database');
        db.loadDatabase({}, function() {
          // call the dbUsers factory which init the users collection
          dbUsers.init(db);
        });
      }
```

in my dbUsers factory I have : 

```javascript
  var factory = {};

      // The database.
      factory.db = undefined;
      // The collections.
      factory.dbMyUsers = undefined;

      /**
       * Init the collection.
       * @param the db to interact with
       */
      factory.init = function(db){
        factory.db = db;
        factory.dbMyUsers = factory.db.getCollection('MyUsers');
        if(!factory.dbMyUsers){
          factory.dbMyUsers = factory.db.addCollection('MyUsers');
          // Put unique index on id field.
          factory.dbMyUsers.ensureUniqueIndex('id');
          // Fixed a problem in angular.
          factory.dbMyUsers.ensureUniqueIndex('$$hashKey');
        }
      }

      /**
       * @param object user the user to create
       * @return object user, the user created
       */
      factory.createUser = function(user){
        // Generateid
        user.id = uuidService.generate();
        var insertUser= factory.dbMyUsers.insert(user);
        factory.db.saveDatabase();
        return insertUser;
      }

      /**
       * Delete the user.
       * @param string userId the user Id.
       * @return array users users list with the user removed.
       */
      factory.deleteUser= function(userId){
       // Find the user :
        var user = factory.dbMyUsers.findOne({'id' : userId});
       // Delete the object.
        factory.dbMyUsers.remove(user);
        factory.db.saveDatabase();
        return factory.dbMyUsers.find();
      }
```

Without refresh in my browser the page, If I called createUser and after deleteUser the user is still present in factory.dbMyUsers.find() . If I called createUser, I refresh the browser page and call deleteUser it's worked my user is deleted from the database. I don't understand why :S 

Can you help me ?

**Comment by obeliskos** [comment]
It seems as though you are using the default persistence adapter, which for web apps is localstorage.  Are you hosting your page within a webserver or are you accessing it via filesystem?  Are you running on desktop or mobile?

**Comment by MisterUlous** [comment]
Hi, 
I'm on desktop on the chrome browser. Yes I used the default persistence localstorage.

**Comment by obeliskos** [comment]
Ah, ok.  Are you sure its already being saved?  When you open browser tools can you inspect localStorage and see your database key/value?

**Comment by MisterUlous** [comment]
When I call the find function before my remove, the user is in .

**Comment by obeliskos** [comment]
Your question and example are a bit unclear but you should probably verify the functionality you are attempting in pure javascript (without angular) in the loki sandbox.

The object you pass to collection.remove() must have our attached $loki property. So verify that the object has that $loki property before calling remove().

**Comment by MisterUlous** [comment]
The $loki property is in. I don't understand the problem and it's really painful for me ...

**Comment by lombafab** [comment]
Hi, I have the same problem. Put in other words, if I do a factory.create(user) and immediately after if I do:
        console.log(factory. dbMyUsers.find())
        factory. dbMyUsers.remove(user);
        factory.db.saveDatabase();
        console.log(factory. dbMyUsers.find());
the two console.log will return the same number of result.

**Comment by MisterUlous** [comment]
Ok, I found the problem. Angular adds a $$hashKey so the remove doesn't execute because it raised an exception $$hashkey not unique. I removed what angular added and now it works. Nothing to do with Loki.
