### ISSUE TITLE
Document removal documentation - speeds and more

### ISSUE THREAD

**Issue by moshewe** [techfort/LokiJS#311]
The performance of remove methods is not mentioned in the docs @lokijs.org
Do we have any statistics?

Also - the behavior of remove(obj) is not well defined - how is the object removed? Is it by some field being used as an id? I'm asking this because I'm facing the following problem: given an object to update which I can't be sure exists in a collection, is it better to attempt to remove it and then insert it instead of finding and updating / not finding and adding?

**Comment by techfort** [comment]
I would most definitely find-update, add on not find.
To answer your question, the remove() method looks for the $loki property of an object, if it's not there it throws an error.
That would also be the fastest way for you to check whether or not the object has already been manipulated by LokiJS. When an object is removed, the `$loki` and `meta` properties are deleted, and the plain object is returned.

**Comment by moshewe** [comment]
What about cases where I don't want to force a resync of indexes? For example, I want to update a simple data field - I don't change the index field's value, why waste time on a resync?

A simple experiment of inserting two objects with the same key shows objects are not overwritten, as such:
```
collection.insert({id:1, val:'moo'})
collection.insert({id:1, val:'zoo'})
console.log(collection.by('id',1)) // moo object
```
I truly expected an overwrite. In this case I really don't need a resync, the index can now just point to `zoo` instead of `moo`.

The obvious solution to this would be to provide a custom update function for each collection which changed field values rather than overwrite objects and such, thus saving garbage collections. That what I implemented in the cache I mentioned earlier, but I wanted to have another go at this problem now that I'm refactoring it for making it public.

**Comment by moshewe** [comment]
After working with this for some time, I can honestly say the insert function needs a flag for un-synced upserts.

**Comment by moshewe** [comment]
I've implemented `upsert` in a fork and I'm testing it right now. The find query to check it the object exists in loki is a little cumbersome for multi-field indexes in general form, but this can be parameterized for extra efficiency.

**Comment by techfort** [comment]
@moshewe now that's a hot one! `upsert` has been on the plans for a while! Looking forward to the PR.

**Comment by moshewe** [comment]
Is this still relevant?

If so - I thought about implementing it via adding a hack to the UniqueIndex object. When setting a new value in the index, if the collection is in cache mode (so as to avoid performance hits when not desired), instead of throwing an error we simply replace the object in the index and add the relevant `$loki` and `meta` data to replacing document.

Did I get this right or am I tinkering with forces beyond my knowledge?

**Comment by jbcpollak** [comment]
@moshewe @techfort what happened to upserts? are they still on the roadmap?

**Comment by moshewe** [comment]
I haven't gotten around to making it push-worthy yet, and I think that it might be a bit pointless considering a re-write is in order for the next version of LokiJS. What do you think @techfort ?

If you want to implement your own upsert, we've thrown about quite a few ideas in this thread. One of the main issues I was facing when I implemented this was that there was no efficient single way to do it, as you can see from the above posts - it really depends on your use-case.

**Comment by techfort** [comment]
@jbcpollak yeah i think the focus is on the stabilization of what's there for LokiJS v1.x rather than adding new feature. Upserts in particular are something that is easy to get wrong or create problems. I'll have a chat with @obeliskos about this and see what the story is.

**Comment by moshewe** [comment]
I'd love to be part of implementing upsert in the next version if possible @techfort .

**Comment by techfort** [comment]
sure @moshewe head over to https://github.com/LokiJS-Forge/LokiJS2
