### ISSUE TITLE
Data TTL daemon

### ISSUE THREAD

**Issue by moshewe** [techfort/LokiJS#312]
I'm thinking about implementing a data TTL daemon, and I was wondering whether this is a feature you would find useful. I'm thinking about adding it to the `meta` field instrumented into objects in loki.

**Comment by techfort** [comment]
@moshewe that's a very good idea, we toyed with it a couple of times already. If you want to submit a PR that is more than welcome!

**Comment by moshewe** [comment]
I've looked into the code and I want to do this through the `meta` field added to all documents. Is there any indexing on fields in `meta`? If so, I could `find` the documents to delete VERY quickly.

**Comment by techfort** [comment]
no i don't believe there is - but it is a rushed answer, let me check and
i'll get back to you, in any case a background daemon doesn't necessarily
have be incredibly fast, or should it?

**Comment by moshewe** [comment]
Well, that depends on your priorities. Generally speaking, no. But for my
purposes that would be preferable. It will also allow users to perform
time-centric queries, which is a nice feature in this day and age IMO.

**Comment by moshewe** [comment]
Anyway, the timestamp-indexing feature is 100% decoupled and synergetic
with a TTL daemon. It's all in the `find`...

**Comment by techfort** [comment]
@moshewe i'm having a senior moment. @obeliskos do we support dot notation indexes? because that would solve it, right? e.g. index `meta.created`

**Comment by obeliskos** [comment]
Currently we only support indexing top level properties. this would affect many layers from indexing, find object parsing, sub-object referencing, index range algorithm...

(On another note, in general indexes could be rebuilt less often if we added update of certain properties only rather than whole object... or if cloning is turned on we could diff object passed and only invalidate index if property changed)

Is your use case just as cache or could objects be updated frequently (invalidating the index)? if not updating, protyping a ttl with top level timestamp with index could be a start.

**Comment by moshewe** [comment]
OK, I see indexing dot notation is complicated to add.
Diffing objects can be more expensive than syncing the indexes, I think we
might as well just implement dot notation indexing.

I've added a decorator to the Collection update function that saves the
index syncing. Whether or not you'd like it as an option always available
to everyone... Your call.

My current implementation uses the expensive `where` function to filter out
TTLed documents. Assuming the load-from-cache interval << TTL interval,
that's OK. Objects can be updated every 5mins or so, but as I said before
most of these updates are not to the index property, so my decorator saves
a lot of time. This is part of an ad-network real time bidder, so saving
processing time is crucial for me.

**Comment by moshewe** [comment]
I've just thought of something - my decorator HAS TO maintain it's own timestamp, outside of the `meta` object. The regular `update` function updates `meta` - my decorator doesn't... I could of course write it so that it updates `meta` just like a regular `update`, but then the timestamp-top-level-property indexing goes to hell.

**Comment by moshewe** [comment]
I've decided to drop the timestamp indexing option. Syncing the timestamp index every time will be, in total, far more expensive than just running through the whole dataset and removing things every once in a while... It is a feature worth considering for other purposes, though.
