### ISSUE TITLE
how to get ResultSet?and other question about the ResultSet of documentation

### ISSUE THREAD

**Issue by faryang-sh** [techfort/LokiJS#316]
![image 3](https://cloud.githubusercontent.com/assets/14032423/12385422/f06f31d2-bdf6-11e5-8db5-8f77c262d336.png)

**Comment by techfort** [comment]
@faryang-sh assuming a collection called `users` then `users.find()` returns a resultset.

**Comment by faryang-sh** [comment]
var searCon=serializeForm($('#mysearch'));
var users;
db.loadDatabase({},function(){
       users=db.getCollection('users');
});
var result=users.find({'city':{'$contains':searCon.username}});
var obj=result.where(function(uu){return uu.username == 'admin123'; });

			
![image 4](https://cloud.githubusercontent.com/assets/14032423/12388934/bfe4b766-be10-11e5-84ca-7607f2ed0583.png)

**Comment by faryang-sh** [comment]
*var searCon=serializeForm($('#mysearch'));

**Comment by faryang-sh** [comment]
# var searCon=serializeForm($('#mysearch'));

**Comment by faryang-sh** [comment]
* var searCon=serializeForm($('#mysearch'));

**Comment by faryang-sh** [comment]
> var searCon=serializeForm($('#mysearch'));

**Comment by techfort** [comment]
I think your problem is in the fact that you're running the queries before the loading of the db is finished. Try including the last two statements  in the load function as a test. If it works then that's where your problem lies.

**Comment by faryang-sh** [comment]
![image 5](https://cloud.githubusercontent.com/assets/14032423/12389556/798f3b52-be14-11e5-8430-7beb381a60bc.png)

**Comment by techfort** [comment]
can you do a few console.log() statements on `result`? like `typeof` and `instanceof` to understand if there's something untoward going on.

**Comment by faryang-sh** [comment]
![image 6](https://cloud.githubusercontent.com/assets/14032423/12390572/3ad7a478-be1c-11e5-9be8-350904db515d.png)

**Comment by faryang-sh** [comment]
![image 8](https://cloud.githubusercontent.com/assets/14032423/12390587/66182e46-be1c-11e5-9d33-f344d1e94161.png)
![image 6](https://cloud.githubusercontent.com/assets/14032423/12390590/69803e0c-be1c-11e5-9d45-b054f6ab1529.png)

**Comment by techfort** [comment]
sorry @faryang-sh i completely forgot that to obtain a resultset you need to use chain() eg `users.chain().find()` , data is then accessible with `.data()`

**Comment by faryang-sh** [comment]
thanks for your anwer.
The documentation of lokijs.com is so simple,sometimes i must take some time to check my thought,can you provide complete documentation or api doc.

**Comment by faryang-sh** [comment]
![image 9](https://cloud.githubusercontent.com/assets/14032423/12391360/3df69f28-be22-11e5-96c2-1064e734e7f1.png)

**Comment by faryang-sh** [comment]
![image 13](https://cloud.githubusercontent.com/assets/14032423/12391515/5235ad3e-be23-11e5-97b7-faf3b0d25cce.png)
this is also 0 object

**Comment by obeliskos** [comment]
As @techfort mentioned above, when using chain, you need to terminate chain with call to .data(), such as : 

```javascript
var resultSet = users.chain().find({'city': {'$contains':searCon.username}});
var resultData = users.chain().find({'city': {'$contains':searCon.username}}).data();
```
you would usually use the second statement unless you wanted to introspect the resultset class itself.

**Comment by faryang-sh** [comment]
thanks for @obeliskos

**Comment by obeliskos** [comment]
closing
