### ISSUE TITLE
http://lokijs.org/#/demo does not persist changes and deletes...

### ISSUE THREAD

**Issue by deenfoxx** [techfort/LokiJS#320]
Checking out LokiJS for the first time and the demo itself is broken. :-( Should I be concerned?

To duplicate...

(1) Go to http://lokijs.org/#/demo
(2) Enter a 'new todo title', click 'create', then refresh page... properly persisted create.
(3) Click complete checkbox and refresh page... does not persist checkbox.
(4) Click delete button and refresh page... does not persist delete.

but...

(5) Click complete checkbox, then enter a 'new todo title', click 'create', then refresh page... checkbox has now persisted.
(6) Click delete button, then enter a 'new todo title', click 'create', then refresh page... deleted todo item has now persisted deletion.

so...

Updates and deletes do not persist, UNTIL you insert a new item. Oops? Tested as not working with Firefox, Chrome and Safari on Mac El Capitan, as well as Firefox, Chrome and IE on Windows 7.

**Comment by techfort** [comment]
hey @deenfoxx thanks a million for flagging this. I'll check it right away! I think the problem lies in the demo using an old version of the library.

**Comment by techfort** [comment]
@deenfoxx again thank you for spotting the bugs. These are bugs in the demo app, not in the library, luckily. Basically calls to `db.saveDaabase()` are missing after removal of documents and document change. All works perfectly well once those persistence calls are implemented. I will upload a new version of the demo asap, for now at least you should not be concerned about Loki working as intended.  I opened an issue on the relevant repo: https://github.com/techfort/lokijs.org/issues/9
