### ISSUE TITLE
Should clear()'ing a collection also reset constraints?

### ISSUE THREAD

**Issue by jumpinjackie** [techfort/LokiJS#328]
I've noticed strange behaviour re-inserting documents into a collection with unique indexes established that has been clear()'d beforehand. Looking at the clear() method I see that the constraints property of the collection is not being reset, so it looks like still holds onto indexed values for documents that are no longer there, that messes up the behaviour of insert() calls after being cleared.

Is this a bug?

**Comment by obeliskos** [comment]
yea this functionality should probably be in a clear method

**Comment by callmeyesh** [comment]
I think this is related to my issue https://github.com/techfort/LokiJS/issues/422. The constraints is keeping track of the old document and this is being retrieved when I query using the collection.by().

**Comment by TheMadBug** [comment]
I've run into this and get "duplicate id on insert" errors when I try to insert into a collection that has zero documents as a result of clear. Pretty sure that classifies as a bug.
I guess the short term solution is to use
collection.chain().find({}).remove();
over
collection.clear();
