### ISSUE TITLE
Duplicate collection should be warned / avoided

### ISSUE THREAD

**Issue by ratson** [techfort/LokiJS#330]
`addCollection` with existing collection name is possible, which could cause issue when user do it after `loadDatabase`.

I think it should either warn user about duplication or return `getCollection`, or there are good reasons for keeping current behavior?

**Comment by obeliskos** [comment]
Old issue but yes we still seem to allow adding collections with duplicate names.  We should fix this.

**Comment by cepm-nate** [comment]
Yes, I would appriciate this fixed as well. Now I have a lot of duplicate collections, and when I call 'getCollection(name)', it returns the FIRST one, not even the most recently added.

Perhaps if .addCollection is called with a duplicate name, return the already existing collection?

**Comment by obeliskos** [comment]
This would be easy to add... not sure why I didn't follow up on this before.  This won't affect function signatures or typescript definitions.  Anyone want to submit a pr for this? If not I will look to do this sometime next week.

**Comment by cepm-nate** [comment]
#635 I don't like duplicate code either, but am not sure how to avoid it without refactoring, as I'm not sure if the author would like to see a warning or info emitted in this case. Feel free to modify it as needed.

**Comment by obeliskos** [comment]
Thanks @cepm-nate for stumbling onto several deficiencies in our toolchain and unit tests... oh and the p.r. too... 😄
