### ISSUE TITLE
Implement $size operator

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#334]
A `$size` operator would be very useful when trying to match for exact matches in arrays.

For example, let's say that all documents in a collection have a key named `test` and that key holds an array (document example: `{name: 'foo', age: 12, test: [3, 7, 2, 4]}`.

A `$size` operator could be used like this:

    .find({'test': {'$size': 3}})

to find all the documents that have 3 elements in their `test` key.

**Comment by VladimirTechMan** [comment]
@alexandernst, good addition, thanks! – I was recently considering it too. I just made a small enhancement to it today (as well as the '$type' and the new '$len' operators) to support sub-expressions on the value. That way, in addition to checking something like
  `{ field_name: { $size: 5 } }`
you can also use tests like
  `{ field_name: { $size: { $lte: 5 } } }`
or
  `{ field_name: { $size: { $and: [ { $gt: 2 }, { $lt: 8 } ] } } }`

Just in case, you may want to fetch the current version from the repo and try it in your project.
