### ISSUE TITLE
Implement $all operator

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#335]
Implement Mongodb's `$all` operator to search for all values in an array.

Document example: 

```
{name: 'foo', age: 42, interests: ['something', 'something more', 'nothing']}
```

Query example:

```
.find({'interests': {'$all': ['sports', 'dancing', 'cars']}})
```

That would find all people that have all and only those 3 interests in their `interests` property.

**Comment by alexandernst** [comment]
Looking at the code, this would work exactly as `$contains`, but in an exclusive way, aka, it will return only the items that have all the items specified in the query, but not anything else.

**Comment by alexandernst** [comment]
If a PR will speed up the process, I'm ready to do it, but I need to know if such a feature will be included, before starting to code.

**Comment by techfort** [comment]
@alexandernst if it's ready that would be awesome, for the sake of saving you time make sure to run npm test so testing and linting is passed, otherwise travis will throw errors and I won't be able to accept the PR. Also if you can provide tests for `$all` that would be great (and of course they pass :D)

**Comment by alexandernst** [comment]
Great, will start working on it right now, as I need it for a project at work. Btw, do the same applies for my previous issue? (implement $size)

**Comment by techfort** [comment]
@alexandernst absolutely! and thanks for the work!

**Comment by alexandernst** [comment]
Great! I'll start with the `$size` operator. I'll post a PR in a few minutes.
