### ISSUE TITLE
Resync indexes of collection on map/reduce?

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#337]
Docs say that if an `update` is called, a resync of the indexes of the collection is forced.
Anyways, I noticed that I can actually modify documents with a simple `map/reduce` operation. 

Example:

    db.chain().find({}).mapReduce(
        function (obj) { return obj; },
        function (objs) {
                for (var i = 0; i < objs.length; i++) {
                        objs[i].my_property = "new value";  // <--- document gets updated
                }
        }
    );

First question: Is this an expected behavior or is this a bug?

Second question: If this is an expected behavior, will it trigger a resync of the indexes of the collection?

Third question: If "yes" to the second one, will the resync happen after each changed document or at the end of the `reduce` function?

**Comment by obeliskos** [comment]
Since your map just returns same object instance, your reduce is modifying collection objects without calling update, which would resolve indexes.  Not sure you want to use map reduce to modify underlying collection data, usually your map would create new objects.

**Comment by alexandernst** [comment]
So I assume this is kind of a bug?

**Comment by alexandernst** [comment]
Also, since re-syncing the indexes (I'm guessing) is kind of a costy/expensive operation, is there a way I can batch-update documents and then do the re-sync?

**Comment by obeliskos** [comment]
If you use chained update function you should be able to bulk update.  We probably should add similar bulk update on collection itself.

The above is expected behavior... unless you have specified collection 'clone' option, in which case this might be a bug.  The is perf cost for clone option so don't enable it unless that is exactly what you need.

**Comment by alexandernst** [comment]
Ah, cool. I think I missed the part in the docs that says I can actually batch-update based on the current results. Thank you for the clarification!
