### ISSUE TITLE
Are all the methods sync or async?

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#338]
I can't find in the docs whether the main methods (`update/find/chain`) are sync or async?

If they are sync, are there any plans to making them async and returning a promise of some sort?

**Comment by techfort** [comment]
@alexandernst they are all sync, if there was any I/O involved in the future we may promisify those, but for now everything is in memory and in a single thread.

**Comment by alexandernst** [comment]
I see. Anyways, a promise could still be useful for 2 corner cases:

1. For operations that will take a longer time (thou I'm not really sure how many elements would be required for those methods to actually take a considerable amount of time)
2. For a possible future integration with WebWorkers.

**Comment by techfort** [comment]
@alexandernst indeed a promise approach would be nice, however: lokijs has no dependencies (only dev ones), and i'm reluctant to add any (e.g. a promise library). To work around that we'd have to move to ES6, which looks daunting at the moment and still requires babel as support is not 100% across the board. In time, definitely.

**Comment by alexandernst** [comment]
As I said in #268, ES6 is already present in all major browsers. Promises in particular are present in ~83% of desktop browsers (counting with IE) and 75% of mobile browsers (counting with Opera Mini, which has 0.01% market share).

I'm not pulling numbers from thin air, those are actual numbers that can be found [here](http://caniuse.com/#search=promise).

So, after analyzing the "per-usage" instead of the "per-browser" numbers, we can say that Promises are actually supported by 100% of the mobile browsers and 94% of desktop browsers (the only browser not supporting Promises is IE11, which will be deprecated soon). Note that I'm not counting IE8/9/10 as those are at EOL and usage is highly discouraged.

There are no real reasons to not switch to ES6 (and therefore, support Promises). IE11 users can still use a polyfill to emulate Promises.

**Comment by techfort** [comment]
@alexandernst you make good points, maybe i'm just being a bit paranoid. I love ES2015 and I write all new code with it. Maybe a move to it isn't such a bad thought after all.

**Comment by alexandernst** [comment]
Once decided if Loki should switch to Async, the next best thing to do is to decide how the entire thing is going to work.

Options are Node-like style and async-everything style.

The **Node-like** style means having two methods that do the same thing. One of then ending with "sync". (`update` vs `updateSync`, `find` vs `findSync`, etc...).

The other way is basically making everything async, without sync option.

**Comment by techfort** [comment]
at this point in time i lack the time to migrate, but when we do, i suggest we offer a node-like style.

**Comment by alexandernst** [comment]
Right now I'm assigned to a project that will probably be based on Loki (I'm yet studying all possible corner cases). If I decide to go with Loki, I'll provide PRs for this and for WebWorkers support.

**Comment by techfort** [comment]
that'd be awesome, thank you!

**Comment by omencat** [comment]
As an alternative you could promisify the loki object with [bluebird promisify](http://bluebirdjs.com/docs/working-with-callbacks.html#working-with-callback-apis-using-the-node-convention). I have not tested on loki, but used that same technique with other non-promise based modules.

**Comment by napa3um** [comment]
```javascript
setIntrval(() => { .../* work with myColl */... }, 1000)
...
myColl.find({ ... }).forEach(doc => {
    doc.prop = ...
    myColl.update(doc)
    // SOMETIMES: Error: Trying to update unsynced document. Please save the document first by using insert() or addMany()
    // SOMETIMES: Error: Trying to update a document not in collection.
})
```
Update() or Find() is not sync?
