### ISSUE TITLE
How do I use it in aurelia?

### ISSUE THREAD

**Issue by vegarringdal** [techfort/LokiJS#339]
What do I change to use loki use loki js in aurelia by using 

import {loki} from 'loki'

Where from = my loki.js from the minified download..

Thx

**Comment by vegarringdal** [comment]
import * as loki from 'LokiJS'; 
worked after I did this: 
jspm install LokiJS=github:techfort/LokiJS
...

**Comment by techfort** [comment]
hey @vegarringdal i'm not familiar with aurelia, even though it looks like a promising project.. i am also not familiar with jspm (i'm feeling old?) - i guess i'll ask around a bit so i can get back to you asap.

**Comment by vegarringdal** [comment]
I got it to work, sample small sample with loki here and anew improved grid Ive made using loki
http://vegarringdal.github.io/aureliaGrid/
