### ISSUE TITLE
query with array of arributes, values

### ISSUE THREAD

**Issue by vegarringdal** [techfort/LokiJS#340]
Is if possible to query with a array off arributes, values and comparison operators?

This is what Im kinda searching for
```javacsript


var params = [
{attribute:firstname, value:"liz", compareOperator:"$contains"}
{attribute:Lastname, value:"Op", compareOperator:"$contains"}
{attribute:Born, value:"01.02.2015", compareOperator:"$gte"}
{attribute:Age, value:50, compareOperator:"$lte"}
}

mySuperCollection.find('$and' :params)
```

And how do I make a find in-casesensitive?
So "liz" and "Liz" is the same..

**Comment by obeliskos** [comment]
You can either : 
* use nested queries
* query chaining
* collection transforms

nested query might look like : 
```javascript
var results = coll.find({
  '$and': [{ 
      'Age' : {
        '$gt': 30
      }
    },{
      'Name' : 'Thor'
    }]
});
```
collection transform might look like : 
```javascript
var tx = [
  {
    type: 'find',
    value: {
      'owner': someOwner
    }
  }
];
```
or chained queries which just run them in sequence

case insensitive find probably need $regex op.

https://github.com/techfort/LokiJS/wiki/Query-Examples
https://github.com/techfort/LokiJS/wiki/Collection-Transforms

**Comment by vegarringdal** [comment]
Thank you for the fast reply

Would have been great if there was a option you could pass into the query where it did lowercase to all database string attribute values, so during my query I could just transform my values to lowercase before passing it to the query if I wanted to.
