### ISSUE TITLE
Saving single collection instead of the whole database?

### ISSUE THREAD

**Issue by kerosin** [techfort/LokiJS#341]
Hey,

Imagine using around 20 collections with some heavy ones (like 4MB JSON data or so).
Is there a way to save a single collection instead of dumping the whole database? There might be changes that only affect a single collection. Or what is the sense of collections? Creating 20 databases seems to be wrong.

I only had a look at loki-cordova-fs-adapter, but it seems that the API currently only allows to dump a whole database.

Thanks in advance

**Comment by obeliskos** [comment]
We do keep dirty flags on each collection so in theory it could be possible to have a single database in memory but serialized each collection separately.   This would require a database adapter which supports our 'advanced adapter interface' which I don't think any support atm.  Advanced adapters get reference to the database itself so get as much control as needed.

There may be some complexity as we would probably want to add methods to collection to provide 'prepare' and 'restore' functionality for the collection.  When saving, the advanced adapter would probably need to clone the collection, 'prepare' and then serialize each collection to unique filename.  The clone collection prepare will remove event listeners and unique constraint object references.   When loading, the advanced adapter would probably deserialize and 'restore' to rebuild any unique indices.

If you are interested you can read a description of the advanced adapter interface here : 
https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters

**Comment by Johnsel** [comment]
I would be open to collaborating on this, I think it makes sense for my particular use-case as well.

**Comment by techfort** [comment]
@Johnsel that would be most appreciated!

**Comment by Johnsel** [comment]
We have this running internally, I will clean up the code and publish it soon, if there is none already?

**Comment by techfort** [comment]
That would be really appreciated

**Comment by kerosin** [comment]
Sounds great :wink:
