### ISSUE TITLE
Implement removeCollection

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#343]
The same way `addCollection` exists, it should be possible to `removeCollection`, dropping all the data, indexed, views, etc...

**Comment by techfort** [comment]
@alexandernst https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L753 - this what you're looking for?

**Comment by alexandernst** [comment]
Yes, exactly. Not sure how I missed it :)
Let me make a PR for the docs (it's missing there)

**Comment by alexandernst** [comment]
Done. https://github.com/techfort/lokijs.org/pull/11
