### ISSUE TITLE
Insert should make a copy of the inserted data instead of using references

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#347]
Consider this simple example:

```
loki = require('lokijs')
var db = new loki('sandbox');
var items = db.addCollection('items');

var data = { name: "Foo" };

items.insert(data);

data.name = "Bar";

console.log(items.find());
```

The expected (and reasonable) value that should be returned is `Foo`, but the value that is actually returned is `Bar`. The problem here is that `insert()` is using a reference instead of copying the data that is being passed. Using a reference is faster (as the data doesn't have to be duplicated in memory), but is very error prone (as I just proved with this simple example).

**Comment by freegenie** [comment]
I stumbled on this too as a novice user of LokiJS. Given it's communicated
a "database", I was expecting a database-like behaviour. Once understood
how ti behaves, I'm doing _.clone all around just to be sure that there's
no reference between the data "in the store" and the one I'm manipulating.
Most of the times I want to ensure that chaning a property by mistake does
not affect the data I inserted or updated explicitly.

Another consideration on this point: this behaviour makes it quite
dangerous to rely on the update event emitted by the collection, as my
application does.

**Comment by techfort** [comment]
hey @alexandernst @freegenie maybe i misunderstand what your problem is, but if you pass `{ clone: true }` as an option when initializing a collection then you get copies instead of references? see: [here](http://lokijs.org/#/docs#addCollection)

**Comment by techfort** [comment]
@alexandernst @freegenie closing this, if i misunderstood the issue feel free to reopen.

**Comment by alexandernst** [comment]
After testing this a little bit further, I really think `clone` should be enabled by default. Consider this other example:

```
loki = require('lokijs')
var db = new loki('sandbox');
var items = db.addCollection('items');

var data = { name: "Foo" };

items.insert(data);

data.name = "Bar";

res = items.find();
console.log(res); // <-- returns Bar

res[0].name = "Koo koo";

console.log(items.find()); // <-- returns Koo koo
```

The expected behavior is the document to contain `Foo`, but I can agree that `Bar` could be accepted as well, as far as the `clone` option isn't used. But then returning a set of result and being able to modify the collection itself from the result set is just not reasonable nor expected. No other database I know (and I have used quite some) allow such a thing.

I do understand `clone` is there for a (performance) reason, but making it `false` by default creates too many problems and too many error-prone situations and the benefits are not that much. Cloning an array of 100.000 elements takes less than a second (actual numbers, will post code below), so unless I haven't noticed other reasons, I can't think of a reason why this isn't set to `true` by default.

I invite you to reconsider making `clone: true` by default, so people that don't know what they are doing can work with the database without any risks and people that do know what they are doing can still squeeze all the performance from a `clone: false`-style database.

* Actual numbers:

```
var a = [];
for (i = 0; i < 100000; i++) {
    a.push({foo: i, bar: "Random string " + i});
}

console.time("Cloning a"); b = _.cloneDeep(a); console.timeEnd("Cloning a");
Cloning a: 672.412ms
```

This was run, as-is, on [lodash's website](https://lodash.com/docs)

**Comment by techfort** [comment]
@alexandernst you make good points but looking at the sheer number of downloads and apps that use LokiJS in production this is not a trivial change to just plonk on people. I actually agree on `false` being the default behaviour, but as it is effectively a breaking change, it will have to wait till 2.0. Pre-requisite for pushing a 2.0 at the moment are the completion of the tcp (which @johanneslumpe is working on) and the http wrapper (i have an unfinished draft in ES5, i want to rewrite it in ES2015).

**Comment by alexandernst** [comment]
Indeed, I wasn't expecting you to change that for 1.3.13. (btw you skipped
a version when you did the release earlier today). As you say, this is a
breaking change, so making "clone" as "true" by default for the 2.0 sounds
good to me.

Cheers
