### ISSUE TITLE
TypeError: null is not an object (evaluating 'dbObject.collections')

### ISSUE THREAD

**Issue by Papipo** [techfort/LokiJS#350]
My app suddenly raises that error when Initialising the database. I have tried deleting the database, autoloading it, and loading it manually, with the same result.

**Comment by Papipo** [comment]
BTW, the environment is Cordova. I also tried uninstalling the application.

**Comment by retorquere** [comment]
Same here, using LokiJS in a firefox extension.

**Comment by retorquere** [comment]
It is triggered by the following loader I've written:

```
loadDatabase: function(name, callback) {
      var file;
      file = Zotero.BetterBibTeX.createFile(name);
      Zotero.BetterBibTeX.debug('DB.loadDatabase:', {
        name: name,
        file: file.path
      });
      if (file.exists()) {
        callback(Zotero.File.getContents(file));
      } else {
        callback(null);
      }
      return Zotero.BetterBibTeX.debug('DB.loadDatabase: done', {
        name: name,
        file: file.path
      });
    }
  };
```

triggered to be specific by the `callback(null)`.

**Comment by obeliskos** [comment]
Sorry, been pretty swamped... if once of you could test out current (github) version and see if that helps.

**Comment by retorquere** [comment]
If that means just getting it from https://raw.githubusercontent.com/techfort/LokiJS/master/src/lokijs.js, then:

```
[JavaScript Error: "ReferenceError: dbstring is not defined" {file: "chrome://zotero-better-bibtex/content/lokijs.js" line: 1141}]
loadDatabaseCallback@chrome://zotero-better-bibtex/content/lokijs.js:1141:15
```

**Comment by retorquere** [comment]
Is there a literal I could feed the callback instead of `null` to signify "empty database"?

**Comment by obeliskos** [comment]
I must have made a typo... which others seem to have already fixed in #357.

No literal at the moment, I suppose we could support falsy literals like -1 or false... just curious why you wouldn't want to pass an Error object?

**Comment by retorquere** [comment]
I don't consider the file missing an error condition, in the same way that
sqlite opens a new file if you give it a name that doesn't exist yet.

**Comment by obeliskos** [comment]
I see... well it appears at the moment you can pass back integers to use however you want.  We would be open for suggestions for how we would like this to function in a future (breaking) 2.0 version.

Are integer literals ok for devising responses that the user can interpret?  They should be passed to user callback unmodified.  When calling loadDatabase on a newly instantiated loki object, if you return null (or let's say an integer literal) or even an error object, the database should be 'fresh' and the user callback where fire to let them know its ready and they can choose to ignore the err param passed in?

**Comment by retorquere** [comment]
That was the existing behavior, correct? This is what I do now (pass null)
and I always got a fresh db instance.

**Comment by retorquere** [comment]
https://raw.githubusercontent.com/techfort/LokiJS/master/src/lokijs.js now seems to work, https://raw.githubusercontent.com/techfort/LokiJS/master/build/lokijs.min.js gives me "ReferenceError: dbstring is not defined"

**Comment by retorquere** [comment]
Latest working release for me is 1.13.11. 

Is there a specced way that I can signal "no data, but that's OK?" I would speculate I could pass it a string with

```
{
   "autosaveInterval" : 10000,
   "autosaveHandle" : null,
   "filename" : "db.json",
   "autosave" : true,
   "verbose" : false,
   "persistenceAdapter" : null,
   "databaseVersion" : 1.1,
   "events" : {
      "warning" : [],
      "flushChanges" : [],
      "init" : [
         null
      ],
      "close" : [],
      "changes" : [],
      "loaded" : []
   },
   "options" : {
      "env" : "BROWSER",
      "adapter" : null,
      "autosaveInterval" : 10000,
      "autosave" : true
   },
   "engineVersion" : 1.1,
   "persistenceMethod" : "adapter",
   "collections" : [ ],
   "ENV" : "BROWSER" 
}
```

but that seems like a roundabout way to do things, and I don't honestly know if this is the minimal set it expects.

**Comment by retorquere** [comment]
Wait, the callback in https://github.com/techfort/LokiJS/issues/350#issuecomment-188696946 is not a user callback, but the LokiJS callback to asynchrously return the loaded data, right? If that callback expects a json-formatted string (in a particular format), then passing in an integer instead of null should also break.

**Comment by obeliskos** [comment]
I have rebuilt the minified version.  If lokijs.js was working for you, the minified should work just as well now.  You could, but should not need to pass an empty serialized db as response if the database (loki object) is newly instantiated and, thus, is already empty.  If it has data and you are trying to load a non-existent database you would need to clear it first, instantiate a new (empty) loki database object, or pass empty serialized loki database in response from your custom adapter method.  In the future maybe we can clear out database manually before attempting a 'loki' load.

As discussed, a response (from -your- loadDatabase() persistence adapter method) of null or integer should be enough.

In the future 2.0 version we might change name of adapter 'loadDatabase' to not confuse with loki's loadDatabase method signature with the adapters loadDatabase method signature.

**Comment by retorquere** [comment]
OK, tests are running again. Are src/lokijs.js and build/lokijs.min.js expected to be the same, usually? Or is build/lokijs.min.js only build when you release a build in https://github.com/techfort/LokiJS/releases?

**Comment by retorquere** [comment]
My tests pass again.

Will the breaking versions be marked in some way? Perhaps build/lokijs-v1.js vs build/lokijs-v2.js? Mu build process currently just picks up the latest released version (assuming that that is the one in the build directory).

**Comment by techfort** [comment]
@retorquere  when we decide to release a v2.0 it will be because it has breaking changes. However, this does not prevent us from creating a 1.x branch where backward compatible releases are created. You will have to manage the version in your project yourself.

**Comment by retorquere** [comment]
Understood, but will both be available for download? Right now, there's no version indication in the filename.

**Comment by techfort** [comment]
no the minified file will be the minification of src/lokijs.js, but you do make a good point in that we could dynamically add a \@version tag at the beginning of the file.

**Comment by retorquere** [comment]
That would be sufficient; I could test for that in my build procedure so I can fail the build if a breaking change is introduced; that would prompt me to update my code.
