### ISSUE TITLE
Browser Usage

### ISSUE THREAD

**Issue by ohenepee** [techfort/LokiJS#361]
I'm trying to build a WebApp where the browser will fetch and load the serialized db (not even sure whether I should use a plain JSON file or a Lokijs DB file) from the server. Now I'm pretty much lost what to do next since there aren't much examples concerning client-side (non-NodeJS) usage.

- GET json file via Ajax (will I need to fetch the db for each page navigation?)
- Utilize loadJSON (what type of JSON file is it expecting? LokiJS db file generated by Node?)
- What Next?

I've built several web apps that use LokiJS server-side but at the client-side, I'm pretty much lost!

**Comment by obeliskos** [comment]
loadJSON is meant specifically for a serialized loki object (json string).  You will need to determine how best to handle the page lifecycle and whether the data will be considered 'stale'.   You might just pull down data in bulk once per 'page load' and use loki just for querying capabilities, or you might cache server data by persisting in browser storage it and utilizing over several page loads.  You will be left to determine when data is 'stale' and needs refreshing from server.  In theory you could have the server pass you a serialized loki database but if your server is other database you will just be passing documents to insert on client.

If your serialized database is small enough (maybe under 5mb) you might use window.onbeforeunload to (synchronously) save to localstorage or another (synchronous) database adapter.  You can simply call db.close() in that routine and if it is dirty it should flush final changes.  

If you want to persist to an asynchronous persistence adapter like indexed db you will either have to rely on mouseleave events to save changes or just rely on autosave intervals to periodically save your data every few seconds if it had changed.

**Comment by ohenepee** [comment]
In fetching the serialized/existing LokiJS db file from server... what about the `env:NODEJS` part in the db?

**Comment by obeliskos** [comment]
When calling loadJSON we only copy db.name and db.version (along with all collections and dynamic views) from the json you pass.  The environment is not copied, so it would use whatever env was specified (or detected) when instantiating the database.

**Comment by ohenepee** [comment]
Will I need to delete the old IndexedDB database to load new data via loadJSON or all old data will be automatically cleared?

`idbAdapter.deleteDatabase('databaseName');`

**Comment by obeliskos** [comment]
If you call loadJSON you are bypassing our adapter loading mechanism.  Are you utiltizing any autoload/autosave functionality?

**Comment by ohenepee** [comment]
Yeah, I'm utilizing the `autoload` with the `autoloadCallback`

**Comment by ohenepee** [comment]
```
var 
  dbReady = false, 
  itemsColl, 
  dbInfoColl, 
  idbAdapter = new LokiIndexedAdapter('softy'), 
  idxdb = new loki('idxdb', {
    adapter: idbAdapter, 
    autoload: true
    autoloadCallback: function () {
      
      dbInfoColl = idxdb.getCollection('info');
      itemsColl = idxdb.getCollection('items');
      
      if (itemsColl == null) {
        
        // GET serialized database
        doXHR({
          
          strMethod : 'GET', 
          strUrl: '/idxdb.json', 
          strPost: null, 
          intTimeout: 3000, 
          boolAsync: true, 
          
          successCallback: function(objXHR) {
            idxdb.loadJSON(objXHR, function () {
              dbInfoColl = idxdb.getCollection('info');
              itemsColl = idxdb.getCollection('items');
              dbReady = true;
              console.log('INIT FETCH: items in db = ' + itemsColl.data.length);
              db.saveDatabase(); // could pass callback if needed for async complete
            });
          },
          
          errorCallback: function(objXHR) {
            console.error("The XHR failed with error ", objXHR);
          },
          
          timeoutCallback: function() {
            console.error("The XHR timed out.");
          }
          
        });
        
      } else {
        
        // Check AGE of db
        var dbInfo = dbInfoColl.get(1);
        
        if ((Date.now() - dbInfo.birth) > 864e5) { // older than 24 hours
          // Should we delete existing data/db? <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
          // DELETE DB
          idbAdapter.deleteDatabase('idxdb'); // delete 'finance'/'test' value from catalog
          freshFetch();
        } else {
          dbReady = true;
        }
        
      }
      
    }
  });
  
  function freshFetch() {
    doXHR({
      
      strMethod : 'GET', 
      strUrl: '/idxdb.json', 
      strPost: null, 
      intTimeout: 3000, 
      boolAsync: true, 
      
      successCallback: function(objXHR) {
        idxdb.loadJSON(objXHR, function () {
          dbInfoColl = idxdb.getCollection('info');
          itemsColl = idxdb.getCollection('items');
          console.log('FRESH FETCH: items in db = ' + itemsColl.data.length);
          db.saveDatabase();  // could pass callback if needed for async complete
        });
      },
      
      errorCallback: function(objXHR) {
        console.error("The XHR failed with error ", objXHR);
      },
      
      timeoutCallback: function() {
        console.error("The XHR timed out.");
      }
      
    });
  }
```

**Comment by obeliskos** [comment]
That logic sequence looks should work fine and that is how I would do that if I needed to do such.

Since you are calling loadJSON in autoloadCallback your manual ajax should 'win' and remain as result.

A word of caution, as I mentioned we do restore database 'name' property when you load a database either from adapter or loadJSON.   So if your server-side downloaded loki serialized database has different 'name' property that what you instantiated loki object with ('idxdb'), then it will save to different slot by name in json object.  If that is the case you might overwrite idxdb.name after calling loadJSON to reapply.

**Comment by ohenepee** [comment]
@obeliskos Thanks a lot for your kind assistance... Stay Blessed!
