### ISSUE TITLE
build/lokiIndexedAdapter.min.js is confusing

### ISSUE THREAD

**Issue by rubenstolk** [techfort/LokiJS#367]
Why is this file there?

**Comment by obeliskos** [comment]
It is an IndexedDB persistence adapter for browser use.

**Comment by rubenstolk** [comment]
@obeliskos difference with loki-indexed-adapter.min.js

**Comment by obeliskos** [comment]
indeed, file in issue title is obsolete.  I'll remove it

**Comment by obeliskos** [comment]
Removed in adedff8cb746bb83eb2810f673fd4d3cee4913fb

closing
