### ISSUE TITLE
Internal key 'meta' is too generic

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#368]
The internal key `meta` is too generic. It could easily collide with a `meta` key from a user-provided object. I propose to change it to `$loki_meta` or something that has less chances to collide with user data.

What do you think @VladimirTechMan @techfort @obeliskos ?

**Comment by techfort** [comment]
@alexandernst @VladimirTechMan @obeliskos some of the suggestions brought up - including this one - are valid points, however they would represent a breaking change as you know. I am thinking of creating a v2.0.0 branch so you can start playing around with all breaking changes (and maybe migrate to ES6). What do you reckon?

**Comment by alexandernst** [comment]
@techfort Yes, that would be great! I already discussed something similar with @obeliskos . Anyways, I first want to get done with my 3 pending PRs. I think I have found a bigger issue, but it's really hard to test, so it would be cool if we could do a final review on those 3 pending PRs and make a new point release (as none of those are breaking changes).

**Comment by deyhle** [comment]
Just ran into this issue. Would be really great if the properties would have less generic names.

**Comment by Redsandro** [comment]
Ran into this issue too. Why would this be a breaking change? I assume `meta` is for internal use. No one should use it, am I wrong?

I recommend `__meta` or `$meta` or `$loki_meta`.

If we could patch this in current rather than waiting for v2, we can move ahead.

**Comment by carchrae** [comment]
+1 on $loki_meta - and yes, you should not use it (or be prepared to be burned if you do).  seems like an easy thing to make a pull request for, just search and replace.

**Comment by Redsandro** [comment]
@carchrae see #608

**Comment by obeliskos** [comment]
```
npm install
npm run test
```

Any acceptable pr would have to have this enabled as a database or collection option and the default should be to continue to use 'meta'.  That would be how to avoid a breaking change.  Lokijs stores versioning information and last updated in meta, so people are probably using.

**Comment by Redsandro** [comment]
@obeliskos ah ok, what I failed to take into account is that:

1. Some people use LokeJS with storage adapters
2. `meta` is stored with the objects, not just for internal use on the fly.

If you can help me fix the paging size in an acceptable way, I can look into this further.

**Comment by thomasconner** [comment]
You can now turn off the use of the `meta` property by passing `disableMeta: true` as an option when you add a collection.

**Comment by metaa** [comment]
I know that's an old topic, but I'd still like to add my thoughts.

What I did to dodge this _possible_ problem is, I just add in a `data` attribute to the root level of items in collections, which then gets passed on to the application that reads from or writes to it through wrapper functions.
This way I'm free to name my attributes whatever I want to.

> I recommend `__meta` or `$meta` or `$loki_meta`.

Since we got both `meta` and `$loki`, I'd rather make `$loki` an object containing attributes `meta` (moved) and `id` which equals the _old_ `$loki` (but of course only in new versions such as `2.0.0` because that might be a breaking change).
This should be the easiest way to make everyone happy.

**Comment by greaterking** [comment]
This is actually causing me issues in [LokiDB](https://github.com/LokiJS-Forge/LokiDB)(the new iteration of lokijs). When docs contain the field meta it causes inters to fail. Often times meta is a typical field name for json data coming from sql database json column. `$meta` would have made more sense.

**Comment by Redsandro** [comment]
@greaterking did you try #644 (`disableMeta: true`)? 
v`1.5.2` and up.

__Disclaimer:__ Mentioning this in the hope it might be useful, however I have not actually tested it. We're now using `redis`.
