### ISSUE TITLE
revision vs version

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#370]
I'm looking at the internal data structure, but I can't see what is the difference between `revision` and `version` (in the `meta` object that lives inside each document). Any tips? @obeliskos @techfort @VladimirTechMan

**Comment by alexandernst** [comment]
Moreover, the only line of code in the entire source is https://github.com/techfort/LokiJS/blob/adedff8cb746bb83eb2810f673fd4d3cee4913fb/src/lokijs.js#L3791 and the only thing that it does is initialize `version` to `0`. It's not doing anything else, and I'm not sure if this is supposed to be used in some future version or if this is just garbage of some past code.

**Comment by techfort** [comment]
@alexandernst i think version is a zombie from the olden days. We can quite definitely eliminate it.

**Comment by metaa** [comment]
Can we revive this? 😮
This isn't a #wontfix but a `didn'tfix`.
