### ISSUE TITLE
Release 1.3.16

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#371]
Now that #365 and #366 (among others PRs of mine) have been merged and given the fact that those fixed quite some bugs, can we make a small patch release (1.3.16)? @obeliskos @techfort @VladimirTechMan

**Comment by obeliskos** [comment]
Fine with me... @techfort @VladimirTechMan  ?

@techfort does all releases but it seems ready should he have time to.

**Comment by techfort** [comment]
@alexandernst @obeliskos @VladimirTechMan  first of all thanks for all the work. v1.3.16 is relased.
Dropping you guys a mail today.

**Comment by alexandernst** [comment]
@techfort  I didn't get a mail :confused:
