### ISSUE TITLE
Question about FileSystem persistence

### ISSUE THREAD

**Issue by wicktus** [techfort/LokiJS#372]
Hello :),

I just wanted to know, LokiJs as of 1.3 (1.1), has a native FileSystem persistence adapter. 

I use Cordova (the app is for both IOS/Android), and I'd like **LokiJs to load my Json  stored in the data directory** (Cordova.file.dataDirectory) folder (check Phonegap-plugin-File) and save all the changes in that same Json, how do i do that ? I'm a LokiJs beginner, and a NoSQL beginner in general, but for what my app is supposed to do, using SQLITE is very heavy and not what I'm looking for at all and for now lokiJs seems to be very fast for everything i do :) (thx guys for the work btw)

**Comment by techfort** [comment]
hi @wicktus i think you're looking for https://github.com/cosmith/loki-cordova-fs-adapter
it provides a nice cordova adapter for lokijs so you can store and load your data locally.
