### ISSUE TITLE
distinct values

### ISSUE THREAD

**Issue by techfort** [techfort/LokiJS#373]
distinct should be supported out of the box

**Comment by obeliskos** [comment]
This could possibly be implemented internally via map/reduce.   Should be trivial for top level properties, might need recursion for dot notation (in map function).

http://stackoverflow.com/a/10468004

**Comment by obeliskos** [comment]
Oh save us, github now has emojis.  At least they seem somewhat safe right now.

**Comment by Simsal** [comment]
Hi!
is there any progression on this feature?

**Comment by techfort** [comment]
@Simsal this week is going to be madness but next week i should be able to get onto this.

**Comment by Simsal** [comment]
@techfort Sounds great :) wish you a happy coding week ;)

**Comment by mirho** [comment]
Any progress on adding distinct support? Thanks!

**Comment by obeliskos** [comment]
If you are really interested and your results are somewhat small you can do [something like this](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/34edf89d554ad88b07aa9dc8d5096f23/raw/ce5db507e8ca6bfdff6e95f5dc658faaaf4202ce/loki%2520distinct%2520mapReduce) in the meantime.

Might take a bit more effort to optimize it across a variety of values and types.

**Comment by mirho** [comment]
Thanks for the quick response! I will give that a try.

**Comment by IrosTheBeggar** [comment]
Any update on this?  I'm looking from switching from SQLite to Loki and a distinct operation would help a lot

**Comment by julien9999** [comment]
Hi, is this feature now implemented?

**Comment by Viatorus** [comment]
For me, these are some open questions:
* How should distinct be used (syntax, code example)?
* Should it be part of the query in find(...) or an extra function call like sort?

**Comment by adrienbuffet** [comment]
Bump ?

**Comment by Wyzix33** [comment]
bump ?
