### ISSUE TITLE
Find object with methods

### ISSUE THREAD

**Issue by Kunze** [techfort/LokiJS#375]
my code:

```
class Person {
    constructor(private _name: string, private _lastName: string) { }

    public get name() {
        return this._name;
    }

    public get lastName() {
        return this._lastName
    }

    public fullName() {
        return this._name + " " + this._lastName
    }
}

var murilo = this._collection.by("name", "Murilo");
murilo.fullName(); // [TypeError: murilo.fullName is not a function]

```
LokiJS is not creating the entire object in "by".
How can I fix this?

**Comment by Kunze** [comment]
I Don't know why but this.collection.by is returning this code below instead of undefined for not existing ids:
 function (value) {
  return self.by(field, value);
}

**Comment by VladimirTechMan** [comment]
@Kunze, two quick questions in relation to your reports above:
* Is the "clone" option for collections in your project enabled or disabled? I mean, when you create your collection, do you pass in the second argument with optional settings to the constructor function `Collection`?
* Do you see the above function being returned from `by` when you pass in a non-empty string, like in your first example above (`this._collection.by("name", "Murilo");`)? Or does the issue happen when you try to pass in the `0` numeric value or the `""` (empty-string) value occasionally. For the latter two value, I certainly see an issue in the current code, worth of fixing. But if you pass in something like `"Murilo"` as the second argument for `by()`, then I would not expect seeing a function returned back to you.

Please, clarify. Then I should be able to better understand your actual issue.

**Comment by Kunze** [comment]
The problem is that I was passing a empty string in "by". thank you.

**Comment by alexandernst** [comment]
@Kunze is this fixed? Can we close it?

**Comment by Kunze** [comment]
@alexandernst Yes, thank you.
