### ISSUE TITLE
Docs: Permalinks do not work

### ISSUE THREAD

**Issue by ArekSredzki** [techfort/LokiJS#376]
The platform which you're using to display documentation does not support permalinking. This is decently inconvenient.

Also, the documentation navigation sidebar is not properly responsive.

**Comment by obeliskos** [comment]
As mentioned elsewhere we are shifting to jsdoc documentation which does appear to allow permalinking.  You can view this documentation [here](https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html).

Feel free to comment on issues you may have on that format.
