### ISSUE TITLE
Use Grunt/Gulp

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#377]
Switch to Grunt for running tests/minifying/uglifying/etc...

Will safe quite some time and will make things easier.

**Comment by obeliskos** [comment]
@techfort switched from grunt to gulp so I'm not sure this would happen if it is just a preference thing.  feel free to give reasons or justifications though.

**Comment by alexandernst** [comment]
Oh, there is already gulp? I didn't realize that. Yeah, gulp will work just as well as grunt. My idea behind this was "make things a little bit more automated"

**Comment by alexandernst** [comment]
Were is the gulp entry point,  @obeliskos ? I can't seem to find it

**Comment by obeliskos** [comment]
ah now that i think about it your probably right.. I think @techfort and/or @seriousme subsequently replaced gulp with plain npm scripts.  I suppose we could add back in if needed... anything in particular that might be useful for you?

**Comment by alexandernst** [comment]
Quite some things! We could add babel, so we can write things in ES6 and
compile them to ES5. We could also add eslint/jslint to check for typos.
Minify/uglify/packer support for better minification of the final files.

Also, we can run tests from gulp/grunt based on env variables, which is
very useful for testing different parts of the code (instead of testing
everything always)

**Comment by obeliskos** [comment]
How would you feel about experimenting with many of these things in the 2.0.0 branch which @techfort has just created?  You and possibly Vlad (if he is interested in shaping a v2 version) can experiment without worrying about breaking changes or backwards compatibility.

So maybe minor features and fixes can still be added to master branch, but anything requiring experimentation, refactoring/breaking changes, and benchmark sensitive changes can work against 2.0.0?

**Comment by techfort** [comment]
regarding this particular issue, i don't like grunt, i like gulp much better, even though i find it really useful only when in conjunction with browser-sync and file watches for hot reloads. For lib development, not so much, but hey - up to you - v2.0.0 is there for the pillaging.

**Comment by VladimirTechMan** [comment]
@obeliskos @techfort @alexandernst I am fine with that, guys.

I am also positive on Gulp. Though for people not very familiar with some of the recent / modern (mostly ES6-originating) concepts and techniques in JS, like streams and promises, the learning curve with Gulp may be somewhat longer. But in terms of its capabilities, it's pretty flexible for automating different types of tasks. And as long as we aim at making Loki 2.0 itself based on ES6 (then, possibly, ES7, etc.) concepts and constructs, Gulp looks like a logical and natural fit.

Actually, my own project on top of Loki is all based on ES6, transpiled back to ES5/3 with Babel and then packaged with Webpack. (Not using Gulp itself there, as webpack covers what I need.) So far I am very comfortable with the results and the workflow. The only caveat of using transpilation back to ES5 is more complicated debugging in some case. But using source maps do help on that side.

**Comment by techfort** [comment]
Stream processing is actually my main rationale for switching to gulp. It
feels a lot more native than the configuration approach grunt uses.

**Comment by alexandernst** [comment]
Yes, working on all those things in the 2.0 branch would be perfect :+1: 

I'm more used to Grunt (just because that's what I have always used), but I can do it with Gulp too.

**Comment by techfort** [comment]
closing this, we will be using grunt for 2.0 or revert to plain npm if we are not satisfied.

**Comment by alexandernst** [comment]
@techfort Grunt or Gulp? I remember you saying you like Gulp over Grunt. Or maybe it was the other way around?

**Comment by techfort** [comment]
@alexandernst gulp. I updated the post above (where i typed grunt originally). Seriously, the baby keeps me up till 2 and then the 4 year old wakes me up at 5.30... and lately a dragon is sitting opposite me wherever i go.

**Comment by alexandernst** [comment]
:laughing: Have you tried asking Thor for some piety or help? (and the goat stuff and all that :D)

**Comment by techfort** [comment]
yeah i did. I got told "next time think twice about naming your projects."

**Comment by alexandernst** [comment]
Fair enough I'd say :D
