### ISSUE TITLE
Docs: Outdated documentation for `removeListener`

### ISSUE THREAD

**Issue by ArekSredzki** [techfort/LokiJS#381]
Your docs still inform users that they can use `db.remove` to remove a listener.

**Comment by stbaer** [comment]
+1, just ran into this Problem.

**Comment by obeliskos** [comment]
At this point, I am inclined to think that the best solution for maintaining 'more complete' and 'up-to-date' reference documentation is via jsdoc documentation.  This might eventually be something we can host on lokijs.com or github.

I have made a fix to the jsdoc comments to correct the jsdoc method description.  The comment now appears as : 
https://github.com/techfort/LokiJS/blob/b4cfb61b744f41dfc18d94f8e5089e970b37d793/src/lokijs.js#L538-L543

Our jsdoc is a work in progress so it is rather rough at the moment, however you can generate this on your own if you download latest master branch from github, npm install dependencies, and run : 
```
npm run jsdoc
```
If you wanted to generate your own

**Comment by techfort** [comment]
@obeliskos I completely agree, separate docs are now a concern instead of a
bonus...

**Comment by obeliskos** [comment]
Our jsdocs for this method is visible at : 
https://rawgit.com/techfort/LokiJS/master/jsdoc/LokiEventEmitter.html#removeListener

May still need to clean up description but the method signature looks correct.  Feel free to request or submit p.r. for any documentation changes as modifications to our jsdoc syntax.
