### ISSUE TITLE
Any plans for a SQLite adapter?

### ISSUE THREAD

**Issue by samuelgoldenbaum** [techfort/LokiJS#382]
Any plans for a SQLite adapter? Need to get around the db size limits in iOS.

**Comment by techfort** [comment]
Hey @samuelgoldenbaum - this is an interesting feature but i'm afraid one that I won't be able to tackle very quickly. Are you using cordova?

**Comment by moshewe** [comment]
This might go hand-in-hand with issue #302 ...

**Comment by DisruptiveMind** [comment]
is there any progress on this? sorry to hijack this but I'm looking to contribute some work on using sqlite as a simple backend so I can integrate it with cordova.

I have tried the cordova FS backend and tried using multiple databases but "stale" data seems to be kept in memory when switching db files...maybe this is a separate issue all together

**Comment by samuelgoldenbaum** [comment]
"simple backend so I can integrate it with cordova." - you do know that it exists right: [https://github.com/litehelpers/Cordova-sqlite-storage](url)

**Comment by DisruptiveMind** [comment]
@samuelgoldenbaum thanks, I am using that plugin but looking to use loki as the frontend

**Comment by samuelgoldenbaum** [comment]
Great, I'd be interested. Currently using PouchDB with the SQLite adapter.

**Comment by samuelgoldenbaum** [comment]
@techfort yes, using Cordova under Ionic. I'll take a look at the adapter implementation

**Comment by retorquere** [comment]
I have a simple (simplistic) adapter at https://github.com/retorquere/zotero-better-bibtex/blob/master/chrome/content/zotero-better-bibtex/db.coffee#L218. It is set up at https://github.com/retorquere/zotero-better-bibtex/blob/master/chrome/content/zotero-better-bibtex/db.coffee#L12, but it's really just a glorified key-value store.

**Comment by kerosin** [comment]
Wouldn't this require some kind of model definition for collections?
