### ISSUE TITLE
Use ES6 features

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#385]
ES6 offers quite some things that Loki could use to perform better some tasks.

I'll update this with all the things I can think about. For now:
- [ ] Use `Map` instead of plain `Object` (performance increase, https://jsperf.com/es6-map-vs-object-properties/2 )
- [ ] Use `Set` instead of plain `Array` (performance increase, http://jsperf.com/es6-map-vs-object-properties/102 )
- [ ] New `String` methods (`startsWith`, `endsWith`, `includes`). Will improve the performance of text search
- [ ] Default values for arguments in functions (will simplify some code)
- [ ] `Object.assign` can be useful for defaulting object-type arguments.

After #377 is implemented, Loki will be able to fallback to ES5 on unsupported platforms.

**Comment by moshewe** [comment]
Yes please.
I have a fork I've originally written in ES6 and the only thing that stopped me from putting a PR for it is the transition back to ES5.

**Comment by techfort** [comment]
@moshewe there is a 2.0.0 branch which - as I understand - is going to be gradually transitioned to ES6.
