### ISSUE TITLE
Unique Index Code Bug?

### ISSUE THREAD

**Issue by hsdk123** [techfort/LokiJS#389]
Hi, I was getting a weird duplicate index error despite not having any duplicates, so I was looking through the code and noticed:

```
UniqueIndex.prototype.set = function (obj) {
      var fieldValue = obj[this.field];
      if (fieldValue !== null && typeof (fieldValue) !== 'undefined') {
        if (this.keyMap[fieldValue]) {
          throw new Error('Duplicate key for property ' + this.field + ': ' + fieldValue);
        } else {
          this.keyMap[fieldValue] = obj;
          this.lokiMap[obj.$loki] = fieldValue;
        }
      }
    };
```
Instead of `if (this.keyMap[fieldValue])`, shouldn't it be `if (this.keyMap.hasOwnProperty(fieldValue))`?

**Comment by hsdk123** [comment]
I think I've found my problem: if you use a loki indexed adapter, the ensureUniqueIndex() function is called automatically. If you then call the ensureUniqueIndex() function manually afterwards, it triggers an error because the key has already been saved in the keyMap.

This seems very convoluted - I'm not quite sure what I should be doing.

**Comment by obeliskos** [comment]
As I remember it, we did not want to serialize the constraints themselves as they are duplicate objects to what we already have in data.   The idea was to not save constraints themselves but save list of unique property names and recreate on load if they are defined on a collection.   

I am noticing our serializeReplacer (at the loki level) is where we are attempting to null out the unique constraints when we probably need to do this in a collection level toJSON override.  I will need to look over to make sure we are not serializing objects themselves in collection unique object.

If you save your db/collections with unique indexes, you should not need to reapply them on load.  Is that ok? We may still have some old documentation indicating need to reapply but those docs should probably be updated if they say that.

**Comment by hsdk123** [comment]
Thanks, I guess my main concern is that my data might have multiple same indexes without my knowing. I hence don't mind using ensureUniqueIndex(), but a function that could just check whether all indices are unique would be a great addition (if one already exists that would be superb).

**Comment by obeliskos** [comment]
That should not be difficult... I will look this over in the next day or two.  ensureUniqueIndex should not create duplicate, and ensureAllIndexes (or possibly a new ensureAllUniqueIndexes) should rebuild all unique indexes if they do not exist... our loadJSONObject should call out to that instead of using inline logic.

**Comment by obeliskos** [comment]
Alright, i made a simple fix which should allow flexibility in (re)applying unique indices without erroring.

I believe @techfort created unique index functionality so i am testing the waters here but here are some thoughts on consistency : 

- If you are just inserting objects, your unique constraints (and collection) should remain valid no problem.
- By default loki does not clone objects.  If you update your object to violate unique constraints, and call update... loki will maintain integrity of the constraints index but damage is already done on your object.  You will be notified of error but you would have to fix it by removing that duplicate key.

So it would seem the 'unique indices' feature should probably require collection cloning be enabled.

Any thoughts @hsdk123 @techfort @alexandernst @VladimirTechMan ?

**Comment by alexandernst** [comment]
I completely skipped unique indices while reading Loki's code, so I can't really say what would be a good fix for this. Reading that part of the code is on my TODO list, just if I could get 483h in a day... that would be awesome.

**Comment by obeliskos** [comment]
I only pulled you guys in since this might be in line with 2.0 'profiles'

**Comment by obeliskos** [comment]
I believe this was resolved, closing.
