### ISSUE TITLE
use just one test framework

### ISSUE THREAD

**Issue by GKuChan** [techfort/LokiJS#39]
I found some new commit also use `gordian` instead of `mocha`, we should use just on test framework, and add more base unit test.

 `mocha` is more popular, isn't it ?

**Comment by techfort** [comment]
@GKuChan sorry for the long delay on this. The whole testing framework has been moved over to `karma`, which in the end is similar to what you were asking. It may even be that we move over to `mocha` soon, thanks for flagging this a long time ago.
