### ISSUE TITLE
Consider using Mindex for LokiJS secondary indexes

### ISSUE THREAD

**Issue by internalfx** [techfort/LokiJS#391]
Hi LokiJS Team,

I created an indexing system based off the technique LokiJS currently uses.

It's called [Mindex](https://github.com/internalfx/mindex).

It adds the capability of compound indexes. So you could search for records where `city = 'denver' and age = 35`. and get very performant results. It also returns fast ranges and has a simple query syntax.

Thanks for the initial idea of how to do a fast index with JS. The code is ISC Licensed so you could just copy it into core if you don't want another dependency.

**Comment by techfort** [comment]
@internalfx thanks for the interesting idea, i was checking Mindex out today and it looks great. We'll definitely keep it in mind, let me peruse your code first.
