### ISSUE TITLE
jsdoc preview

### ISSUE THREAD

**Issue by obeliskos** [techfort/LokiJS#393]
In order to improve loki documentation, I am attempting to leverage jsdoc to allow for better 'distributed' documentation effort.  We are still very early in the process so the documentation structure is still very rough. 

At least for the time being, i will check in the actual generated jsdoc web pages into master branch.  By doing so we can have live web link to review this documentation online (as well as your own computer).  If there are any issues with this let me know, it adds maybe 1mb to master.  I have 'npm ignored' this directory though, those users can 'npm run jsdoc' to generate it themselves.

A link to preview this documentation can be viewed here : 
https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html

My current thought is to look into adding markdown pages, possibly mirroring our wiki pages and utilize better topic link organization.  This will allow you to choose class reference topics or subject matter topic pages.

 If anyone wants to help out with identifying discrepancies, typos, styling, or help out with structuring our jsdoc configuration, feel free to do here or as a pr.

**Comment by techfort** [comment]
@obeliskos this is so welcome and badly needed!!

**Comment by Smurf-IV** [comment]
Please fix the "Optional" parameters
i,e, 
`     * @param {bool} isdesc - (Optional) If true, the property will be sorted in descending order`
should be
`     * @param {bool=} isdesc - (Optional) If true, the property will be sorted in descending order`

This will then remove the "noise" from the IDE's that know how to read the param data.
Thanks

**Comment by obeliskos** [comment]
Thanks for heads up, after searching that seems to match up with [this](http://usejsdoc.org/tags-param.html).  I'll test that out and phase in, or if you would like to submit p.r. with changes feel free to do so.

Could you mention a few examples of ide's that are able to use that info?

Thanks

**Comment by Smurf-IV** [comment]
I've been using webstorm since 11 (Currently on 2016.2.eap) and I understand that visualCode makes use of the jsdoc as well.
Also look up the usage of the following symbols for the type markup ?! []
i.e. `@param {?string}`

**Comment by obeliskos** [comment]
Well I have cleaned up a bit regarding optional parameters, feel free to let me know if there are any issues.  I will try to make another pass to clean up handling of null specifications later.   As always if you need expedited changes, feel free to submit pr's to fix any issues that may be nagging.

These changes are in github repo and will be propagated to npm as new releases are made.

Thanks

**Comment by techfort** [comment]
@obeliskos is there any way to use the generated docs from our github repo
as a live html page so I can replace the current docs page on the website
with a constantly up to date one?

**Comment by obeliskos** [comment]
hmm well they are already live at : 
https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html

Maybe embed within iframe in your page?  I just tweaked the master/jsdoc/styles/jsdoc-default.css to more closely match lokijs.org theme but you can further tweak that css if you want.

**Comment by obeliskos** [comment]
old non-issue and it was mine so closing
