### ISSUE TITLE
How would I load a database direct from a url pointing to a JSON file?

### ISSUE THREAD

**Issue by dukedougal** [techfort/LokiJS#397]
I'd like to load a JSON file directly from a URL into the database.

Is this possible?

thanks

**Comment by techfort** [comment]
@dukedougal is the JSON file a LokiJS dump or a plain JSON? If it's a plain JSON then I assume you have an array of object you want to load into LokiJS, simply load the file then iterate the array like:
```javascript
jsonArray.forEach(o => myColl.insert(o));
```

**Comment by dukedougal** [comment]
OK thanks.
