### ISSUE TITLE
[FEATURE] collection.extract() multiple properties

### ISSUE THREAD

**Issue by roblav96** [techfort/LokiJS#398]
It would be awesome if I could do something like:
```javascript
collection.extract( ['uname', 'dname'] )
```
but currently it only allows one field to be extracted.

Any way we can quickly implement this?

**Comment by obeliskos** [comment]
I'm not sure who wrote the extract() function or if mongo has something similar it's trying to be compatible with.

So this function returns array of values for the property you are extracting.  So how would you expect multiple columns to work, would it return something like this ?

[['un1', 'dn1'], ['un2', 'dn2'], ['un3', 'dn3']]

or : 
[ { un: 'un1', dn: 'dn1' }, { un: 'un2', dn: 'dn2' }, { un: 'un3', dn: 'dn3' }]

Without adding anything you can currently do something like this (with native javascript) : 
```javascript
coll.find().map(function(obj)) {
   return { un: obj.uname, dn: obj.dname};

  // or you could return subarray
  return [obj.uname, obj.dname];
}
```

If you mean to do this without a js function, feel free to specify that as well.

**Comment by roblav96** [comment]
Thanks for the input! I never knew you could do something like that! Thanks!!!
