### ISSUE TITLE
Bulk loading from a JSON document

### ISSUE THREAD

**Issue by carlskii** [techfort/LokiJS#399]
Hi, I have some fairly large JSON files which contain an array of documents. Is there an easy/preferred way to import them into a LokiJS database ? 

Are there any example on how to do this ?

**Comment by techfort** [comment]
@carlskii would this be of help: https://github.com/techfort/LokiJS/issues/397

**Comment by carlskii** [comment]
Thanks yes. 

Is `jsonArray` a LokiJS function ?

**Comment by techfort** [comment]
@carlskii no `jsonArray` is a hypothetical variable representing your json array. It could be a file you loaded from fs in node or a json response in the browser, whatever your use case is.

**Comment by carlskii** [comment]
Argh of course - sorry. Thanks.

**Comment by techfort** [comment]
@carlskii no problem! happy Loki-ing. Closing this, feel free to reopen if you need more help.

**Comment by carlskii** [comment]
Sorry one more question - just trying to get my head around LokiJS

Can you explain what the `o` represents in the example ?

**Comment by techfort** [comment]
That's ES6 syntax, look up ES6 arrow functions.

**Comment by obeliskos** [comment]
According to my recollection and to our [documentation](https://rawgit.com/techfort/LokiJS/master/jsdoc/Collection.html#insert), you can pass an array of documents to collection.insert()... es6 not required.

**Comment by techfort** [comment]
@obeliskos i just slapped my face so hard i got dizzy.
