### ISSUE TITLE
Running Loki as a process

### ISSUE THREAD

**Issue by carlskii** [techfort/LokiJS#400]
I thought I would clarify this question a bit more. 

I'm trying to understand the best place to instantiate LokiJS from within an Electron app. 

It would make sense to me that I do this in the main process?  This leads to the core of my question. I assume that if LokiJS is instantiated here then it will continue to run as part of that process ?

**Comment by obeliskos** [comment]
I just tried out the [electron-quick-start](https://github.com/electron/electron-quick-start) app and was able to attach a global reference using info found at [this post](https://discuss.atom.io/t/how-to-set-global-variable-of-main-process/24833/3).

**Comment by carlskii** [comment]
Thanks - I'll give this a try.

**Comment by carlskii** [comment]
Did you use the IPC or Remote methods referenced in the post ? Also would you mind sharing you're example.

**Comment by obeliskos** [comment]
Just did a quick test where the global looks something like this : 

```javascript
const electron = require('electron');
var loki = require("lokijs");
var db = new loki('test');
var coll = db.addCollection("tc");
coll.insert({
   first: 'hey',
   last: 'there'
});
global.sharedDB = db;

// Module to control application life.
const app = electron.app;

```

And then in index script or dev-tools console you can : 
```javascript 
require("electron").remote.getGlobal("sharedDB").getCollection("tc").find()
```

**Comment by carlskii** [comment]
Perfect now I get it thanks

**Comment by carlskii** [comment]
I'm making some good progress here, however and everything seems to work in my dev environment. However, when I package my app including the `loki.json` file into the electron resources directory it appears that it can't find `loki.json`. I have other files in the same directory as `loki.json` that are accessible by the electron app. 

Does Locki expect anything different with regards to this JSON file ?

**Comment by carlskii** [comment]
It seems that Locki needs an absolute path to the json db file.

**Comment by obeliskos** [comment]
Interesting... I just added a db.save() and it saved to directory I launched process in (from console).  Are you starting as part of a script/batch from another directory?

**Comment by techfort** [comment]
@carlskii @obeliskos strictly speaking this seems resolved so I'm closing it. Feel free to reopen if needed.
