### ISSUE TITLE
simplesort is not a function?

### ISSUE THREAD

**Issue by kunkinkan** [techfort/LokiJS#402]
When I run the example, I get the above error message

`var results = coll.find({'Age': {'$gt':20}})
                  .where(function(obj) {
                     return obj.Country.indexOf('FR') === 0;
                   })
                  .simplesort('Name')
                  .offset(100)
                  .limit(25)
                  .data();
`

**Comment by obeliskos** [comment]
Should have started out as coll.chain().find().....  Our query examples wiki page had that wrong so I just fixed it.
