### ISSUE TITLE
Minor: Mozilla linter complains that `setInterval` is called in potentially dangerous manner 

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#403]
It's complaining about this line specifically: https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L3591 . They recommend using only direct function arguments for setTimeout for what they claim are security reasons, so something like

```
this.ttl.daemon = setInterval((function() { this.ttlDaemonFuncGen() }).bind(this), interval);
```

whether their claim makes sense I do not know.

**Comment by obeliskos** [comment]
Interesting, could it be they just don't like passing factory/funcgen?  Does it complain if you do something like this ? 

```javascript
  var tdf = this.ttlDaemonFuncGen();
  this.ttl.daemon = setInterval(tdf, interval); 
```

**Comment by retorquere** [comment]
Yep, they don't like anything but 

```
setInterval(function() { ... }, interval)
```

Even if all that function does (the linter even suggests it) is calling `tdf`.

I don't agree with everything Mozilla claims on security, but I do happen to know that it's very, very easy to "wrap" functions in javascript to augment their behavior. That's a general thing in JS though. I don't know exactly what the purported danger is in wrapping functions that happen to get called by setTimeout.
