### ISSUE TITLE
Expose the built in persistenceAdapters.

### ISSUE THREAD

**Issue by Kanaye** [techfort/LokiJS#404]
Hey there!

As the title suggests I want to discuss if you could expose the Loki built in persistence adapters to something like:
```javascript
loki.adapters //  => {fs: /* constructor function of fs adapter */, localStorage: ...}
/* or */
loki.persistenceAdapters // => like above
```
To make this more clear: the ``loki`` variable in the example above is the constructor not an instance of lokijs.

My use case is a "proxy" adapter that serializes the database to [messagepack](http://msgpack.org/) instead of json. And I would like to use the built in adapters instead if writing an own one for fs and local storage.

Greetings from Germany

**Comment by obeliskos** [comment]
I don't see why not... would you care to submit a p.r. for this?
