### ISSUE TITLE
Question: id field for unique id

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [techfort/LokiJS#407]
Looking for aliasing "$loki" used in the JSON document for indexing something like "id",  we want auto-incremented, no-duplicate ids for database, primarily used for training purpose in the class room.

Can I use "id" as unique and auto-increment or alias $loki with "id"? Both shall work for me.

**Comment by obeliskos** [comment]
As of now I don't think so.... you could set your own unique key property but we don't autoincrement it for you. 

I suppose it could be possible to pass in as loki constructor option to specify our unique property name but would need to replace internal $loki references and verify performance is not adversely affected.  If your purpose is immediate you could fork and search replace $loki with id.  Collection protos might allow defining 'getters' to alias but wouldn't be very hidden.

**Comment by gopalakrishnan-subramani** [comment]
Forking is good for me, I would replace $loki with 'id'. As stated, this is for educational purpose, used for workshop. I am using json-server, moving to loki for performance, more features.

**Comment by gopalakrishnan-subramani** [comment]
Forked, replaced $loki with id, works fine. I shall look into using unique id defined via constructor.

**Comment by techfort** [comment]
@gopalakrishnan-subramani @obeliskos i'm going to close this as `$loki`was introduced to eliminate the conflict with the `id` field which is a very common field name especially when syncing remotely.

**Comment by artch** [comment]
+1 for configurable option to expiclitly specify which field name should be used for auto-incrementing (with `$loki` as default value).

**Comment by taymoor89** [comment]
I really want to rename `$loki` to something like `id`. Completely agree the way @artch suggested!

**Comment by techfort** [comment]
@taymoor89 @artch maybe not ideal - but as an interim solution you can assign an `id` property to your object that references the `$loki` on `insert` event in the collection.

**Comment by developer82** [comment]
@techfort how would you go about it? In the time of the insert it would just add a property with `undefined` value

**Comment by ViggoV** [comment]
@developer82 After playing around a bit I got what @techfort meant. You can add an event listener to your collection that fires on insert, and there you can update the id to the value of `$loki`:

```javascript
var myCollection = db.addCollection('my_collection');
myCollection.on('insert', function(input) { input.id = input.$loki; });
```

Hope it can save someone some frustration.

**Comment by TimPchelintsev** [comment]
As insert value can be array, previous comment solution should be expanded to:

```js
myCollection.on('insert', function (input) {
  if (Array.isArray(input)) {
    input = input.map(item => ({ ...item, id: item.$loki }))
  } else {
    input.id = input.$loki
  }
})
```

Hope it can save someone some frustration and thanks to @ViggoV for pointing out to right direction.
