### ISSUE TITLE
window.indexedDB causes errors in web worker

### ISSUE THREAD

**Issue by thrownblown** [techfort/LokiJS#408]
i use a web worker to communicate with my servers and update the indexedDB in a background thread.

i simply removed the window from the window.indexedDB in the checkAvailablity method (line 66 in the indexedDB adapter, https://github.com/thrownblown/LokiJS/commit/8223f484648cc9871da0e9e849fd5742a1b89d9b) and my web worker stopped throwing errors.

Is there any need to absolutely have the reference to window explicitly named, since idexedDB is in the global scope without "**_window._**" preceding it?

**Comment by obeliskos** [comment]
I suppose we could get rid of the window qualifier, I can do that later or feel free to submit p.r.
