### ISSUE TITLE
How to "find" Mixed value type in collection

### ISSUE THREAD

**Issue by mathcoll** [techfort/LokiJS#411]
Hello,

I have (sadly) mixed some id in theCollection, some 'id' are in string, and other are as integers.
sample collection:
{ "$loki":6,  "name":"My Name 1", "id":6 ... ...},
{ "$loki":7,  "name":"My Name 2", "id":"0f03ca55-306e-4d35-b162-e4bb8e44c30f" ... ...},
 ... ...

Then, I'm not able (maybe my bad?) to find (or findOne) using that id; I have tried all the following variants in querying, all of them worked on only one case (the Integer mode OR the String mode):
```
var searchId = 6;
var res = collection.findOne({'id': ''+searchId });
var res = collection.findOne({'id': parseInt(searchId) }); // of course bad results
var res = collection.findOne({'id': searchId });
var res = collection.findOne({'id': { '$eq': searchId } });
var res = collection.findOne({'id': { '$regex': searchId } });
```

What would you suggest? Thanks.

**Comment by obeliskos** [comment]
Yea our $eq op (which you are using implicity/by default) is strict equality.  We should probably have a non strict equality op which would coerce the types.

**Comment by obeliskos** [comment]
I have added an $aeq operator which you can use for finding based on abstract/loose equality.  The default implicit equality uses $eq so you will have to specify the operator as (for example) : 

```javascript
var res = collection.findOne({ 'id': { '$aeq': searchId } });
```

**Comment by mathcoll** [comment]
$aeq is fine and works as expected.
Thank you for the fast commit ! :-)
