### ISSUE TITLE
Inserting document with unique key violation

### ISSUE THREAD

**Issue by eschlosser** [techfort/LokiJS#413]
I am running the latest, as of 5.3.2016, minified Lokijs from Lokijs.org and NW.js v0.12.3-win-x64.

I am trying to generate an error when I attempt to insert() a duplicate key value. The collection has a unique constraint set for the 'name' key.  To be clear, I do receive an error when I update() duplicate keys.

When I run the code below, as expected, no additional documents are inserted into the collection and the database is saved. However, no errors are generated.

When I change the key value to something else, the unique document is then inserted and saved properly.

Should an error be thrown on insert() as is, or are there additional steps I need to perform first?

**loki.db:**
`{"filename":"loki.db","collections":[{"name":"test","data":[{"name":"erik","meta":{"revision":0,"created":1462493328062,"version":0},"$loki":1}],"idIndex":[1],"binaryIndices":{},"constraints":null,"uniqueNames":["name"],"transforms":{},"objType":"test","dirty":true,"cachedIndex":null,"cachedBinaryIndex":null,"cachedData":null,"transactional":false,"cloneObjects":true,"cloneMethod":"parse-stringify","asyncListeners":false,"disableChangesApi":true,"autoupdate":false,"ttl":{"age":null,"ttlInterval":null,"daemon":null},"maxId":2,"DynamicViews":[],"events":{"insert":[null],"update":[null],"pre-insert":[],"pre-update":[],"close":[],"flushbuffer":[],"error":[null],"delete":[null],"warning":[null]},"changes":[]}],"databaseVersion":1.1,"engineVersion":1.1,"autosave":false,"autosaveInterval":5000,"autosaveHandle":null,"options":{},"persistenceMethod":"fs","persistenceAdapter":null,"verbose":false,"events":{"init":[null],"loaded":[],"flushChanges":[],"close":[],"changes":[],"warning":[]},"ENV":"NODEJS"}`

**code:**
`var loki = require('lokijs-1.3.min.js');`
`var db = new loki();`
`var collection = db.addCollection('test', {`
`    clone: true,`
`    unique: 'name'`
`});`

`collection.on('error', function(error) {`
`    return console.log(error);`
`});`

`collection.insert({ name: 'erik'});`
`collection.insert({ name: 'erik'});`

`db.saveDatabase();`

**Comment by obeliskos** [comment]
Ok so I was unfamiliar to how this was implemented but after looking it over it seems : 
- an exception is being caught on [line 4021](https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L4021-4024)
- within that catch block it is redirecting to a collection.console which ignores the error even if database verbose is true.

I think we could emit in the catch block of collection.add() which I linked to above.  I will try to work that fix in as time permits or you can submit a p.r.

**Comment by obeliskos** [comment]
We should now emit an 'error' event when attempting to insert duplicate key.  Seems to work for my test, feel free to test out and post results.

**Comment by eschlosser** [comment]
The 'error' event is now triggered successfully.  However, the error is not caught if you were to use try/catch instead.

`try {`
`            collection.insert(document);`
`        } catch(error) {`
`            console.log(error);`
`        }`

**Comment by obeliskos** [comment]
alright, verify that works as expected

**Comment by eschlosser** [comment]
Verified both methods catch errors as expected, thank you.  However, $loki increments regardless if the inserted document errors or not.  For example, my first document in the database has $loki: 1.  I then try to insert a document which violates the unique constraint which generates $loki: 2.  I then insert a document successfully and save.  The database now contains $loki: 1 and $loki: 3.

**Comment by techfort** [comment]
@eschlosser thanks for flagging that. I am happy enough with the current state of things, i will look at skipping increment in case of a rollback.

**Comment by eschlosser** [comment]
Thanks guys.

**Comment by webmutation** [comment]
Is it possible to bulk insert and skip existing keys? Use case, I am scanning a feed of articles and save the URLs to cache so i don't have to call the service every time something like 

` coll.insert([{a},{b}], skipExisting)`

I can handle when doing single inserts but doing a bulk insert would be much nicer...

**Comment by techfort** [comment]
@webmutation it would be possible but - like bulk inserts - under the hood this would just be an iteration of single insert operations, so you wouldn't get much out of it other than syntactic sugar.

**Comment by webmutation** [comment]
Thanks for the quick reply. So i should just use an object instead of an array and in case it exists i continue 

I was under the impression that bulk inserts would be faster if that is not the case then i will not use it :)

So I can simply do something like 

```
for(let document in networkCollection){
                try {
                    collection.insert(document);
                } catch(error) {
                    console.log(error);
                    //continue flow...
                }
}
```
