### ISSUE TITLE
Is there a non-minified release?

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#415]
I'm getting exceptions from an insert into a collection, but the minified version makes debugging very hard.

**Comment by Kanaye** [comment]
You can just use the src/lokijs.js file e.g. [here](https://github.com/techfort/LokiJS/blob/master/src/lokijs.js).

**Comment by retorquere** [comment]
Oh, I had assumed the "build" directory would have stable releases vs the src dir. Thanks!
