### ISSUE TITLE
Deep find in array.

### ISSUE THREAD

**Issue by Kanaye** [techfort/LokiJS#416]
Hey,
I tried to migrate an app using an old loki version but got in some trouble.
 
I start with an example to clarify the problem:
```javascript
// ...
// imagine a collection like this:

myCollection.insert({
    /*...*/
    id: 1,
    children: [{
            someProperty: 42
        }
        /* ... */
    ]
});

myCollection.insert({
    /*...*/
    id: 2,
    children: [{
            someProperty: 60
        }
        /* ... */
    ]
});
// ...

// In a previews version of lokijs this worked:
myCollection.find({'children.someProperty': 60}); // now returns: []
```
Unfortunatly I have no more time to spend on this yet.
[This](https://github.com/techfort/LokiJS/commit/6e2720832bd468db9335b422e4a31c8dde826d4d) is the commit that broke it.
I might have time to look at this later.
For now I will just use where and implement it myself...

Have a nice day and greetings from germany
Joscha

**Comment by obeliskos** [comment]
Hah, I didn't realize we even had that functionality, I was about to tell you we never had that functionality.  But I tested it and sure enough we did.  So I got curious and seems it was me who added it back [here](https://github.com/techfort/LokiJS/commit/e75078db38a86aea35a9c1acab3e9f1c5bddee87).  

Yea I will look into fixing it.  If @VladimirTechMan is still around somewhere he might look at fixing or sanction any changes I might make in next few days.  I'll probably add tests to ensure this keeps working after we fix.

**Comment by obeliskos** [comment]
Should be fixed now, let me know if there are any issues

**Comment by Kanaye** [comment]
Awesome!
Works as expected. Thank you for that fast fix :+1:.
Closing this.

Have a nice day :smile:

**Comment by VladimirTechMan** [comment]
@obeliskos, thanks for addressing that while I was away!

@Kanaye, my apologies for the inconvenience that the code change caused. I used my own tests to check that the things work, as I am relying on nested properties quite a bit in my project. But my situation with the nested array properties was a bit different, thus I can see why it broke it in your case.

@obeliskos, good that we have that part covered with tests now.
