### ISSUE TITLE
Index a database by more than 1 field

### ISSUE THREAD

**Issue by joehui** [techfort/LokiJS#419]
I am looking into creating a database for storing some user statistics.  For example, my table may have the following fields:

- UserID
- Date/Time
- ProjectID
- NumberOfHits

I want to perform a search to quickly find the user's statistics for (UserID= "John and a specific date range).  I am wondering if there is a way to create an index that combines both UserID and Date/Time, and then be able to filter the result set by these 2 fields.

Thanks,
Joseph

**Comment by obeliskos** [comment]
We currently do not support compound keys... it would not be an easy feature to add with the variety of data types and expectations of strict or loose evaluations, especially with ranges involved.

From a pure performance perspective, we currently do not have a 'between' find operator, so your range filter would be implemented as two operations ($gt/$gte your lower range, and $lt/$lte your high range) and only the first would be able to utiltize a binary index if it were applied to the property... the subsequent operator would execute an array scan on the results of the first with no index optimization.

Having said that, this is an in-memory database so it is still quite fast, but if I were you I would determine which of the three ($eq userid, $gt datetime, or $lt datetime) would consistently filter out the most results.  If either of the datetime filters filter out more documents than the userid itself you can apply it to the datetime property and put that op first, but I would expect I would just use UserID.

How many documents do you expect the collection to contain?  Out of that number, how many documents might exist for a given user?

**Comment by joehui** [comment]
Yes, the other problem is the size.  I expect the rows will grow by at least over a thousand entries per month.  (Each user will have atmost several hundred entries per month.)

I will probably look into using some other database technology for this implementation.
