### ISSUE TITLE
.update(obj) does not work as expected

### ISSUE THREAD

**Issue by Mojo90** [techfort/LokiJS#420]
My Problem is a bit weird because for one sort of my DataModel the .update(object)-Function does not work.
I am pulling Elements from a Wordpress Blog and if there is something new I overwrite all properties of the old/persisted element with the new one with this code:
```
function replaceObjectWith(n, db){
	var old = db.findObject({
			ID: n.ID
	});
	if(old != null){
		for (var property in n) {
			if (n.hasOwnProperty(property) && old.hasOwnProperty(property)) {
				old[property] = n[property];
			}
		}
		db.update(old);
	}
}
```
I have a few different categories and for each category I have one collection. This does work for all categories/collections except for one and I don't know why because I do it always the same way. With this category I get the following error:
`TypeError: null is not an object (evaluating 'arr')`
`lokijs.min.js:3:18710`

And then in this collection the Item is doubled, how can this be? I mean not only the complete Element is doubled but also the $loki has the same ID. How could that happen? I thought this is the unique ID... Already tried a lot of things but now a bit confused

EDIT: 
The object I pass with db.update(old) is of course not null.
What is really strange is that if I commenting out the last line of Collection.prototype.update ("throw err") than it works like a charm! If it is not commented out it throws this error, and no I do not pass an array I pass a normal Object with a few properties!
Any help appreciated what is wrong here?

**Comment by obeliskos** [comment]
If you are able to reproduce this by "not commenting out the throw in collection.update()" then you have more to go on than me :)  Maybe post a plunkr or swap out the minified for full loki.js and step into it.

By default, loki returns your 'find' results as the same object references as it keeps internally.   So it would be easy for you to overwrite the internal objects if you modified the objects returned unintentionally and/or did not bother to call update().  The other possibility is that somewhere in findObject() and/or update(), we are ourselves duplicating your object.  

I tried to recreate this in a [simple example](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/2465f4a1a99f546f968d3f2f4d6c87d2/raw/2d69cef22e1fe0a53e0e4e324c1e136b90656833/graftObject) but it seemed to be working as expected for me.  

Aside from posting a plunkr, if you can recreate this on a new collection you might use the 'clone' option when calling db.addCollection() to ensure internal object references are not exposed to user.  If it was your code corrupting it, that should prevent it and/or shed more light on issue.

**Comment by Mojo90** [comment]
Thanks for your help. I'll try with the full loki.js this evening and have a look if it is the same behavior or not. With your simple exmaple please click 2x very fast one after another on "Run" an then the result for me is this: 
<img width="1033" alt="screen shot 2016-05-17 at 14 15 33" src="https://cloud.githubusercontent.com/assets/2122156/15321968/2c515c88-1c3a-11e6-8b86-951fc4618ed6.png">

Not sure why but it seems that my code tries to update the object very fast 2 times for this one category, could that be? Whats going on than with loki.js? As be said I'll try out later and report...

**Comment by obeliskos** [comment]
Hmm not sure 2x click is loki issue, probably the sandbox page scripts since I clear text, wait 250 ms and -then- async add/run your script.  Both clears are happening before both logs.

You can modify the last line in that script to read : 
```javascript
sbv.editorOutput.setValue('');
logObject(result);
inspectObject(result);
```

Then the log is normal and Object inspector shows array of 1 document.

Yes if you can reproduce in the sandbox or somehow else please report.

**Comment by Mojo90** [comment]
So I tried out with the normal loki.js and I found out that in the `Collection.prototype.update`-Function my $loki-ID (via `doc.$loki`) is the right one for the object. But this function: `var arr = this.get(doc.$loki, true)` returns null --> does not find the object with specified $loki id, but if I log the whole collection this id is definetely in the collection. Not sure how to deal with that!?

**Comment by obeliskos** [comment]
Ok I'd still like to trace into the get statement, but here's a few things you might check.  

- Inspect the value of collection.idIndex (I believe you call collections db) and make sure all the 'values' in that array are ordered lowest to highest.

- You might also make sure they are number and not a string... although loki ensures that the id you pass to get is number (integer), it does not ensure that $loki itself is number and since you are shallow cloning maybe there was a string $loki in object passed to replaceObjectWith.

If your data is not sensitive and you are running node/filesytem, maybe you could upload your db somewhere I can download and import into the sandbox.

**Comment by Mojo90** [comment]
- In the first time the collection.idIndex is correct if I load it clean. But when trying to update the first item of category ("releases") than this index gets corrupted and nothing works as normal for this category. not sure how and why the idIndex gets bad for this category. I am not doing anything in another way than for other categories and for them it works.

- I checked and it is always a number. You are right I am always try to complete clone the object with the new one. I searched for a method for this like "replaceObjectAtIndex:$loki With:newObject" but didn't find one. Now what I tried is it possible and good if I replace my for-loop with `n.$loki=old.$loki;db.update(n);` or is this not better?

Here you have a link to my fresh created database: https://www.dropbox.com/s/fsxqmk2p9jbyemd/lokiDB__hyphyDB?dl=0 It should not be corrupted and as said it works well for every collection except for "releases".

**Comment by obeliskos** [comment]
Usually if you were to inspect the collection data, you would find it is and should always be sorted by $loki and so the idIndex would also be sorted by $loki.   

Does the object you pass to replaceObjectWith have its own $loki property?  Is this an import from an existing / alternate loki database?  If so you might want your for-loop to not clone any properties named '$loki' or 'meta'.  Maybe try something like : 

```javascript
function replaceObjectWith(n, db){
    var old = db.findObject({
            id: n.id
    });
    if(old != null){
        for (var property in n) {
            if (n.hasOwnProperty(property) && old.hasOwnProperty(property) && property !== "$loki" && property !== 'meta') {
                old[property] = n[property];
            }
        }
        db.update(old);
    }
}
```

That should in theory keep your update function from updating the 'in-place' data[] references with $loki document properties that are out of order.

**Comment by Mojo90** [comment]
You are right there is a "meta" field in my old/new Object. But this field is not only for that one category where it does not work rather every collection/category has it (due to Wordpress REST-API there it returns always a meta field).
I updated the replace Function as you mentioned but it did not help, the error persists. And I also thought previously of that the $loki property gets overwritten somehow but this is also not the case. Thus I am really helpless whats goingon. And as already mentioned I tried a lot of thins but this error persists and I can not update my app like this because the releases-Collection will than be corrupted... The weirdest thing is that it is really the same code for every collection (I think I have 9) and only one collections have this error all other work as expected.

**Comment by obeliskos** [comment]
Yes its even more curious because I don't have a good repro case to help you out with.  I am left to conjecture upon conjecture.

Do you need the old $loki to match with replaced object $loki?  If not, and you are just looking up by 'id' I would suggest remove() of old and insert() of replacement if time is short and you need quick fix.

If you need $loki id's to be the same, it might be better solution to just set $loki and meta on 'new' object and pass that to update rather than graft all properties onto old object.

**Comment by Mojo90** [comment]
Sorry for the circumstances. I find loki is pretty cool and it is really very helpful and fast! But I don't know what to try out on top to get this working 🙈.

It is completely irrelevant what $loki id an object has. The only requirement is that I can replace one old object with a new one. Because if there is an update from Wordpress for that object I don't want to store it twice because than it will be shown twice to the user, thus I somehow net to delete/update the old one with the new one.

I already tried to find the Object by ID. Delete this with db.remove(object) and insert the new one with db.insert(object), but it results in the same error after a few updates.

Now what really drives me crazy as already mentioned my Object from Wordpress has a Meta field and I tried to set the meta field to "null", because not sure if that somehow disturbes the loki function and then add the first time to Database:
`var object = tempArray[i];
object.meta = null;
db.insert(object);`

But if I do that than there is the following error: `TypeError: Attempted to assign to readonly property. lokijs.min.js:4043 (add-Function)`. How could that be? This is a none-loki-object (it is a normal JSON-Object) but why is there a Loki Error‽

And what I also tried is to randomly update some Objects by id with this Code:
`function replaceObjectWith(old, n, db) {
		console.log(JSON.stringify(db.idIndex));
		n.$loki = old.$loki;
		n.meta = old.meta;
		db.update(n);
		console.log(JSON.stringify(db.idIndex));
}`
So as you can see I log the index before and after update and this is the (randomly) result:
<img width="966" alt="screen shot 2016-05-19 at 16 30 14" src="https://cloud.githubusercontent.com/assets/2122156/15397064/02ffac1c-1ddf-11e6-9995-7a053b7ab809.png">
And from the first update on the index is corrupted...

If you have a suggestion how to very easy store the objects, and possibility to replace the object with a new one or just update some properties of the object i would be very happy ;-)

**Comment by Mojo90** [comment]
So after long time of investigation I finally solved it 🙃🎉
The problem was that I show up the "Releases" in reversed order (I read out the Array from length to 0). I dont do this for the other categories. And this was the problem. Now I copy the data to read out with:
`var releasesArray = JSON.parse(JSON.stringify(dbReleases.data));` and it works like a charm.
Thanks @obeliskos  for your thoughts and help!!!

**Comment by obeliskos** [comment]
Sure... glad you got it figured out!
