### ISSUE TITLE
.update(obj) don't save new fields (as electron global object)

### ISSUE THREAD

**Issue by solisoft** [techfort/LokiJS#421]
Hi,

I'm working on a new project using lokijs
I have a little issue while updating : 

````
var a = mymodel.insert({ a: 1 });
a.b = 2;
a = mymodel.update(a);
console.log(a.b) // will return 2
````

If I reload my page, and do 
````
var a = mymodel.get(mylastID) // load previous inserted object
console.log(a.b) // will return undefined
````

It is possible to update a document with new keys ?

**Comment by techfort** [comment]
@solisoft are you calling `db.saveDatabase()` at any stage after the update call?

**Comment by solisoft** [comment]
no, should I?

**Comment by techfort** [comment]
yep that's the persistence mechanism. Otherwise your data will save only until the end of the session (in this case until you reload the page).

**Comment by solisoft** [comment]
I use electron ... so I guess that reloading page, don't reload database 
I save database on quit, though
I save DB periodically too (each 10s)

**Comment by techfort** [comment]
ok so what persistence adapter are you using?

**Comment by solisoft** [comment]
I save file on loki.json (on disk)

**Comment by techfort** [comment]
ok - naturally this should work just fine, so maybe share some of the code (e.g. the db instantiation)

**Comment by solisoft** [comment]
in electron
````
var db = new loki('loki.json', {autosave: true, autosaveInterval: 60000 })
global.models = {}
global.db.loadDatabase({}, function () {

  global.models["customers"]  = global.db.getCollection('customers')
  global.models["documents"]  = global.db.getCollection('documents')
  global.models["documents_details"]  = global.db.getCollection('documents_details')
  global.models["payments"]   = global.db.getCollection('payments')
  if(global.models["customers"] == null)  global.models["customers"] = global.db.addCollection('customers')
  if(global.models["documents"] == null)  global.models["documents"] = global.db.addCollection('documents')
  if(global.models["documents_details"] == null)  global.models["documents_details"] = global.db.addCollection('documents_details')
  if(global.models["payments"] == null)   global.models["payments"] = global.db.addCollection('payments')
});
````

from my webpage 
````
// document is created like that
var quote = models["documents"].insert({ type: 'q', num: moment().format('YYYYMM') + s.pad(nb, 5, "0") })
//... 
// then in my riotjs tag
var self = this;
this.data = models["documents"].get(opts.quote_id)
self.data.ht = self.ht
self.data.tva = self.ttc - self.ht
self.data.ttc = self.ttc
models["documents"].update(self.data)
````

ht, tva, ttc fields are not save

**Comment by solisoft** [comment]
Inserting, updating, removing documents works just fine ...
updating object with new fields (key=>value) fail

**Comment by techfort** [comment]
ok let me see if i can recreate the problem, it could take me a little while. Meantime could you add a listener to the error even on your collection to see if there is an error silently thrown.

**Comment by solisoft** [comment]
Here some logs : 
from
````
models["documents"].on("pre-update", function(e) {
  console.log("pre-update", e)
})
models["documents"].on("error", function(e) {
  console.log("error", e)
})
models["documents"].on("update", function(e) {
  console.log("update", e)
})
````
````
pre-update Object {ht: 200, tva: 40, ttc: 240, free_text: "adzd"}
templates/quotes.html.tag.js:18 update Object {ht: 200, tva: 40, ttc: 240, free_text: "adzd"}
````

none of these ht, tea, ttc, free_text are persisted...  no error thrown

**Comment by solisoft** [comment]
I confirm that lokiJS seems to works fine 
here a little script which behave correctly
````
var loki = require('lokijs')
var db = new loki('demo.json')

var mytable = db.getCollection('mytable')
if(mytable == null)  mytable = db.addCollection('mytable')

var data = mytable.insert({ a: 1 })

data.b = 2
mytable.update(data)

db.saveDatabase()
````

If I inspect my demo.json I can see my "b" field inside it !

**Comment by solisoft** [comment]
If I copy paste it in my electron console ... it fail ... argh ... not an easy one :/

**Comment by solisoft** [comment]
I just moved my database instantiation inside my index.html file (no more in my app.js / electron) seems to works fine now ... Maybe the global mechanism is the issue !?

**Comment by techfort** [comment]
maybe! unfortunately it seems to be electron specific because i had no luck reproducing. I will see if  i can get a dummy electron project up.

**Comment by obeliskos** [comment]
Might issue #400 help? :
