### ISSUE TITLE
LokiJS thinks it's running on Node.js when loaded with jspm/systemjs

### ISSUE THREAD

**Issue by sondreb** [techfort/LokiJS#423]
When referencing and loading LokiJS with jspm and SystemJS, it thinks it's running within Node.js. This require that we then manually specify the persistenceMethod: 'localStorage' for LokiJS to work properly and not throw error.

**Comment by techfort** [comment]
@sondreb I am not too familiar with jspm and systemjs but if they leverage node.js for any task (building etc.) then this may cause LokiJS to think it's runinng on node.js. Specifying the persistence method is the correct approach to avoid this kind of "misunderstanding".
