### ISSUE TITLE
QuotaExceededError: DOM Exception 22

### ISSUE THREAD

**Issue by nuruddinbadawi** [techfort/LokiJS#425]
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

what's the reason of this Error ?

**Comment by techfort** [comment]
localstorage has a maximum size (not sure what the size is, i think it's 5MB) and you are exceeding that. This is a feature of localstorage, not a bug of LokiJS. If you need to store large datasets either utilize indexeddb or - if possible - the file system.
