### ISSUE TITLE
Generate a new npm release from current branch

### ISSUE THREAD

**Issue by stefalda** [techfort/LokiJS#426]
Currently nativescript support has been added but it's available only by cloning the git repository:

`npm install --save git+https://git@github.com/techfort/LokiJS.git`

It would be easier to use if a new version is created on npm.

Thanks

Stefano

**Comment by techfort** [comment]
@stefalda i released a v1.3.17 yesterday, does that work for you?

**Comment by stefalda** [comment]
Ups, I made the test just before your released.
Now it's fixed.

Thank tou

Stefano
