### ISSUE TITLE
lokijs@1.3.18 Error: Cannot find module 'file-system'

### ISSUE THREAD

**Issue by roblav96** [techfort/LokiJS#427]
Just updated npm lokijs to 1.3.18 and I receive this error when trying to build my browserify bundle.

```
Error: Cannot find module 'file-system' from '/Volumes/OSX HD/Projects/my-app/src/node_modules/lokijs/src'
```

**Comment by techfort** [comment]
@roblav96 hey Rob is it possible you don't have the persistence adapter explicitly specified? i know there has been recent changes to the logic to work out the default adapter (it now includes nativescript) so more and more it would be recommended to explicitly set this to whatever adapter you intend to use

**Comment by roblav96** [comment]
I'm not using an adapter though :/

**Comment by roblav96** [comment]
This is literally the only time I even call 'Loki'
```javascript
this.$db.contacts = new Loki.Collection( 'contacts', {
	indices: this.$sql.map.contacts,
	unique: this.$sql.map.contacts[ 0 ]
} )
```

**Comment by techfort** [comment]
then that's weird as the file system module is only called when persistence is involved.. will investigate asap.

**Comment by roblav96** [comment]
No worries! Just thought I'd let you know. Thank you!!

**Comment by raphaguasta** [comment]
Same problem here! In my case, i'm specifying 'localStorage' in persistence method:

`new loki(name, {
      autosave: true,
      autosaveInterval: 5000,
      persistenceMethod: 'localStorage'
    })`

_Error: Module not found: Error: Cannot resolve module 'file-system' in /Users/raphael/Desktop/projetos/uolet/uolet-mobile-redux/node_modules/lokijs/src_

Any ideias?

**Version:** "lokijs": "^1.3.18"

**Comment by raphaguasta** [comment]
**UPDATE:** I updated the version of lokijs to 1.3.16, and it solved the error!

**Comment by roblav96** [comment]
Yes backtracking to 1.3.16 resolves the issue.

**Comment by obeliskos** [comment]
Can either of you try installing latest 1.3.18 and removing [these lines](https://github.com/techfort/LokiJS/blob/3c5dc157f4582891b86fcedbc50d3b873bb09bf2/src/lokijs.js#L635-L642) and seeing if your problem if that fixes the problem (I am unable to reproduce the error in node or web script include environs).

I believe that the 8571eb39950eb553de78c96e4ede631bb41f3d5d commit which @stefalda kindly provided probably should not attempt to 'autodetect' and require within the main source itself.  Nativescript users can easily instantiate the adapter external to loki and pass into constructor.

Let me know if that fixes, and we should probably remove that block anyways.

**Comment by stefalda** [comment]
Sorry If I've created any problem by adding nativescript autodetection...
I guess that we can remove those lines from the loki.js main file and instruct nativescript users  to explicitly use the adapter or if someone knows how to make browserify to ignore that require, that shouldn't be called unless the nativescript adapter is used...

**Comment by techfort** [comment]
@obeliskos @roblav96 @stefalda i had a real hunch the nativescript detection was the culprit but i really hoped it was not because it's a great feature. Going forward however i think it's a good idea to suggest to all LokiJS users to explicitly specify the adapter they are using to avoid problems.
BTW, yesterday the Product Marketing Manager for Nativescript (Dan Wilson) sent me a mail saying LokiJS is badass, so for as long as the docs and wiki are clear on how to use the adapter i'd say we're all happy :)

**Comment by techfort** [comment]
@stefalda @roblav96 @obeliskos i have released v1.3.19 which comments out the nativescript detection. Let me know if everything is gone back  to normal.

**Comment by stefalda** [comment]
@roblav96 I was wondering... have you got the 'fs' module in your browserify `ignore` list, because I don't understand why it doesn't complain about it, too.

Maybe that's because the `fs` require is conditionally required (under an if) in the main lokijs module, while the `file-system` require is directly required in another module (the adapter) that is conditionally required...

**Comment by obeliskos** [comment]
So I set up a repro case for this and even if I wrap that block of code in an 'if (false)' block the AST seems to want to include it, so this browserify AST is not as smart as I thought it was.  Perhaps browserify has been coded to deal with 'fs' module explicitly?

**Comment by roblav96** [comment]
@obeliskos I installed via my package.json

Updating to lokijs@1.3.19 has resolved the issue.

My apologies on the late response :X

**Comment by roblav96** [comment]
@stefalda This build is for a client Cordova hybrid app. I do not have the `fs` module anywhere. I'm also not using typescript if that helps.

Here's my package.json in case anyone was curious:
```
├── axios@0.11.1
├── babel-core@6.9.0
├── babel-plugin-lodash@3.1.4
├── babel-plugin-transform-async-to-module-method@6.8.0
├── babel-plugin-transform-runtime@6.9.0
├── babel-plugin-transform-strict-mode@6.8.0
├── babel-preset-es2015@6.9.0
├── babel-preset-stage-2@6.5.0
├── babel-runtime@6.9.0
├── babelify@7.3.0
├── browserify@12.0.2
├── browserify-hmr@0.3.1
├── chance@1.0.3
├── create-keyframe-animation@0.1.0
├── cross-env@1.0.7
├── dexie@1.3.6
├── events@1.1.0
├── exorcist@0.4.0
├── hammer-timejs@1.1.0
├── hammerjs@2.0.8
├── http-server@0.9.0
├── lockr@0.8.4
├── lodash@4.12.0
├── lokijs@1.3.19
├── moment@2.13.0
├── node-forge@0.6.39
├── npm-run-all@1.8.0
├── smartcrop@0.0.1
├── socketcluster-client@4.3.17
├── turf@3.0.5
├── uglify-js@2.6.2
├── url@0.11.0
├── vue@1.0.24
├── vue-async-data@1.0.2
├── vue-hot-reload-api@1.3.2
├── vue-router@0.7.13
├── vue-touch@1.1.0
├── vueify@8.4.1
├── vueify-insert-css@1.0.0
└── watchify@3.7.0
```

Let me know if you guys need anything else from me. I'd be more than happy to help! Thanks again for this amazing project :)

**Comment by stefalda** [comment]
I've made some tests myself with browserify and it seems that the 'fs' module is treated in a different way from the others modules...

this (wrong) code passes...

`         if (false){
              var LokiNativescriptAdapter = require('fs');
            }
`
this no...

`         if (false){
              var LokiNativescriptAdapter = require('file-system');
            }
`

I don't know if it's possible to fix this behaviour without adding complexity to the setup (like adding the module to the browserify ignore list), but I'm by no means a Browserify expert...

**Comment by roblav96** [comment]
You'd want to use something like System.loader() using https://github.com/whatwg/loader/
