### ISSUE TITLE
Data more than 5mb what happened ?

### ISSUE THREAD

**Issue by NuruddinBadawi** [techfort/LokiJS#428]
hello ... I have large text data  object size 5mb, but in iPhone not able to insert this object in the collection, and no log error, what should I do ? can anyone give me advise and thanks a lot.

**Comment by NikoRoberts** [comment]
is your persistence adaptor set to use LocalStorage? If so, then that would be the problem.
If you are inside a Cordova/Phonegap you can uitilise the file system using something like https://github.com/cosmith/loki-cordova-fs-adapter
