### ISSUE TITLE
Are LokiJS writes, updates atomic?

### ISSUE THREAD

**Issue by shakthimaan** [techfort/LokiJS#430]
I would like to know if the writes and updates to LokiJS are atomic?

**Comment by techfort** [comment]
all operations in LokiJS are atomic due to the single threaded nature of javascript, the only exception being the persistence to file as it involves I/O (but only in a node.js context).

**Comment by xeoshow** [comment]
Hello @techfort , 
Regarding the persistence to file, is it possible to integrate below node module to add the atomic write feature? 
https://github.com/npm/write-file-atomic

I met below issue which seems will crash my whole application:
https://github.com/techfort/LokiJS/issues/724

Any help is highly appreciated!

Best regards, Jason

**Comment by xeoshow** [comment]
And some more info found which might be useful:
https://github.com/typicode/steno
https://github.com/sindresorhus/write-json-file

**Comment by xeoshow** [comment]
Seems this one should be the best one for the partition adapter:
https://www.npmjs.com/package/fs-write-stream-atomic
