### ISSUE TITLE
Clone mode

### ISSUE THREAD

**Issue by esellier** [techfort/LokiJS#431]
It seems there is a bug in the _clone_ function ( if clone mode is true for a collection and parse-stringify is the method used for cloning (BTW, documentation does not present other methods).
When you search for an not existing object for the key (collection.by method), the clone method is called with undefined... JSON.parse will not be able to parse and throw an exception.

I would suggest the following code :
cloned = !data ? undefined : JSON.parse(JSON.stringify(data));

**Comment by techfort** [comment]
thanks @esellier i will add this as soon as possible.

**Comment by esellier** [comment]
Thanks,
BTW, would you be interested in a NodeJS dbStorage module using lokijs as storage adapter?
It's not an exact polymorphic implementation... but that makes the game.

**Comment by techfort** [comment]
Very much so!

**Comment by lutsykigor** [comment]
Any updates on this? Strangling from this issue and need to use try/catch

**Comment by obeliskos** [comment]
Since that could be affected by multiple code paths, I made a fix within our clone helper method.  Seems to work with by() example, let me know if you have any issues.

**Comment by lutsykigor** [comment]
Yes, I can confirm that it works.
Can you put that fix to next version 1.4.3 I beleive?
Thanks
