### ISSUE TITLE
Category/Subcategory, hierarchical, normalized database, many-to-many, many-to-one, one-to-many, etc.

### ISSUE THREAD

**Issue by deenfoxx** [techfort/LokiJS#432]
This is not an issue. I just wanted to say thank you for providing such an awesome tool. I'm just now starting to use LokiJS and quickly learning its features. For example, I had no clue how to get data across multiple results. After fiddling with eqJoin for awhile, which didn't work for multiple, I gave up and wrote this...

```
var cat = data.c.chain().find({ p: undefined }).simplesort('n').data();
var cat_array = [];
for (var cat_index in cat) {

    var sub = data.c.chain().find({ p: cat[cat_index].i }).simplesort('n').data();
    var sub_array = [];

    for (var sub_index in sub) {
        sub_array.push({
            'id': sub[sub_index].i,
            'name': sub[sub_index].n
        });
    }

    cat_array.push({
        id: cat[cat_index].i,
        name: cat[cat_index].n,
        children: sub_array
    });
}
```
[data.c is my LokiJS "categories" collection, 'p' is "parent id" (if it exists, it is a child of a root category), 'n' is "category name", and 'i' is "category id". Sorry for the short naming conventions; since I'm storing in user's LocalStorage, I wanted to use as little space as possible.]

But, then, after getting it to work I realized LokiJS had a mapReduce functionality and I was going to just ignore the reduce part. Then, I tried map() and, low-and-behold, Javascript's Array.prototype.map() already works without the reduce. I assume because LokiJS Collections are Array-Like Objects? So, the above code reduced down to just...

```
var cat_array = data.c.chain().find({ p: undefined }).simplesort('n').data().map(function(root_obj) {
    return {
        id: root_obj.i,
        name: root_obj.n,
        children: data.c.chain().find({ p: root_obj.i }).simplesort('n').data().map(function(sub_obj) {
            return {
                id: sub_obj.i,
                name: sub_obj.n
            };
        })
    };
});
```

I realize this example is not multiple collections, but the concept can easily be extended across multiple collections. If it can be simplified further, let me know. I'm excited about all the possibilities LokiJS has to offer.

Go ahead and close this, but now it is there in case anyone else searches the issues for database normalization issues.

**Comment by techfort** [comment]
@deenfoxx thanks a lot about this contribution. I'll close the issue but i will review the above more in detail because there is definite food for thought!

**Comment by deenfoxx** [comment]
Heh... I just found that you DO include .map() in the resultset chaining (from https://github.com/techfort/LokiJS/wiki/Query-Examples#resultset-chaining). So, to be "proper", I switched the .map() before the ".simplesort('n').data()". So, this works, also, but leaves in the "$loki" and "meta" fields within the final results, which I also figured out were an Array of Objects, which is why the Javascript .map worked on them.

```
var cat_array = data.c.chain().find({ p: undefined }).map(function(root_obj) {
    return {
        id: root_obj.i,
        name: root_obj.n,
        children: data.c.chain().find({ p: root_obj.i }).map(function(sub_obj) {
            return {
                id: sub_obj.i
                name: sub_obj.n
            };
        }).simplesort('n').data()
    };
}).simplesort('n').data();
```

No response necessary. Just wanted to document my find for future patrons. So many possibilities.
