### ISSUE TITLE
Does $ne works ?

### ISSUE THREAD

**Issue by bdedardel** [techfort/LokiJS#437]
Hi,

I'm surprised of having some problems with some basic queries.
May I don't understand something or is there a problem with $ne ?

### query to get french words

```
var col = myDb.getCollection('mytable');
var query = { 'lang': { '$eq': 'fr' } }; 
var res = col.find(query);
console.log('res ' + res.length); => 2 items
```
### query to get english words

```
var col = myDb.getCollection('mytable');
var query = { 'lang': { '$eq': 'en' } }; 
var res = col.find(query);
console.log('res ' + res.length); => 3 items
```

### what's wrong with $ne

Indeed, I don't have any items !

```
var col = myDb.getCollection('mytable');
var query = { 'lang': { '$ne': 'en' } }; 
var res = col.find(query);
console.log('res ' + res.length); => 0 items
```

Regards,
Benjamin

**Comment by obeliskos** [comment]
Seems at some point we added tests for NaN which to $ne op that yielded false positives.  I believe I have fixed this and added unit tests to verify this over future changes.

**Comment by bdedardel** [comment]
It works fine with the last github version. Thanks.

**Comment by techfort** [comment]
@bdedardel closing this, will release a new version soon.
