### ISSUE TITLE
Bug in DynamicView...

### ISSUE THREAD

**Issue by deenfoxx** [techfort/LokiJS#439]
I found a bug (or misunderstanding) in DynamicView which I was easily able to duplicate on the Loki Sandbox using most of the demo code...

In a nutshell... If a DynamicView does NOT have a filter, it appears to force one into existence as soon as an item is updated. Try copy-pasting into https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm

If I am just misunderstanding, perhaps you can clarify, because I thought I would be able to removeFilters() and be able to access the entire database as if I were accessing it directly. However, if I modify a single document through the primary db, suddenly I no longer can view anything except what was just updated.

```
var db = new loki('sandbox.db');

// Add a collection to the database
var items = db.addCollection('items');

// Add some documents to the collection
items.insert({ name : 'mjolnir', owner: 'thor', maker: 'dwarves' });
items.insert({ name : 'gungnir', owner: 'odin', maker: 'elves' });
items.insert({ name : 'tyrfing', owner: 'Svafrlami', maker: 'dwarves' });
items.insert({ name : 'draupnir', owner: 'odin', maker: 'elves' });

// Create a DynamicView with NO filter.
var dv = items.addDynamicView('query');
logText('GOOD... Shows everything, as expected with no filter.');
logObject(dv.data());

// Find and update an existing document
var tyrfing = items.findOne({'name': 'tyrfing'});
tyrfing.owner = 'arngrim';
items.update(tyrfing);

// Try and get Dynamic View again... Whoops?!
logText('BAD... No Filter applied, but only shows updated item. Lost all the others items.');
logObject(dv.data());

// Try to do the applyFind a little late?
dv.applyFind({ 'owner': 'odin' });
logText('This SHOULD be able to find odin items... nope...');
logObject(dv.data());

// This statement sends to Inspector
inspectObject(db);
```

**Comment by deenfoxx** [comment]
Unrelated... but wanted to show off... Your LokiJS is working awesomely! Fast as hell even with some bad programming choices because I was rushing things yet still wanted it feature-rich. haha...

https://bestticketprinting.com/search-test/bachelor-party

Play with the search keywords, categories and filters... Uses AJAX to pull in search results live as you change keywords/categories/filters... FUN!

It uses LokiJS in conjunction with pure.js (https://beebole.com/pure/) for really simple and quick template rendering. Also uses JQuery Multiselect (http://loudev.com/) for the filters (select multiple with Shift/Option/Alt/Command key) and JQuery Bonsai (http://simonwade.me/jquery-bonsai) for the category treeview (also supports multiple select with modifier keys).

**Comment by techfort** [comment]
@deenfoxx awesome stuff! that is really impressive, really glad to see you got the benefit of loki's speed and that loki delivered as promised. Will review the bug on dynamic views too later!

**Comment by obeliskos** [comment]
Nice... if dataset is small enough maybe even pull all data on page load and just async pull images?  Either way that site is pretty instant for loading.

Thanks for providing an easy way to replicate this error, I will look into it over the next day or so and get back to you.

**Comment by obeliskos** [comment]
Thanks @deenfoxx, I believe I have found the bug causing this.  When you update a collection document and that collection has dynamic views applied to it, each of the dynamic views are notified to 're-evaluate' whether the document should be in the view.  That re-evaluation on an empty internal resultset was causing it to lose its 'uninitialized (give me everything)' status by incorrectly and partially adding the object to the view's inner resultset results.  Since there is no need to re-evaluate a 'give me everything' (this should just be collection.data[]), I just bypass evaluation and leave internal resultset state as is (filter not initialized).

Added a unit test based on your example as well.  If you find anything else, we can easily expand test cases in that.

**Comment by hongxiangrong** [comment]
Firstly, great job on the excellent blazing speed of this library!
I have the same issue here. Even though I have a DynamicView set with .applyFind() or .applyWhere(), when i update the main collection with a value that will be filtered out in DynamicView, the count() still shows the same, indicating that the DynamicView did not get updated.

**Comment by obeliskos** [comment]
I believe this issue was resolved... 
hongxiangrong : autoupdate depends on object.observe being supported by your environment.  Since object.observe has been deprecated I would not depend on it and make sure you do collection.update()
