### ISSUE TITLE
Upload json files

### ISSUE THREAD

**Issue by Mowso** [techfort/LokiJS#445]
Hi, 

I'm currently using LokiJs and the loki-indexed-adapter and I would like to know if it was possible to uplooad database from existing json files without installing a new adaptater. I did not find any means to do that.

Thank you in advance for your reply.

**Comment by ashstr** [comment]
actually, I did something before like this  I don't know if it can help u.
check that... 
`

       module.exports = function() {
	  var loki = require('lokijs');
	  var videoDevData = require(__dirname + '/videosDEV.json');
	  var db = new loki(__dirname + '/../db.json');
	  var videoCollection = db.addCollection('video');
	  for (var i = 0; i < videoDevData.length; i++) {
		videoCollection.insert(videoDevData[i]);
	  }
	  db.saveDatabase();
        }







`
