### ISSUE TITLE
Queries only working on db.getCollection()

### ISSUE THREAD

**Issue by Emilios1995** [techfort/LokiJS#446]
**The problem: The queries are not running correctly when I apply them directly to the collection object.**
This is my code: 
```
var db = new loki('users.json'),
    users = db.addCollection('users')

 const load = () => new Promise((res, rej) => {
  db.loadDatabase({}, () => {
    console.log(db.getCollection('users').data);
    res()
  });
})

const findEmilio = () => {
  var result = users.where(function(obj) {
      return obj.email === 'emilios1995@gmail.com' && obj.password === 'emilio'
  });
  return result
}
```
Then I run: 
```
load()
.then(_ => console.log(findEmilio()))
```
But I only get an empty array. `[]`, which is incorrect. Because from the `console.log(db.getCollection('users').data)` call on `load()`, I get this: 
```
[ { email: 'emilios1995@gmail.com',
    password: 'emilio',
    meta: { revision: 0, created: 1467742649842, version: 0 },
    '$loki': 1 } ]
```
However, if I replace `users.where` with `db.getCollection('users').where` it works as expected

Why is that?

**Comment by Emilios1995** [comment]
It might be worth noting that `insert` does work directly in `users`

**Comment by VladimirTechMan** [comment]
@Emilios1995, please, note that you are trying to get the object for the "users" collection before you have actually loaded a database from file and had a callback on the load completion, inside your `load` function above.

What happens here is, that you created a new Loki DB, then added a new collection with name "users" to it. Then you "saved" a reference to that new empty collection object in the `users` variable. Then you loaded the contents of the database from a file, which actually re-creates all the underlying objects and structures in the database representation (including the "users" collection in your case). When you call `db.getCollection('users')`, you get access to your newly loaded collection with name "users". But if you access variable `users`, you simply deal with an empty collection that you added right after creating the database object, and that was later replaced with a new collection object, when loading the DB contents from the file.

**Comment by Emilios1995** [comment]
Of course, that makes sense.
Thanks!
