### ISSUE TITLE
Cannot resolve module 'fs'

### ISSUE THREAD

**Issue by najamkhn** [techfort/LokiJS#449]
I'm not sure why but I've been getting it everytime when I install loki from npm install and initialise it with the following lines:
```
import Loki from 'lokijs'
const ldb = new Loki('example.db')
```

**Comment by VladimirTechMan** [comment]
@najamkhn, just in case, are you trying to build a web-client app (= to be running in the browser) using LokiJS with the webpack / babel toolchain (or alike)?

**Comment by najamkhn** [comment]
Yes using it with webpack and building web app.

**Comment by VladimirTechMan** [comment]
Okay, that's what I suspected based on the specific issue that you reported. But I needed to double-check my guess with you first. What you need to do is, to add the following configuration section and parameters into your webpack.config.js file:
```javascript
node: { fs: 'empty' }
```

**Comment by VladimirTechMan** [comment]
@najamkhn Also, depending on your specific configuration and other modules that you use in your web app, you may need to extend that section above to something like:
```javascript
node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      'crypto': 'empty'
},
```

**Comment by VladimirTechMan** [comment]
@najamkhn Finally, in the case if you need a piece of Webpack's official documentation on that part, you can refer to: https://webpack.github.io/docs/configuration.html#node

**Comment by jetiny** [comment]
will you extract it outside ?

**Comment by VladimirTechMan** [comment]
@jetiny, extract what? I am not sure if I understand your question. Please, elaborate.

**Comment by obeliskos** [comment]
Thanks to all who answered, I believe this is resolved.  In future releases we may extract the (node) filesystem adapter out into its own module.

**Comment by jamesmikesell** [comment]
For what it's worth, I was having this problem with Angular 5 and Angular CLI 1.5.0 when running unit tests, but not when doing a regular build / serve.  

While the webpack.config that angular cli was using already had  `fs: 'empty'` set, the problem was that karma was using different settings for webpack.  I fixed this issue by putting the following in my `karma.config.js`

```javascript
    webpack: {
      node: {
        fs: 'empty'
      }
    }
```

**Comment by davidsavoie1** [comment]
Would someone give me some guidance as to how to fix the configuration in Rollup instead of Webpack? I also get the `fs is not defined` error. I tried adding 
```
node: {
  fs: "empty",
  net: "empty",
  tls: "empty",
  crypto: "empty",
}
```
at the root of the default exported object of the `rollup.config.js` file with no success...

**Comment by jeremychone** [comment]
Thanks @davidsavoie1 Big time-saver, I was going to give up. 

I wished LokiJs would be more browser-friendly out of the box, or have a lokijs-browser. Anyway, the functionalities look to be what I am looking for.
