### ISSUE TITLE
insertOne could use a second clone command

### ISSUE THREAD

**Issue by TheMadBug** [techfort/LokiJS#454]
(This is a minor case with an easy work around, but it did trip me up)

var collection = db.addCollection('foo', {clone:true});

val oldObject = {val:3};
var insertedObj = collection.insert(oldObject);

// this line doesn't do anything, which is good
oldValue.val = 4;

// the below line updates the in database reference of the object
insertedObj.val = 4;

It is useful to deal with the returned value from insert so you can look at timestamps or loki id if need be. However, my understanding of clone:true is that you should never get a reference to an instance of the object that's considered to be inside the lokijs's db.

A fix would just be a second call to clone just before returning a value from insertOne.

**Comment by obeliskos** [comment]
Sorry for the delay, your description sounds right so I updated to do double cloning.

If we need to optimize insert speeds in cloning scenarios, we could potentially do internal (first) clone after grafting $loki and meta properties onto -original- object and just return original object.

Also could disable return values (2nd cloning) when inserting arrays of objects for faster 'batch' inserts.

**Comment by TheMadBug** [comment]
No problem about the delay.

I like the idea of mutating the passed in object so that only a single clone is needed and people can still get the ids and metadata, but I do worry about existing code bases and people who try to make things as functional as possible.

You could potentially add a second parameter boolean to insert() which would determine if it returns anything (regardless of if it's a clone collection or not just to keep things consistent).

Regardless both your proposals work for my use case so it's just the fun decision of subtly modifying backwards compatibility or increased memory/CPU usage.
