### ISSUE TITLE
feedback (db depth option for saving flexiblity)

### ISSUE THREAD

**Issue by benzmuircroft** [techfort/LokiJS#457]
This is really hard to explain!

I like this project but i feel like - because a db can hold so much (collections > objects) It is intended to be flexible but on _another level_ the 'can hold' part makes it inflexible... **like a big guy who can lift anything but can't fit through tiny doors** If that make sense

I'm finding that because of the saving method of (only) an entire db at once _(**This is though a good thing** - it's good because one db/one file/one save)_ ... but, for some of my dbs (ones that get accessed often by different individuals) I'm creating duel (helper db) structures like so:
- db called user_ids (only has an `_id` field so I can find users without knowing what their db file is named)
- individual dbs named after each `users _id` (has complete user objects linked by `_id` fields)

So an actual user account would sit in a file named with their `_id` **_xxxx[user_id]xxxx.db_**

the reason for this is because they get updated often (I wan't to instantly save as little as possible when something changes rather than save all users at once because of one users change)

I know there is the option to autosave at intervals but, just for example of what I am doing I am going to iterate over users in `user_ids` **with bad sudo code** and do something with each users db file ...

```
var user_ids=new loki(__dirname+'/user_ids.db',{env:'NODEJS',autoload:true,autoloadCallback:function(){
    var uids=user_ids.getCollection('user_ids').find({});
    var i=-1,
        uid;
    function loop(){
        uid=uids[i]._id;
        var user_db=new loki(__dirname+'/users/'+uid+'.db',{env:'NODEJS',autoload:true,autoloadCallback:function(){
            var user=user_db.find({})[0];
            //do something with the user
            user.saveDatabase();
            each();
            }});}
    function each(){
        i+=1;
        if(i<uids.length){
            loop();
            }
        else{/*end();*/}
        }
    each();
    }});
```

Though iteration would not always be the case in my code (I may never do this), the example saves less of a sizable JSON file each time (without timers) as not all users may even be active on the site at once, but It looks like _funky-madness_ because I have a database named `user_ids` with only one collection inside also called user_ids while also I have only one object in the collection with the `_id` of both the collection name and the db file name! 

> imho with all users in one db.collection it feels like the collections are stuck together in an 'egg and spoon race' (or tied together) when saving.
## Suggestion (db depth option)

Can You implement  3 options on the level of depth we can define on a db?
- full db (**how it is now** with collections that can support many objects stored in each) **default**
- db that is just one collection `(no db.getCollection just db.find({x:y}), db.update({x:y}))`
- db that is just one object `(just db.x, db.x=y)`

**Sounds retarded** but, It would (not only make some code less convoluted but also) make saving data - flexable / less timer based in some cases (a lot of the time a timer will be mindlessly spending server resources writing the same thing over and over with no change in data)... it would be good to use a timer on big dbs but on smaller dbs; it would be good to just `db.saveDatabase()` but on a much simpler JSON object!

> Please Note: This proposal attempts to highlight that saving an entire db is always a good thing but, the depth of what you are compelled to save could be flexible

Sorry if I have offended anyone - LokiJs is really awesome btw!! I'm moving from mongodb to use this instead because it's just npm install and I can see the dbs more hands on with pure javascript!

**Comment by techfort** [comment]
hey @benzmuircroft - thanks for the feedback. I have begun work on an "incremental" adaper, which saves documents in separate files, collections are saved in separate folders.
I only got as far as saving documents for now, which is the easy part. Next up is loading, including loading collections options and stuff like dynamic views, that's going to be a lot more tricky. When this is done I'm going to do journaling, basically storing the history of each document for offline or out-of-memory use. I don't know how soon I will have this done though as I am quite busy. The adapter is in the latest source tree [here](https://github.com/techfort/LokiJS/blob/master/src/loki-incremental-adapter.js)

**Comment by benzmuircroft** [comment]
Ok sounds like the best course, In the mean time I'm going to do the best I can to wrap loki in something that pretends to do what I want lol and makes the crazy madness I'm doing simple to code/read.

Thanks @techfort
