### ISSUE TITLE
search in nested objects

### ISSUE THREAD

**Issue by NuruddinBadawi** [techfort/LokiJS#458]
I'm trying to search inside nested object but it didn't work.

The objects look like the following:
`
{
  "relations": {
    "ids": [379]
  }
}
`

I use this query to search:
`
collection.find({
  "relations.ids" : { $contains: 379 }
});
`

But it is not working :( 

Any way to solve it?
Lokijs version : 1.4.1

**Comment by obeliskos** [comment]
Thanks for pointing this out, there are many edge cases with dot notation involving arrays and this (primary) use case fell through.  I believe I have fixed and added unit tests.

@VladimirTechMan can verify if this affects any logic he may have introduced... if it does he should probably add unit tests to cover other edge cases.

Fix is checked into repo, if you are able to test that version feel free to let me know your results.

**Comment by VladimirTechMan** [comment]
That looks good to me – makes perfect sense. Thanks for the quick fix, @obeliskos – and thanks, @nuruddinbadawi, for reporting that to us.

P.S. @techfort, you may want to consider releasing an update to the public version of Loki with this one in, in some near term (if and when you have time for that – and if no other reasons to delay such an update).

**Comment by obeliskos** [comment]
Thanks!  Maybe we can add some test cases for those edge cases to avoid breaking them in the future.
