### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by archasek** [techfort/LokiJS#461]
Hi. 
I couldn't just find it in the readme...
How does the LokiJS work? Does it use localstorage, indexeddb, websql, web workers? When? How? 
What about IE, Edge, Safari?
Thanks :)

**Comment by techfort** [comment]
ALL OF THEM :)
Jokes aside, you can use whatever persistence adapters are available. In a web browser localStorage, indexeddb, localForage are available. LokiJS has vast browser compatibility so I believe we're ok for IE 9+ (maybe even 8, can't remember). Edge and Safari are also ok. Naturally Chrome and Firefox are.
On nodejs you can persist to the file system.

Persistence is described in detail [here](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters)
