### ISSUE TITLE
Duplicate key error when inserting new record after coll.clear()

### ISSUE THREAD

**Issue by dbubs** [techfort/LokiJS#462]
Actually, I'm pretty sure I'm missing something here, but I'm getting some strange results. Hoping someone could shine some light on this situation. 

In the attached test case, I am simply creating a new loki collection (or loading from disk), clearing the collection (to start with zero records each time), inserting, then updating a record.

When I run it the first time, it works perfectly. The second time it complains that there is a "Duplicate key" - even though, I'm clearing the collection before doing the insert. Before I do the insert I have a log statement that shows the collection count is `0`.

Attached is a simple nodejs test case that shows the issue. Run `npm install` then `npm test` and you'll see the test pass successfully. Then run `npm test` again to see it fail.

Or you can run it from my [runnable snippet](http://code.runnable.com/V7h0iQC9GZZrBdfM/lokijs-test-for-node-js)

[loki_test.zip](https://github.com/techfort/LokiJS/files/428365/loki_test.zip)

**Comment by dbubs** [comment]
I figured out what the problem is. I am setting the `unique` option on the collection and when I load the json file, then `clear()` the collection, it does not clear the `UniqueIndex`.

I have to run `coll.constraints.unique.id.clear();`

Am I wrong in thinking that `coll.clear()` should also clear the indexes?

**Comment by obeliskos** [comment]
Good catch... we are a little inconsistent with this.  Collection.clear() method also completely removes our binary indices, requiring user to reapply them.

So @dbubs, @VladimirTechMan, @Techfort (or anyone else who has thoughts on this) : do any of you have opinions as to whether Collection.clear() should : 
- clear indices with their definitions (require user to call ensureIndex and ensureUniqueIndex)
- clear indices while leaving definitions in place or 
- add options object to clear to allow picking between the two

I'm trending toward the options object but not sure which would be default.  Either way feel free to sound off.

**Comment by dbubs** [comment]
I don't think it should clear the index definitions. In the case of `autoload: true` then we should assume the `index` value already exists for the collection. If you go with passing an options object, then I think that should be the default.

**Comment by philipgiuliani** [comment]
I just ran into the same issue. I called
```
collection.clear();
collection.insert(data);
```

and it crashed because of the unique index constraint.

**Comment by obeliskos** [comment]
think this was fixed with referenced commit
