### ISSUE TITLE
Documenting performance characteristics of unique / exact / indices

### ISSUE THREAD

**Issue by bottleofwater** [techfort/LokiJS#464]
I may have missed the relevant page in the documentation, but I haven't been able to find detailed descriptions of the "unique", "exact", and "indices" properties, and how they differ from one another.

Some particular questions that I think could use some help:

- If multiple properties are listed in the "unique" array, does it means "unique combination of A and B", or "A is unique and B is unique, but the combination of A and B might not be unique"?

- Same question about "indices"

- How does "unique" differ from "indices"? Is it because multiple records can have the same indexed value, but only a single record can have a same unique value?

- What happens if a bug arise in my application, and multiple records have the same unique values? I know it's probably a bit of an unspecified behaviour, but as far as the implementation goes, what happens? Will some records be dropped?

- How does "indices" fares compared to "unique", performance-wise? I would assume unique properties to be more efficient than indexes, but is it really the case?

- What is "exact"? For a quick glance at the source code, it doesn't seem to be implemented but still appears in the documentation.

Thanks for your time!

**Comment by obeliskos** [comment]
Well 'indices' are binary indices which support range operations other than $eq... so if you want optimized $lt, $lte, $gt, $gte ops along with $eq, $aeq, and $dteq equality ops then you may want to you these binary 'indices'.  Multiple binary indices on a single collection are all treated independently.

If all you need are id equality lookups, then 'exact' lets you implement a hashobject index.  I would imagine (at least at the current moment) that multiple exact indices within a single collection would be handled separately and not as a compound key of sorts.  

I also am unsure about the 'exact' indices, maybe @techfort could provide some insight about that.

Unique is faster, especially from 'index rebuild' performance... we have room to optimize this rebuild cost in our binary indices in the future, but depending on use case they can be expensive for now.

**Comment by bottleofwater** [comment]
I see, thanks :)
