### ISSUE TITLE
How to observe changes by query?

### ISSUE THREAD

**Issue by iovglaz** [techfort/LokiJS#465]
In Meteor minimongo, we can do something like:

``` js
var cursor = collection.find({ $gt: { abc: 120 } });
cursor.observe({ updated: function(oldDoc, newDoc) {});
cursor.insert({ abc: 123 });
```

In LokiJS i see `collection.on`, but how can we keep track of such an event for a particular data?

Or how do something like this?:

``` js
var doc = collection.insert({ abc: 123 });
collection.on('remove', function(data) {
  if (collection.match({ $gt: { abc: 120 } }, data)) {
    console.log(true);
  }
});
collection.remove(doc);
```

**Comment by obeliskos** [comment]
It would seem [here](https://github.com/techfort/LokiJS/blob/e9a2e51d104a0c2a420e42182d82b5ea55d17a39/src/lokijs.js#L4151) that our emitted event is called 'delete'... maybe in future we can rename this event to remove.

Since it looks like you are not attempting to affect outcome of remove, just monitor it... your logic looks good.   We don't have a collection.match method but if i understand logic correctly, you don't need it?  Maybe something like : 

```javascript
var doc = collection.insert({ abc: 123 });
collection.on('delete', function(data) {
  // in case your doc is missing property, don't throw js error
  if (data.hasOwnProperty('abc') && data.abc > 120) {
    console.log(true);
  }
});
collection.remove(doc);
```

**Comment by iovglaz** [comment]
I think this is a joke... You are offer to write an universal interpreter of any queries?

In lokijs I not found two things for the work triggers.

##### Old state of the document on `update` event.
I do not know how to solve it ...

##### Checks the document for compliance with the request manually.
Of course we can write a crutch.
Create a temporary collection with out data and then make a find query for them.
But... It awful.

-----

There's something that could be done almost without any loss of performance.

We can assign for all operations of a numeric value by the counter. This may be optional feature. If this number is transmitted to the event, we can be accurately associate the request with the event on it. We do not have to check the document for compliance with the request, and so on.

**Comment by obeliskos** [comment]
I'm not sure I understand what your asking or what your points are...   Perhaps you can rephrase the important points.

Regarding 'old state of document on update event' : while our current implementation only passes a single document, this could be modified to pass original as well as new document as long as you have the collection 'clone' option passed as true in [constructor](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html#addCollection).

We are open to suggestions or pull requests but we probably would need to clarify and break this down into clearly defined and testable features which do not break backwards compatibility.  If it involves a breaking change we can use the v2.0.0 branch.
