### ISSUE TITLE
Typescript definitions are outdated

### ISSUE THREAD

**Issue by mnasyrov** [techfort/LokiJS#467]
For example, now `Collection.prototype.find(query)` returns an array while it is defined as `LokiCollection.find(query: LokiQuery): LokiResultset<E>` in the typescript definitions.

**Comment by obeliskos** [comment]
Your right, collection find should return object[] or null.  It should be just collection.chain() that returns a (Loki) 'Resultset'.

@TeamworkGuy2 kindly [provided those definitions](https://github.com/techfort/LokiJS/issues/167).  I've  not yet had time to research this enough to be familiar with the syntax to fix any issues with them.   

If you are able to, it would be nice if you could help update those as our v1.4.x (main) branch is stable (maybe a few non-breaking extra constructor options we may want to add).   Otherwise I will add this to my todo list for when I (or anyone interested in updating these) can get around it.

**Comment by TeamworkGuy2** [comment]
If I ever have spare time I'll update it.  But it's a 6+ hour process for me to extract accurate definitions from a library of loki.js' size and it's a very boring task :)

**Comment by obeliskos** [comment]
Great... while my request was meant for @mnasyrov, if you ever get some time, it would be appreciated :) 

Would be nice if there was a way to leverage jsdoc/closure annotations to scaffold some definitions.

**Comment by mnasyrov** [comment]
Sorry guys, have no time right now.

**Comment by mnasyrov** [comment]
There are definition file generators from js like [dtsmake](https://github.com/ConquestArrow/dtsmake), but they also require manual work to define type structures.

**Comment by RobertoMalatesta** [comment]
Moving the whole of the project to TypeScript could be an option, since that could favor reading the code and submitting patches/issues/contributions.

--R

**Comment by foxel** [comment]
Any update on this?

**Comment by thasmo** [comment]
This project look pretty awesome, too bad there are no up-to-date TypeScript typings available. Just wanted to add my +1 for conversion to TypeScript or maintaining official typings.

**Comment by TeamworkGuy2** [comment]
I found some time to update the definition; I'll hopefully be finished by the end of the weekend.

**Comment by Viatorus** [comment]
@thasmo

Have a look at https://github.com/LokiJS-Forge/LokiJS2 - a official successor, converted to Typescript (but still beta).

**Comment by thasmo** [comment]
@Viatorus Thanks! Tried it but it seems the npm package doesn't include typing or do I miss something?

**Comment by Viatorus** [comment]
Next update should have them - probably tomorrow.

**Comment by TeamworkGuy2** [comment]
Latest lokijs 1.5.1 definition just got merged to definitely typed (pull: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21747, commit: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/766089f4e8107fd0fba147ed4543ae4b3cb0b3b8).
Should auto update to npm in a day or two.

**Comment by foxel** [comment]
I can't get how do I use LokiIndexedAdapter with typings now. :(

**Comment by TeamworkGuy2** [comment]
@foxel I'm not sure how LokiIndexedAdapter works, I've never used it.  I probably won't have time to analyze the code and write a definition in the near future. :/ 
If you're familiar with LokiIndexedAdapter, please help write one up and send a pull request to DefinitelyTyped!
Also take a look at these definitions inside lokijs, maybe they're related to what you're looking for:
* [LokiPersistenceAdapter](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lokijs/index.d.ts#L564)
* [LokiMemoryAdapter](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lokijs/index.d.ts#L582)
* [LokiPartitioningAdapter](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lokijs/index.d.ts#L641)
* [LokiFsAdapter](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lokijs/index.d.ts#L707)
* [LokiLocalStorageAdapter](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lokijs/index.d.ts#L741)

**Comment by ShiroiKuma** [comment]
@TeamworkGuy2 Will the typescript definitions for 1.5.2 work for loki 1.5.5 or are their too many changes?

**Comment by TeamworkGuy2** [comment]
@ShiroiKuma A quick diff of the src/lokijs.js files from [releases](https://github.com/techfort/LokiJS/releases) version [1.5.2 zip](https://github.com/techfort/LokiJS/archive/v1.5.2.zip) to [1.5.5 zip](https://github.com/techfort/LokiJS/archive/v1.5.5.zip) shows there's several changes to method signatures and enumerations, for example `LokiOps` has some new values and `Resultset.prototype.simplesort` 2nd parameter changed from a boolean to an options object (although it looks like you can still pass a boolean for backward compatibility).
Answer: I'm not sure, I don't work on LokiJS, I just wrote a one time definition for it which I updated once or twice.

**Comment by obeliskos** [comment]
I did update our typescript definitions but apparently i missed a versioning number somewhere because when i run : 
```
npm i @types/lokijs
```
it will report version 1.5.2, however the definitions are actually 1.5.3 which are latest.

@TeamworkGuy2 : any idea why that might be?

**Comment by TeamworkGuy2** [comment]
@obeliskos I'm not sure why it's wrong, version numbers of npm @types packages are controlled by the version string in the definitely typed definition file (for lokijs see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lokijs/index.d.ts)
You're right though, NPM https://www.npmjs.com/package/@types/lokijs lists the version as 1.5.2.
I'd report it as an issue to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository, although that repository has over 2000 open issues and the Microsoft team doesn't curate it much.
You could look at the types-publisher tool the definitely typed team use for publishing the packages: https://github.com/Microsoft/types-publisher
looks like you changed
