### ISSUE TITLE
No insert event when loading a database

### ISSUE THREAD

**Issue by arcanis** [techfort/LokiJS#468]
Maybe insert isn't the right name (maybe something like `hydrate` would be better), but could it be possible to emit some kind of event when a record has been loaded into a database?

In my use case, I have a custom index (that is used to power my autocorrect suggestions) that listen for `insert` events in order to to add the specified record into its tree. However, it doesn't work with data loaded from a database, because it has no event to listen.

There's already `autoloadCallback`, but it only works for autoload.

**Comment by arcanis** [comment]
On a similar note, the `loaded` event name is incoherent with other event names (which are all verbs, such as `insert`, `rebuild`, and `update`), and isn't emitter when a database is loaded through any other function than `loadDatabase` (so `loadJSON` and `loadJSONObject` do not emit it, despite their name).

**Comment by obeliskos** [comment]
Sure, but we don't want to break existing, expected functionality.  So we should probably leave the existing 'loaded' emit and augment it with your new (lower level) emit name.

Are you familiar enough with this submit a pull request?

**Comment by arcanis** [comment]
Sure, I'll put something together.

**Comment by JpEncausse** [comment]
It seems I have the same issue:

```
var db    = new loki(file, { autosave: true });
var users = db.addCollection('users');
if (fs.existsSync(file)){
    db.loadDatabase();
}
... insert some data ...
```

The first run the file is created and updated, it works very well.
After a reload nothing works
