### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by dbubs** [techfort/LokiJS#469]
When setting `ttl` and `ttlInterval` on a new collection, I am getting this error:
`TypeError: Converting circular structure to JSON`

It seems that the `ttl` key should be added to `Loki.prototype.serializeReplacer`. When I add that, the error goes away:

```
    Loki.prototype.serializeReplacer = function (key, value) {
      switch (key) {
      case 'autosaveHandle':
      case 'persistenceAdapter':
      case 'constraints':
      case 'ttl':
        return null;
      default:
        return value;
      }
    };
```

**Comment by stigi** [comment]
A similar issue just showed up on my end. I was able to fix it by adding another case to `serializeReplacer`:
```
      case 'console':
        return undefined;
```
