### ISSUE TITLE
Querying empty collection with binary index throws error

### ISSUE THREAD

**Issue by assafweinberg** [techfort/LokiJS#47]
If a collection has a binary index set, and the collection is empty, querying it will result in an error.  The error happens in the calculateRange function on the following lines: 

`var minVal = rcd[index[min]][prop];`
`var maxVal = rcd[index[max]][prop];`

If the collection is empty, then rcd[index[min/max]] will be undefined.  We may want to set default min and max values here, but also, maybe shortcut the find() function to return an empty result set if the data is empty to save some work.

**Comment by retorquere** [comment]
I'm getting an error that looks a lot like this on lokijs 1.5.1

**Comment by obeliskos** [comment]
I just tried the following in sandbox and got no errors  : 
```javascript
var db = new loki('sandbox.db');
var items = db.addCollection('items', { indices: ['owner'] });
console.dir(items.find());
console.dir(items.find({owner:'thor'}));
console.dir(items.chain().find().data());
```
Please provide a repro script or more info

**Comment by retorquere** [comment]
I have a repro script but I'd rather not post the database that accompanies it (which triggers the error) here (the database is not mine). Can I send it somewhere in private?

The script that does it is:

```
var loki = require('lokijs')

var FileStore = {
  mode: 'reference',

  loadDatabase: function(name, callback) {
    callback(require('./db.json'))
  }
}

var db = new loki('db.json', { adapter: FileStore })
db.loadDatabase()

console.log(db.collections.map(coll => coll.name))

var keys = db.getCollection('citekey')
console.log(keys.data.length)

keys.findOne({ itemID: 1})
```

**Comment by retorquere** [comment]
I've not seen the problem before, so as far as I know, it's unique to this database. I can't reproduce this other than with this database from one of my users, and I don't know how this database got into this state.

I've also tried the script below, and to my surprise it echoes `2858` twice instead of echoing `0` after the `removeDataOnly`.

```
var loki = require('lokijs')

var FileStore = {
  mode: 'reference',

  loadDatabase: function(name, callback) {
    callback(require('./db.json'))
  }
}

var db = new loki('db.json', { adapter: FileStore })
db.loadDatabase()

console.log(db.collections.map(coll => coll.name))

var keys = db.getCollection('citekey')
console.log(keys.data.length)

keys.removeDataOnly()
console.log(keys.data.length)
keys.find({ itemID: 1})
```

**Comment by retorquere** [comment]
There's a 2nd collection in that DB that behaves as expected (clears & finds): this:

```
var loki = require('lokijs')

var FileStore = {
  mode: 'reference',

  loadDatabase: function(name, callback) {
    callback(require('./db.json'))
  }
}

var db = new loki('db.json', { adapter: FileStore })
db.loadDatabase()

console.log(db.collections.map(coll => coll.name))

function probe(name) {
  var coll = db.getCollection(name)
  console.log(`${name}: ${coll.data.length} records`)
  coll.removeDataOnly()
  console.log(`${name}: ${coll.data.length} records after removeDataOnly`)
  coll.find({ itemID: 1})
}

probe('autoexport')
probe('citekey')
```

gives me

```
[ 'citekey', 'autoexport' ]
autoexport: 1 records
autoexport: 0 records after removeDataOnly
citekey: 2858 records
citekey: 2858 records after removeDataOnly
/home/emile/github/better-bibtex/node_modules/lokijs/src/lokijs.js:5820
      var maxVal = rcd[index[max]][prop];
                                  ^

TypeError: Cannot read property 'itemID' of undefined
    at Collection.calculateRange (/home/emile/github/better-bibtex/node_modules/lokijs/src/lokijs.js:5820:35)
    at Resultset.find (/home/emile/github/better-bibtex/node_modules/lokijs/src/lokijs.js:3269:38)
    at Collection.find (/home/emile/github/better-bibtex/node_modules/lokijs/src/lokijs.js:6080:27)
    at probe (/home/emile/github/better-bibtex/894/db.js:21:8)
    at Object.<anonymous> (/home/emile/github/better-bibtex/894/db.js:25:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by retorquere** [comment]
```
var loki = require('lokijs')

var FileStore = {
  mode: 'reference',

  loadDatabase: function(name, callback) {
    callback(require('./db.json'))
  }
}

var db = new loki('db.json', { adapter: FileStore })
db.loadDatabase()

console.log(db.collections.map(coll => coll.name))

function probe(name) {
  var coll = db.getCollection(name)
  console.log(`${name}: ${coll.data.length} records`)
  console.log('idIndex:', coll.idIndex.length)

  for (const [index, data] of Object.entries(coll.binaryIndices || {})) {
    console.log('binaryIndices.', index, data.values.length)
  }

  coll.removeDataOnly()
  console.log(`${name}: ${coll.data.length} records after removeDataOnly`)
  // coll.find({ itemID: 1})
}

probe('autoexport')
probe('citekey')
```

gives me

```
[ 'citekey', 'autoexport' ]
autoexport: 1 records
idIndex: 1
binaryIndices. exportNotes 1
binaryIndices. path 1
binaryIndices. translatorID 1
binaryIndices. id 1
binaryIndices. status 1
binaryIndices. type 1
binaryIndices. useJournalAbbreviation 1
autoexport: 0 records after removeDataOnly
citekey: 2858 records
idIndex: 2858
binaryIndices. itemKey 2859
binaryIndices. libraryID 2859
binaryIndices. pinned 2859
binaryIndices. itemID 2859
binaryIndices. citekey 2859
citekey: 2858 records after removeDataOnly
```

so all the binaryIndices are one lone, but I wouldn't know how to clean them up. Can I trigger a rebuild of the index?

**Comment by retorquere** [comment]
this fixes it for me, but is there a better way to detect index corruption? General thoughts on how I managed to corrupt the indices?

```
var loki = require('lokijs')

var FileStore = {
  mode: 'reference',

  loadDatabase: function(name, callback) {
    callback(require('./db.json'))
  }
}

var db = new loki('db.json', { adapter: FileStore })
db.loadDatabase()

console.log(db.collections.map(coll => coll.name))

function probe(name) {
  var coll = db.getCollection(name)
  console.log(`${name}: ${coll.data.length} records`)
  console.log('idIndex:', coll.idIndex.length)

  for (const [index, data] of Object.entries(coll.binaryIndices || {})) {
    if (data.values.length > coll.idIndex.length) {
      console.log('fixing binaryIndices.', index)
      delete coll.binaryIndices[index]
      coll.ensureIndex(index)
    }
  }

  console.log(coll.find({ itemID: 7}))
}

probe('autoexport')
probe('citekey')
```

**Comment by retorquere** [comment]
and is there a way to do this during `loadDatabase`?

**Comment by obeliskos** [comment]
So generally indexes would become corrupt if you don't call update() after updating a document and you do not have cloning option turned on for your collection.  We recently fixed an issue where batch updates (array of docs sent to update) might have corrupted the index... 1.5.2 will have that fix in npm in a day or so.  Index corruption involving updates would usually affect results not cause errors (the index is just not sorted right but the same amount of elements).

For insert or remove to corrupt index you would have to access collection.data directly, without going through collection.insert() or collection.remove() which ensures indices are 'adaptively' updated.

To rebuild a single index, you can call : 
```javascript
coll.ensureIndex('column1', true);
```
Now that 'adaptiveBinaryIndices' is set to true by default, they probably will not be flagged as dirty so you need to pass 'force' option (true).

To rebuild all indices on a collection, you can call : 
```javascript
coll.ensureAllIndices(true);
```
Which will 'force' rebuild all indices.

That is time consuming depending on how big your database is and would be better to either fix your code or for us to fix loki if corruption occurs during normal use.

So your example above would fix corruption where there were different number of elements in index but not invalid ordering (which would result in invalid results but no errors).

It would appear that you have devised a custom reference mode adapter that allows you to handle i/o synchronously (where the loki filesystem adapter would run asynchronously).  I also see you are wrapping alot of functionality around loki persistence to handle saving on idle and simulating async. Are there still reasons for this, or now that we have great examples, would you be able to refactor your initialization logic, similar to [quickstart4](https://github.com/techfort/LokiJS/blob/master/examples/quickstart4.js) if you still need manual loading/saving or [quickstart3](https://github.com/techfort/LokiJS/blob/master/examples/quickstart3.js) if you can use autosave/load?

**Comment by retorquere** [comment]
I didn't set cloneObjects before -- I do now.

But extra items in the index, how would that happen by updating (which means modifying I guess?) a document without calling `.update()`? I've scoured my sources but I don't see any instances of accessing the `data` directly. Accidental change of documents is possible, but that would maybe mean the index got out of whack, but how would it get longer than the data array?

The lfsa adapter (quickstart3) assumes the code is running in node, and my code is running inside privileged Firefox code (aka "chrome" javascript, but that nomenclature often gets confused with "page-level JS running in the Chrome browser"), so I can't use that adapter.

I don't understand how quickstart4 loads the existing data. 

WRT the wrapping, my code makes heavy use of promises/async+await, and the wrapping code is meant to add promise support. I'm very much looking forward to the next loki version which does promises.

**Comment by obeliskos** [comment]
Ah I didn't mean to suggest that storage adapter which partitions and would be different file format on disk (and not work in browser).  I probably meant quickstart2 but I was thinking you were in node.  I think i found your real adapter is that a transactional websql adapter?  If so i guess you allow exporting to actual file when user needs to.

I would think/hope there is next to no chance of index corruption if you have enabled cloning... the exception being issues with loading/saving and asynchrony.   

If you want to add detailed diagnostics to detect your 'probe' conditions you could  tap into collection events, like 'insert', 'update', 'delete', etc.  You probably would want that not enabled by default as that would be slow.  And should any inconsistencies occur would be good to narrow code path/stack track where problem was detected.

**Comment by retorquere** [comment]
It's a transactional SQL adapter, but not websql; this is the privileged-js SQLite connector that Firefox provides to pre-FF-57 extensions. And correct, I have added debug code to an instrumented build that would save the database contents after it was loaded from disk; that's not in my production builds, it was just a one-off for this particular user.

cloning is now structurally on, but I'm still curious by what means I could have gotten an index that has more items than the data array. You know LokiJS better than me obviously, but since I'm loading and saving whole collections in one go transactionally, and since collections include both indexes and data, I don't see how they could have gotten out of sync during save/load.

For my tests I have a running log of events on the DB, but that's disabled in production, and since I can't create this at will (this is the only time I've seen it), I'm afraid I can offer no diagnostics on when it happens. If there's a way to detect index corruption I could do that during start and rebuild, but I don't know how I'd go about detecting, and I think I'd rather not rebuild at every startup.

**Comment by obeliskos** [comment]
Yea since (when not cloning), loki doesn't own the object instances, you may have no way of knowing if the logic that provides you those object instances are intentionally or unintentionally tampering with this same objects without notifying loki... cloning would be safest but slower in those instances. 

So we have simple unit test coverage of binary indices but I could look into a stress test for normal usage patterns of insert/update/remove with random object generation and querying.  I would probably add that to benchmarks as it would be computationally expensive.

**Comment by retorquere** [comment]
That would explain the indexes being ordered wrongly, but does it explain the indexes being longer than the data?

In any case, I managed to repair the users' DB with a one-off release, and I now have cloning on, so I'll just see how it goes.

**Comment by obeliskos** [comment]
It shouldn't, but an update triggers an adaptive index update which removes from index and reinserts to newly calculated position.

**Comment by obeliskos** [comment]
I have created a 'bindex-stress.js' script in the benchmarks folder which I created to stress test the adaptive binary indices.  That initial version just uses integer and string datatypes and no serialization (or simulated serialization) and my results seemed to indicate that adaptive indexing was working without any errors.  

Feel free to use that as a base and throw some more variations at it to see if you can find repeatable corruption scenarios.

**Comment by obeliskos** [comment]
Also, in addition to the new stress test, I have commit changesets to master branch to include a collection.checkIndex(propertyName, options) function.

You can use this to do simple test for index validity/consistency by calling : 
```javascript
var isValid = coll.checkIndex("orderCount");
```
Which would return true if a binary index on an 'orderCount' property was determined to be valid.  I check index length and validate sort order is correct in making that determination.

If you want to fix any errors found by forcibly rebuilding the index (slower), you can run : 
```javscript
var isValid = coll.checkIndex("orderCount", { repair: true });
```

Which will return whether it was valid before repairing (if false).

**Comment by retorquere** [comment]
Is this test expensive? If the test is inexpensive, I don't care how long the repair takes.

**Comment by retorquere** [comment]
This test/repair will make it to the next release?

**Comment by obeliskos** [comment]
techfort already released 1.5.2 last week so this will not be in that version, it should arrive on npm in the next 1.5.3 whenever we are ready for that.  If you need it in the meantime can you patch the new methods into yours?

By default the full index scans might take a while if your collections are large, how many rows could this grow to?

I added 'randomSampling' and 'randomSamplingFactor' options to checkIndex and added a checkAllIndexes() method.  You might use them like this : 

```javascript
// full test
var valid = coll.checkIndex('name');
// full test with repair (if issues found)
valid = coll.checkIndex('name', { repair: true });
// random sampling (default is 10% of total document count)
valid = coll.checkIndex('name', { randomSampling: true });
// random sampling (sample 20% of total document count)
valid = coll.checkIndex('name', { randomSampling: true, randomSamplingFactor: 0.20 });
// random sampling (implied boolean)
valid = coll.checkIndex('name', { randomSamplingFactor: 0.20 });
// random sampling with repair (if issues found)
valid = coll.checkIndex('name', { repair: true, randomSampling: true });

// check all indices on a collection, returns array of invalid index names
var result = coll.checkAllIndexes({ repair: true, randomSampling: true, randomSamplingFactor: 0.15 });
if (result.length > 0) {
  results.forEach(function(name) { 
    console.log('problem encountered with index : ' + name); 
  });
}
```

**Comment by retorquere** [comment]
I can't say how large they'd get as use varies a lot across my users, but I'd not expect any single collection to have more than 250k items.

**Comment by retorquere** [comment]
(I'd rather not patch more than I have to, I can wait for 1.5.3 to drop)

**Comment by retorquere** [comment]
Turning on "clone" introduces a new problem for me: I had a custom inflater that transformed a string into a Date during load, but having "clone" on gets me a stringified date in the cloned object I get back from queries.

**Comment by retorquere** [comment]
Any word on a timeframe for 1.5.3 dropping? I have a second user that has the problem -- and this is with cloning on.

**Comment by obeliskos** [comment]
So far all we really have is some added diagnostic and repair functionality... we have not found or fixed any problems to prevent it from happening again.

Can we make a new issue for this as it is not really relevant to this older issue?

So to answer your question, I still need to finish up some minor cleanup and examine effects of my recent changes to simplesort and new ops to our typescript definitions but in theory i could ask techfort after that.

Maybe if you have more diagnostic info we can make a final attempt to diagnose before dropping a diagnostic/repair build with the new index verification and repair logic.

**Comment by retorquere** [comment]
I'm happy to make it a new issue, but I can't reproduce the matter, and I can't enable long-term logging for all users to catch it if it occurs. I'd be happy just to be able to detect and repair.
