### ISSUE TITLE
Understanding binary index re-index triggering

### ISSUE THREAD

**Issue by dbrugne** [techfort/LokiJS#477]
I struggle with documentation and tests to understand how the binary could -and should be- used for my particular need.

I've a collection with potentially millions of small records (dataId, timestamp, value).
For a given dataId I have thousands of records.
I would like to retrieve a subset of records by dataId ($eq) and timestamp ($lte, $gte).
**I add records almost often as I request data**.
The data insterted are not ordered (timestamp are not inserted chronologically).

First I test the binary index gain: 

``` javascript
let noIndex = database.addCollection('noIndex');
noIndex.insert(_.cloneDeep(data));

for (let id = 0 ; id <= 10 ; id ++) {
  const result = collection.find({
      $and: [
        { dataId: id },
        { timestamp: { $gte: now - 10000 } },
        { timestamp: { $lte: now + 10000 } },
      ],
  });
}
// done in 743.415636

let withIndex = database.addCollection('withIndex', { indices: ['timestamp'] });
withIndex.insert(_.cloneDeep(data));
for (let id = 0 ; id <= 10 ; id ++) {
  const result = collection.find({
      $and: [
        { dataId: id },
        { timestamp: { $gte: now - 10000 } },
        { timestamp: { $lte: now + 10000 } },
      ],
  });
}
// done in 6.778491
```

Obiouvsly the performance gain is massive.
Now I would like to simulate writing operation(s) between finding ones. In the loop I had a write operation.

Now the performance variation between my collection with index is worst than without index (with same insert/find operations):
- Average without index: **2.363856**
- Average with index: **3.054125**

So I wonder how the index is managed. After a quick (very quick) look in source code it seems that index is not maintained on collection insertion, but lazilly when a .find() operation need an index that was marked as dirty by a previous write operation.

I'm right?

**Comment by obeliskos** [comment]
Yes, you are correct.  There is room to drastically improve our binary indices performance by doing index maintenance rather than full rebuild after an insert/update/remove occur (all of those flag index for rebuild).

I have been meaning to find time to address each (insert, update, remove) functions and immediately rebuild rather than lazily rebuild.   Delete should be the easiest to start off with and this could be added along with benchmarks to verify effective performance and unit tests to verify integrity. 

Depending on how narrow your filter reduces document count (and you did say that it was unsorted), DynamicViews should be less prone to performance degradation by a 1-1 insert/find ratio.   This also could use more benchmarks to model out and verify.  Since you have a dataset already in use, maybe you could try benchmarking the exact same scenario using DynamicView filters.

I may try to find time to begin looking into (as a first step) optimizing the collection.remove() to perform index maintenance (rather than flag full rebuild) sometime this weekend.  If you are interested in contributing to meet your immediate needs feel free to contribute and I will help out where possible.

**Comment by obeliskos** [comment]
Making progress... will probably have something in next few days.

**Comment by dbrugne** [comment]
Great! I was thinking how can I help you but wasn't able to free up enough time (before next month).
At least I'll be able to perform and complete some tests on the new code.

Thanks @obeliskos

**Comment by obeliskos** [comment]
Finished first draft, leaving as experimental collection option for now.  Benchmarks of interlaced inserts/finds are on par with consecutive finds now.  Will need a few more benchmarks to guage performance impact on insert/update/remove ups which now have added index maintenance.  

When you get some time it would be great to help model out some benchmark scenarios and or if anyone wants to do so... or test and report bugs that would be most welcome.

**Comment by Zbatux** [comment]
I've tested the new version with the experimental 'adaptativeBinaryIndices' option. 

I compare execution time of interlaced inserts/finds in different collections:
* Old Loki version without index
* New one without index
* Old one with index
* New one with index
* New one with index and adaptativeBinaryIndices

Here are the differents steps that we run through during the test:

1) Create each collections described before
2) Fill each with the same data records (object composed of { timestamp: number, stringData: string, payload: string }. The collection isn't ordered after insertion but every collection have the same records in the same order (I compare comparable things)
3) For each collection I run a serie (the same for each) of interlaced inserts/finds

After my benchmark I notice that the new loki version with index AND adaptativeBinaryIndices (59.785641ms for 10 000 operations) is twice to three times faster than the old one with index (168.462814ms for 10 000 operations). The gain is about 281%.

Good job @obeliskos! :)

Here is spreadsheet with the results i got with different collection's size/amount of interlace inserts/finds:
https://docs.google.com/spreadsheets/d/14QAd6WE_mJ7g_Bk728bya8TQZUk_T_4I9aNbqjbiwP8/edit?usp=sharing

And my (humble) source code is available here: https://gist.github.com/Zbatux/54d99a74126456b969c636c12422b827

If you confirm the result, when can we expect this feature will be added to official release?

**Comment by obeliskos** [comment]
Thanks, that's very helpful information.  Yes this feature is meant to raise the worst-case scenario 'find' performance.   

It is currently an 'opt-in' feature now in GitHub but I might make it the default soon.

updating npm might take a while as @techfort would need to do this and I am not sure when he will have time.  I may also want to revisit our ensureIndex() so user can possibly toggle between the two based on performance needs.... (if your inserts/updates/removes are vastly more frequent than selects the adaptive might be slower).

There is also a possibility I may be able to optimize for situations where the indexed property was not changed (or is still in correct order).

**Comment by obeliskos** [comment]
adaptive binary indices have been added to loki for a while now and are the default mode for binary indices so i am closing this - thanks
