### ISSUE TITLE
Collection ttlInterval not working

### ISSUE THREAD

**Issue by adi130987** [techfort/LokiJS#478]
I'm trying to set an expired time for collection aged documents and It's not working. Either I'm not giving the ttlInterval value correctly or there might be a bug. My code looks something like this:

var idbAdapter = new LokiIndexedAdapter('idbAdapterName');
var db = new loki('dbName', {
        verbose: true,
        autoload: true,
        autoloadCallback: lokidbAutoloadHandler,
        autosave: true,
        autosaveInterval: 600000,
        persistenceMethod: 'adapter',
        adapter: idbAdapter
});
var addCollectionOptions = {
    unique: ['id'],
    indices: ['id'],
    ttlInterval: 120000
};
var tCollection = db.addCollection('testingCollection', addCollectionOptions);
tCollection.insert([{id: 1, name: 'John Doe'}, {id: 2, name: 'Jane Doe'}]);
console.log(tCollection);

If I check console logs the collection object has a ttl property which is an object like this 
ttl: {age: null, daemon: null, ttlInterval: null}

I looked a little bit at the code here: https://rawgit.com/techfort/LokiJS/master/jsdoc/lokijs.js.html#line3359 and then I added a new property to addCollection options object, something like this:

addCollectionOptions['ttl'] = Date.now() + ttlInterval;
addCollectionOptions['ttlInterval'] = ttlInterval;

Now the ttl collection property looks like this:

ttl: {
    age: 1474612572707,
    daemon: 4,
    ttlInterval: 120000
}

But if I want to get the collection later (later than 2 min) on another page or if I set a timeout and then get the collection the ttl object has null values again(ttl: {age: null, daemon: null, ttlInterval: null}) and collection documents are the same, no aged docs cleanup was made.

**Comment by obeliskos** [comment]
Can't remember who wrote that feature, but I did a quick test and it seems to work if I use the following addCollectionOptions : 

```javascript
var addCollectionOptions = {
  unique: ['id'],
  ttl: 120000,
  ttlInterval: 120000
};
```

So the interval determines how often it 'sweeps' documents which are older than the ttl value.  You also don't need both 'unique' and 'indices' for same property.  If it is unique you should get rid of 'indices' property and query using collection.by().

**Comment by adi130987** [comment]
Thanks, I will test this asap and let you know how it goes.

**Comment by adi130987** [comment]
I just made some tests with collection options looking like this (as you said):

```javascript
var addCollectionOptions = {
  unique: ['id'],
  ttl: 120000,
  ttlInterval: 120000
};
```

So it works in this case: I create the collection, insert some docs in it, wait for ttlInterval to pass and check the collection again, the old docs were removed. All good so far.

If I save the database right after collection docs insert is done, wait for ttlInterval to pass and check the collection again, the old docs are removed from collection. But if I refresh the page get the same collection, the old docs are still there.

**Comment by obeliskos** [comment]
Sorry I let this drop, hard to keep up... 

Each collection has a 'dirty' property (flag) that should get set to true whenever there is an insert/update/remove on a collection.  The next time the autosave interval kicks off it should check if any collections are dirty and, if so, it will do a save otherwise it will not actually save because it thinks nothing has changed.  

So your autosave interval of 600000 is 10 minutes right... you sure it saved after docs were removed (and dirty flag set).  IndexedDb is asynchronous so if you are relying on unbeforeunload to call db.close() and flush the changes that is unreliable since it will not wait for it to finish before shutting down page.  In that case you might need to tap into mouseout event if you want to flush changes with db.close() while you still have a few ms left before user leaves.

**Comment by adi130987** [comment]
I'm not relying on unbeforeunload or something similar. I just set the ttlInterval to see if my collection is cleaned up of old docs. I inserted the docs right after I created the collection then triggered save database  then I waited for ttlInterval to pass, checked the collection, the old docs were removed. I refreshed the page, the loki database was reloaded and the old docs were still in my collection.

From what I understand from your last comment when the collection is cleared of old docs by ttlInterval, the `dirty` flag becomes `true` and the changes will be made permanent only if you save the database or wait for autosave. If that's the case it makes perfect sense and you can close this issue :)

**Comment by obeliskos** [comment]
Yea only if a manual or autosave is run will it be stored across page visits.  Everytime you refresh the web page all has to be reconstructed from its most previous save.  I see ttl being used in many scenarios where loki is memory cache and not even saved at all, but if your ttl is high enough I can see usefulness when using along with persistence.
