### ISSUE TITLE
getCollection return value

### ISSUE THREAD

**Issue by assafweinberg** [techfort/LokiJS#48]
Right now, the behavior for getCollection is to throw an error if the collection requested isn't present.  I think it might be more convenient to return null if the collection isn't found. Then a user can test the value and initialize the collection if necessary. e.g.

```
var col = db.getCollection('test');
if(!col)
  col = db.addCollection('test')
```

Right now, there's no great way to know if a collection already exists before trying to get it.

**Comment by lakshmankotipalli** [comment]
Hey @techfort , I am new to LokiJS, and finding it a bit difficult to know few things which already exists but I cannot find the documentation for them.

For example : I am not able to find the documentation for getCollection(), in fact, I don't know that getCollection() exists in LokiJS, I recently started migration from IBM Worklight's JSON Store to LokiJS.

Can you suggest me on how can I broadly understand what is in LokiJS? I got familiar with basic stuff like creation of db/collection, find, clear, get etc.., But at a deeper level I don't understand how few things work, like saveDb(), getCollection, onLoad.

Please help :)

**Comment by assafweinberg** [comment]
Have you found the documentation at https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html ?

**Comment by lakshmankotipalli** [comment]
Hey @assafweinberg , i didn't know about this, I was going through the documentation provided in lokijs.org and in github - techfort.
This link provided by you seems to be very helpful, thanks a ton!!
I ll go through this. :) :+1:

**Comment by CryptoSharon** [comment]
I think a more efficient way of checking the collection according to this method would be

```js
const messages = db.getCollection('messages') || db.addCollection('messages')
```

Unless there is a more recent way of doing it. Does anyone know any?
