### ISSUE TITLE
Specific exception classes

### ISSUE THREAD

**Issue by metanav** [techfort/LokiJS#481]
How can be sure what kind of exceptions are thrown?

Example from docs:

```
var collection = db.addCollection("test", [
  unique: ["name"]
]);

collection.insert({ name: "Peter" });

var doc = collection.insert({ name: "Jack" });
doc.name = "Peter";

try {
  collection.update(doc);
} catch(err) {
  console.log(err);
  doc.name = "Jack";
}
```

Here we can not say that the error is thrown due to unique property constraint.
It would be only useful if it throws user defined exception e.g., DuplicateKeyException

**Comment by obeliskos** [comment]
I'm open for suggestions, but yea right now you would probably have to do string matching to verify specific error types.  Any changes to exception logging would probably have to be implemented as database or collection option, with default behavior being as it is now to avoid breaking changes.

**Comment by metanav** [comment]
For minimal changes, the error can be thrown as a specific class inherited from the Error (base class) with the same message to retain the backward compatibility.
