### ISSUE TITLE
saveDatabase() not working

### ISSUE THREAD

**Issue by adi130987** [techfort/LokiJS#484]
Hi,

I'm trying to see how many data I can store with loki using LokiIndexedAdapter. So, I did this test:

```
// get data from url
function getData (file, callback) {
    var request = new XMLHttpRequest();
    request.overrideMimeType("application/json");
    request.open("GET", file, true);
    request.onreadystatechange = function() {
        if (request.readyState === 4 && request.status == "200") {
            callback(request.responseText);
        }
    }
    request.send(null);
}

var db = new loki('testDB', {
          verbose: true,
          autoload: true,
          autoloadCallback: dbLoaded,
          autosave: true,
          autosaveInterval: 600000,
          persistenceMethod: 'adapter',
          adapter: new LokiIndexedAdapter('appAdapter')
        });


function dbLoaded() {

    console.log(db.getCollection('dummyData'));

    getData('https://silex-test-app.local/big-json-test-data/143407', function (responseText) {
        var data = JSON.parse(responseText);
        console.log(data); // Object {big_test_data: Array[143407]} (143407 objects)
        var c = db.addCollection('dummyData');
        c.insert(data.big_test_data);
        db.saveDatabase();
    });
}
```

I do not want to wait for autosave interval to pass to save data and I trigger the save right after I received the server data. The result is an error: 

```
Uncaught Error: Error saving database
saveCallback    @   loki-indexed-adapter.js:147
(anonymous function)    @   loki-indexed-adapter.js:455
```

https://silex-test-app.local/big-json-test-data/143407 is a local endpoint I used to read a json file and get 143407 test objects to be stored in loki database. Each object has around 17 properties including a short description.

I manage to avoid the above error passing a function to saveDatabase method:

```
        db.saveDatabase(function() {console.log('database saved...';)});
```

but id doesn't save the database and the collection is null at page refresh.

I suspect it can not process so much data, so I reduced the received data from server. I was able to save the database this time, but but only ~50000 objects that I added in a test collection.

I used Chrome browser while I made this test.

I couldn't find any loki documentation related to browser limitations. Is there any?

**Comment by obeliskos** [comment]
You may want to open Chrome developer tools, click on 'Application', and under storage/indexeddb inspect to see if you have any other database/keys using up your indexeddb quota for the domain your page is served from.

If your database or adapter are in global scope you might also want to call your indexed adapter's 'getCatalogSummary' method within developer tools console to see estimated size of key.  Console diagnostic commands for indexed db adapter are summarized [here](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#examples-of-using-loki-indexed-adapter-from-console).

Alternatively, you can log db.serialize().length to see how big the string is you are trying to save.

Another limit is that indexeddb is probably storing in Unicode which may double the size which it uses within your indexed db quota for your current domain.

So let me know what size we are talking about and we can determine if you are bumping up against a 5MB 'soft limit' or find out what limit you are encountering.

**Comment by adi130987** [comment]
I can not find the app key in Chrome developer tools, I only have IndexedDB->LokiCatalog->LokiAKV with app, appkey and key(all empty).

I added your diagnostic line and used the other methods to get database size and serialized string length.
This are the results:

```
queryUsageAndQuota: we are using  65346402  of  3569279060 bytes
db.serialize().length: serialized string length: 234153360

catalog summary: 
app : appAdapter
key : testDB
size : 60506243
```

**Comment by obeliskos** [comment]
So : 
- the index adapter reports you have a roughly 60mb key already in the database
- Your serialized string which you are trying to save into the database is 234megs.
- Chrome reports there is around 3.5 gigs left in temporary storage

If the 'testDB' entry is corrupt somehow and all fields are empty (yet it still takes up 60Megs?) then you can try deleting it using : 
```javascript
adapter.deleteDatabase('testDB');
```

IndexedDb is not only asynchronous but probably handled on different thread (not locking up ui) so if you leave the page while it was still saving it might leave corrupt (incomplete) record.  Maybe clear out the old (empty?) record and (now that you have your callback passed to saveDatabase you will be able to tell when it is done saving.  Not sure how long it would take to save 234 megs into an indexeddb key.

Its possible you are running into quota management api limit for temporary storage [more info here](https://developers.google.com/web/updates/2011/11/Quota-Management-API-Fast-Facts?hl=en).   Not all browsers support quota management api (yet?) so the adapter wasn't written for that but I believe storage is granted as 'temporary' by default.  Your queryUsageAndQuota results show max of 3.5 gigs, of which I believe each domain is allowed 20% of which would be around 680megs.  

Also i'm wondering does the 3.5 gigs match your free disk space? If that is your limit because that is your free disk space you might try freeing up some space to see if chrome is less protective of indexeddb usage.

**Comment by adi130987** [comment]
My app it's a single page app built with Polymer and I do not refresh the page too often. I'm trying to use loki to sync my the server data at some point and make it work offline.

I do not know how exactly those 3.5 gigs are calculated. I guess it's some percentage of my total free disk space, which is around 80gigs.

I cleared all indexedDb storage several times, deleted the database and the results are the same. Even the database save callback is fired, but no database is actually saved.

I tried do the same tests using PouchDB with indexedDB adapter and I could save all data without any issues. Also I have tried with twice as much data and still worked. 

I do not think it's a indexedDB limit issue.

**Comment by obeliskos** [comment]
I will try over the next several days to work up a loki sandbox example to stress memory constraints by randomly generating objects.  To be as close as possible, was your 234meg serialized database the 50000 record test or more objects?

If you have latest lokijs, you might try reverting the Loki.prototype.serialize back to : 
```javascript
    Loki.prototype.serialize = function () {
      return JSON.stringify(this, this.serializeReplacer); 
    };
```

...just to get rid of pretty printing whitespace.  Eventually that may be a constructor option.

**Comment by adi130987** [comment]
234Mb serialized contained ~170000 objects. I was only able to save ~50000 (~60-65Mb).

**Comment by obeliskos** [comment]
Thanks, just to follow up I have tested various browsers and found out that on many (such as chrome and safari), JSON.stringify seems to break above 50megs or so.  Additionally the delay to stringify 50megs is pretty high to be practical for browser usage anyways.

Immediate advise is to keep single database under 50megs (db.serialize().length).  You should be able to put as many databases as indexeddb will store, just keep each under 50megs or so.

When i get time I will look into creating alternative 'reference' mode adapter which skips serialization and just persists the object itself.  I may need to rework the adapter interface to allow returning reference as well (to skip JSON.parse() delays or possible limitations).  That may be over next few weeks.

I have created in [indexed db stress gist](https://gist.githubusercontent.com/obeliskos/3d4884a52f036288553f2704b65b4505/raw/a1fd2b9012b8e9b201470c836314385768de4ffe/idb%2520stress) you can paste into the [sandbox](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm) but lower the numObjects to around 5000 before running and increment by 1000 until it breaks to find the limit for your browser.

**Comment by obeliskos** [comment]
In case you are following, i have moved this discussion to #498 and will be updating findings and developments there.

**Comment by obeliskos** [comment]
Well I took a very circuitous route to get there but I believe I have fixed the problem.  You may or may not still need this solution but I will outline the fix and how you or others can avoid this limit.

So I believe Chrome treats indexeddb a bit differently than others in that it imposes a roughly 60meg limit on any single indexeddb document/row.  The whole database can be bigger but not a single document.

So I have added a 'paging' option to the new LokiPartitioningAdapter which will break up large collections into pages that will fit within those limits.  The default page size is 25megs which should be fine for Chrome.  

I created a [stress test loki sandbox gist](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/2ed332f469a39c94fe1c17d1251234b5/raw/9d38f6eefa769870bfc0bdcac7ca9f9a6683ba34/Chrome%2520IndexedDB%2520Stress%2520Test) if you want to try it out, or if you have your own test let me know your results.

As you can see in loki sandbox gist, the additional step you need to do is pass in your indexeddb adapter to construct a (wrapper) LokiPartitioningAdapter like : 

```javascript
var idbAdapter = new LokiIndexedAdapter('appAdapter');
var pa = new loki.LokiPartitioningAdapter(idbAdapter, { paging: true });

var db = new loki('sandbox.db', { adapter: pa });
```

Currently the LokiPartitioningAdapter does not have a way to delete a database so if your database shrinks it may leave lingering pages or partitions.   I will need to think how best to automate that cleanup, until then you might need to use indexed adapter to manually delete partitions/pages.

**Comment by obeliskos** [comment]
closing since i believe a fix is to use partitioning adapter with paging option enabled
