### ISSUE TITLE
Any instructions for using Loki with Nativescript + Angular?

### ISSUE THREAD

**Issue by patrickpereira** [techfort/LokiJS#485]
Can't find the modules, if I follow the instructions.

**Comment by obeliskos** [comment]
Sorry I missed this as I played no part in the angular adapter.  If I remember correctly, our angular adapter is included in /src along with lokijs.js and other adapters.  I believe the documentation we do have on it can be found [here](https://github.com/techfort/LokiJS/wiki/Lokiwork---LokiJS-Angular-Service).
