### ISSUE TITLE
Error: Can't resolve 'fs'  in lokijs version "1.4.1"

### ISSUE THREAD

**Issue by metanav** [techfort/LokiJS#486]
I am getting this error:
ERROR in ./~/lokijs/src/lokijs.js
Module not found: Error: Can't resolve 'fs' in 'node_modules/lokijs/src'
 @ ./~/lokijs/src/lokijs.js 1141:16-29

I am using Angular2/webpack with following code:

```
const Loki = require('lokijs');
const LokiIndexedAdapter = require('lokijs/src/loki-indexed-adapter');
const idbAdapter = new LokiIndexedAdapter('app');
       
 this.db = new Loki('mydb', {
            autoload: true,
            autoloadCallback: this.loadHandler,
            adapter: idbAdapter,
            options: {
                persistenceMethod: 'adapter'
            }
        });

```

I hope to see some example to work with Typescript in node environment which is built for browser environment.

**Comment by Kanaye** [comment]
Hi @metanav!

Please take a look at #449.

**Comment by metanav** [comment]
Thanks @Kanaye. It was helpful to fix.
