### ISSUE TITLE
why on node.js don't exit when done 

### ISSUE THREAD

**Issue by ystyle** [techfort/LokiJS#489]
Is autoload of lokijs asynchronous?
In the node.js after the program does not run out of automation.

**Comment by obeliskos** [comment]
auto'save' does spin up an interval timer which would keep program from exiting but autoload should yield thread when the load is complete.

if you use autosave, you should be able to call db.close(); to tidy up and disable autosave interval timer.

**Comment by ystyle** [comment]
1. If disable autosave ', can call db.close () or bd.saveDatabase at process.on (' exit ', function () {})?
2. In node v5.4.1, autoload not waiting for the process, the need to install promise.js ?.

**Comment by ystyle** [comment]
In the cli program, the collection of historical data will sometimes be emptied. 
I just save some url and title, run the program to display or search some.
and  also can  add some records.

```javascript
new loki(`${filename}${path.sep}${FILE}`, {
    verbose: true,
    autosave: true,
    autosaveInterval: 5000,
    autoload: true,
    autoloadCallback: function () {
        var coll = db.getCollection('meizitu');
        if (coll === null) {
            console.log("create meizitu data collection...");
            coll = db.addCollection('meizitu',{
                unique:['url'],
                autoupdate:true
            });
        }
    }
});
```


The other is the end of the program does not automatically shut down. i use `ctrl +  c` every time
