### ISSUE TITLE
findOne( {} ) returns the whole Collection .data

### ISSUE THREAD

**Issue by RobertoMalatesta** [techfort/LokiJS#491]
Hi, first and foremost thanks for this wonderful piece of code.

I noticed (on the latest github version as well as on later versions) a strange behavior:

if I call *.findOne( {} )   (with empty criteria) the result I get is the whole .data of the collection.

Calling *.findOne({live:1}) where live is a parameter all stored documents satisfy, 
the query correctly returns an Object of the Collection.

(btw: calling *.findOne() <-- without arguments the result is a Resultset but the call itself is uncorrect.)

Thanks for your time,

--R

**Comment by obeliskos** [comment]
Not sure how we missed both of those... thanks for pointing out.   Both cases should be fixed, let me know if you have any issues.  I will try to remember to add unit test for that.

**Comment by RobertoMalatesta** [comment]
Hi @obeliskos . Confirmed.
tested find() and find({}) and now they are OK.

--R
