### ISSUE TITLE
Our demo doesn't work properly

### ISSUE THREAD

**Issue by hieunc229** [techfort/LokiJS#492]
I have been research on offline storage for browser, especially for cordova. LokiJS seems really interesting. Though I just have a quick look at our demo at http://lokijs.org/#/demo and it doesn't work properly. The issue was once the item deleted, refresh the browser and it would come back (not all of items). Tested using Chrome and Safari lastest version

Thanks for creating such a great library!

**Comment by obeliskos** [comment]
I don't believe techfort's demo has any persistence wired up so its probably just not even trying to save.

I am not aware of the state of persistence adapter support for cordova, so if localstorage and indexeddb are not available you may need to use the third party [loki cordova adapter](https://github.com/cosmith/loki-cordova-fs-adapter).
