### ISSUE TITLE
Default sort for DynamicViews

### ISSUE THREAD

**Issue by Thrilleratplay** [techfort/LokiJS#495]
I have a collection where documents are assigned based on a boolean flag.  These are broken into two views for assigned and unassigned.  Similar to the code below:

```Javascript
// Collection of tasks
var myTasks = loki.addCollection('MyTasks', {indicies: ['assigned']});

// Assigned/Unassigned views
var myAssignedTasks = myTasks.addDynamicView('Assigned');
myAssignedTasks.applyFind({assigned: true});

var myUnassignedTasks = myTasks.addDynamicView('Unassigned');
myUnassignedTasks.applyFind({assigned: false});
```

I found through unit testing that, after a document's assigned value has been changed, the sort of the DynamicView which had the document removed no longer returns the order of insertion.  I have already tried difference combinations of `persistent` and `sortPriority` options.  The only way that consistently works is sorting by the $loki value.

```Javascript
myAssignedTasks.applySimpleSort('$loki');
myUnassignedTasks.applySimpleSort('$loki');
```

Is there a less hacky way to have the default sort DynamicViews be the insertion order?

If it is relevant, this is being used with the Loki Angular adapter and retrieving the view data by using `myAssignedTasks.data()` and `myUnassignedTasks.data()`

**Comment by obeliskos** [comment]
At the moment, no... I believe what you encountering are that when a document is removed (which is currently in view resultset) that we just fill the hole by moving the last element to that position and truncating array.  

That was meant to be optimization, assuming unordered doesn't care... but it probably wouldn't be much of a performance hit to just do a splice().  I think it would be good to add it to 'todo' list or if your feeling enterprising you can submit a pr updating the DynamicView.prototype.removeDocument to use splice in the 'if not last row in resultdata' block, updating both the main logic and persistent option logic to use splice.

**Comment by obeliskos** [comment]
Thanks for the pr! Closing.
