### ISSUE TITLE
error when an array of events is used

### ISSUE THREAD

**Issue by cristyansv** [techfort/LokiJS#499]
#### Class: [LokiEventEmitter - on](https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L522)

when it is passed to the method 'on' an array of events, this is not handled properly it.

Also in the code comments reads:
`@returns {int} the index of the callback in the array of listeners for a particular event`
but returns the callback.

I think the solution is:

``` javascript
LokiEventEmitter.prototype.on = function (eventName, listener) {
        var event;
        var self = this;

        if (Array.isArray(eventName)) {
          eventName.forEach(function(currentEventName) {
            self.on(currentEventName, listener);
          });
          return listener;
        }

        event = this.events[eventName];
        if (!event) {
          event = this.events[eventName] = [];
        }
        event.push(listener);
        return listener;
      };
```

I should make a pull request with this solution?

**Comment by techfort** [comment]
Hi @cristyansv the reason why the index of the listener is returned is that a single event can have many listeners, and if you want to remove one of those you need to know what position they occupy in the listeners array. It's an edge case as removing listeners isn't really a common practice, but I can't think of another way to do that. If you can please go ahead and submit a PR, i'll be happy to check it out.

**Comment by cristyansv** [comment]
> the reason why the index of the listener is returned is that a single event can have many listeners, and if you want to remove one of those you need to know what position they occupy in the listeners array

Yes, I agree, but at this time, does not happen.

I'll make small change to accept arrays properly.

**Comment by cristyansv** [comment]
@techfort what you think about https://github.com/techfort/LokiJS/pull/501
