### ISSUE TITLE
Improve documentation for persistent functionality

### ISSUE THREAD

**Issue by nabilfreeman** [techfort/LokiJS#504]
I noticed a couple of missing things in the documentation related to database persistence.

- Understanding how to explicitly set `persistenceMethod` in the constructor is confusing
- Autoload is always asynchronous (makes sense due to the functionality of different adapters), but the documentation suggests that some adapters are synchronous and other are async.

If you permit me (:grin:), I would like to modify the wiki a bit to explain things more clearly: https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters

Also, I think autoload could be implemented better - it makes more sense to me to move the onload handler to a separate argument in the constructor, with Loki autoloading if the callback is supplied.

Alternatively it might be simpler to not have it at all, and require that connections are always explicitly made with `loadDatabase(() => {})`. A lot of Node database clients work like this.

**Comment by obeliskos** [comment]
Sure, go ahead and clarify if you would like...  maybe we could add more information to our [jsdoc generated pages](https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html) to help clarify as that should be our main reference for accuracy.

While the way we have persistence / autoload set up right now could use improvement, our master branch is trying to avoid any breaking changes.  So moving parameters is not an option if it breaks compatibility.  

We recently discussed overhaul of this in our 2.0.0 branch in [this issue](https://github.com/techfort/LokiJS/issues/482).  If you don't need to support legacy es5 environments we have that branch not only for breaking loki changes but for changes that break es5 compatibility.
