### ISSUE TITLE
Must use $and in .find() when using more than one parameter?

### ISSUE THREAD

**Issue by junerockwell** [techfort/LokiJS#506]
This is the data:
````
items.insert({ name : 'mjolnir', owner: 'thor', maker: 'dwarves' });
items.insert({ name : 'gungnir', owner: 'odin', maker: 'elves' });
items.insert({ name : 'tyrfing', owner: 'Svafrlami', maker: 'dwarves' });
items.insert({ name : 'draupnir', owner: 'odin', maker: 'elves' });
````
The query is `items.find({'owner': 'odin', 'name': 'gungnir'});`
I expect the result to be just the documents that match both the parameters which there is only one:
````
[
  {
    "name": "gungnir",
    "owner": "odin",
    "maker": "elves",
    "meta": {
      "revision": 0,
      "created": 1478205381405,
      "version": 0
    },
    "$loki": 4
  }
]
````
But instead, the results are all documents that match `'owner':'odin'` but both don't have the same `'name': 'gungnir'`:
````
[
  {
    "name": "draupnir",
    "owner": "odin",
    "maker": "elves",
    "meta": {
      "revision": 0,
      "created": 1478205381405,
      "version": 0
    },
    "$loki": 4
  },
  {
    "name": "gungnir",
    "owner": "odin",
    "maker": "elves",
    "meta": {
      "revision": 0,
      "created": 1478205381405,
      "version": 0
    },
    "$loki": 2
  }
]
````
It seems like it only looks for the first parameter because if I reversed the parameters: `items.find({'name': 'gungnir', 'owner': 'odin'});`, the result is just one json object that matches `'name': 'gungnir'`.

So if I really want to query using two (or more) parameters and expect a result that matches the two parameters, I have to use `$and`. **Am I understanding this correctly? Or is this a bug? Was this the intention?**

This is my find query with `$and`: `items.find({'$and': [{'owner': 'odin'}, {'name': 'gungnir'}]})` and the result is as expected: the only one document that matches both parameters.

**Comment by obeliskos** [comment]
That is as expected... I am not opposed to eventually adding support for your first notation but initial implementation was with $and op and array of expressions.  If chaining there is coll.chain().find(exp1).find(exp2).data() equivalent as well.

**Comment by junerockwell** [comment]
@obeliskos Oh I suppose chaining is a good idea though. For some, it might be too much chaining, but I do see a good advantage where the find parameters are more readable in the long run. Thanks!
