### ISSUE TITLE
Enable binary search for $in.

### ISSUE THREAD

**Issue by Viatorus** [techfort/LokiJS#508]
Consider the attached code sample:

```javascript
let db = new loki("test");
let users = db.addCollection("users", {
  indices: ['id']
});

for (let i = 0; i < 10000; i++) {
 users.insert({id: i});
}

let searchIn = {
    id: {$in: [40, 50, 60]}
}

let searchOr = {
     '$or': [{id: {'$eq': 40}},
             {id: {'$eq': 50}},
             {id: {'$eq': 60}}]
}

let iterations = 50000;
for (let j = 0; j < 3; j++) {
    console.time('Function in');
    for(let i = 0; i < iterations; i++ ) {
        const results = users.find(searchIn);
    }
    console.timeEnd('Function in') // Takes ~ 4000 ms


    console.time('Function or');
    for(let i = 0; i < iterations; i++ ) {
        const results = users.find(searchOr);
    }
    console.timeEnd('Function or') // Takes ~200 ms
}
```
I think, $in on indices columns should perform similar to the $or / $eq query.

What do you think about it?

**Comment by obeliskos** [comment]
Yea that's a great observation...  the challenging part to doing that is that most of our ops are only aware of a single document and not a set of documents.  Currently $and and $or are hardcoded exceptions which use resultset chaining and branching to orchestrate... $and can use index for first expression and $or can use index on all subclauses because they are run in parallel and aggregated into single result set.

In theory we could implement $in similarly by creating Resultset.findIn() method and hardcode op to use it... but since (as you have mentioned) this has alternate existing syntax, it may be worth thinking about adding an expression 'preparser' to convert your $in clause into $or clause before query execution.

**Comment by Viatorus** [comment]
My attempt is after line 2066 inside lokijs.js:

```javascript
// Unpack the $in operation into a chained $or $eq query.
if (operator === '$inex') {
    queryObjectOp = [];
    for (let i = 0, len = value.length; i < len; i++) {
        let subQuery = {};
        subQuery[property] = {'$eq': value[i]};
        queryObjectOp.push(subQuery)
    }

    // Reset property to $or.
    property = '$or'
    if (this.searchIsChained) {
        this[property](queryObjectOp);

        // for chained find with firstonly,
        if (firstOnly && this.filteredrows.length > 1) {
            this.filteredrows = this.filteredrows.slice(0, 1);
        }

        return this;
    } else {
        // our $and operation internally chains filters
        result = this.collection.chain()[property](queryObjectOp).data();

        // if this was coll.findOne() return first object or empty array if null
        // since this is invoked from a constructor we can't return null, so we will
        // make null in coll.findOne();
        if (firstOnly) {
            return (result.length === 0) ? ([]) : (result[0]);
        }

        // findAndnot first only return all results
        return result;
    }
}
```

It works quiet well. :)

The only problem is, that the performance difference between $in and $inex are depending on the number of values inside the collection and the number of values in the query.

That means for example:
For small collections and medium/large number of values in query -> $in performs better.
For medium/big collections and small/medium number of values in query -> $inex performs better.

I think we can find a good intersection when to use $inex over $in and vice versa. 

What do you guys think?

**Comment by obeliskos** [comment]
Nice, I am at a good stopping point so I will re-familiarize myself with this critical path function maybe tonight.  

Ideally we won't need to add any logic to execute the query itself we will just fix up the query components to be an $or query before we actually test to see if it is an $or query and let existing logic execute it from there.  

Once we distill that 'query fix-up' logic which you may have already have, we might be able to extract it into a generic 'preprocess' utility method.

**Comment by obeliskos** [comment]
Alright I took your example and quickly adapted it to please our (es5) linter and just reinvoke find() after transposing query object.  

So in Resultset.prototype.find(), (right before the test for operator === '$regex') I have added this block : 

```javascript
  // transpose 'virtual' $inex operator to $or op for performance
  if (operator === '$inex') {
    var subQuery,
      qi,
      al = value.length;

    queryObjectOp = [];
    for (qi = 0; qi < al; qi++) {
      subQuery = {}
      subQuery[property] = {'$eq': value[qi]};
      queryObjectOp.push(subQuery);
    }
          
    return this.find({'$or':queryObjectOp}, firstOnly);
  }
```

Could you verify if that seems to work equally as well for you?  If so, if you want you can submit a p.r. otherwise I will look at doing that later today.

**Comment by Viatorus** [comment]
Great! :)
Let me please submit a pull request. ;)

But first I am going to (currently working on it) benchmark the "$i" vs. "$inex".

**Comment by Viatorus** [comment]
Still doing some tests. 

Here is a small result:
![dataset](https://cloud.githubusercontent.com/assets/3637911/20413001/a3c685c8-ad2a-11e6-901f-30c6bd0ab4a8.png)
The surface with the yellow plane is $in and the other is $inex.
Entries are the number of values in the db.
Values is the number of values in the query.

As you may can see, at around ~200 entries $inex gets better than $in. (for me with node.js). With chrome its around ~300 entries.

The number of values is less important than the number of entries.

**Comment by obeliskos** [comment]
Nice, very helpful to have visualization...  so 

- are 'values' the number of values passed to $in/$inex
- are 'entries' the number of docs in the collection, and 
- are ops the same as ops/s?   

There are so many possibly combinations in Loki which could be benchmarked that it would take so long that I have not bothered.  Would be nice at some point to come up with (relatively) simple algorithm to randomly generate and benchmark based on ranges of acceptable variations... would be great to get visualization of raw output in such a case.

**Comment by Viatorus** [comment]
Yes, your assumption are correct.

The current problem is, that the results seems to differ for each browser/device (150-600 entries). I want to do some more tests next week.

Yes, at some point deep benchmarking is a good thing for optimation. I personally like optimation problems most.

**Comment by Viatorus** [comment]
My pull request fixed the issue.

The [first idea](https://github.com/techfort/LokiJS/issues/508#issuecomment-260916134) transpose $in to a sequence of $or/$eq leads to heavy memory usage, because every value in the query of $in has to be copied.

My new attempt uses the standard calculateRange and "unpack" the $in array inside it. It is much more memory-saving and is faster! The old "$in" functionality of indexed search is only for ~50 entries faster.
