### ISSUE TITLE
Add load/serialize methods to Collection

### ISSUE THREAD

**Issue by techfort** [techfort/LokiJS#51]
Ideally the exposed Collection class should also have the ability to be serialized and loaded.

**Comment by simonvizzini** [comment]
+1 for this. No, actually, +1000 ;-)

We don't need persistence, so my plan is to just use collections and sync them with a db on a server. So being able to load a collection from plain JS objects/JSON string and "inflate" them with a specific prototype would be very important for our usecase.

**Comment by techfort** [comment]
I postponed this issue to 1.3.0: at the moment Collection has no encapsulated attributes, so - effectively - you can simply do a `JSON.stringify` to serialize, then do a `JSON.parse` and iterate the properties of the  parsed object copying them into an instance of collection. An example of this pattern is available here: https://gist.github.com/techfort/519dc03e2bf10251e2df
By 1.3.0 we'll add a utility method to automate this process.

**Comment by techfort** [comment]
I am going to close this as it really needs its own persistence adapter to work properly, and this might be a separate component.
