### ISSUE TITLE
Null-check validation for Collection.update happens to late

### ISSUE THREAD

**Issue by sondreb** [techfort/LokiJS#510]
The null-check validation that occurs inside Collection.prototype.update happens to late, after the result array have been read from. This throws an error something like "cannot update 0 of null".

This code happens before the check:

`oldInternal = arr[0]; // -internal- obj ref  
`

This happens after trying to read array:

`if (!arr) {
          throw new Error('Trying to update a document not in collection.');
        }`

I'm creating a PR for this issue, will link to it shortly.

**Comment by obeliskos** [comment]
thanks for fixing this! closing..
