### ISSUE TITLE
Implement full-text search

### ISSUE THREAD

**Issue by Viatorus** [techfort/LokiJS#513]
I would like to integrate a full-text search for lokijs using a record-level inverted index .

**Basic proceed:** 

_For the user:_
The user declares some properties at collection creation(`new Collection(...), addCollection(...)`)  to be available for full-text search (similar to indices).

The user can perform a full-text search with `find({"<property>": {"$text", "<text query>"}})`. 

_For the db:_
With each collection change (`insert(...)`, `update(...)`) the properties of each document enabled for full-text search get tokenized and an inverted index is created/updated.

If the user performs a query at an full-text search enabled property, the query string gets tokenized and the tokens are getting look up inside the inverted index to find the corresponding documents.

**Possible interface:**
Adding a new key (`fulltext`) to `options` -> `new Collection(name, options)`.

_fulltext:_
Array of fulltext_options

_fulltext_options:_

| Name | Type | Description |
| ------ | ---- | ---- |
| fields | array | array of fields to combine for full-text search  |
| alias _opt_ |  string | alias name to search over |
| tokenizer _opt_ | array | array of functions to tokenize the input/query strings |
| min_length _opt_ | int | minimum length of a token |
| max_length _opt_ | int | maximum length of a token |
| direction _opt_ | string | inverted index direction<br> Query text: <ul><li> "forward": from left to right</li><li>"backward:" from right to left</li><li>"both": in both directions</li></ul> |

_field:_

| Name | Type | Description |
| ------ | ---- | ---- |
| name | string | property name |
| boost _opt_ | number | increase rank of search results |

**Example usage**:
```javascript
options = {
  "fulltext": [{
      "fields": [{"name": "firstName"}, {"name": "surName"; "boost": 10}],
      "token_length": 2,
      "alias": "name",
    }]
};

var users = db.addCollection("users", options);
users.insert([
  {"firstName": "Carly", "surName": "Gross"},
  {"firstName": "Gregory", "surName": "Carlos"}
]);

users.find({"name":      {"$text", "Carl"})   // returns both users, Gregory Carl has higher rang.
users.find({"name":      {"$text", "Gr"})     // returns both users, Carly Gross has higher 
users.find({"surName": {"$text", "Gr"})   // returns only Carly Gross
users.find({"name":      {"$text", "Grev"}) // returns none
```

**Implementation:**

_Tokenizer:_

At the beginning, I just want to implement one tokenizer, which splits a text into words at whitespace and lowercase them.

Possible other tokenizer could be: 
- Split also on punctuation
- Language stemmer

_Inverted index:_

Is a chained js object. Each character is a key with a new object as value - containing the next character, et cetera. Each object contains matching document ids.
```javascript
// World
{"w": { "doc": [1],
   "o": { "doc": [1],
     "r": { "doc": [1],
       "l": { "doc": [1],
         "d": { "doc": [1]
}}}}}}
```

---
My proposal is not complete, so:
Let us discuss about the proposal, interface, names.... Nothing is carved in stone.

I want to start the first implementations next week.
- Any suggestions, wishes?
- Is it allowed or do you plan to use the new ECMAScript 6 language specification in lokijs?

---
Reference:
- [Inverted Index](https://en.wikipedia.org/wiki/Inverted_index)
- [Lunr](https://github.com/olivernn/lunr.js)
- [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-analysis.html)

**Comment by obeliskos** [comment]
Interesting... is this something that can be encapsulated into a class similar to how @techfort implemented 'UniqueIndex'?  

I have not run enough javascript filters to do full text search to have an idea of performance gains/cost...  but as long as all constructs are serializable without duplicating object references in serialized output, it sounds like this could be great addition.  

Currently our master 1.4x branch is ES5 only (at least for main lokijs.js source file) but we have already begun establishing and working on (well @Cortys has at least) a 2.0.0 branch which can fully utilitize ES6 and you are more than able to participate in that branch if you wish to do so.  

A few areas you may want to watch out for... when you update a document you have no way of knowing what the value was before unless we have collection cloning turned on which most people probably don't use.  Also, I imaging deletion of objects will require similar index maintenance to reduce the relevant word hit counts.

Sounds like something @techfort would like as well, maybe he or others can chime in if they have any preferences.

**Comment by techfort** [comment]
This is interesting indeed! Please do go ahead and experiment, I think it
would greatly improve the existing functionality and make Hel's gods happy.
The inverted index is an awesome idea which might even open up the path to
NLP features.

**Comment by Viatorus** [comment]
@obeliskos
Yes, it will be similar like UniqueIndex. Thank you for the hint. The performance gain will be huge for text search in long text properties. 
I will try to implement an acceptable memory usage which is serialisable.

I have to study the insert/update/remove/load process of lokijs to provide a user, memory and performance friendly solution.

I am going to use the ES6 because of maps and sets. So it could be a great feature for V2.0. :)

@techfort
Thank you, I will. Now I know why it is named Loki.  :D

**Comment by VladimirTechMan** [comment]
@Viatorus @obeliskos @techfort I am also supporting this request and the idea – indeed, we had other requests in the past asking for more advanced text search options with Loki. And I was considering that same functionality for my use cases as well (as having it could really boost the efficiency for me in some scenarios, if the implementation is done properly for the token-based text search). To note, I also remember that @alexandernst was interested in having similar functionality early this year (though he wanted to rely on Lunr.js and just provide a way to integrate it into Loki – see his issue #333).

@Viatorus Looking forward to your follow-ups on it. Depending on my actual load closer to Christmas / New Year time, I may be able to help you (at least, with code reviews – or even parts of the implementation), though cannot give a solid promise yet. But keep me in the loop anyways.

**Comment by alexandernst** [comment]
Hey guys!! Really long time no talk :(  (new job takes all my time, sadly... my GitHub stats are nullified).

Indeed, as @VladimirTechMan recalls, I wanted to join somehow Lunr.js and LokiJS. And IMHO this would be a better solution rather than reinventing the wheel from 0.

Basically, what I was going to do was duplicate all the data from Loki inside Lunr and let it do it's magic, then I'd used a deterministic id or some other sort of identifier and match the query results from Lunr to Loki documents.

**Comment by Viatorus** [comment]
Thank for for your participants - I really appreciate it. :)

Yes, at first I wanted also to integrate Lunr.js into LokiJS but now,
I am not quite sure if an own implementation for a cleaner integration
would not be better (as I already started...) - it is not a start from
zero because we can learn from others.

But nevertheless, I want to do it right, so lets see what lunr.js
really does and what we maybe can use or can make better. The
following breakdown should help me for brainstorming and
understanding what is going on.

---

_Create lunr:_

At Lunr's construction you define the fields (`name` and `boost`) and
the pipeline to convert text to tokens.

```javascript
var idx = lunr(function () {
    this.field('title', { boost: 10 })
    this.field('body')

    this.pipeline.remove(lunr.stopWordFilter) // Remove one default tokenizer.
    this.pipeline.remove(function(token) { /* custom tokenizer */);
})
```

_Pipeline:_

The pipeline is a chain of tokenizer functions which get called for
each token one by one. There are three default tokenizer:

* Trimmer to trim a token to bounded by words (e.g. +FooBar, -> FooBar)
* English language stemmer (e.g. nothing -> noth)
* English stop word filter (e.g. ignore tokens like not, an, or)

You can add/remove tokenizer functions by your own. The pipeline is
serializable (keeping the name of each function) - custom tokenizers
has to be saved/reload separatly for deserialization.

_Add document:_

An object as document is not fully stored inside lunr, only the tokens
and the reference document id property (here `id`).

```javascript
var doc = {
    "title": "Twelfth-Night",
    "body": "If music be the food of love, play on: Give me excess of it…",
    "author": "William Shakespeare",
    "id": 1
}
idx.add(doc)
```

1. Split each string into lowercase tokens between a separator (default is whitespace).
2. Pass each token through the tokenizer pipeline.
3. Add each token to a document specific SortedSet.
4. Add each token to a global SortedSet.
5. Calculate the [term-frequency][tf-idf] for each token.
6. Add each token to the TokenStore.

_TokenStore:_

The token store is a tree, starting with the first character of each token as property. Each property is an own branch containing the the next character of each token, after the previous character. The leaf (end of token) contains the real document reference. All other branches contain an empty docs property (why?).

```javascript
// World
{"docs": {},
 "w": { "docs": {},
   "o": { "docs": {},
     "r": { "docs": {},
       "l": { "docs": {},
         "d": { "docs": {1: {"ref": 1, "tf": 0.5}}
}}}}}}
```

idx.search("hello world")
```

[tf-idf]: https://en.wikipedia.org/wiki/Tf%E2%80%93idf

**Comment by techfort** [comment]
@Viatorus very interesting post - thank you very much for taking the time to work on it. 
I believe you're looking for this line with regards to your serialization question: 
https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L973
This allows to specify properties that are not to be serialized to avoid circular references.

PS by the way i have a library https://github.com/techfort/mimir that does BOW and TF-IDF, feel free to pillage if it saves you some work.

**Comment by Viatorus** [comment]
@techfort Thank you. I had not yet look closely at Lokijs serialization. But its all there. :)

For the sake of completeness, I analyzed lunrs id-idf/score model to understand how it works. The code below is not the exact implementation. I smarten it up .

---

### Add document

```javascript
fields = [{"name": "user", "boost": 10}, {"name": "desc", "boost": 2}];
newDoc = {"user": "Carl", "desc": "Well done Carl, well", "id" = 1};

fieldTokens = {"user": ["carl"], "desc": ["well", "done", "carl"] };
documentStore[newDoc.id] = ["carl", "well", "done"];

for (let token of documentStore[newDoc.id])  {
    let tf = 0;
    for (let field of fields {
        let tokenCount = 0;
        for (let fieldToken of fieldTokens[field.name]) {
            if (fieldToken == token) {
                tokenCount++;
            }
        }
        tf += tokenCount / fieldLength * fieldBoost;
    }
    // store token with docRef and tf inside tokenStore
    // ... 

    // *1
    let documentFreuqncy = tokenStore.count(token);
    let idf = 1 + log_e(documentStore.length / documentFrequency)
    idfMap.set(token, idf);

    // Find position of similarToken in corpusToken. *2
    let pos = corpusTokens.indexOf(similarToken);
    documentVectors[newDoc.id].insert(pos, tf * idf * similarityBoost)
}

```
*1 Lazy evaluation, cached.
*2 Lazy evaluation, not cached.
Lunr calculates these values if required at search, for simplification I mention it here.

### Search query

```javascript
query = "Wel Si, wel";
queryTokens = ["wel", "si"];

// fields.length = 2 <- user and desc
// fields.boost = 12 <- users 10 + desc 2
let tf = 1 / queries.length * fields.length * fields.boost;

for (let queryToken of queryTokens) {

    // wel -> well
    // si -> sir
    for (let similarToken of tokenStore.similar(queryToken)) {
        let simularityBoost = 1;
        if (similarToken !== queryToken) {
          let diff = Math.max(3, similarToken.length - queryToken.length);
          similarityBoost = 1 / Math.log(diff);
        }        
        // Find position of similarToken in corpusToken.
        let pos = corpusTokens.indexOf(similarToken);
        let idf = idfMap.get(similarToken);
        queryVector.insert(pos, tf * idf * similarityBoost);
        
        // Find all matching documents.
        docRefs.insert(tokenStore.get(similarToken).docRefs);
    }
}

let score = [];
for (let docRef of docRefs) {
    // Calculate cosine similarity 
    score[docRef] = queryVector.dot(documentVectors[docRef]) / (queryVector.magnitude() * documentVectors[docRef].magnitude());
}

return score;
```

---

I think there is also a big potential to create a data model which work with [tf-idf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf), [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) and [naive Bayes classifier](https://en.wikipedia.org/wiki/Naive_Bayes_classifier).

Okay, now I am going to think about an own implementation concept. See you. ;)

**Comment by Viatorus** [comment]
Hey guys,
I have got a first implementation on an inverted index tree. But I still spend a lot of time to analyze different scoring  models. 

Some question for me are at the moment:
- Split index for different fields/properties?
- How to handle not exact matches for scoring?

Some new inputs come from:
- [Lucence BM25](https://lucene.apache.org/core/6_3_0/core/org/apache/lucene/search/similarities/BM25Similarity.html)
- [Lucence TFIDF](https://lucene.apache.org/core/6_3_0/core/org/apache/lucene/search/similarities/TFIDFSimilarity.html)
- [Elasticlunr](https://github.com/weixsong/elasticlunr.js)
- [Lunr V2](https://github.com/olivernn/lunr.js/tree/2.x)

**Comment by obeliskos** [comment]
Nice, hopefully others can provide suggestions about implementation I am unfamiliar with those algorithms / scoring models. 

Do you expect to persist index or rebuild on load?   I wonder what cost/benefit of that is... I know for unique indices we rebuild those on startup but that is mainly the simplest way to remove duplicate document references.  Your fts would have more value in saving meta but worth examining rebuild costs if nominal.

Do you expect algorithms to prefer many documents with small text fields and/or fewer documents with large text fields? Or can it adapt to both?  I mean in theory (as example) in 1 gb heap space we could retrieve numerous txt ebooks from online repository and run searches against them.  Those text properties could be a meg or two text.  

I guess you have probably already started thinking about benchmarking and saved database size, so i'm sure you will evaluate an optimal solution for scale.

**Comment by Viatorus** [comment]
I am not absolut sure about how to persist the index. It depends - maybe the user have to decide.

If the db contains less data, the index can be recalculate fast, for more data it needs more time. The relative memory overhead would be the similar but for absolute: 1 GB of data needs more storage memory than 1 MB. This should be sure.

Similar applies to removing a document from the inverted index. Keeping track of a token from a document inside the token tree needs some additional memory. _Elasticlunr_  just tokenize the document again and then remove the founded token in the tree - clever but it needs more calculation time.
 

Yes, more documents needs more memory/calculation - this should be clear. But also, you gain a faster query for such a big database. With the help of tokens stemmer you can control the inverted index to remove words like _and, an in with not..._ 

Yes, I am looking for an optimal implementation. Apache lucene is a very good reference for this. :)

**Comment by Viatorus** [comment]
Hey there. :)

Some updates on my side.

---

What I have done so far:
- implementation of a serializable inverted index tree for different document properties
  - add/update/remove docs without big overhead
  - deserialization needs some reconstruction because of object references
- implementation of BM25 and TF-IDF similarity
  - Both measure the relevance of a token inside a document but they work a bit [different](http://opensourceconnections.com/blog/2015/10/16/bm25-the-next-generation-of-lucene-relevation/)
  - BM25 is faster and has better scoring results towards TF-IDF (simple summarized)
  - For me the biggest difference: BM25 does not consider non matching query tokens
- implementation of a fuzzy-search with [damerau-levenshtein](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance)
  - My extended implementation from [kigiri](https://gist.github.com/andrei-m/982927#gistcomment-1931258) seems to be the fastest out there for js
  - Can still be optimized to use already calculated rows from similar query tokens
- implementation of a wildcard search
  - you can search for _hel?o w?rld_
  - still have no efficiency way to allow the non prefix/suffix star operator: _learn*g_

For me the most relevant TODOS are:
- Combining wildcard, fuzzy search and BM25/TF-IDF similarity to one scoring model
   - theory is known - implementation is needed ;)
- Integrate inverted index into lokijs
   - Define the new filter query / query parser  (if possible like [Elastic](https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html))
   - variable/function naming
- Code cleanup and documentation

Other TODOS:
- Add a token pipeline (trimmer, stemmer, etc.) with [language support (eng, rus, de...)](https://github.com/MihaiValentin/lunr-languages)
   - lunr has this - but I don't really like the implementation
   - elasticlunr writes wrapper to use lunr language support - which is similar ugly for me - sorry
- Test/Benchmark

---

Currently, there is no up to date working branch - I want to push it soon so you could/can cast an eye at it. ;)

**Comment by techfort** [comment]
@Viatorus needless to say this is outstanding work and something i will very much look forward to play with. One thing I will ask you is to document this thoroughly as users will find this functionality extremely helpful so we want to be absolutely clear on its usage. Thanks a lot again.

**Comment by Viatorus** [comment]
Heyho guys, some update:

I implemented a query builder which can be used to build a (complex) full text search query. While implementing I defined the structure of how a query could be structured.

The structure is similar to elasticsearch but on some points more restricted, a little bit bloated but more precised because I don't want to parse and verify the query over and over again.

The next step would be to interpret the query, do the index search, score and return the resulting documents. :)

---

Useless example:

```javascript
var query = new QueryBuilder()
 .bool().boost(2)
  .startFilter().boost(3)
      .wildcard("123", "123")
      .term("how", "are").boost(5)
  .endFilter()
  .startMust().boost(11)
    .match("123", "123")
    .term("with", "todo").boost(5)
  .endMust()
  .startNot()
    .bool()
      .startNot()
        .terms("name", ["carl", "harry", "unknown"])
        .matchPhrasePrefix("123", "123").boost(5)
        .matchPhrase("with", "todo other").slop(5).analyzer("wow")
      .endNot()
  .endNot()
.build();

// Result in:
{
  "query": {
    "type": "bool",
    "boost": 2,
    "filter": {
      "type": "array",
      "value": [
        {
          "type": "wildcard",
          "field": "123",
          "value": "123"
        },
        {
          "type": "term",
          "field": "how",
          "value": "are",
          "boost": 5
        }
      ],
      "boost": 3
    },
    "must": {
      "type": "array",
      "value": [
        {
          "type": "match",
          "field": "123",
          "query": "123"
        },
        {
          "type": "term",
          "field": "with",
          "value": "todo",
          "boost": 5
        }
      ],
      "boost": 11
    },
    "not": {
      "type": "array",
      "value": [
        {
          "type": "bool",
          "not": {
            "type": "array",
            "value": [
              {
                "type": "term",
                "field": "name",
                "value": [
                  "carl",
                  "harry",
                  "unknown"
                ]
              },
              {
                "type": "match_phrase_prefix",
                "field": "123",
                "query": "123",
                "boost": 5
              },
              {
                "type": "match_phrase",
                "field": "with",
                "query": "todo other",
                "slop": 5,
                "analyzer": "wow"
              }
            ]
          }
        }
      ]
    }
  }
}
```

**Comment by Viatorus** [comment]
Hello guys, some updates:

Now there is a working scored search for most query types besides token matches:
- Bool, ConstantScore, Term, Terms, Fuzzy, Wildcard, MatchAll

The supported scoring model is BM25 only, which is the current state of art. I dropped TF-IDF similarity because of simplification. If it is really needed, I will implement it but it is mostly out dated by the other libraries (elasticsearch/lucene).

My next steps are:
- Scoring with tokens (queries that use trimmer/stemmers).
- Better documentation
- LokiJS integration

**Comment by s-a** [comment]
@Viatorus any news for LokiJS integration?

**Comment by Viatorus** [comment]
@s-a Good news I have. =)

Check out [LokiJS2](https://github.com/LokiJS-Forge/LokiJS2). There is a full-text search similar to elasticsearch and lucene. It's still in beta but mostly because of the missing documentation - I am working on this. ;)

**Comment by zipavlin** [comment]
@Viatorus, I apologize for commenting in closed thread, but this seems like an appropriate place. If I understand correctly this (fulltext search) is implemented in lokidb as a plugin? How would one go about using it? I get that documentation is not really written yet - but it seems end usage of lokidb is identical to lokijs (albait a bit faster in my quick tests).

**Comment by Viatorus** [comment]
@zipavlin 
Yes, LokiDB has now plugins and the full-text search is one of them.

See https://github.com/LokiJS-Forge/LokiDB/blob/master/packages/full-text-search/spec/generic/full_text_search.spec.ts how to use the full-text search with LokiDB.

Yes, the docs are not ready now, but there is a branch at LokiDB#docs with some more information.
See https://github.com/LokiJS-Forge/LokiDB/blob/docs/docs/full-text-search.md

**Comment by zipavlin** [comment]
@Viatorus thanks a lot! I tried it and it seems to work great :)

**Comment by tonyxiao** [comment]
@Viatorus is it possible to search across all fields? Or is it necessary to always specify a field?

**Comment by Viatorus** [comment]
You have to specify the field but you can search multiple fields at once.

**Comment by Bug-Reaper** [comment]
Sorry to bump this old thread y'all. LokiDB appears to no longer be actively maintained. Did regular LokiJS ever get full-text-search? I know there's regex support but I'd assume that's a slower text comparison with no indexing?
