### ISSUE TITLE
Organize docs per platform

### ISSUE THREAD

**Issue by webmutation** [techfort/LokiJS#515]
Hi,

I really like the idea of LokiJS, however I am having a bit of problem finding documentation specific to node. The docs are filled with multiple setups, use in browser, ionic, nativeScript. It takes some time to scan everything and find answers. I have it working but it took me much more effort (i don't particularly want to know about all the persistence adapters, just the one for node in my case) to go over the docs than on NeDB for instance. Organizing the documentation per platform could be a good step toward more adoption. Thanks for all the effort in this project.

**Comment by obeliskos** [comment]
Sounds like a good idea for the 'Persistence and Adapters' page... everything else should be the same across all environments.  I may not be entirely done with changes to persistence so I may wait a week to overhaul wiki.
