### ISSUE TITLE
Does autoload work? 

### ISSUE THREAD

**Issue by webmutation** [techfort/LokiJS#517]
So I loaded some date in a collection and now I am trying to simply sort the data

```
//initialize to null if there is no existing file
let mycollection = null;

//Create database
let db = new loki('mycollection.json',
    {
        autoload: true,
        autoloadCallback: loadHandler,
        autosave: true,
        autosaveInterval: 10000
    });

//load Database from file
function loadHandler() {
    // if database did not exist it will be empty so I will intitialize here
    mycollection = db.getCollection('mycollection');
    if (mycollection === null) {
        mycollection = db.addCollection('mycollection', {
            unique: ['id']
        });
    }
}

function sortByDate(){
	let latestFive = mycollection.chain()
        .simplesort('timestamp', true)
        .limit(5)
        .data();

    console.log(latestFive);
}

sortByDate();
```
I thought that the autoload was guaranteed to load the database, but if I call this function it has no data loaded the value is still null. 

`TypeError: Cannot read property 'chain' of null`

Do I manually have to load the database whenever I want to use it? What is the point of autoload... am I missing something here?

The only way to use that I can see is to load the database using

`loadDatabase(options, sortByDate)`

**Comment by obeliskos** [comment]
Well the loadHandler callback is invoked asynchronously so you need to wait until that gets invoked before querying.  Your sortByDate will be called before loadHandler since you have not yielded thread and possibly also because async io has not yet completed.

Maybe for logical example you could rename sortByDate function to 'init' and invoke that at end of loadHandler()

**Comment by webmutation** [comment]
Thank you for your reply. I see, I am used to having the database being available as soon as i try to do something with it, i have changed the code to run after the database is loaded only :) 

Looks like a great improvement for 2.0.0 is there a release date for it? what promises library are you going to use?

**Comment by obeliskos** [comment]
No release date for 2.0.0 but soon that branch will become our active branch and existing 1.4 branch will be maintenance.  Probably will start shifting around January not sure when 'release' will be.  By default 2.0.0 will rely on your environment supporting es6 promises as loki is a 'dependency free runtime'... not sure how easily a babelified path can be provided in toolchain... maybe others have ideas on this as this would be only a 'dev dependency'?

**Comment by webmutation** [comment]
Is there a way to store the data in a sorted way by default? Or do I have to sort and persist the sorted array?

Thanks!

**Comment by obeliskos** [comment]
sorry i missed this, usually binary indices or dynamic view alleviates need to store data sorted
