### ISSUE TITLE
Lokijs “Changes” are not being persisted on load database

### ISSUE THREAD

**Issue by stack-amehta** [techfort/LokiJS#519]
LokiJs has a very useful `changesAPI` that returns dirty data (so we can sync this with server when needed & flush dirty data after syncing)
 
**ISSUE:**
*When a persisted Database is loaded* (*having dirty data*), the changesAPI `getChanges()` returns empty object, although *dirty-data* is persisted.    

PS:

After loadDatabase()

 - Loki Object has `isDirty` property (for database) as true.
 - In collection, 
   - New Data(dirty) is present with `isDirty` as true.
   - `changes` property is empty.

**Comment by stack-amehta** [comment]
Thanks for a quick reply @obeliskos 

I will try this out & update you.

Meanwhile i have found a workaround 
--> By maintaining a separate collection for dirty changes on logout, 
and i read this new collection to populate the `change` object in collection. It seems to work for me. 

Please let me know your thoughts / any possible issues with this. 

Thanks again (Y)

**Comment by obeliskos** [comment]
i think this was fixed in ccd919b so i'll close.  reopen if still an issue
