### ISSUE TITLE
browserify support

### ISSUE THREAD

**Issue by RnbWd** [techfort/LokiJS#52]
Using browserify I'm getting this error message: 

```
 Uncaught TypeError: undefined is not a functionlokijs.js:738 
```

It's not properly detecting ENV when commonjs modules are used in the browser. Easy fix would be to change line 226:

```
81:     var fs = (typeof exports === 'object') ? require('fs') : false;

226:      if (fs) {
227:        return 'NODEJS';
228:      }
```

```
226:      if (typeof window === 'undefined') {
227:        return 'NODEJS';
228:      }
```

Also need to configure browserify to ignoring the 'fs' module.  I can submit a pull request for line 226.

**Comment by xbenjii** [comment]
This breaks node-webkit functionality, since both `exports` and `window` are defined. :disappointed:

**Comment by techfort** [comment]
Yeah - automatic env detection is never 100 % reliable. I'm thinking of changing the setting of the ENV property from `this.ENV = getENV();` to `this.ENV = options ? (options.env || 'NODEJS') : getENV();`.
