### ISSUE TITLE
Web worker support

### ISSUE THREAD

**Issue by Wyzix33** [techfort/LokiJS#520]
Hi, is there any version of LokiJs that can run inside a web Worker? I get 

`Uncaught ReferenceError: require is not defined`

on 

`var db = new loki('example.db');` 

at 

````
 /**
     * A loki persistence adapter which persists using node fs module
     * @constructor LokiFsAdapter
     */
    function LokiFsAdapter() {
      this.fs = require('fs');
    }

````
if i remove all the adapter stuff it's working, so maybe some checks for 

`if (typeof require === 'function') ` 

might solve it ... 
I only want to use LokiJs in Browser and i don't need persistence on disk or node, i send updates/inserts/delete to server and update Loki for faster autocomplete/reports generation and i will like to run it inside a web Worker because some query's are 10-20 seconds  long (millions of rows Colections ... ) and UI get unresponsive...

Thanks and great work!

**Comment by thrownblown** [comment]
I use loki in a web worker using the indexDB adapter no problems.  I even made a contribution to get it to work too!
https://github.com/techfort/LokiJS/issues/408

`LokiFsAdapter `should only be called in a node environment. maybe for some reason `getENV` is deafaulting to a NODEJS env?

How are you accessing loki in the web worker?

**Comment by obeliskos** [comment]
Thanks @thrownblown I think you're correct.  If you create loki without an adapter, loki attempts to detect environment.  It checks for window and if that global does not exist, it assumes node. Not sure the best environment detection for main loki, we could test for (window || indexedDB || typeof importScripts === 'function')

If you don't need persistence at all you should be able to override env detection with : 
```javascript
var db = new loki('example.db', { env: 'BROWSER' });
```

**Comment by Wyzix33** [comment]
Thanks @obeliskos that works, i missed that option ,,, Now everything works.

**Comment by Wyzix33** [comment]
Hi @thrownblown , did you find any solution on transferring larger results from inside the worker, I am getting 19 seconds+ on 30k+ results, and for converting all the results to  ArrayBuffer and back it seems a little too complicated... I will try to work with smaller results and many requests to see how it's going or get Loki out in the main thread

Thanks
