### ISSUE TITLE
Accessing collection by custom id

### ISSUE THREAD

**Issue by Wyzix33** [techfort/LokiJS#521]
Hi, i have a collection like this:

```
var o = [
{id:100,name:"Joe"},
{id:102,name:"Max"}
...
]
```
and i'm getting a list of id-s from my server like this:

`[100,102, ...]`
and in order for me to display all the names in the array i have to do this:

var db = new loki('example.db', {env: 'BROWSER'});
var users = db.addCollection('users');
users.insert(o); //o is my array with all the names

inside my loop i have to search each id to find a name:

var result = users.find({id:100});

and display the name `result[0].name`

is there a way to access directly the name by id without using find? something like `users[100].name` to get Joe

or if i do this `users.findOne({id:100}).name` do i have to set 
```
{
    unique: ['id'],
    indices: ['id']
}
```
 options on Collection creation? or if a field is unique is indice too?

Thanks

**Comment by obeliskos** [comment]
I would say you would use only a unique index to do it like this : 

```javascript
var db = new loki('example.db', {env: 'BROWSER'});
var users = db.addCollection('users', { unique: ['id'] });
users.insert(o); //o is my array with all the names

var result = users.by('id', 100);
```

As a general rule I would say that if your adding a 'unique' index, you probably don't want to add that same column to the (binary index) 'indices'.  The exception being that you not only do single object lookups but also frequently query it with range ops like : 

```javascript
users.find({ id: { $between: [100, 200] } });
```

**Comment by Wyzix33** [comment]
Hi, 
i just found [https://github.com/techfort/LokiJS/wiki/Indexing-and-Query-Performance](url) with lots of useful info on this, 

Thank you for your help.
