### ISSUE TITLE
what are you guys planning for a persistent/low latency connection?

### ISSUE THREAD

**Issue by victusfate** [techfort/LokiJS#530]
I have been using a custom db with web sockets, but I need to build a pool, using jwt auth, reconnections, load balancing to be able to support other server access. Since remote access is on your project plan, curious what you've come up with?

Is there a higher level framework for "service layer" network access? Stuff I've looked at pure tcp sockets, web sockets (ws, socket.io, uwebsockets) to potentially allow client side access down the road. Feels like I'm reinventing answers to solved problems with socket pools, replenishment.

**Comment by techfort** [comment]
@victusfate Siemens use LokiJS internally as part of a home-automation product, and they use MQTT to sync devices, not sure if this answers your question.

**Comment by victusfate** [comment]
It helps thanks. 
Also looked at redis pubsub and kue.js

Thought there were roadmap issues for LokiJS to get a socket like remote connector, may have misread some docs
