### ISSUE TITLE
Ionic 2 Database Provider

### ISSUE THREAD

**Issue by BradyLiles** [techfort/LokiJS#531]
I just wanted to share the way I am currently instantiating LokiJS for my Ionic2 Application.
I feel a bit dirty the way I am getting the IndexedDbAdapter but I feel better about it then doing a decare var require and/or including scripts in my index.html. If anyone has any suggestions let me know! (:

**app.component.ts**
 ```
platform.ready().then( () => {
      console.debug( "Platform Ready!" );
      StatusBar.hide();

      databaseProvider.initDatabase().subscribe( () => {
```

**database.provider.ts**
```
import {Injectable} from "@angular/core";
import * as loki from "lokijs";
import {Platform} from "ionic-angular";
import {Observable} from "rxjs";

@Injectable()
export class DatabaseProvider {

  public db: any;

  constructor( private platform: Platform ) {
  }

  public initDatabase() {

    return Observable.create(observer => {

      let indexDBAdapter:any = new loki("").getIndexedAdapter();
      var idbAdapter = new indexDBAdapter('myDatabase.db');

      this.db = new loki("myDatabase.db", {
        adapter: idbAdapter,
        autosave: true
      } );

      this.db.loadDatabase( "dbo.myDatabase", (result) => {
        console.log("the result", result);
        observer.next();
        observer.complete();
      }, (err) => {
        observer.error(err);
        observer.complete();
      });
    });

  }
}
```

**OtherProvider.ts**
```
import {Injectable} from "@angular/core";
import {Observable} from "rxjs";
import {DatabaseProvider} from "../../database/database.provider";

@Injectable()
export class PeopleProvider{

  private peopleProviderDataCache: LokiCollection<People>;

  constructor( private databaseProvider: DatabaseProvider ) {
    this.peopleProviderDataCache = databaseProvider.db.addCollection( 'People' );
  }

  getPeople( top?: number, skip?: number ): Observable<People> { ....
   
```

**Comment by obeliskos** [comment]
We added that function as an experiment for browserify and no one verified if it even worked for that but in theory we could probably override the 'env' or another [loki constructor](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html#Loki) option to call that function and instantiate the adapter behind the scenes.   Another option is to just roll the indexed adapter into lokijs.

For upcoming 2.0 version [LokiJS2 project](https://github.com/LokiJS-Forge/LokiJS2) we have more versatility if you'd like to help shape that version.

**Comment by ChristopherTotty** [comment]
Have you considered using a custom adapter that implements Ionic Storage?  This is great because if running on a device it will use SQLite for persistence but fallback to IndexedDB when running in browser.

Something like this:

IonicStorageDatabaseAdapter.ts
```
import { Injectable } from '@angular/core';
import { Storage } from '@ionic/storage';

@Injectable()
export class IonicStorageDatabaseAdapter {

    constructor(private storage: Storage) {
    }
    
    public loadDatabase(dbname:any, callback:any) {
      this.storage.get('loki-db-'+ dbname).then((val) => {
          callback(val);
      }).catch((error) => {
          callback(error);
      });
    }

    public saveDatabase(dbname:any, dbstring:any, callback:any) {
        this.storage.set('loki-db-' + dbname, dbstring).then((val) => {
          callback(null);
      }).catch((error) => {
          callback(error);
      });
    }
}
```

Database.ts
```
import { Injectable } from '@angular/core';
import { IonicStorageDatabaseAdapter } from './IonicStorageDatabaseAdapter';
import * as loki from "lokijs";

@Injectable()
export class Database {
    private db: any;
    constructor(private ionicStorageDatabaseAdapter: IonicStorageDatabaseAdapter) {
        this.db = new loki('db-name', {adapter: ionicStorageDatabaseAdapter});
    }
}
```

**Comment by obeliskos** [comment]
Sure, that would be great...  care to submit an es6 version p.r. of IonicStorageDatabaseAdapter?

**Comment by ChristopherTotty** [comment]
Sorry, I was meaning that as a suggestion for Brady.

I'm only learning Ionic 2, myself, but I'm not sure if it would be possible to add an implementation to Loki that could work with the way that the Ionic Storage provider is being injected by angular/core at run-time.

I will look more into how the angular providers work and see how to do the dependency injection without TypeScript.

**Comment by BradyLiles** [comment]
@ChristopherTotty That's an interesting concept... But I believe IndexedDB is completely persistent just like  Ionic Storage. I forget exactly what Ionic Storage does other than integrate with the native SQLite. But what is above should work completely fine and be persistent as well.
I also think that indexedDB has better performance than SQLite in certain scenarios... (Correct me if I'm wrong on that.)

**Comment by ChristopherTotty** [comment]
Sure, IndexedDB would persist just as well.  I can't speak to the potential performance advantages over SQLite, but I do know that SQLite has the advantage of storage size.  The size limitation for IndexedDB is different for each browser, though generally < 100 MB.  SQLite should only be limited by the device's storage space.

**Comment by mobidev111** [comment]
SQLite is a good working common base when targeting apple, google & microsoft platforms - IndexedDB is buggy on iOS 9 and not very much supported on Microsoft Windows/Edge - see http://caniuse.com/#feat=indexeddb, footnote 2 ("Partial support in Safari & iOS 8 & 9 refers to seriously buggy behavior as well as complete lack of support in WebViews.")

**Comment by ronaldaraujo** [comment]
@ChristopherTotty I tried to implement your code but got the following error. Can you help me?
![image](https://user-images.githubusercontent.com/1413455/36105310-0c5da2de-0ff3-11e8-94d4-61f88135593a.png)

**Comment by ChristopherTotty** [comment]
@ronaldaraujo I would need to see some code, but it looks to me like when you passed in the adapter to loki it had not been properly instantiated.  This should be done for you if you are using it as I did in the example above, which injects an instatiated copy of the class into the constructor.

**Comment by ronaldaraujo** [comment]
@ChristopherTotty what I did was put all the code in my home.ts file...

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { GasPage } from '../gas/gas';
import { SettingsPage } from '../settings/settings';
import { Storage } from '@ionic/storage';
import * as loki from "lokijs";

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  private gas: any;
  private settings: any;
  private db: any;
  private robots: any;

  constructor(public navCtrl: NavController) {
    this.gas = GasPage;
    this.settings = SettingsPage;
    this.db = new loki('db-name', {
      adapter: IonicStorageDatabaseAdapter,
      autoload: true,
      autoloadCallback: this.databaseInitialize,
      autosave: true,
      autosaveInterval: 1000,

    });
  }

  databaseInitialize() {
    if (this.db.getCollection("robots") === null) {
      this.robots = this.db.addCollection("robots");
    }
  }

  createRobots() {
    this.robots.insert({ name: 'Ronald', idade: 27 });
  }

  findRobots() {
    console.log(this.robots.find());
  }

}

export class IonicStorageDatabaseAdapter {

  constructor(private storage: Storage) {
  }

  public loadDatabase(dbname: any, callback: any) {
    this.storage.get('loki-db-' + dbname).then((val) => {
      callback(val);
    }).catch((error) => {
      callback(error);
    });
  }

  public saveDatabase(dbname: any, dbstring: any, callback: any) {
    this.storage.set('loki-db-' + dbname, dbstring).then((val) => {
      callback(null);
    }).catch((error) => {
      callback(error);
    });
  }
}

```
I really do not understand what's wrong.

**Comment by ChristopherTotty** [comment]
@ronaldaraujo Please take another look at my Database.ts above and notice how the IonicStorageDatabaseAdapter is being injected as a Service/Provider into the Database Provider.  You will need to setup and use something similar to Database instead of instantiating the loki db directly from a page.  If you do not, then you will only have access to the data from that single page and not from your entire application.

Please check out this tutorial for more info on this process.
https://www.joshmorony.com/an-in-depth-explanation-of-providers-in-ionic-2/
