### ISSUE TITLE
LokiJS collection has `0` documents

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#532]
I have a collection on which I do

```
var itemIDs = [1,5,8,10];
collection.removeWhere(function(o) { return itemIDs.indexOf(o.itemID) < 0; });
```

which errors out with

```
TypeError: can't convert null to object
```

I've traced this back to the following sequence of events:

1. `removeWhere` sees that it's passed a functio, calls `collection.data.filter(query)` and runs `this.remove` on the result
2. `this.remove` sees it's passed an array and calls `this.remove` on each of the elements

but since for some reason I haven't found yet, `collection.data.filter(query)` returns the array below, at some point `this.remove` is called on `0`, which will cause `this.remove` to call `doc = this.get(0)`, which yields a null (because it doesn't exist). As `typeof null` is `object`, it passes to the call to 

```
if (!hasOwnProperty.call(doc, '$loki')) {
        throw new Error('Object is not a document stored in the collection');
      }
```

which then errors out with the TypeError.

Any idea what I could have done to trigger this? I've looked at the database and there's not something obvious (to me) in there which would cause `filter` to return numbers instead of documents.

-----

```
[
  {
    "version": 0,
    "itemType": "journalArticle",
    "tags": [
      "Barad",
      "new-materialism"
    ],
    "collections": [
      
    ],
    "relations": {
      
    },
    "volume": "10",
    "pages": "87-126",
    "publicationTitle": "DIFFERENCES-BLOOMINGTON-",
    "ISSN": "1040-7391",
    "date": "1998",
    "journalAbbreviation": "DIFFERENCES-BLOOMINGTON-",
    "title": "Getting real: Technoscientific practices and the materialization of reality",
    "creators": [
      {
        "creatorType": "author",
        "lastName": "Barad",
        "firstName": "Karen"
      }
    ],
    "dateAdded": "2015-06-05T12:18:14Z",
    "dateModified": "2015-06-05T12:18:14Z",
    "uri": "http:\/\/zotero.org\/users\/2295317\/items\/CXP8JSAN",
    "attachments": [
      {
        "version": 0,
        "itemType": "attachment",
        "tags": [
          
        ],
        "collections": [
          
        ],
        "relations": {
          
        },
        "title": "Barad - 1998 - Getting real Technoscientific practices and the m.pdf",
        "parentItem": "CXP8JSAN",
        "linkMode": "imported_file",
        "contentType": "application\/pdf",
        "charset": "",
        "path": "storage:Barad - 1998 - Getting real Technoscientific practices and the m.pdf",
        "dateAdded": "2015-06-05T12:14:40Z",
        "dateModified": "2015-06-05T13:09:27Z",
        "uri": "http:\/\/zotero.org\/users\/2295317\/items\/HRT2KG9N",
        "localPath": "\/Users\/olaf\/Library\/Application Support\/Zotero\/Profiles\/k3xi5rnf.default\/zotero\/storage\/HRT2KG9N\/Barad - 1998 - Getting real Technoscientific practices and the m.pdf",
        "itemID": 396,
        "meta": {
          "revision": 0,
          "created": 1484374061992,
          "version": 0
        },
        "$loki": 5161
      }
    ],
    "notes": [
      
    ],
    "itemID": 838,
    "attachmentIDs": [
      396
    ],
    "meta": {
      "revision": 0,
      "created": 1484374061989,
      "version": 0
    },
    "$loki": 5160
  },
  {
    "version": 0,
    "itemType": "book",
    "tags": [
      "Environmentalism",
      "Human ecology",
      "new-materialism",
      "Philosophy",
      "Political aspects"
    ],
    "collections": [
      
    ],
    "relations": {
      
    },
    "place": "Durham",
    "publisher": "Duke University Press",
    "ISBN": "978-0-8223-4619-7 978-0-8223-4633-3",
    "date": "2010",
    "callNumber": "GF21 .B465 2010",
    "libraryCatalog": "Library of Congress ISBN",
    "title": "Vibrant matter: a political ecology of things",
    "shortTitle": "Vibrant matter",
    "numPages": "176",
    "creators": [
      {
        "creatorType": "author",
        "lastName": "Bennett",
        "firstName": "Jane"
      }
    ],
    "dateAdded": "2015-06-05T12:21:10Z",
    "dateModified": "2015-06-05T12:21:10Z",
    "uri": "http:\/\/zotero.org\/users\/2295317\/items\/JN46QAAZ",
    "attachments": [
      {
        "version": 0,
        "itemType": "attachment",
        "tags": [
          
        ],
        "collections": [
          
        ],
        "relations": {
          
        },
        "title": "Vibrant Matter_ A Political Ecology of Thi - Jane Bennett.epub",
        "parentItem": "JN46QAAZ",
        "linkMode": "imported_file",
        "contentType": "application\/octet-stream",
        "charset": "",
        "path": "storage:Vibrant Matter_ A Political Ecology of Thi - Jane Bennett.epub",
        "dateAdded": "2015-06-05T12:20:42Z",
        "dateModified": "2015-06-05T12:21:16Z",
        "uri": "http:\/\/zotero.org\/users\/2295317\/items\/GQPSGJE9",
        "localPath": "\/Users\/olaf\/Library\/Application Support\/Zotero\/Profiles\/k3xi5rnf.default\/zotero\/storage\/GQPSGJE9\/Vibrant Matter_ A Political Ecology of Thi - Jane Bennett.epub",
        "itemID": 402,
        "meta": {
          "revision": 0,
          "created": 1484374062010,
          "version": 0
        },
        "$loki": 5163
      }
    ],
    "notes": [
      {
        "key": "SSJMDB5Z",
        "version": 0,
        "itemType": "note",
        "tags": [
          
        ],
        "collections": [
          
        ],
        "relations": {
          
        },
        "parentItem": "JN46QAAZ",
        "note": "The force of things -- The agency of assemblages -- Edible matter -- A life of metal -- Neither vitalism nor mechanism -- Stem cells and the culture of life -- Political ecologies -- Vitality and self-interest",
        "dateAdded": "2015-06-05T12:21:10Z",
        "dateModified": "2015-06-05T12:21:10Z"
      }
    ],
    "itemID": 840,
    "attachmentIDs": [
      402
    ],
    "meta": {
      "revision": 0,
      "created": 1484374062007,
      "version": 0
    },
    "$loki": 5162
  },
  {
    "version": 0,
    "itemType": "journalArticle",
    "tags": [
      
    ],
    "collections": [
      
    ],
    "relations": {
      
    },
    "url": "https:\/\/journals.ku.edu\/index.php\/jdtc\/article\/viewArticle\/1648",
    "volume": "1",
    "issue": "2",
    "pages": "3\u00e2\u20ac\u201c16",
    "publicationTitle": "Journal of Dramatic Theory and Criticism",
    "date": "1987",
    "accessDate": "2015-06-05T12:41:58Z",
    "libraryCatalog": "Google Scholar",
    "title": "Aristotle's Poetics and Aristotle's Nature",
    "creators": [
      {
        "creatorType": "author",
        "lastName": "Schmitt",
        "firstName": "Natalie Crohn"
      }
    ],
    "dateAdded": "2015-06-05T12:41:58Z",
    "dateModified": "2015-06-05T12:41:58Z",
    "uri": "http:\/\/zotero.org\/users\/2295317\/items\/UKMDDQCQ",
    "attachments": [
      {
        "version": 0,
        "itemType": "attachment",
        "tags": [
          
        ],
        "collections": [
          
        ],
        "relations": {
          
        },
        "title": "Schmitt - 1987 - Aristotle's Poetics and Aristotle's Nature.pdf",
        "parentItem": "UKMDDQCQ",
        "linkMode": "imported_file",
        "contentType": "application\/pdf",
        "charset": "",
        "path": "storage:Schmitt - 1987 - Aristotle's Poetics and Aristotle's Nature.pdf",
        "dateAdded": "2015-06-05T12:09:17Z",
        "dateModified": "2015-06-09T18:33:06Z",
        "uri": "http:\/\/zotero.org\/users\/2295317\/items\/5ZIQE6FM",
        "localPath": "\/Users\/olaf\/Library\/Application Support\/Zotero\/Profiles\/k3xi5rnf.default\/zotero\/storage\/5ZIQE6FM\/Schmitt - 1987 - Aristotle's Poetics and Aristotle's Nature.pdf",
        "itemID": 369,
        "meta": {
          "revision": 0,
          "created": 1484374062046,
          "version": 0
        },
        "$loki": 5167
      }
    ],
    "notes": [
      
    ],
    "itemID": 842,
    "attachmentIDs": [
      369
    ],
    "meta": {
      "revision": 0,
      "created": 1484374062043,
      "version": 0
    },
    "$loki": 5166
  },
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
]
```

**Comment by retorquere** [comment]
On further inspection the collection actually has `0` in the `data` array, but how could it have gotten there? I thought `insert` would allow only objects because `insertOne` checks that documents are typeof `object`.

**Comment by obeliskos** [comment]
yea your query looks good... but your right, the internal data array should not look like that

so far I am unable to corrupt the internal data array... by not enable cloning by default its as fast as possible but we do use array.slice so we -should- never return actual reference to data array where you might overwrite specific contents.  also overwriting a returned object instance with a value of 0 just local variable to another object instance (preserving internal data object).

what options are passed in when you construct your loki object and your collection object?  does your code ever access directly the collection.data array?  not sure if you can reproduce this at will, if so maybe see if its something easily simplified to post here.

**Comment by retorquere** [comment]
Unfortunately I can't reproduce the issue at all -- I have a user whose database contains this data but we don't know how it got there.

This *was* on an older version of LokiJS (1.3.17) but I don't see anything in that release which would make this easily explainable.

The insertion code looks roughly like this:

```
// item is passed to me but *should* always be an simple JS object or null
if (item) {
  this.fixup(item, itemID) // this expects item to be an object and would raise TypeError if not
  if (item.itemType != 'note' && item.itemType != 'attachment') { item.attachmentIDs = [] }
} else {
  item = {itemID, itemType: 'cache-miss'}
}
// serialized is the collection
serialized.insert(item)
```

I did do direct access to `.data` to get the collection size (`.data.length`) but I've replaced those with `.collection.count()` now.

For the time being I've enabled cloning on all my collections, if my test set is any indication (it likely isn't), the performance hit is acceptable. Just removing the zeroes from the collection gets things going again (as expected).

**Comment by retorquere** [comment]
Sorry, forgot to add how I constructed the collection:

```
serialized = db.addCollection('serialized', { indices: ['itemID', 'uri'] })
```

**Comment by obeliskos** [comment]
nothing you mentioned should cause that, you can't insert those 0 vales as docs as you mentioned we check for valid object(s) we can graft meta and $loki properties on

in general, i would make a practice to not call coll.data.filter(fun) as coll.where(fun) should do the same, but that shouldn't modify values in the way you described

any other patterns involved like map, mapreduce, chained updates, etc?

the obvious easy way to cause that is to just assign coll.data to an invalid array as you posted, but i assume your on the lookout for that now (if you can even see other users code)

**Comment by Viatorus** [comment]
> $nin ... since only mongo queris benefit from binary indices

Good point. I totally forgot to enable _$nin_ for binary indices. Currently only _$in_ is implemented.

**Comment by retorquere** [comment]
I only called `.data.filter` because I wanted to mimic what `removeWhere` does when passed a function for diagnostic purposes -- in my own code I just call `removeWhere`. No other things like `map` etc -- my use of LokiJS is entirely basic. No assignments either; I've gone over the code, and all the code is mine (except libraries, but I'm not passing the `.data` property around, so I wouldn't know how they could get into there).

On `$nin`, that sounds super useful, but as per @Viatorus comment wouldn't work right now?

**Comment by Viatorus** [comment]
It **works** quit good. It is just not enabled for binary indices.

This does mean: _$nin_ iterates over the hole dataset like every _where()_ query.

So it is equivalent like:

```javascript
coll .where(function(obj) {
   return itemIDs.indexof(obj.itemID) === -1;
})
```

**Comment by retorquere** [comment]
OK, so I could start using it now and when a new LokiJS version drops that includes it it would just be faster, correct?

**Comment by Viatorus** [comment]
Correct. :)

**Comment by retorquere** [comment]
Is there a function that does something like findAndRemove but returns the removed documents? Or should I just run `.query` first and then call `.remove` on those results?

**Comment by obeliskos** [comment]
Hmm, I don't think so... the alternative approach using chaining would be : 

```javascript
coll.chain().find({ itemID: { $nin: itemIDs }}).remove();
```
does not return to you the documents before deleting them... I suppose we could add a chain op like data() that could assign within a chain like : 

```javascript
var results;
// use some potential future 'retain' chain op to get interim results
coll.chain().find({ itemID: { $nin: itemIDs }}).retain(results).remove();
```

without that future retain method you would currently have to do : 
```javascript
// chaining 
var rs = coll.chain().find({ itemID: { $nin: itemIDs }});
var results = rs.data();
rs.remove();

// or non-chaining
var results = coll.find({ itemID: { $nin: itemIDs }});
coll.remove(results);
```

ok, you are not databinding the results in any way that might lead to ui updating objects?

**Comment by retorquere** [comment]
Databinding?

I'm currently doing the non-chaining version and that seems to work well.

**Comment by obeliskos** [comment]
I guess your not... if you were two way databinding in a web app (where user interface will update if you change an object and object will update if you change user interface value) you would know about it... usually requires third party framework.  

I never saw your loki constructor, are you doing any autosaving on intervals?  What persistence adapter if any?

If not persistence I don't have any other ideas at the moment...  changesAPI might be used as an audit trail if the dataset was small enough to get an idea of usage patterns.

**Comment by retorquere** [comment]
Ah, right, that databinding. That will come in a next version as Zotero moves away from Firefox to Electron + React. Right now, no databinding.

My code runs in a Firefox extension, so it won't run as-is under node or on a webpage, but [here](https://gist.github.com/70878d5be0801cc3efec9054c9557328)'s the loader + the persistence adapter. Roughly, it loads from a fixed filename but if that isn't valid json it will try numbered backups. Saves go the same way, current files are backed up to numbered versions before I write out the data and move it (write+move to try to get atomic writes of the DB).
