### ISSUE TITLE
Data loss issue when saving large data at once when using LokiFileSystemAdapter

### ISSUE THREAD

**Issue by shashankdevp** [techfort/LokiJS#533]
I have a weird issue, that is when saving large amount of data in one shot at a time and in the mean time if I close the app or due to any other reason if the app gets closed, **all the saved data are lost**. This is happening only when I am using LokiFileSystem Adapter. 

Before I was using localstorage of browser implementation of loki, for saving the data. As there is a limitation on the amount of data that can be saved on the browser, I moved to Loki FileSystem Adapter.

I have created a sample project [here](https://github.com/shashankdevp/LokiFSApplication). In viewController **if I change the value to 1000 and during save if I close the app, the size of the DB file created in the application folder is reduced to 0**.

       `function insertData(n) {
            var insertingData = [];
            var iValue = n > 99 ? n : 0;
            var toValue = iValue + 1000; // Changed from 100 to 1000
            for (var i = iValue ; i < toValue; i++) {
                var insertDataSet = {
                    Id: i, personId: i + 100, empId: i + 1000, name: i + "-TestPerson",
                    address: i + "-Address"
                };
                insertingData.push(insertDataSet);
            }
                
            return insertingData;
        }`

To reproduce the issue

1. Hit the add button on the view to insert the data
2. On the second time click, add a **BREAKPOINT near fs.root.getFile**

       `FileSystemAdapter.prototype.saveDatabase = function (name, data, callback) {
         fs.root.getFile( // Add a BREAKPOINT here
            this.options.base_dir + "/" + name,
         {
            create: true
        },
        function (fileEntry) {
            fileEntry.createWriter(
                function (fileWriter) {
                    fileWriter.onwriteend = function () {
                        if (fileWriter.length === 0) {
                            var blob = new Blob(
                                [data],
                                {
                                    type: 'text/plain'
                                }
                            );
                            fileWriter.write(blob);
                        }
                    };
                    fileWriter.truncate(0);
                    callback(null);
                },
                function (err) {
                    throw new FileSystemAdapterError("Unable to write file" + JSON.stringify(err));
                }
            );
        },
        function (err) {
            throw new FileSystemAdapterError("Unable to get file" + JSON.stringify(err));
        }
       );
       };`

3. Now close the app at the break point
4. If you look at the file size in the app folder its either 0 or a lesser value.

Kindly let me know if am I doing something wrong.

**Comment by obeliskos** [comment]
So you are creating your own persistence adapter to work with cordova and not using built in LokiFsAdapter right?

If you expect to shut down the whole environment before your save is complete you might want to explore all -synchronous- filesystem io options available for your environment.

In node that might mean using the 'sync' versions of the fs methods but i'm guessing you can't use those.

If your problem was overlapping saves that would be easier to fix using [throttledSaves](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#high-frequency-save-throttling) loki option... but since your repro says to shut down the app I'm guessing you need synchronous adapter.

**Comment by shashankdevp** [comment]
Yes I am using a custom adapter [this one](https://github.com/annoyingmouse/lokiFileSystemAdapter) and also I tried using loki-cordova-fs-adapter [this one](https://github.com/cosmith/loki-cordova-fs-adapter).

Both I tried out, but in vain. Using both of them gives same issue of data loss on immediate close of application (Forcefully kill the app). Both the adapters uses truncate method of file writer, at that point if the app is closed data is lost completely because in both adapters fileWriter.truncate(0) is done.

    `fileEntry.createWriter(
                function (fileWriter) {
                    fileWriter.onwriteend = function () {
                        if (fileWriter.length === 0) {
                            var blob = new Blob(
                                [data],
                                {
                                    type: 'text/plain'
                                }
                            );
                            fileWriter.write(blob);
                        }
                    };
                    fileWriter.truncate(0); // At this point while updating an existing file, its been truncated to 0 length then again created a new file.
                    callback(null);
                },
                function (err) {
                    throw new FileSystemAdapterError("Unable to write file" + JSON.stringify(err));
                }
            );`

Same thing is done in loki-cordova-fs-adapter.

    `fileWriter.onwriteend = function () {
                            if (fileWriter.length === 0) {
                                var blob = _this._createBlob(dbstring, "text/plain");
                                fileWriter.write(blob);
                                callback();
                            }
                        };
                        fileWriter.truncate(0);
      // At this point while updating an existing file, its been truncated to 0 length then again created a new          file.`

Is there any solution for this?

As an alternative I tried using LokiFsAdapter, but was not able to include in the existing cordova project I was getting **LokiFsAdapter not defined error**.  

Can LokiFsAdapter be included on an existing Cordova project? If so could you share a sample application link.

**Comment by obeliskos** [comment]
I am not very familiar with cordova, but techfort was... I believe we made the default persistence for cordova to be localstorage so perhaps not.

Well the synchronous vs asynchronous nature of each persistence method are probably the key issue.  After a [brief search](http://cordova.apache.org/docs/en/latest/cordova/storage/storage.html) I see only localstorage as a synchronous option.  Are you tapping into any of the app lifecycle events available to you (Like [here](http://simonmacdonald.blogspot.fr/2011/04/phonegap-lifecycle-events.html) if that is still accurate)? Is that where you are firing off a saveDatabase?  How long does it take to save the amount of data normally?

Using loki in a web page with the (async) indexeddb adapter exhibits the same behavior... if you try to save 100megs of data in 5 seconds or so and you shutdown the whole browser your data will not have been saved correctly.

If cordova provides you a way to synchronously issue some command to delay shutting down the process you might force delay to allow async io time to complete but I am guessing hacks for environments I am not familiar with.

If anyone else knows if cordova lifecycle events and ability to guarantee safely persisting asynchronously, please chime in.
