### ISSUE TITLE
LokiPartitioningAdapter corrupts maxId

### ISSUE THREAD

**Issue by dfoody** [techfort/LokiJS#535]
If you use the LokiPartitioningAdapter, the data appears to be saved correctly to the database, but - when the database is reloaded - the maxId values are 0 for all collections. So, if you insert new entries in a collection after the reload the collection becomes corrupted.

You can see it with the loki sandbox example used in the docs (just go to the object inspector):
https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/15c1aa87da16cd89b328eb84bbcdf8fa/raw/d91ac3fee212dc5aa96cb05f479d825faa17c1c8/PartitionedMemoryAdapterTest

**Comment by dfoody** [comment]
The specific issue seems to be related to line 1486:
```copyColl.maxId = (coll.data.length === 0) ? 0 : coll.maxId;```
coll.data.length is always 0 when loading the db container - so this resets the maxId.

**Comment by obeliskos** [comment]
ouch, yes this sounds bad... I think I have made a quick fix to prevent further issues.  I need more unit tests around this which I will try to do this weekend.  Did the invalid maxId get persisted back into your database?

**Comment by dfoody** [comment]
@obeliskos my code crashed before getting to the point of persisting the database (I found it because my code did a "find" (which found the record) followed by an "update" which failed due to an exception that the record wasn't in the database (because two records had the same $loki value).

But, based on the in-memory data, I suspect it would have persisted the invalid maxId - though that's the least of the worries I suspect (having multiple records with the same $loki meant the corruption was deeper).

**Comment by obeliskos** [comment]
right, thanks for detailed info btw...  so will you need to rebuild you data or can you regenerate it from scratch?

If no inserts have been made then maxId can be 'recalculated' after reassembled load based on : 
```javascript
// take the last object in data, gets its $loki id and add one to it
coll.maxId = (coll.data.length > 0)?(coll.data[coll.data.length-1]].$loki+1) : 0
```

Before fix, if partitioned db was saved and restored, and inserts were made and persisted back to disk you would likely have to rebuild your collection id's manually.  Let me know if you or anyone needs to go that route and i'll help devise a rebuild algorithm to run manually after db load.

**Comment by dfoody** [comment]
We're just using it for a local cache - so we can rebuild its content from our server easily. So we don't need a rebuild algorithm.
