### ISSUE TITLE
LokiPartitioningAdapter can have data consistency issues

### ISSUE THREAD

**Issue by dfoody** [techfort/LokiJS#537]
If a database gets partially saved (e.g. the when used in a browser saving to IndexedDB, and the browser page is reloaded mid-save) you can end up with various error scenarios (many of which we've seen in testing so far):

(1) If the database has never previously been saved, and gets partially saved, when you next try and load the database you'll get uncaught exceptions and the loadDatabase callback never gets called.

(2) If the database has previously been saved, and next time gets partially saved, when you next load the database you can have inconsistent data (some collections from the most recent save, some from the save before that).

(3) I assume the same type of issue as #2 might happen with individual pages of a single collection - though I'm less sure how that would behave.

(4) Less likely to happen in real-world use, but if the stored data in the database gets corrupted (we tested by replacing the row with garbage data), you get an uncaught exception (the various calls to JSON.parse aren't wrapped with try/catch) and the loadDatabase callback never gets called.

#1, #2, and #3 all happen because the underlying saves of each partition/page are serialized. So, there seems to be two potential solutions: At least for IndexedDB, parallelize all saves and put them all within the same transaction (not very generalized though). Alternately, before saving you could delete all existing saved partitions/pages then do the rest of the save. This combined with handling errors of pages/partitions not being found on load should create the most consistent solution.

**Comment by obeliskos** [comment]
I usually would advise to avoid such situations where browser could get shutdown mid-save as something inherently buggy in outcome, but for indexeddb yea I guess they do support transactions on individual saves... leading to mix and match descriptions outlined above if you don't allow saves to complete.

I would think indexeddb specific 'reference mode' adapter which combines LokiPartitioningAdapter and LokiIndexedAdapter and wraps the transaction around all ops as you suggested could be very useful option (possibly becoming the recommended adapter for web).

Any interest in contributing on that?  If not I can put that on our roadmap and look into that in the future.  Not sure how large transactions affect indexeddb quotas.

We do not do try/catch on individual json parse as I would expect that would be very costly in performance.  If you have time to do benchmarks on that feel free to verify performance cost.

**Comment by dfoody** [comment]
So, for the try/catch part - the issue is that IndexedDB is async - so if an exception is thrown inside the IndexedDB loadDatabase callback (e.g. inside the this.adapter.loadDatabase callback in LokiPartitioningAdapter) there's no way for the lokijs user to catch the exception. This is a general issue inside any async callback. So, rather than wrapping each JSON.parse, you could instead put a try/catch right inside each call to loadDatabase, which wraps the entire content of the callback.

For example, if the database partially saves the first time, inside LokiPartitioningAdapter.prototype.loadNextPage the first line inside the this.adapter.loadDatabase callback is ```var data = result.split(self.options.delimiter);``` which throws an exception since the data was not found. And there's no way to catch this exception. A try/catch right inside the loadDatabase callbacks would have caught this - and, while this one issue can be fixed, the core issue is that if other problems happen, without any try/catch in the async blocks code will just "lock up" (since the callbacks will never be called).

In our use case we're now removing all the existing rows from the underlying database before we save again. It's a simple, safe, and relatively performant solution to the issue (along with a check in LokiPartitioningAdapter.prototype.loadNextPage for loadDatabase having no result).

I'm not sure you could easily write a wrapper around LokiPartitioningAdapter to add transactions to the underlying LokiIndexedAdapter without a fairly significant re-write (you'd have to pass state context from the wrapper through the LokiPartitioningAdapter and then through to the LokiIndexedAdapter - which would mean APIs would change in a lot of places).

**Comment by xeoshow** [comment]
Does the LokiPartitioningAdapter have the transaction support now? Thanks!
