### ISSUE TITLE
LokiEventEmitter removeListener not working

### ISSUE THREAD

**Issue by chmmou** [techfort/LokiJS#538]
Hi,

i found a issue to remove listener. The second parameter is not used.

The issue is on line **590** in lokijs.js: listen is not defined. It must be **listener** instead of **listen**.
    
    self.removeListener(currentEventName, listen);

Code:

    LokiEventEmitter.prototype.removeListener = function (eventName, listener) {
      var self = this;
      if (Array.isArray(eventName)) {
        eventName.forEach(function(currentEventName) {
          self.removeListener(currentEventName, listen);
        });
      }

      if (this.events[eventName]) {
        var listeners = this.events[eventName];
        listeners.splice(listeners.indexOf(listener), 1);
      }
    };

**Comment by ChMaster** [comment]
Hi,

no problem. 

I use this function to remove all listener before I use the listener **.on('eventName', (value: any) => {});** again.

And at least, my little ideas.

**First variant to fix**: Return the listener in the first  **if** statement.

    LokiEventEmitter.prototype.removeListener = function (eventName, listener) {
      var self = this;
      if (Array.isArray(eventName)) {
        eventName.forEach(function(currentEventName) {
          self.removeListener(currentEventName, listener);
        });

        return listener;
      }

      if (this.events[eventName]) {
        var listeners = this.events[eventName];
        listeners.splice(listeners.indexOf(listener), 1);
      }
    };

**Second variant to fix**: Create a **else if** - **else** block.

    LokiEventEmitter.prototype.removeListener = function (eventName, listener) {
      var self = this;
      if (Array.isArray(eventName)) {
        eventName.forEach(function(currentEventName) {
          self.removeListener(currentEventName, listener);
        });
      }
      else if (this.events[eventName]) {
          var listeners = this.events[eventName];
          listeners.splice(listeners.indexOf(listener), 1);
        }
      }
      else {
        // do something
      }
    };

**Third variant to fix**, let play your fantasy. ;-)

Regrads,
ChMaster

**Comment by obeliskos** [comment]
Alright I made a quick fix as you suggested, let me know if you still have issues...

Thanks!
