### ISSUE TITLE
Change API - serializeChanges not working 

### ISSUE THREAD

**Issue by emichaf** [techfort/LokiJS#539]
Using the following params:
autoload: true,
autoloadCallback : autoloadHandler,
autosave: true,
autosaveInterval: 3000,  
persistenceMethod: 'fs',
autosaveCallback: autosaveHandler
 
in collection part:
disableChangesApi: false
 
 
Trying to the following:
1.      Insert object1 to lokijs
2.      in the autosaveCallback -> fetch changes via serializeChanges
3.      Update MongoDb with the changes
4.      Flush changes in mem (LOKIJS), and save to DB (saveDatabase)
5.      Restart service, upload jsonDB to LokijS (no changes exist in DB)
6.      Modify existing object1
7.      Autosave -> saves changes to lokijs json file on disk, but changes is empty via serializeChanges ?? Why is that, the modified changes should be included ?
So no MongoDB updates are performed…

**Comment by obeliskos** [comment]
Can you make a loki sandbox gist or some other site to post example, possibly using LokiMemoryAdapter to mock persistence?  If so can a problem be generated without autosave/autoload to simplify this to exactly the issue you believe is performing incorrectly?

Thanks

**Comment by emichaf** [comment]
https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/emichaf/77cd5e662e1f5b8ffd1a2753b22937ac/raw/6aad5fa648fb52346ed99fe16235762b91cf1e04/gistfile1.txt

**Comment by obeliskos** [comment]
I see, thank you... when inflating collections during load we needed to do in a way that would attach the appropriate event listeners.

Your gist was very helpful, but it has typo... at the very end you are looking up changes for a 'coll' collection where it should be 'items'

**Comment by emichaf** [comment]
The fault can not be recreated with LokiMemoryAdapter!

The fault appears when loading json file via disk with the settings below!

EI_lokijsdb = new loki(config.EI_LOKIJS_DB_PATH,
                    {
                        autoload: true,
                        autoloadCallback : autoloadHandler,
                        autosave: true,
                        autosaveInterval: config.EI_LOKIJS_DB_AUTOSAVE_INTERVAL,  // in millisec
                        persistenceMethod: 'fs',
                        autosaveCallback: autosaveHandler
                    });

**Comment by obeliskos** [comment]
Well your gist logic does not support asynchronous adapters since you are not using callbacks.  

Might I suggest to use [this gist](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/25844db104fe4073e215dd64dfe3444b/raw/bb1d9a09db016e0b991604bb75e8163b3b008965/changesApiTest) as a basis for testing where you might swap in an asynchronous adapter in place of LokiMemoryAdapter.  

Our LokiMemoryAdapter does support simulating asynchronous responses so I have enabled that in the gist.

**Comment by emichaf** [comment]
Hi,

tried the code below for persistenceMethod: 'fs'!

and received the following output: the changes is not included...

db serializeChanges before flush: [{"name":"items","operation":"I","obj":{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"created":1487070161946,"version":0}
,"$loki":1}}]
db serializeChanges after flush: []
loaded DB (db2)
db2 serializeChanges before change: [{"name":"items","operation":"I","obj":{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"created":1487070161946,"version":
0},"$loki":1}}]
Inserting in db2
db2 serializeChanges after insert (now missing changes): [{"name":"items","operation":"I","obj":{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"created":148
7070161946,"version":0},"$loki":1}}]
db2 serializeChanges in autosaveHandler: (now missing changes):[{"name":"items","operation":"I","obj":{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"create
d":1487070161946,"version":0},"$loki":1}}]
DB content: [{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"created":1487070161946,"version":0},"$loki":1},{"name":"gungnir","owner":"odin","maker":"elves"
,"meta":{"revision":0,"created":1487070161995,"version":0},"$loki":2}]
Inserting in db2 -> gungnir2
db2 serializeChanges in autosaveHandler: (now missing changes):[]
DB content: [{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"created":1487070161946,"version":0},"$loki":1},{"name":"gungnir","owner":"odin","maker":"elves"
,"meta":{"revision":0,"created":1487070161995,"version":0},"$loki":2},{"name":"gungnir2","owner":"odin2","maker":"elves2","meta":{"revision":0,"created":1487070167949,"version":0},"
$loki":3}]


-----------------------------------------------------------------------------

var loki = require('lokijs')
    ,config = require('./app/config');

var coll;
var db2;

// Add a collection to the database & Insert
var db = new loki(config.EI_LOKIJS_DB_PATH);
var items = db.addCollection('items', {disableChangesApi: false});
items.insert({ name : 'mjolnir', owner: 'thor', maker: 'dwarves' });

db.saveDatabase(function(err) {
    console.log("db serializeChanges before flush: " + db.serializeChanges(['items']));
    items.flushChanges();
    console.log("db serializeChanges after flush: " + db.serializeChanges(['items']));

     db2 = new loki(config.EI_LOKIJS_DB_PATH,
        {
            autoload: true,
            autoloadCallback: autoloadHandler,
            autosave: true,
            autosaveInterval: 1000,  // in millisec
            persistenceMethod: 'fs',
            autosaveCallback: autosaveHandler
        });
});


function autoloadHandler() {
    coll = db2.getCollection('items');
    console.log("loaded DB (db2)");
    console.log("db2 serializeChanges before change: " + db2.serializeChanges(['items']));
    console.log("Inserting in db2");
    coll.insert({ name : 'gungnir', owner: 'odin', maker: 'elves' });
    console.log("db2 serializeChanges after insert (now missing changes): " + db2.serializeChanges(['items']));
}

function autosaveHandler() {
    console.log("db2 serializeChanges in autosaveHandler: (now missing changes):" + db2.serializeChanges(['items']));
    coll.flushChanges();
    var dbcont_ = coll.find({});
    console.log("DB content: " + JSON.stringify(dbcont_));
}


setTimeout(function(){
    console.log("Inserting in db2 -> gungnir2");
    coll.insert({ name : 'gungnir2', owner: 'odin2', maker: 'elves2' });
}, 6000);

**Comment by obeliskos** [comment]
You do realize the fix I made has not yet been pushed to npm right?  Until then you need take the latest GitHub version of lokijs.js and copy over your npm version.

When I run your post above (with 'test.db' as the filename/path) I get : 
```
db serializeChanges before flush: [{"name":"items","operation":"I","obj":{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"created":1487071017720,"version":0},"$loki":1}}
db serializeChanges after flush: []
loaded DB (db2)
db2 serializeChanges before change: [{"name":"items","operation":"I","obj":{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"created":1487071017720,"version":0},"$loki":1
Inserting in db2
db2 serializeChanges after insert (now missing changes): [{"name":"items","operation":"I","obj":{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"created":1487071017720,"
on":0},"$loki":1}},{"name":"items","operation":"I","obj":{"name":"gungnir","owner":"odin","maker":"elves","meta":{"revision":0,"created":1487071017800,"version":0},"$loki":2}}]
db2 serializeChanges in autosaveHandler: (now missing changes):[{"name":"items","operation":"I","obj":{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"created":148707101
"version":0},"$loki":1}},{"name":"items","operation":"I","obj":{"name":"gungnir","owner":"odin","maker":"elves","meta":{"revision":0,"created":1487071017800,"version":0},"$loki":2}}]
DB content: [{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"created":1487071017720,"version":0},"$loki":1},{"name":"gungnir","owner":"odin","maker":"elves","meta":{"re
n":0,"created":1487071017800,"version":0},"$loki":2}]
Inserting in db2 -> gungnir2
db2 serializeChanges in autosaveHandler: (now missing changes):[{"name":"items","operation":"I","obj":{"name":"gungnir2","owner":"odin2","maker":"elves2","meta":{"revision":0,"created":14870710
,"version":0},"$loki":3}}]
DB content: [{"name":"mjolnir","owner":"thor","maker":"dwarves","meta":{"revision":0,"created":1487071017720,"version":0},"$loki":1},{"name":"gungnir","owner":"odin","maker":"elves","meta":{"re
n":0,"created":1487071017800,"version":0},"$loki":2},{"name":"gungnir2","owner":"odin2","maker":"elves2","meta":{"revision":0,"created":1487071023742,"version":0},"$loki":3}]
```

**Comment by emichaf** [comment]
Thnx, it's working now!

**Comment by obeliskos** [comment]
Great, thanks for reporting this
