### ISSUE TITLE
Init erro by node-webkit context

### ISSUE THREAD

**Issue by zhaoxingyun** [techfort/LokiJS#54]
use [node-webkit](/rogerwang/node-webkit). 

	var db = new loki();
	
will throw error

	Uncaught node.js Error 

	ReferenceError: document is not defined
		at Loki.getENV (D:\workspace\radium\canvas\node_modules\lokijs\src\lokijs.js:228:15)
		at LokiEventEmitter.Loki (D:\workspace\radium\canvas\node_modules\lokijs\src\lokijs.js:237:18)
		
change source code in file `lokijs.js:224` like this will be ok

	   if (typeof exports === 'object' || typeof window === 'undefined') {

**Comment by techfort** [comment]
I am going to change the db constructor so that it takes (among others) the option 'env', so environment can be set explicitly skipping detection. So you would do `var db = new loki('myApp', { env: 'NODEJS' })`
