### ISSUE TITLE
Incremental persistence adapter for nodejs backend

### ISSUE THREAD

**Issue by emichaf** [techfort/LokiJS#540]
I wonder if any incremental persistence adapter exist for nodejs backend. Today rewriting a large json file (fs)  is timeconsuming...

**Comment by obeliskos** [comment]
Not sure how an incremental persistence adapter would work, would it work with changes api?  If so how do you know when a full save vs incremental save and how would you catalog all sets of incremental saves?  

On a different note, we do have a slightly faster loki-fs-structured-adapter which should scale better than stock fs adapter.

**Comment by emichaf** [comment]
Runnning Node and received: TypeError: this.persistenceAdapter.loadDatabase is not a function

When added:
var lfsa = require('./node_modules/lokijs/src/loki-fs-structured-adapter');
and
adapter : lfsa,

**Comment by Kanaye** [comment]
That's because you're passing the constructor of the loki-fs-structured-adapter and not an instance of it.
Replace ``adapter: lfsa`` with ``adapter: new lfsa()`` in your example.

**Comment by emichaf** [comment]
tried it, but reveive: (no db file exist in dir when starting)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\app\db\lokijs\autosave\StreamProcessorDB.db'
    at Error (native)

**Comment by obeliskos** [comment]
Thanks @kanaye and @emichaf ...

I not only need to fix our wiki page showing quickstart for using this adapter but I also need to fix it so it gracefully returns when loading database that doesn't (yet) exists.

**Comment by obeliskos** [comment]
ok emichaf, as of commit be84a7317a462026c1ac75c8b3fd27e742fb5464 this should be fixed.  If you want you can grab it off master and try it out.  

I have some scripts in benchmarks folder (stress.js and distress.js) I was using to determine scalability when working on serialization overhaul in #498 (towards the end).
