### ISSUE TITLE
Autosave vs Change API 

### ISSUE THREAD

**Issue by emichaf** [techfort/LokiJS#542]
I would like to use the built-in autosave callback to trigger save (change API) to external DB, but i don't want to save json file to disk (time consumig).

 Loki.prototype.autosaveEnable = function (options, callback) {
..if (self.autosaveDirty()) {
          //self.saveDatabase(callback);  <--- parameter to handle if save to disk should be used or not ...
        }

Is it possible to add flag in option if "saveDatabase" should be performed or not, or maybe new params for changeapi ex ChangeApiInterval and ChangeApiCallback (to be used if  autosave = false....)

**Comment by obeliskos** [comment]
Well we could add an emitted event to that which you can listen for... we could maybe add a 'null' persistence adapter or use the memory adapter if db is small enough.

Or If you are only using and changes api and not saving to disk, you could implement your own 'reference' mode persistence adapter which would act as a change synchronizer, maybe something like : 

```javascript
function SomeSyncAdapter() {
   this.mode = "reference";
}

SomeSyncAdapter.prototype.exportDatabase = function(dbname, dbref, callback) {
  var changes = dbref.serializeChanges().

  // To be implemented
  // this.postSomeAjaxChanges(changes);
}

// don't care, at least for this example
SomeSyncAdapter.prototype.loadDatabase = function(dbname, callback) {
}
```

**Comment by emichaf** [comment]
Will use your proposal (reference) adapter!
