### ISSUE TITLE
ES6 : Angular 1.6 : $injector:modulerr

### ISSUE THREAD

**Issue by darkiron** [techfort/LokiJS#543]
hi, 
I have this error in my app : 
`Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module function Loki(filename, options) due to:
Error: [$injector:unpr] Unknown provider: filename`

I not found where module filname was injected in Loki !

**Comment by Viatorus** [comment]
filename is a variable (string).

**Comment by darkiron** [comment]
I know, why angualr think is an unknow provider ?

**Comment by darkiron** [comment]
The problem comme when inject Loki in angular. 
I use webpack with babelJS to build my app.

**Comment by darkiron** [comment]
no idea ?

**Comment by darkiron** [comment]
I try  this change Loki declaration : 
` //function Loki(filename, options) {
    function Loki() {`

> Failed to instantiate module function Loki() due to:
ReferenceError: filename is not defined

If I can help you, and you me :(
