### ISSUE TITLE
findOne does returns a record, when criteria is set to `undefined`

### ISSUE THREAD

**Issue by kaasdude** [techfort/LokiJS#545]
Hey Guys,

I was unit testing [gibbons](https://www.npmjs.com/package/gibbons) and tried to have funny criteria to predict the behaviour of lokijs (1.4.3):

http://plnkr.co/edit/TP7Hee8Nfl2ZlbFV0i29
_(Credits to: @Badisi borrowing a piece of Plunker)_

Please correct me if I'm wrong, but when I got an user collection filled with users, and I try this funny query:
```
const result = users.findOne(undefined); 

```

Assuming it's a mongo-style query: [Mongo findOne](https://docs.mongodb.com/manual/reference/method/db.collection.findOne/) 
Lokijs should have the same behaviour according to it's documentation:
```
    /**
     * Find one object by index property, by property equal to value
     * @param {object} query - query object used to perform search with
     * @returns {(object|null)} First matching document, or null if none
     * @memberof Collection
     */
    Collection.prototype.findOne = function (query) {
      query = query || {};

      // Instantiate Resultset and exec find op passing firstOnly = true param
      var result = new Resultset(this, {
        queryObj: query,
        firstOnly: true
      });

      if (Array.isArray(result) && result.length === 0) {
        return null;
      } else {
        if (!this.cloneObjects) {
          return result;
        } else {
          return clone(result, this.cloneMethod);
        }
      }
    };
```
It shouldn't give any result right?
Still it just returns a record?
I would expect an error, or something else a `null`, but not some user record.

:ok_hand: Regards :ok_hand:

**Comment by obeliskos** [comment]
findOne (similarly to find) treats the absence of a filter object as no filter, meaning 'find all docs'

whether this behavior should be different for one or the other can be up for debate but it makes sense to me and for this lokijs 1.4.x, we can't change it now and coll.findOne(undefined) is indistinguishable from coll.findOne() to that method. 

a null return value occurs when a filter does exist but no matches were found

Feel free to suggest breaking changes over at : 
https://github.com/LokiJS-Forge/LokiJS2

That is where we are exploring next gen loki development

**Comment by kaasdude** [comment]
I understand you can't change the behaviour for 1.4.x.

Thanks!

(Looking forward to V2!)
