### ISSUE TITLE
LokiJS -> distributed

### ISSUE THREAD

**Issue by emichaf** [techfort/LokiJS#547]
Is it possible to use LokiJS as an distributed inmem DB ?

**Comment by obeliskos** [comment]
This has been an interest of @techfort in the past, and he has even a few projects prototyping tcp ([here](https://github.com/techfort/lokijs-server)) and http ([here](https://github.com/techfort/snaptun) and [here](https://github.com/techfort/snaptun-cli)) services.

I would imagine if your application could define a simple rest interface it could be implemented fairly easily but we have no generic solution atm.

**Comment by emichaf** [comment]
Will check the repos. Do you know if any locking mechanism exist in LokIJS for handlig race conditions?
