### ISSUE TITLE
Loki in NativeScript: avoid using LokiFsAdapter

### ISSUE THREAD

**Issue by dnalor** [techfort/LokiJS#553]
When using Loki in NativeScript, using "new Loki()" (in Loki itself, e.g. in Loki.prototype.copy) fails, since it by default uses LokiFsAdapter, which requires the unavailable node fs module.

So either the configured persistence adapter could be used:

```
Loki.prototype.copy = function(options) {
//var databaseCopy = new Loki(this.filename);
var databaseCopy = new Loki(this.filename, (this.persistenceAdapter === null)?{}:{adapter: this.persistenceAdapter});
      

LokiPartitioningAdapter.prototype.loadDatabase
this.dbref = new Loki(dbname, {adapter: this.adapter});

// doesn't work, since we're using a copy without a persistenceAdapter (removeNonSerializable)
Loki.prototype.serializeDestructured 
/dbcopy = new Loki(this.filename);
      dbcopy = new Loki(this.filename, (this.persistenceAdapter === null)?{}:{adapter: this.persistenceAdapter});

```
Or a default persistence for NativeScript could be provided:

```
    Loki.prototype.configureOptions = function (options, initialConfig) {
      var defaultPersistence = {
          'NODEJS': 'fs',
          'BROWSER': 'localStorage',
          'CORDOVA': 'localStorage'
//		  'NATIVESCRIPT': 'nativeScript'
        },
        persistenceMethods = {
          'fs': LokiFsAdapter,
          'localStorage': LokiLocalStorageAdapter
//		  'nativeScript': LokiNativeScriptAdapter // would need a require somewhere
        };
```

and then this would work in NativeScript:
```
global.ldb = new Loki(path, {
	adapter: partitioningAdapter,
	env: "NATIVESCRIPT",
	throttledSaves: true,
	verbose: true
});
```

**Comment by obeliskos** [comment]
I am not sure I understand what exactly you are trying to do to begin with.   Are you including the loki nativescript driver which is separately included in the src directory?  Then instantiating it and passing into loki constructor?  I see you (or want to) instatiate loki with a partitioning adapter but I cant see what adapter you passed into its constructor.

For normal nativescript adapter I would expect you would do something like [this](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#simple-example-of-using-lokinativescriptadapter-) : 
```javascript
const loki = require ('lokijs');
const LokiNativescriptAdapter = require('lokijs/src/loki-nativescript-adapter');
let db = new loki('loki.json',{
            adapter:new LokiNativescriptAdapter()
});
```

For partitioning with nativescript I would expect you would do something like this : 
```javascript
const loki = require ('lokijs');
const LokiNativescriptAdapter = require('lokijs/src/loki-nativescript-adapter');
const pa = new loki.LokiPartitioningAdapter(new LokiNativescriptAdapter());
let db = new loki('loki.json',{
            adapter: pa
});
```

**Comment by dnalor** [comment]
I'm doing exactly what you described in the second case:
```
const Loki = require ('lokijs');
var LokiNativeScriptAdapter = require("loki-nativescript-adapter");
var lokiNativeScriptAdapter = new LokiNativeScriptAdapter();
var partitioningAdapter = new Loki.LokiPartitioningAdapter( lokiNativeScriptAdapter, { paging: true, pageSize:5*1024*1024});

global.ldb = new Loki(path, {
	adapter: partitioningAdapter,
	env: "NATIVESCRIPT",
	throttledSaves: true,
	verbose: true
});
```
This works fine, if one prevents Loki from requiring the node fs module.
This ugly hack does the trick:
```
   function LokiFsAdapter() {
      //this.fs = require('fs');
    }
```
Obviously, this is not a real solution, so that's why I'm suggesting the approaches outlined above.
Note that part of second solution is already in the Loki sources, but commented out:
```
      var getENV = function () {
        // if (typeof global !== 'undefined' && (global.android || global.NSObject)) {
        //   //If no adapter is set use the default nativescript adapter
        //   if (!options.adapter) {
        //     var LokiNativescriptAdapter = require('./loki-nativescript-adapter');
        //     options.adapter=new LokiNativescriptAdapter();
        //   }
        //   return 'NATIVESCRIPT'; //nativescript
```

**Comment by obeliskos** [comment]
I think I get what is going on...  I made a few fixes which should resolve this issue.  Feel free to try out and let me know your results.

Our nativescript adapter is separate module and our feature detection was commented out because we can't require it and remain browserify compatible.  I am (now) letting the fallback be 'no persistence adapter'.

Separate from your problem, if you were running in NATIVESCRIPT or any other environment which is not properly environment detected, you could pass in 'MEMORY' to use our LokiMemoryAdapter.   If you never intend to call save or load, you can pass in any other string like 'NA' to bypass environment detection and leave the persistence adapter null.

**Comment by dnalor** [comment]
I tested it, and it does fix the issue. There is a small error:
```
04-23 21:52:28.050  2242  2242 W System.err: TypeError: Cannot read property 'adapter' of undefined
04-23 21:52:28.050  2242  2242 W System.err: File: "file:///data/data/net.nexus0.lms.LMSlib2go/files/app/tns_modules/lokijs/src/lokijs.js, line: 674, column: 23
04-23 21:52:28.050  2242  2242 W System.err: StackTrace: 
04-23 21:52:28.050  2242  2242 W System.err: Frame: function:'getENV', file:'file:///data/data/net.nexus0.lms.LMSlib2go/files/app/tns_modules/lokijs/src/lokijs.js', line: 674, column: 24
```
Solution:
```
      var getENV = function () {
        if (typeof global !== 'undefined' && (global.android || global.NSObject)) {
           // If no adapter is set use the default nativescript adapter
           if (options && !options.adapter) {
             //var LokiNativescriptAdapter = require('./loki-nativescript-adapter');
             //options.adapter=new LokiNativescriptAdapter();
           }
           return 'NATIVESCRIPT'; //nativescript
        }
```
After changing that, the issue should be solved. Thanks.
