### ISSUE TITLE
Sharing a db between node and browser

### ISSUE THREAD

**Issue by bgits** [techfort/LokiJS#555]
Lets say I generated a db `myDb.json` using node.js. How would loki support loading that json into a new DB in the browser?

**Comment by obeliskos** [comment]
you could ajax request it and use [db.loadJSON](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html#loadJSON) to load into a new loki db instance.

**Comment by bgvianyc** [comment]
That works loading the db, but the `collections` array is empty in the browser. Also worth noting the `ENV` property is 'NODEJS' in the browser.

**Comment by obeliskos** [comment]
It should work as that function is what we use internally when loading from disk...

Are you by chance partitioning?  If your database is under 50 or so megs on the node side, you should be fine with regular LokiFilesystemAdapter and even that is way to big to send as ajax for most purposes...   or would this be a specially controlled upload process of sorts?

**Comment by bgvianyc** [comment]
It being loaded into the bundle by webpack. Here is the example:
```
const JSONdb = require('../nycOpenData.json')
const JSONstring = JSON.stringify(JSON);

db.loadJSON(JSONstring);
db.loadDatabase({}, () => {
      console.log(db);
});
 
```

nycOpenData.json is about 500k

**Comment by obeliskos** [comment]
I think your example has variable name typo where you are calling stringify().

If you are getting an object then call [db.loadJSONObject](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html#loadJSONObject) instead.

Here is [example deserializing from string](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/164c9ebf62abcb61e8c52a3df3c4158a/raw/ccf9611bff7847bd0011c9a3831f5bfdee9154b1/deserializeFromString).

**Comment by bgvianyc** [comment]
I don't think that is the problem because only this solution works:

```
const JSONdb = require('../nycOpenData.json')
db.loadJSONObject(JSONdb);

db.loadDatabase({}, () => {
Object.assign(db.collections, JSONdb.collections);
});
```
Without Object.assign it has no collection. I'm attaching the actual json (it's a public dataset).
[nycOpenData.json.zip](https://github.com/techfort/LokiJS/files/902529/nycOpenData.json.zip)

**Comment by obeliskos** [comment]
So you shouldn't need to call loadDatabase at all since your loading manually but I cam look at your sample file later today

**Comment by obeliskos** [comment]
Yea it works for me in node at least with the following code : 

```javascript
const loki = require("lokijs");
const JSONdb = require('../nycOpenData.json')

// Example showing deserializing from a string
var db = new loki('sandbox.db');

db.loadJSONObject(JSONdb);

db.collections.forEach(function (coll) {
  console.log("coll '" + coll.name + "' has " + coll.data.length + " records.");
});

```

**Comment by bgvianyc** [comment]
Wonder if it works for you using that code in the browser? You likely would have to bundle.

**Comment by obeliskos** [comment]
I've think I've tried enough varieties to conclude loki is probably working correctly.  

You should try the basic successful methods I have posted above and use whatever diagnostic capabilities are available to you to figure out where it stops working for you.  Check sizes of json (possibly by doing a JSON.stringify) and inspect the object collections in that object to see if collections array is empty before passing that object into loadJSONObject.

Let me know if you find anything to suggest otherwise but this seems beyond the scope of loki at this point.
