### ISSUE TITLE
Projection with LokiJS to show specified fields only

### ISSUE THREAD

**Issue by vasyl-shumskyi** [techfort/LokiJS#557]
Can projection be used with LokiJS to show specified fields only? 
Simular to https://docs.mongodb.com/manual/reference/method/db.collection.find/#find-projection

Thanks!

**Comment by obeliskos** [comment]
I think you'd have to do a javascript array map() on the results... 

in theory we could add our own map or project function which accept an object to control fields / mapping... if we did that you could persist that (along with the database) if using in collection transforms
