### ISSUE TITLE
How to sync a lokiJs indexeddb based database between two browser?

### ISSUE THREAD

**Issue by hz0324** [techfort/LokiJS#559]
Hi, 

We are building a reading app that using Lokijs store some computation results. It's an web app, so we use the LokiIndexedAdapter for persistence.
Our user may upload their books as along with the books' reading info to our server and resume reading from another web browser.

How can we sync the Lokijs persistent data between two browser?
Thanks.

**Comment by obeliskos** [comment]
well lokijs has a [changes api](https://github.com/techfort/LokiJS/wiki/Changes-API) you might post to server... your server would either need to parse the json or run isomorphically using lokijs itself
