### ISSUE TITLE
"Data is undefined" thrown when using loadDatabase in browser

### ISSUE THREAD

**Issue by chimon2000** [techfort/LokiJS#56]
To verify that this was an issue, I made a simple index.html file w/ the following code (taken from the docs)

```javascript
    var db = new loki('test', { env: 'BROWSER'}),
            db2 = new loki('test', { env: 'BROWSER'});

    var users = db.addCollection('users');
    users.insert({
        name: 'joe'
    });
    users.insert({
        name: 'john'
    });
    users.insert({
        name: 'jack'
    });
    console.log(users.data);
    db.saveDatabase();

    db2.loadDatabase(function () {
        var users2 = db2.getCollection('users')
        console.log(users2.data);
    });
```

`loadDatabase` breaks in the following code snippet (which exists in two areas):

```javascript
        if (localStorageAvailable()) {
          self.loadJSON(localStorage.getItem(this.filename));
          cFun(null, data);
        } else {
          cFun(new Error('localStorage is not available'));
        }
```

Data is undefined and an error is thrown. I've verified that removing data from the callback resolves the issue.

**Comment by techfort** [comment]
Thanks for flagging this Ryan.
As it is a callback that cFun looks like it was meant to be a
cFun.call(null, data);
Would you be able to test if that works? I won't be in front of a pc for
a few days and this seems a  pretty major bug.

joe

**Comment by chimon2000** [comment]
That alone didn't work. Data being undefined but referenced like a global variable still causes that nasty error to get thrown. 

Assuming that you want the localStorage / BROWSER version to work just like the NODEJS version, the following

````javascript
            var data = localStorage.getItem(this.filename);

            self.loadJSON(data, options || {});
            cFun.call(null, data);
````

worked fine and may suffice as a solution.

**Comment by techfort** [comment]
If you want to submit a PR i'm happy for you to get the credit for it.
Otherwise I'll see if @obeliskos has time to address this.

**Comment by chimon2000** [comment]
PR Submitted. Thanks!

**Comment by obeliskos** [comment]
I needed to modify the call to just cFun(null, data) instead of the cFun.call which appears to treat the first param as a 'this' context before mapping the other args so the data was being mapped to err.  I suppose we could have just passed this as first param but I don't know that we need that context to a user function.

**Comment by obeliskos** [comment]
Re-opening to allow time for all to review changes
