### ISSUE TITLE
insert/clone same data in 2 collections

### ISSUE THREAD

**Issue by sellou** [techfort/LokiJS#566]
Hi,
I am trying to use loki for storing binary data in memory. I created 2 collections with this configuration : 
{name, unique  : ['i'], indices : ['s']} then generated an array just for testing:
`let buf = new ArrayBuffer(1024) for (let i =0; i < 4; ++i) arr.push({ i: i, s: 0, d: buf });` 

I used then the insert method. For one collection, no problem but for the second I got "Document is already in collection, please use update()". In real case scenarios, I might have the same 'i' and 's' fields but different 'd' buffers. I expected no trouble saving these in different collections. Is this expected ? When I tried with 2 different arrays, I had no issue.

Then I tried with the clone param set to true. With 'shallow' option, I get 

`obj[idx].hasOwnProperty is not a function
    at insertMeta (http://127.0.0.1:8080/js/libs/lokijs.min.js:2:27802)
    at insertCallback (http://127.0.0.1:8080/js/libs/lokijs.min.js:2:28719)
    at http://127.0.0.1:8080/js/libs/lokijs.min.js:1:8408
    at Array.forEach (native)
    at Collection.LokiEventEmitter.emit (http://127.0.0.1:8080/js/libs/lokijs.min.js:1:8311)
    at Collection.insert (http://127.0.0.1:8080/js/libs/lokijs.min.js:3:2500)`

i didn't get an error with 'jquery-extend-deep', but as I will not have any nested objects so I thought shallow could be the most appropriate approach.

**Comment by obeliskos** [comment]
I think there was an issue with our 'shallow' clone method, it should be fixed in main branch now.  Let me know if that works for you.

If you only need to support newer browsers/node I also added 'shallow-assign' cloneMethod which may be faster but might not be supported by older browsers.

**Comment by sellou** [comment]
It works fine with the fix, thanks. I run some benchmarks and found out that shallow and shallow-assigned performance are very close.

**Comment by obeliskos** [comment]
ah, great... thanks

**Comment by obeliskos** [comment]
I think this is resolved, closing...
