### ISSUE TITLE
filter query with two params does not working :(

### ISSUE THREAD

**Issue by darknos** [techfort/LokiJS#567]
```
var db = new loki('sandbox.db');

// Add a collection to the database
var items = db.addCollection('items');

// Add some documents to the collection
items.insert({z:1, name : 'mjolnir', owner: 'thor', maker: 'dwarves' });
items.insert({z:1, name : 'gungnir', owner: 'odin', maker: 'elves' });
items.insert({z:2, name : 'tyrfing', owner: 'Svafrlami', maker: 'dwarves' });
items.insert({z:2, name : 'draupnir', owner: 'odin', maker: 'elves' });

logText('odins items');
logObject(items.chain().find({ 'owner': 'odin'}).find({'z':2}).data() );
//one record as expected

logObject(items.chain().find({'owner': 'odin', z:2}).data() );
//BUG! expected one but received two


// This statement sends to Inspector
inspectObject(db);
```

expected result was
```
[
  {
    "z": 2,
    "name": "draupnir",
    "owner": "odin",
    "maker": "elves",
    "meta": {
      "revision": 0,
      "created": 1495809690258,
      "version": 0
    },
    "$loki": 4
  }
]
```

but i got 

```
[
  {
    "z": 1,
    "name": "gungnir",
    "owner": "odin",
    "maker": "elves",
    "meta": {
      "revision": 0,
      "created": 1495809690258,
      "version": 0
    },
    "$loki": 2
  },
  {
    "z": 2,
    "name": "draupnir",
    "owner": "odin",
    "maker": "elves",
    "meta": {
      "revision": 0,
      "created": 1495809690258,
      "version": 0
    },
    "$loki": 4
  }
]

```

**Comment by darknos** [comment]
in mongodb concept 
```
db.inventory.find( { status: "A", qty: { $lt: 30 } } )
```
The operation corresponds to the following SQL statement:
```
SELECT * FROM inventory WHERE status = "A" AND qty < 30
```

**Comment by Kanaye** [comment]
Hi @darknos,

you need to use the $and operator so the query from your example would look like:
```javascript
logObject(items.chain().find({$and: [{'owner': 'odin'},{z:2}]}).data());
```
You can run the full updated example [here](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/Kanaye/bc56b153d8ae823a0c1c9f311a80eda0/raw/9ee8e34515d4ec3449c113cc71db149f9bdca480/query-and.js).

You can read more about the supported operators [here](https://github.com/techfort/LokiJS/wiki/Query-Examples).

**Comment by darknos** [comment]
It's a pity. I choose LokiJS as offline options to existing mongodb api and I was hope that API are the same in basic operations. :(

**Comment by obeliskos** [comment]
yea @Kanaye is correct, we added $and at the same as $or functionality and at the time did not consider the syntax you described.

I'll look into if this can be done easily the next time i get the time.

**Comment by darknos** [comment]
at least throw an exception if you got more then one key in a query filter statement. otherwise it is a bit confusing. :(

**Comment by obeliskos** [comment]
While we don't claim full mongo compatibility, this syntax was able to be easily implemented so I added it on main branch.  If you care to try it out, feel free to confirm if that is working for you.

**Comment by darknos** [comment]
Great job! thank you very much
