### ISSUE TITLE
Cannot resolve module 'loki-indexed-adapter'

### ISSUE THREAD

**Issue by mchavaillaz** [techfort/LokiJS#568]
Hi everyone

I'm building an angular2 App with LokiJS 1.4.3 and I'm stuck with the following error message:

```
Cannot resolve module 'loki-indexed-adapter'
```

I'm building my app with webpack.

In my package.json I'm using the following typescript definition for lokiJS

```
"@types/lokijs": "1.2.30"
```

Here is my service that uses lokiJS:

```
import {Injectable} from '@angular/core';
import loki = require('lokijs');
import lokiAdapter = require('loki-indexed-adapter');

@Injectable()
export class MasterpiecesService {
	private composers: LokiCollection<any>;
	private db: Loki;

	constructor() {
		let myAdapter: LokiIndexedAdapter = new lokiAdapter('myAdapter');
		this.db = new loki('masterpieces.db', {adapter: myAdapter});
		this.composers = this.db.addCollection('composers', {unique: ['name'], indices: ['name']});
	}

	public saveComposer(value): void {
		try {
			let newComposer = this.composers.insert({name: value});
		} catch (error) {
			console.info("Already exist");
		}
	}

	public getComposerByName(name): any {
		let result: LokiResultset<any> = this.composers.where((obj: any) => {
			return obj.name == name;
		});
		return result;
	}
}
```

After searching in the opened issues, I tried another syntax to import lokiJS like this:

```
import * as loki from 'lokijs';
import * as lokiAdapter from 'loki-indexed-adapter';
```

But the issue is the same.

I had a look in the index.d.ts for lokiJS and found the following code:

```
declare var LokiIndexedAdapterConstructor: {
    new (filename: string): LokiIndexedAdapter;
}

declare module "loki-indexed-adapter" {
    export = LokiIndexedAdapterConstructor;
}

declare var LokiConstructor: {
    new (filename: string, options?: LokiConfigureOptions): Loki;
    LokiOps: LokiOps;
    Collection: LokiCollection<any>;
    KeyValueStore: LokiKeyValueStore<any, any>;
}

declare module "lokijs" {
    export = LokiConstructor;
}
```
The import of the module module "lokijs" works but not for the module "loki-indexed-adapter".

What am I doing wrong?

Thank you for you help.

**Comment by obeliskos** [comment]
the loki indexed provider is currently bundled along with the lokijs package and not its own package... 

for stock node you would probably : 
```javascript
const lokiAdapter = require("node_modules/lokijs/src/loki-indexed-adapter.js");
```
so i would guess : 
```javascript
import * as lokiAdapter from 'node_modules/lokijs/src/loki-indexed-adapter.js';
```

Let me know if that works... not the cleanest but should work...

**Comment by Kanaye** [comment]
In node you can also just do 
```javascript
const indexedAdapter = require('lokijs/src/loki-indexed-adapter.js');
```
what is (imho) a little bit cleaner because you hand over the resolving of the module path to node.
I'd guess it also works the same with ``import`` but I haven't tried it.

**Comment by mchavaillaz** [comment]
Thank you guys for your quick answers.

The solutions that work are:

```
const lokiAdapter = require("../../../node_modules/lokijs/src/loki-indexed-adapter.js");
```
and the more elegant syntax

```
const lokiAdapter = require("lokijs/src/loki-indexed-adapter.js");
```
When I try using the 'import' syntax as follow

```
import * as lokiAdapter from 'node_modules/lokijs/src/loki-indexed-adapter.js';
```

or

```
import lokiAdapter = require('node_modules/lokijs/src/loki-indexed-adapter.js');
```

It still gives me the error

```
Cannot find module 'lokijs/src/loki-indexed-adapter.js'
```

I can now go on with LokiJS
Thank you very much :).

**Comment by robertdavid010** [comment]
> import * as lokiAdapter from 'node_modules/lokijs/src/loki-indexed-adapter.js';

I did find this to work (Node/Webpack/Browser): 
`import * as LokiIndexedAdapter from 'lokijs/src/loki-indexed-adapter.js';`
