### ISSUE TITLE
Can't get persistent data in Cordova (using cordova-fs-adapter)

### ISSUE THREAD

**Issue by chasebank** [techfort/LokiJS#569]
When I serve the app using the Phonegap Desktop app, Chrome pops up a dialog asking me to allow storing files on this device. So, that's promising... and everything appears to work as expected, but the data isn't persistent. If I refresh the page, all data is lost. This is also the case when I build the app using Phonegap Build and test on my iPhone. If I close the app, data is lost.

I've noticed an FS adapter console error: `Unable to resolve local file system URL`, but I'm not sure how to fix that.

Here's how I'm creating the database:

```
var loki = require('lokijs'),
    products,
    prices;

var LokiCordovaFSAdapter = require("loki-cordova-fs-adapter");

var adapter = new LokiCordovaFSAdapter({"prefix": "loki"}),
    db = new loki('pricelog_db', {
        autosave: true,
        autosaveInterval: 1000,
        adapter: adapter
    });
```

Which is all in a store.js file, which is then imported into my main js file (this is a Vue app). I'm confused about the whole device ready thing, and wonder if this is related to that? Sorry if I'm leaving out any relevant info or have made some glaring mistake. But any advice would be appreciated, thanks!

**Comment by obeliskos** [comment]
You should probably be passing 'autoload' and 'autoloadCallback' options to loki constructor similarly to 'Web Quickstart' examples here : 
https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters

**Comment by chasebank** [comment]
Hi @obeliskos , thanks for the quick reply, and I appologize for my delay. I've been out of town all week.

So, that looks promising, especially autoload, but I'm still having issues. First, if I follow that example directly with the callback, everything breaks, I guess because the callback function isn't called and my collections aren't added? I get a ton of console errors. It looks like getting the data via `.data()` no longer works. If I pull the .addCollections out of the callback, everything works again, but I still don't have persistent data.

```
var loki = require('lokijs');

var LokiCordovaFSAdapter = require("loki-cordova-fs-adapter");

var adapter = new LokiCordovaFSAdapter({"prefix": "loki"}),
  db = new loki('pricelog.db', {
    autoload: true,
    autoloadCallback : databaseInitialize,
    autosave: true,
    autosaveInterval: 1000,
    adapter: adapter
  });

if(!db.getCollection('products')){
  db.addCollection('products');
}
if(!db.getCollection('prices')){
  db.addCollection('prices');
}

function databaseInitialize() {
  if(!db.getCollection('products')){
    db.addCollection('products');
  }
  if(!db.getCollection('prices')){
    db.addCollection('prices');
  }
}

let store = {
  productsData: db.getCollection('products'),
  pricesData: db.getCollection('prices'),
};

export default store;
```

As a sidenote, I'm confused about databasename vs. databasename.db vs. databasename.json   Does it matter? I'm seeing all three in different examples...  My data is formatted as json though. According to the loki-cordova-fs-adapter readme it should be `var db = new loki("dbname", {adapter: adapter});`

**Comment by obeliskos** [comment]
Hmm well autoloadCallback is asynchronous and i'm not sure that the export is allowed to be returned asynchronously.  You also have both async and sync 'init' logic.

It would probably be better though to return a function which accepts a callback and move all your logic into that function maybe something like : 

```javascript
var loki = require('lokijs');
var LokiCordovaFSAdapter = require("loki-cordova-fs-adapter");

function storeFactory(callback) {
  var adapter = new LokiCordovaFSAdapter({"prefix": "loki"}),
    db = new loki('pricelog.db', {
      autoload: true,
      autoloadCallback : function() { databaseInitialize(callback) },,
      autosave: true,
      autosaveInterval: 1000,
      adapter: adapter
    });

function databaseInitialize(callback) {
  if(!db.getCollection('products')){
    db.addCollection('products');
  }
  if(!db.getCollection('prices')){
    db.addCollection('prices');
  }

  let store = {
    productsData: db.getCollection('products'),
    pricesData: db.getCollection('prices'),
  };

  callback(store);
}

export default storeFactory;
```

**Comment by chasebank** [comment]
Thanks again @obeliskos   I was originally getting a syntax error `'import' and 'export' may only appear at the top level` which appeared to mean babel wasn't running on the file, but it turned out that storeFactory was missing a closing `}` and that seemed to fix that error.

But now I'm still getting the same console errors I had before, when I tried using a callback. For example: `Cannot read property 'productsData' of undefined`.

Originally, I was using
exporting: `export default store;`
importing: `import store from './store.js'`
accessing: store.productsData.data

Now that store is wrapped in the storeFactory function, I'm
exporting: `export default storeFactory;`
importing: ?
accessing: ?

Both store and storeFactory show as undefined if I console.log them

Again... thanks so much for taking the time to look in to this.

**Comment by chasebank** [comment]
@obeliskos I have a CodePen project running with this https://codepen.io/chasebank/project/editor/AKKqar/

Cordova doesn't work on it obviously, but I'm just trying to get this db running.

If I import the storeFactory function, and call it, I see `[LokiCordovaFSAdapter] loading database` in the console, so something is working... But I still can't figure out how to access any of the data. Everything shows up as not defined.

**Comment by obeliskos** [comment]
Well I would think the easiest way would be to do this in main : 

```javascript
import storeFactory from './store.js';
var globalStore;

storeFactory(function(store) {
  globalStore = store;

  console.log(globalStore.productsData.find());
  console.log(globalStore.pricesData.find());
});
```
The point being that the callback function will be  invoked whenever the async loading/initialization is complete.  

Every time you call that function you are spinning up a new lokijs instance so re-use that store object returned from factory and don't call it multiple times.  Later, if you ever wanted to support multiple database instances (with separate filenames) you might add a filename parameter to your storeFactory function.  If you wanted to expand the 'store' functionality into a class with its own internal variables you can do that as well.

**Comment by obeliskos** [comment]
Oh also, you might need to (within store.js) move the db variable outside of the function to be global singleton (for now).

**Comment by chasebank** [comment]
Ok... I have Loki working now, but still no persistent data. I started a fresh clean test project, and tried a different approach to avoid the whole export default/import of the data.

I wasn't sure a storeFactory function was needed if I'm not exporting anything?

Also, if I called the databaseInitialize function as is with the callback, I was getting an error "callback is not a function", so I just removed it, along with the store var

```
var loki = require('lokijs');
var LokiCordovaFSAdapter = require("loki-cordova-fs-adapter");

var adapter = new LokiCordovaFSAdapter({"prefix": "loki"});
var db = new loki('pricelog.db', {
  autoload: true,
  autoloadCallback : function() { databaseInitialize(callback) },
  autosave: true,
  autosaveInterval: 1000,
  adapter: adapter
});

function databaseInitialize() {
  if(!db.getCollection('products')){
    db.addCollection('products');
  }
  
  db.getCollection('products').insert([{name:'Tacos'}, {name:'Moar Tacos'}])
}

databaseInitialize();

console.log(db.getCollection('products'))
```
Everything appears to work, except the persistence. I can add new items, but the new data clears when I close the app.

I'm adding new items with
```
db.getCollection('products').insert({
      name: newProduct
    })
```
Is there some special way to insert when you're using an adapter, or does that look right? The new data appears to get added correctly, with all the auto-generated Loki metadata...

Here's what I get in my console 

```
[LokiCordovaFSAdapter] loading database
build.js:6 Uncaught TypeError: Cannot read property 'dataDirectory' of undefined
    at t.value (build.js:6)
    at t.value (build.js:6)
    at d.loadDatabaseInternal (build.js:6)
    at build.js:6
    at d.throttledSaveDrain (build.js:6)
    at d.loadDatabase (build.js:6)
    at build.js:6
(index):87 adding proxy for File
(index):87 Received Event: deviceready
(index):87 Persistent fs quota granted
```
The dataDirectory bit is concerning... I'm assuming that is related to my data not persisting, but no idea what the cause is. I'm leaning toward that being more of a Cordova problem than Loki. But does anything stand out as incorrect about my implementation?

Thanks again for your help. My project was just about finished but now I'm at a complete stand still until I can fix this. So I really appreciate your suggestions!

**Comment by obeliskos** [comment]
Your example looks good except I would pass the autoloadCallback constructor option as : 
```javascript
  autoloadCallback : databaseInitialize,
```

Also, your console.log(db.getCollection('products')) will always be null since it is not waiting for database to be initialized.  You will have to async bootstrap all logic that needs to happen after database loading similar to how [quickstart2](https://github.com/techfort/LokiJS/blob/master/examples/quickstart2.js) uses a runProgramLogic() method.

While I have not used the [cordova adapter](https://github.com/cosmith/loki-cordova-fs-adapter) myself, its main page states that it depends on the apache [cordova-plugin-file](https://github.com/apache/cordova-plugin-file) plugin to work.  Have you added that plugin?

The error message seems to imply that [this line of code](https://github.com/cosmith/loki-cordova-fs-adapter/blob/master/src/loki-cordova-fs-adapter.es6L101) is causing the error because 'cordova.file' probably is not set... maybe because the plugin has not been added.

Some other possible relevant fixes : 
https://stackoverflow.com/a/34703752
https://stackoverflow.com/a/27944520

**Comment by chasebank** [comment]
Would it mean anything to you if the console wasn't returning null? For what it's worth, I actually do get the collection `Collection {name: "products", data: Array(2), idIndex: Array(2), binaryIndices: Object, constraints: Object…}`

But if I follow that quickstart, I assume I still run the databaseInitialize function after all that?

Like this?
```
import Vue from 'vue';
import Vuex from 'vuex';

var loki = require('lokijs');
var LokiCordovaFSAdapter = require("loki-cordova-fs-adapter");

var adapter = new LokiCordovaFSAdapter({"prefix": "loki"});
var db = new loki('pricelog.db', {
  autoload: true,
  autoloadCallback : function() { databaseInitialize(callback) },
  autosave: true,
  autosaveInterval: 1000,
  adapter: adapter
});

function databaseInitialize() {
  var products = db.getCollection('products');
  
  if(!db.getCollection('products')){
    db.addCollection('products');
  }
  
  runProgramLogic();
}

function runProgramLogic() {
  var products = db.getCollection('products');
  
  products.insert([{name:'Tacos'}, {name:'Moar Tacos'}])
}

databaseInitialize();
```
And then I'd access that collection via `db.getCollection('products')`?

As for Cordova, I guess it looks like the adapter can't communicate with the local file system, but whether or not that failure is with the adapter or Cordova, I don't know...  I posted an issue on the adapter's repo and the author said he wasn't sure what the problem was.

I am indeed running the cordova-plugin-file plugin, which is suppose to facilitate accessing the device storage. As far as I can tell, it's running fine.

The fix in one of those stack threads was Cordova it'self not being initiated correctly (definitely not the problem). The other is related to making sure all this runs after "deviceready". That I'm foggy on and still working through. *Might* be related

**Comment by obeliskos** [comment]
I would try a hello world app with the cordova file system adapter to make sure that variable exist (and is not null) and to make sure it works.  (I guess making sure to wait for deviceready)  Make sure you can actually save a file to your device / emulator... cordova probably has different implementations of file system access depending on what OS it is running under so make sure it works your whatever environment you are currently running under.

Since you are no longer instantiating loki from with a separate module, just use : 
```javascript
autoloadCallback : databaseInitialize,
```
like i mentioned previously.... you no longer need to callback outside of this module which was the only reason we wrapped an anonymous function around it (before).

Your autosaveInterval is also too low... if for some reason it hasn't finished loading after one second it will try to save an empty database.  I would raise that at least 2000 or 3000.

**Comment by chasebank** [comment]
Sorry about the callback, I had that corrected but copy/pasted the wrong version into my message. Trying a COMPLETELY vanilla hello world test was a good idea. I should have done that from the beginning.

The database is finally initializing *after* deviceReady, which is apparently very important, so that's good. I also see that my earlier error with 'dataDirectory' is no longer a problem, since the cordova-plugin-file is showing a directory in the console. You can `console.log(cordova.file);` to see that.

Here's my full browser console:
```
adding proxy for File
Preparing.js:174 Persistent fs quota granted
build.js:7460 Received Event: deviceready
build.js:7421 Object
    applicationDirectory: "http://localhost:8000/"
    applicationStorageDirectory: null
    cacheDirectory: "filesystem:file:///temporary/"
    dataDirectory: "filesystem:file:///persistent/"
    documentsDirectory: null
    externalApplicationStorageDirectory: null
    externalCacheDirectory: null
    externalDataDirectory: null
    externalRootDirectory: null
    sharedDirectory: null
    syncedDataDirectory: null
    tempDirectory: null__proto__: Object
build.js:63 [LokiCordovaFSAdapter] loading database
build.js:118 Uncaught LokiCordovaFSAdapterError
```

And that adapter error is coming from
```
_getFile: {
            value: function _getFile(name, handleSuccess, handleError) {
                var _this = this;

                window.resolveLocalFileSystemURL(cordova.file.dataDirectory, function (dir) {
                    var fileName = _this.options.prefix + "__" + name;
                    dir.getFile(fileName, { create: true }, handleSuccess, handleError);
                }, function (err) {
                    throw new LokiCordovaFSAdapterError("Unable to resolve local file system URL" + JSON.stringify(err));
                });
            }
        },
```
I posted this on the adapter github a few days ago but no response yet. I threw the hello world project into a repo https://github.com/chasebank/lokijs-cordova  Really the only thing I've added is Loki, the adapter, and the corova-plugin-file.

I suppose I'll close this, since the problem is more likely something I'm still doing wrong, or an issue with the adapter. Thanks again for your help though

**Comment by chasebank** [comment]
@obeliskos  So, I spent most the last few days trying to solve this 'once and for all' and still can't get it. I'd be **eternally** grateful if you or another contributor could make a cordova quickstart example. I would think my repo, linked above, would be as good of a starting point as you can get.

I can't find anything to reference, aside from what we've discussed here. There's a few [solid examples](https://gonehybrid.com/how-to-use-lokijs-for-local-storage-in-your-ionic-app/) using the cordova-fs-adapter with Ionic, but they're also using `loki-angular.js`, and setting up the database within an angular module.

I can't find a single basic, vanilla, hello world cordova example.

My only other option is trying PouchDB or something, which will surely bring new nightmares... Loki seems like the perfect all-around solution though!

At any rate, I appreciate all the help you've given so far

**Comment by obeliskos** [comment]
No luck so far... mainly running from windows10.   What OS are you running this on and/or are you running in an emulator?  It would seem all the errors i encounter would probably not occur on-device... if it does work on device but not in chrome we can detect environment at runtime and maybe use indexed adapter while in development.

The main error i get is : 
```
SecurityError: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources
```
I have tried launching chrome with the following option (not positive if it needs it), but it did not help : 
```
--allow-file-access-from-files
```

I tried rewriting (inline) adapter with basic loadDatabase and saveDatabase methods, maybe it will help and you will have better luck with it.  

Here is a reworked version of your 'index.js' file : 
[index.js.txt](https://github.com/techfort/LokiJS/files/1100454/index.js.txt)

I tried a crude browser extension emulator but it didn't seem to work either, i may try visual studio emulator later.

**Comment by chasebank** [comment]
Also on Windows 10. Haven't ran any emulators, but I do have an Apple dev account and have been installing test apps on my iPhone. Unfortunately I can't debug errors on it... but I'm spitting out the data into a pre tag so I can see it, and added an input to insert. Not seeing persistence...

I swear... I figured out how to work with basic Loki, designed an entire UI, built an app with vue.js, figured out how to create Apple author certificates on a Windows machine... Even did some user testing. But getting some basic, persistent, client-side data is taking longer than all of that 0_0

Does [this](https://www.neontribe.co.uk/cordova-file-plugin-examples/) tell you anything? Looks very similar to your adapter, but I can't even get that working without an error. It's default, non-descript 'Unknown error' from his error handler.

One of the things that keeps coming up in my reading is content security policies set in the HTML, like
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: cdvfile://* content://* file://*;">
```

Seems a lot of issues are caused/solved by those params. I've played with them but haven't had any luck. There's also some [content security stuff](http://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/index.html#content-security-policy) related to the whitelist plugin.

Another thing is the data file path. Cordova is serving the app at localhost, but Chrome is showing the dataDirectory at file:///...

After reading [this](https://stackoverflow.com/questions/34283600/encodingerror-when-cordova-plugin-file) I tried
```
var pathToFile = cordova.file.applicationDirectory + 'persistent/' + dbname;
window.resolveLocalFileSystemURL('filesystem:' + pathToFile, function (fileEntry) {
...
window.resolveLocalFileSystemURL('filesystem:' + cordova.file.applicationDirectory + 'persistent/'', function (directoryEntry) {
```
Which returns `filesystem: http://localhost:8000/persistent/products`. That removes the security error, but gives `NotFoundError: A requested file or directory could not be found at the time an operation was processed.` So, it looks like your code is looking in the right spot, just not able to write... 

If I'm reading [this](https://stackoverflow.com/questions/37892253/how-to-save-file-locally-in-apache-cordova-using-file-plugin/37916371?noredirect=1#comment76490226_37916371) right, `cordova.file.dataDirectory` theoretically shouldn't work in browsers. But I tried `cordova.file.syncedDataDirectory` on my phone (same thing, but it syncs to iCloud and is what they suggest for iOS) and that doesn't work either.

I'm almost glad to hear that `--allow-file-access-from-files` doesn't fix this, because that keeps things consistent with it not working in iOS webview.

**Comment by obeliskos** [comment]
Yea they definitely should smooth out the rough edges over native deployments with javascript debug console or polyfill storage on chrome browsers to use sandbox safe storage mechanism.  I tried cordova run windows but that appx deploy loads window but it closes instantly... so i can't debug anything.  'cordova run osx' on mac osx load window but i have no javascript debug console.

My google searches are starting to return messages you are commenting on but I'm thinking the cordova file plugin is geared towards native host environments where browser is less sandboxed than the "cordova run browser" and chrome provides.   I would need to figure out a good way to debug javascript in those less 'inspectable' containers though.

Would localstorage be an acceptable "temporary fix" for ios just to see your app up and running (at least until you figure out best practice for native storage) ?  The following works for me in chrome and localstorage should be supported on all platforms : 
```javascript
    var db = new loki('products', {
      autoload: true,
      autoloadCallback : databaseInitialize,
      autosave: true,
      autosaveInterval: 3000,
      env:"BROWSER"
    });
```

**Comment by Kanaye** [comment]
I have created a [simple todo test app](https://github.com/Kanaye/LokiCordovaExample) using only lokijs, the cordova-fs-adapter and the dom api.
I couldn't test on a windows or ios device but it works fine on android.
@chasebank can you test it on ios/windows.
You should only need to clone/download the repository and run ``npm i --save-dev`` and ``cordova add <your platform>``.

**Comment by chasebank** [comment]
## Progress!

Works flawlessly on iOS! Data persists after closing the app and even restart. [Cordova docs recommend](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html#ios-persistent-storage-location) adding `<preference name="iosPersistentFileLocation" value="Library" />` to the config.xml, similar to how you have the location specified for Android, But even without that, seems to work fine...

On Windows, we're back where we started, with an error on getFile
```
_getFile: {
            value: function _getFile(name, handleSuccess, handleError) {
                var _this = this;

                window.resolveLocalFileSystemURL(cordova.file.dataDirectory, function (dir) {
                    var fileName = _this.options.prefix + "__" + name;
                    dir.getFile(fileName, { create: true }, handleSuccess, handleError);
                }, function (err) {
                    throw new LokiCordovaFSAdapterError("Unable to resolve local file system URL" + JSON.stringify(err));
                });
            }
        },
```

I'm seeing conflicting things on whether or not you can use `cordova.file.dataDirectory` on the browser platform. If you check the [docs on where to store files](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html#where-to-store-files) you'll notice "browser" isn't listed for any of those locations. Some Stack posts say you have to manually write out the path. I've seen a few others that say dataDirectory should work. I haven't been able to get anything to work...

If that is indeed the problem, perhaps the adapter should be extended to allow changing the path (if that isn't an option already?). Otherwise the actual adapter has to be edited for each platform. iOS has a similar concern, dataDirectory doesn't back up or sync, for that you have to use `cordova.file.syncedDataDirectory`. But if you change that in the adapter, I believe you'd have to change it back for Android.

But for now, I took a page from @obeliskos's earlier dev work-around, using indexed adapter until I'm ready to build.
```
// BROWSER PLATFORM
var LokiIndexedAdapter = require("lokijs/src/loki-indexed-adapter.js");
```
And then within the deviceReady listener
```
  // var adapter = new LokiCordovaFs({ prefix: 'todos' });
  // BROWSER PLATFORM
  var adapter = new LokiIndexedAdapter("HelloWorld");
```

I also removed the saves from the add and delete handlers, and added autosave. Still works... Can't believe my eyes lol

**Comment by obeliskos** [comment]
@Kanaye thanks for that example... since that is a known 'working' project (and when i run it with platform 'browser' i still get the same error/exception), that must mean the error we have been dealing with stems from browser/chrome sandboxing as @chasebank has pointed out.

Kanaye's project ran unmodified with cordova platform osx.   I have installed visual studio 2017 community (with visual studio cordova development components selected during vs install) on windows 10.  I managed to get chasebank's example to run through visual studio ide/debugger as well.  

@chasebank : at a minimum, I had to fix your autocallback syntax (should be just 'autoloadCallback: databaseInitialize') and remove the extra manual call to databaseInitialize and your example ran fresh from your github repo clone.

**Comment by chasebank** [comment]
Awesome. Thanks so much to you both. I'm cruising right along now... I have Loki working with Vue and even Vuex (Vue's version of React's Redux).

Hopefully someone else stumbles onto this thread and benefits from it!

**Comment by mesqueeb** [comment]
@chasebank I'm making a cordova app for Android and iOS and I need to save data that will be persistent.

After googling I stumbled on LokiJS and I'm now trying to implement it in my Cordova app.
I'm also using VueJS and Vuex.

I'm kinda afraid to use [loki-cordova-fs-adapter](https://github.com/cosmith/loki-cordova-fs-adapter) since that project was deprecated, and since then Cordova already supports indexedDB on iOS 10+.

I was trying to go through this thread, but could greatly benefit if you could summarise what you learned in a blog post on Medium or something? 🌝

It is my understanding that you as well use `loki-indexed-adapter` now instead of `cordova-fs-adapter`? 🌞

## My humble request

I don't need Windows, just iOS and Android, but is there any Repository you could share with me with a minimal implementation to save information via Loki and make that persistent on a Vue + Vuex + Cordova build?

Thanks so much!!! 💫

**Comment by chasebank** [comment]
@mesqueeb I'd be glad to share what I learned! I really should write a blog post like you suggest. (as you can see from just this thread alone, it was a process... I definitely learned a lot).

For better & worse, the whole progressive-web-hybrid-native-app scene is evolving rapidly, so I'm sure some of my stuff is already "old"... And even then, I've never been truly sure I know what I'm doing...

I'll actually re-visit the app I made soon, to add a feature, so that'll be a good time to re-familiarize myself and write a post. In the mean time hopefully I can answer some questions here.

IndexedDB persists data to localStorage. Are you familiar with the limitations of that? There's a storage limit (5 MB, not that big of a deal) but the major concern for me personally, was localStorage can be easily (and accidentally!) cleared by the user and/or OS. It's particularly concerning on iOS, because when device memory runs low, localStorage can be auto-deleted without warning. I believe localStorage is also **not** included in synced device back ups.

That's not always a problem. Something like app preferences (saved user location, interface settings like 'dark mode' etc.) aren't really important, so if they get cleared, it's not the end of the world. But for just about everything else, I wouldn't risk losing a user's data. But, it just depends on the use case...

If you already know all that and are comfortable with localStorage, then I suppose you can just use the indexed adapter, and all this gets much much simpler. You just need to get Cordova, Vuex and Loki to all work together.

But, if you need persistent ***native*** storage, then you end up down the deep rabbit hole that this thread was originally about.

So first, I'll ask, are you planning on just using localStorage? Or do you need the truly persistent native storage, like I did?

If you need true native storage, I'll tell you all about that in another post.

Also, I know you say you don't need Windows as a Cordova platform, but is your development computer Windows?

**Comment by mesqueeb** [comment]
Hi @chasebank
(I wrote a very long comment for about 20 minutes, but accidentally closed the tab...... 😐 and couldn't get it back when re-opening..... So here's the short version 😀)

I was unaware that IndexedDB persists data to localStorage! Thanks not good for my use case!
I was able to get indexedDB to work with Cordova, but as you say, it's not persistent, so bad in my case!!!
Is the cordova FS adapter: `loki-cordova-fs-adapter` one that uses _**native storage**_? I'd love to hear all about your rabbit hole that (hopefully) leads towards native storage. 😅

PS: I'm developing on macOS and building iOS and Android apps with Cordova (and Vue & Quasar)

**Comment by mesqueeb** [comment]
Hi @chasebank We ran into a real roadblock now we found out that almost all storage methods on cordova have the possibility to be wiped by iOS....
And we really only need to save just a few strings and that's it! But it must be utmost persistent.

Did you, in the end, ever figure out a way to introduce **real persistent storage** on iOS cordova?
After much further research I'm beginning to get real scared. XD
I did found this repo: [cordova-plugin-nativestorage](https://github.com/TheCocoaProject/cordova-plugin-nativestorage) but it seems outdated and from the issues I think cordova-ios v5 is not yet supported (and the devs are not maintaining it atm...)

If possible, could you have a quick look and let me know if that's something similar you went for?

**Comment by mesqueeb** [comment]
@chasebank was able to get persistent storage working on Cordova with help from this repo:
https://github.com/Kanaye/LokiCordovaExample

However, it seems to me that it works just like indexedDB. If you happen to know, how could I test out scenarios where an iPhone would normally erase indexedDB and force that event (eg. low memory) so I can check if my Cordova app really persisted the data via the (very outdated) cordova-fs-adaptor?

Cheers!!

**Comment by chasebank** [comment]
Hey @mesqueeb   Sorry about the delay! I didn't forget about you!

The same thing happened to me, with typing up a long post and losing it! And then things got busy and I just haven't had a chance to properly revisit until now.

Here's a very rough draft of a post, explaining what worked for me: https://dev.to/chase/vue-cordova-app-with-persistent-data-using-loki-js-5p-temp-slug-9365613?preview=8f8daa786bdc71f404b5808114c70f0e51a73fb5469a67511fd65f0ee76cfd006031607bcf246a65d134463a86280d66b5801769f938bb760e7c25ec

And here's a repo for reference: https://github.com/chasebank/vue-cordova-loki

Now, there's a major caveat with that repo. It's using [vue-cli-plugin-cordova](https://github.com/m0dch3n/vue-cli-plugin-cordova) to turn a normal Vue project into a Cordova one. That plugin is installed using the `vue add cordova` command.

That plugin is based on another one, which I used for my app, that is now deprecated.

In my experience with that older plugin there was some symlinks creating during the `vue add` command that were vital to Cordova working properly. But then when I committed my work to a git repo, and tried to pull it down to another computer, things didn't work, because those symlinks weren't syncing properly.

So, the point is, if you clone that repo and try to run it on your computer, I wouldn't be surprised if it doesn't work. Maybe all those problems are fixed in the new plugin. I haven't had a chance to test it yet.

But I suspect it's main use to you will be more of a code reference, in case something in the post doesn't make sense.

Also... I barely know what I'm doing lol. So if anything stands out to you as wrong, or if you find a better way, please let me know. But what's in that post, seemed to work for me.

Let me know if you have any questions.

**Comment by josephharveyangeles** [comment]
Hi @mesqueeb! Sorry to disturb and bother you with the same question. But you seem to have moved along with your project. If I'm understanding it correctly, `loki-cordova-fs-adapter` truly persists because unlike `indexedDB` it store your database on an actual file within a device using the `cordova-plugin-file`. That being said, how did your project went? Did you find any trouble using this?

I'm kinda on the same boat, I need a truly persistent storage for a little Quasar project I'm working on. I won't be storing a few strings though, I'll be using it as a local database. An offline app that you can _sync_ to the cloud, that kind of thing. I stumbled upon _PouchDB_ as well, which has an actual remote syncing support to Cloudant. The problem with _PouchDB_ is that it doesn't really have a clear way to add collections. 

Now, I'm here. A Loki sqlite-adapter is probably the best. But I guess I'll settle for this one for the moment. That's why I'm curious on what you ended up on implementing.

**Comment by josephharveyangeles** [comment]
I stumbled upon [RxDB](https://rxdb.info/adapters.html). Uses CouchDB under the hood but seems like it supports subcollections or via creating a schema that referenced a different collection. Looks promising.
