### ISSUE TITLE
Unusual behavior of offset and limit methods

### ISSUE THREAD

**Issue by asuroalex** [techfort/LokiJS#570]
I`am trying to get a set of items with the limit and offset methods.

`articles = collection.chain()
                .find()
                .limit(10)
                .offset(0)
                .data();`

I am getting 10 items as expected, but if I increase offset like this:

`articles = collection.chain()
                .find()
                .limit(10)
                .offset(10)
                .data();`

I am getting 0 items and not the expected 10 items.
If i set offset to 5 and limit to 10 I am getting 5 items.
If I set limit to 20 and offset to 10 I am getting 10 items.

If I set limit to 100 and offset to 110 and there are just 99 items in collection I am getting all 99 items and not the expected 0 items.

Is that the right behavior or did I do something wrong?

Tested with lokijs 1.2.5 and 1.4.5

**Comment by obeliskos** [comment]
Offset should be used before limit 

If you limit to 10 docs, the next chained op only has 10 docs to work against

**Comment by asuroalex** [comment]
Thanks for your response.
It is working as you says.

But what if I want to get docs with an offset of 100 and the are just 99 docs in the collection, why do I get all 99 docs?

Should I get the count of docs in the collection and then look if count is greater than the offset? 
Just like this?
```javascript
count = collection.find().length;
if (count > offset) {
//get next 10 docs
```
Or is there an other way?

**Comment by obeliskos** [comment]
My test doesn't behave as you describe... Can you post a sample gist for LokiSandbox?  Offset of 100 on set of 99 docs should yield empty results.  I can post example later if you need.

**Comment by obeliskos** [comment]
Here is a [Loki Sandbox limit/offset example](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/6524a2a5cc752f4a9ab314ef2b21a0b4/raw/bde2a0cb0bac2c38d05173d08792444ae998040b/limit-offset-example)

Let me know if your still having issues but i might need a example demonstrating what you think isn't working....

**Comment by asuroalex** [comment]
Hey obeliskos,

thanks for the sandbox example. I found my mistake.

**Comment by obeliskos** [comment]
Ah great, thanks I'll close this then
