### ISSUE TITLE
Can't create persistence database

### ISSUE THREAD

**Issue by Samega7Cattac** [techfort/LokiJS#572]
Hi,
This is my first time using LokiJS and I'm having some issues.
Ok, I created the database "database".
```
var db = new loki("database",
{
	autosave: true,
	autosaveInterval: 1000,
    autoload: true
});
```
Then I check if already exist the Collection "tests".
```
var tests_db = db.getCollection("tests");
if (tests_db === null) tests_db = db.addCollection("tests");
```
And finally insert some data.
```
tests_db.insert({name:"test1"});
tests_db.insert({name:"test2"});
```
Save the database, load it and output the data(show it correctly).
```
db.saveDatabase();

db.loadDatabase({}, function() {
  console.log(db.getCollection("tests").data);
});
```
I can work normaly with the database, but I don't know why he store the data in the memory. Don't create any file "database".
I already try to use a adapter and don't worked.
`persistenceAdapter: new LokiIndexedAdapter("database")`

I don't know what is missing and the why he don't create a file.

**Comment by obeliskos** [comment]
LokiJS persistence (file i/o) is mostly 'asynchronous' so you are probably not registering the appropriate callbacks.  

See examples here or in github repo : 
[examples/quickstart2.js](https://github.com/techfort/LokiJS/blob/master/examples/quickstart2.js)
[examples/quickstart3.js](https://github.com/techfort/LokiJS/blob/master/examples/quickstart3.js)

You should decide whether you need or want autosave functionality... if you prefer manual loading and saving you can use this example : 
[examples/quickstart4.js](https://github.com/techfort/LokiJS/blob/master/examples/quickstart4.js)

**Comment by Samega7Cattac** [comment]
thx @obeliskos now I understood the why.
But I can't make a "require".
`ReferenceError: require is not defined`

**Comment by obeliskos** [comment]
Sorry, that was for node... Try : 
https://gist.github.com/obeliskos/b3b50f3589596218da68b6252ed236bd

Loki sandbox now has web quickstarts you can pick from as well

**Comment by Samega7Cattac** [comment]
Thx @obeliskos 
Now worked like a cham!!!
Using callbacks and Loki Indexed Adapter was the point.

**Comment by Samega7Cattac** [comment]
#off_topic
Where Loki save the database?
He save the data but where is the database?

**Comment by Viatorus** [comment]
If you used the indexed adapter - inside the [IndexedDB](https://en.wikipedia.org/wiki/Indexed_Database_API) of your web browser.

**Comment by obeliskos** [comment]
Thanks @Viatorus yep its in sandboxed browser indexeddb storage

See this for inspecting storage : 
https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#loki-indexed-adapter-interface

**Comment by Samega7Cattac** [comment]
ok thx @obeliskos @Viatorus 
Close this issue

**Comment by Samega7Cattac** [comment]
If someone want really to store the database in the server see [Changes API](https://github.com/techfort/LokiJS/wiki/Changes-API)

**Comment by Mapiac** [comment]
@viatorus would you recommend using the indexedDB adaptor or LocalForge?

**Comment by Viatorus** [comment]
If you need much space (> 5MB) take partitioning adapter with IndexedDB.
Otherwise localForge.

>
