### ISSUE TITLE
TypeError: Cannot assign to read only property 'recursiveWait'

### ISSUE THREAD

**Issue by mathcoll** [techfort/LokiJS#573]
Hi,

I suddently get new errors loading database. By suddently I mean I probably run some updates recently, upgrading from lokijs 1.3.15 to 1.4.3 - big jump. :-)

In the stack trace error, it is mentioned this piece of code:
`db	= new loki('myDb.json', {autoload: true, autosave: true});
db.loadDatabase('myDb.json')`.

> node --version
> v4.2.6

> npm --version
> 3.7.1

> npm view lokijs version
> 1.4.3

Any idea what should I do - except upgrading node... yes I know I should.

**Comment by obeliskos** [comment]
if you are passing autoload:true option to [loki constructor](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html), you should probably be passing autoloadCallback option to be notified when load is complete.  

Having said that, [loadDatabase](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html#loadDatabase) accepts an options object and callback as its params, not a string... that's what raised the error. 

I have recently created some node 'quickstart' examples, perhaps [examples/quickstart2](https://github.com/techfort/LokiJS/blob/master/examples/quickstart2.js) or [examples/quickstart3](https://github.com/techfort/LokiJS/blob/master/examples/quickstart3.js) would give ideas about how you might want to do that.

**Comment by mathcoll** [comment]
Hello @obeliskos,
The script in my sample is run at script startup. I understood, that I don't need loadDatabase when application is starting.
So I removed the line about loadDatabase... and that looks to solve the issue - without the need of callback.

I will let you know if I noticed any regression somewhere else.. I can't be 100% confident on what I'm coding...

Thanks a lot.
