### ISSUE TITLE
sorting on sub properties of and object

### ISSUE THREAD

**Issue by mo0om** [techfort/LokiJS#574]
i'm trying to sort an array on a sub property of an object without success. For example..
```
items.insert({ name : 'mjolnir', owner: { test: 'a'});
items.insert({ name : 'gungnir', owner: { test: 'b'});
items.insert({ name : 'tyrfing', owner: {test: 'c'});

logObject(items.chain().find({'name': {'$contains': 'i'}}).compoundsort([['owner.test', false]]).data() );
logObject(items.chain().find({'name': {'$contains': 'i'}}).compoundsort([['owner.test', true]]).data() );
```
the 2 logs give the same response even though one of them should be reversed.

**Comment by obeliskos** [comment]
Compound sort only supports multiple top level properties... sorry. 

We don't currently directly support sorting by nested properties, you would have to use the resultset sort() function and supply a basic javascript comparison function similar to : 

```javascript
var db = new loki('sandbox.db');

// Add a collection to the database
var items = db.addCollection('items');

// Add some documents to the collection
items.insert({ name : 'mjolnir', owner: 'thor', maker: { name: 'dwarves' } });
items.insert({ name : 'gungnir', owner: 'odin', maker: { name: 'elves' } });
items.insert({ name : 'tyrfing', owner: 'Svafrlami', maker: { name: 'dwarves' } });
items.insert({ name : 'draupnir', owner: 'odin', maker: {name: 'elves' } });
items.insert({ name : 'extra' });

// find all docs with a custom sort function using nested property
var result = items
	.chain()
    .sort(function(obj1, obj2) { 
      if (!obj1.maker) {
        return (obj2.maker?-1:1);
      }
      if (!obj2.maker) {
        return (obj1.maker?1:-1);
      }
      if (obj1.maker.name == obj2.maker.name) return 0;
      if (obj1.maker.name < obj2.maker.name) return -1;
      return 1;
	})
    .data();

logObject(result);
```

We could add that feature request for [LokiJS2](https://github.com/LokiJS-Forge/LokiJS2).

**Comment by Viatorus** [comment]
Tracked for LokiJS2. :)

**Comment by obeliskos** [comment]
The simplest implementation might be : 
```javascript
// sort should compound sort on two properties (the first being nested property)
var result = items
    .chain()
    .sort(function(obj1, obj2) { 
      if (obj1.maker.name == obj2.maker.name) return 0;
      if (obj1.maker.name < obj2.maker.name) return -1;
      if (obj1.maker.name > obj2.maker.name) return 1;

      // obj.maker.name must be equal, so compare on obj.owner property
      if (obj1.owner < obj2.owner) return -1;
      if (obj1.owner > obj2.owner) return 1;

      // both must be equal
      return 0;
    })
    .data();
```

If there is a possibility that the object hosting subproperty could be null, you should add in a null check (like the earlier example did) just for that nested property test.

**Comment by Redsandro** [comment]
@obeliskos said:
> We could add that feature request for LokiJS2.

@Viatorus said:
> Tracked for LokiJS2. :)

Does this mean that LokiJS1 is EOL? Feature freeze?

**Comment by Viatorus** [comment]
Actually yes. But if you want this feature in v1 you can still submit a pull request. ;)

**Comment by Redsandro** [comment]
@Viatorus added test in PR

**Comment by obeliskos** [comment]
@Viatorus has been single handedly making great progress towards LokiJS2 refactoring, although I don't know what the progress is towards a production ready release would be on it. 

I think the goal is to keep this lokijs 1.x free as stable as possible so I do not intend to do anything other than bug fixes and (very) minor feature enhancements... so that lokijs2 can be easily updated to include them.  We will continue to allow user community to submit pr's if they want to.  

Long term, I imagine when lokijs2 becomes production ready we will no longer update it with any 1.x changes and their feature sets can differentiate.

I think your pr for dot notation is small enough in scope but it should probably work across chained and nonchained find ops (havent had time to look into yet).  So : 
```javascript
 var result = coll.find(dnFilterObject);
 var result2 = coll.chain.find(dnFilterObject);
```
should both be equal.

**Comment by Redsandro** [comment]
@obeliskos I would be happy to add a test for that. Can you point me to documentation about how to create a `dnFilterObject` that I can pass to `find()`?

**Comment by obeliskos** [comment]
Oh, sorry i misspoke... we only support sorting on collection chaining simplesort and compoundsort and dynamic view sorting so maybe those are the paths you would need to make sure work correctly.  dnFilterObject was just shorthand for any queryObject that contained dot notation.

**Comment by Redsandro** [comment]
@obeliskos if you want simplesort support, I'd have to hack into the binaryIndex too. Is that within the scope of acceptability?

**Comment by Redsandro** [comment]
There are no existing tests for _dynamic view sorting_, so I am assuming these are covered with the normal sort tests, and in extension also covered by the new nested property tests.

**Comment by Redsandro** [comment]
Added index support for nested keys. Pretty sweet. Like `mongodb`.
