### ISSUE TITLE
Very small collection filesystem

### ISSUE THREAD

**Issue by christopherreay** [techfort/LokiJS#576]
What Im exactly looking for is an in memory database that transparently persists and loads documents as json files on the filesystem.

Im thinking something like a per document / per file (for good reason), though im not sure that ext4 is up to the task (their are other file systems designed for such a thing).

Do you think that Loki would be a good base for this, and that it is possible to create an adaptor that would provide this kind of behaviour.

There is one level of granularity above document that I can use, for between ten and a hundred or so, that might be good, but either way, the question stands.

Thanks :)

**Comment by obeliskos** [comment]
@techfort had begun implementing an ['incremental adapter'](https://github.com/techfort/LokiJS/blob/master/src/loki-incremental-adapter.js) similar to what you describe...  maybe that can give some ideas.

**Comment by obeliskos** [comment]
Also (as i re-read), if your ok with more than one document per file, you can use the LokiPartitioningAdapter, along with default LokiFsAdapter to break into smaller files.  Along with 'paging' and 'pageSize' options it can dump pages of documents of (roughly) the size you set.

Here's a [sandbox gist how you might use it](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/ff2687e8496ec53a8a74ba47bb4eefa0/raw/8485066f97e9143e2959ae2a862584c03b7690a2/PagePartitionedMemory).

When you run that and view output, 'value' will be the contents of your files, and the filenames are variations of your original filename with collection/partition and page number file extensions.

The transparently persisting and loading will have to come from merging that example with an autosave example like [quickstart2](https://github.com/techfort/LokiJS/blob/master/examples/quickstart2.js)

**Comment by christopherreay** [comment]
Thank you very very much for your help. I will study this, and get back to you with what I come up with. 

So kind

Chirstopher
