### ISSUE TITLE
Do you support letter case insensitive queries?

### ISSUE THREAD

**Issue by shibin-you** [techfort/LokiJS#580]
Hi,
I can't find documents like this, and I can't find any examples.Is there anything wrong with my writing?
```
var like = {
    $regex: 'admin',
    $options: '$i'
};

var result  = children.find({
    "$or": [{
        "name": like
    }]
});
```

Thanks

**Comment by obeliskos** [comment]
Our [Query Examples](https://github.com/techfort/LokiJS/wiki/Query-Examples) page describes this : 

**$regex** - filter for document(s) with property matching provided regular expression
>_If using regex operator within a named transform or dynamic view filter, it is best to use the latter two examples since raw regex does not seem to serialize/deserialize well._

```javascript

// pass in raw regex
var results = coll.find({'Name': { '$regex' : /din/ }});

// or pass in string pattern only
results = coll.find({'Name': { '$regex': 'din' }});

// or pass in [pattern, options] string array
results = coll.find({'Name': { '$regex': ['din', 'i'] }});

```
