### ISSUE TITLE
Wildcard (don't care) search fields.

### ISSUE THREAD

**Issue by mrb1090** [techfort/LokiJS#583]
Have a number of search patterns, some of which have wildcard (*) fields.  Is there a way to do document queries with such fields?

Thx,

Mike B.

**Comment by Viatorus** [comment]
You can do such queries with regex:
https://github.com/techfort/LokiJS/issues?utf8=%E2%9C%93&q=is%3Aissue%20regex

LokiJS2 will have a full text search very similar to Lucene & Elasticsearch:
https://github.com/LokiJS-Forge/LokiJS2
