### ISSUE TITLE
Memory leak in chrome 32bit

### ISSUE THREAD

**Issue by cuongtl1992** [techfort/LokiJS#587]
I use lokijs for read only database. I pull data from server via Http and merge them into collections in DB.
My adapter i use is Indexed DB.
Problem in a request a have ~ 2M record and i insert it into a collection it work very fast.
But my page is cashed. i open task manager and see current tab open my site has memory > 1GB
In 32bit chrome can only 1GB / 1 tab to running. 
How to resolve problem?. Any idea.
Partion DB can resolve??.

Thanks

My init function

```
let idbAdapter = new LokiIndexedAdapter(this.name);
        this.context = new loki(this.name, <LokiConfigureOptions> { 
            adapter: idbAdapter,
            autosave: true,
            autosaveInterval: 5000,
            env: 'BROWSER'
        });

        this.context.loadDatabase({}, () => {
            let isInititalized = this.context.getCollection('Products');
            if (isInititalized === null)
                this.initSchema();

            successCallBack();
        });
```

**Comment by cuongtl1992** [comment]
![capture](https://user-images.githubusercontent.com/21033583/28513976-7d9f9b66-7082-11e7-9db5-5b0e63d6d945.PNG)

**Comment by obeliskos** [comment]
So this is a 'read-only' database that you need to store in client indexeddb storage?  Or do you fetch data every time?  If you only need to save once, you can probably not use autosave logic and just manually call [saveDatabase](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html#saveDatabase) when finished populating it.

Partitioning adapter will reduce memory overhead but if have one big collection it wont help as much unless you also use paging mode of partitioning adapter. Try the second or third partitioning adapter example here and see if that resolves your problem : 
https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#lokipartitioningadapter

**Comment by cuongtl1992** [comment]
Yes i need save them store in client (indexeddb store). And i fetch data in the first time then second time to more... i only fetch changes data.
But in the first time i feed a large data ~ 2M record. I disable **autosave** option and save all after i fetch all data.

But memory use ~700MB and after 1 minutes down to ~500MB

see above picture
![3](https://user-images.githubusercontent.com/21033583/28521236-da62fcd4-709c-11e7-87eb-749202ca5f3a.PNG)

How  you can give me a solution :-?

**Comment by obeliskos** [comment]
Well you are dealing with ~2M records so I don't know how much memory it should be using up...

Load your database without saving or autosave and tell me how much memory its using... then save database and see how much the memory went up after saving.

If your database ends up being over 50megs or so, you will definitely need the partitioning adapter with paging mode.

**Comment by cuongtl1992** [comment]
💃 Maximum to ~2M record. 
I will take a snapshot memory profile for you.
I cached data and save it in IDB to reuse for next time end user reopen. 

First time i load my database without saving and auto save memory with ~1,2M record maximum memory use can up to 2,6GB
Then after i call saveDatabases() memory down to 926MB. after 15s it down to 507MB.

profile above i had a collection with name PriceBookItem with ~270k objects. I can't profile large data than it case. Because chrome will crashed.

https://drive.google.com/file/d/0BzS4sLJqRwPJcExjVnl4UGNsaG8/view?usp=sharing

Thanks
