### ISSUE TITLE
Duplicate items after findAndRemove followed by insert

### ISSUE THREAD

**Issue by zofskeez** [techfort/LokiJS#588]
I'm seeing strange behaviour in Nodejs while using the default instance new loki(). I insert a series of documents into a collection with a unique index on ID. I then findAndRemove a number of documents and insert new ones. There is no error thrown when inserting the documents as the newly inserted documents have truly unique ID's. When doing a find for documents in the collection after, I see that there are duplicates with the same ID.

Has anyone seen this behaviour or have suggestions? I am using no persistence and looking for a strictly in memory solution.

**Comment by Viatorus** [comment]
Could you provide an example?

**Comment by zofskeez** [comment]
Sorry that message was in haste. Here's the gist:

`const db = new loki();`
`let coll = db.addCollection('foo', { unique: [ 'ID' ] });`
`coll.foo.insert(someObjectWithUniqueID);`
`coll.foo.findAndRemove(queryObject);`

After I do the findAndRemove I `console.log(coll.foo.find(queryObject));` and an empty array is returned. Next I insert more documents:

`coll.foo.insert(moreObjectsWithUniqueIDs);`

This insert has the potential of generating some of the same unique ID's because I am taking utc time values and a resource ID from an API call and concatenating them so I can do ` coll.foo.by('ID', id);` for quick lookup.

After the insert and no errors are thrown (I have seen the error referencing Duplicate ID's thrown on other occasions) I do `coll.foo.find(queryObject)` for all documents matching the same query and I find duplicate records with the exact same ID.

Let me know if additional info would be helpful. I'm running on a Mac with Nodejs v6.9.2.

**Comment by obeliskos** [comment]
Yea I can't reproduce any errors in examples I am coming up with, so a more complete example might be useful.   I can't see your queryObject or example values for your ID column to guess whether they are suspect, but for basic ID value like '100' it seems to work correctly.  

You are probably already aware of this but to summarize, we don't currently implement a 'removeBy' method which can leverage a unique index to quickly remove an object if it exists.  So you are utilizing a findAndRemove which will do a full array scan to remove any objects matching your query object.  Performance issues aside this is completely valid but the ideal method to remove would be : 
```javascript
var obj = coll.by('ID', id);
if (obj) {
  coll.remove(obj);
}
```
