### ISSUE TITLE
does lokijs have onchange handlers?

### ISSUE THREAD

**Issue by sprajagopal** [techfort/LokiJS#589]
can I register a callback function to be called when a particular find (or chained find) returns non zero results?

**Comment by obeliskos** [comment]
We should have the following events defined for collections : 
'insert', 'update', 'pre-insert', 'pre-update', 'close', 'flushbuffer', 'error', 'delete','warning'

Not sure you would want to run a query within any of those though... maybe clarify your use case.

**Comment by obeliskos** [comment]
To clarify before closing (and after re-reading), i think what you would want to use are DynamicViews where you would call [applyfind()](https://rawgit.com/techfort/LokiJS/master/jsdoc/DynamicView.html#applyFind) to apply filters and get current results via call to [data()](https://rawgit.com/techfort/LokiJS/master/jsdoc/DynamicView.html#data).

You might then listen for the dynamic view "rebuild" event which would occur when the results change to determine if non-zero results are available and take relevant action.

Let me know if there are still questions-- closing for now.
