### ISSUE TITLE
Ignore properties when serializing.

### ISSUE THREAD

**Issue by AskingQuestions** [techfort/LokiJS#592]
Say we have a collection like so `{"name": "John", "age": "50", "events": {...}}`. The events property is storage for any dynamic events that are added to this instance.

I load in instances like so:
```javascript
var people = db.getCollection("people").find({age: 50});
Loop over people and Object.assign(person, Person.prototype);
people[0].on("birthday", function () {
  console.log(people[0].name + " birthday");
});
//This works but when I serialize it.
db.saveDatabase(); //I dont want the events property to be serialized. 
```

I could remove the events property before saveDatabase but I would much rather have loki js ignore these properties.

Is this possible or should I do it differently?

**Comment by obeliskos** [comment]
Maybe by creating your own class, within it implement a toJson method and possibly implement a [custom inflater with collection protos functionality](https://github.com/techfort/LokiJS/blob/master/spec/generic/typed.spec.js)?  I haven't tried this but I think that might work.

**Comment by AskingQuestions** [comment]
@obeliskos I could not find any docs on how to implement a toJson method within the User class?

**Comment by AskingQuestions** [comment]
Oh toJSON
