### ISSUE TITLE
Quicky tip: adding JSON-Schema validators

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#593]
Not saying it needs to be added to LokiJS (I was contemplating adding it to the wiki, but I don't know whether outside contributions to the wiki are wanted), but here's a quick way to add JSON-Schema validation to LokiJS:

```
var Ajv = require('ajv');
var Loki = require('lokijs');
var validator = new Ajv();

Loki.prototype.addCollection = (function(original) {
  return function(name, options) {
    var coll;
    coll = original.apply(this, arguments);
    if (options.schema) {
      coll.validate = validator.compile(options.schema);
    }
    return coll;
  };
})(Loki.prototype.addCollection);

Loki.Collection.prototype.insert = (function(original) {
  return function(doc) {
    if (this.validate && !this.validate(doc)) {
      throw this.validate.errors;
    }
    return original.apply(this, arguments);
  };
})(Loki.Collection.prototype.insert);

Loki.Collection.prototype.update = (function(original) {
  return function(doc) {
    if (this.validate && !this.validate(doc)) {
      throw this.validate.errors;
    }
    return original.apply(this, arguments);
  };
})(Loki.Collection.prototype.update);
```

**Comment by retorquere** [comment]
And as I've just learned, you could use a transform to persist the schema with the database should you so choose.

**Comment by Smolations** [comment]
This would be huge. As it stands, you can add almost any document to a collection (assuming no indices). I hope this gets considered, at least for v2!

**Comment by Smolations** [comment]
I hope no one is trying to store methods, lol. But validation on POJOs for simple types, supported by the JSON Schema spec, seems like a reasonable ask. Maybe in LokiDB2?

**Comment by retorquere** [comment]
Storing of methods isn't supported, but adding of objects with methods to a running db is. Loki even supports re-inflating the json into objects-with-methods during load. Nothing new about that.
