### ISSUE TITLE
Reference Mode adapter

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#595]
I'm looking to write a reference mode adapter that saves each collection to a separate file and only saves the collection file if it's changed. Can I see on a collection if it's changed in exportDatabase? In loadDatabase, is there a way to just assemble a plain-old javascript object and make a new LokiJS instance from that?

**Comment by retorquere** [comment]
This works for me, but I'd love to know whether I've gotten it right:

```
var Adapter, DB, Loki, fs;

fs = require('fs');

Loki = require('lokijs');

Adapter = (function() {
  function Adapter() {}

  Adapter.prototype.mode = 'reference';

  Adapter.prototype.exportDatabase = function(dbname, dbref, callback) {
    var coll, collfile, header, j, k, len, v;
    header = {};
    for (k in dbref) {
      v = dbref[k];
      if (k === 'collections') {
        for (j = 0, len = v.length; j < len; j++) {
          coll = v[j];
          collfile = dbref.filename + "." + coll.name + ".json";
          if (coll.dirty || !fs.existsSync(collfile)) {
            console.log("saving " + collfile);
            fs.writeFileSync(collfile, JSON.stringify(coll, null, 2), {
              encoding: 'utf8'
            });
          }
        }
        header[k] = v.map(function(coll) {
          return coll.name;
        });
      } else {
        header[k] = v;
      }
    }
    return fs.writeFileSync(dbref.filename + ".json", JSON.stringify(header, null, 2), {
      encoding: 'utf8'
    });
  };

  Adapter.prototype.loadDatabase = function(dbname, callback) {
    var coll, db, i, j, len, ref;
    db = JSON.parse(fs.readFileSync(dbname + ".json", 'utf8'));
    ref = db.collections;
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      coll = ref[i];
      db.collections[i] = JSON.parse(fs.readFileSync(dbname + "." + coll + ".json", 'utf8'));
    }
    return callback(db);
  };

  return Adapter;

})();

DB = new Loki('db.json', {
  adapter: new Adapter()
});

DB.loadDatabase();

DB.getCollection('serialized').insert({
  hello: 'world'
});

DB.saveDatabase();
```

**Comment by obeliskos** [comment]
Since our interface was set up for both sync and async, we will never use the return value of loadDatabase or exportDatabase.  I suppose if you intend to directly call your adapter at times it may be useful to return info but only if using synchronous persistence (like you are in this example).

I see you are checking collection 'dirty' flags but why are you check if !fs.existsSync(collfile) in export, don't you want to overwrite files if they changed?  I guess eventually you will need to convert any exist calls to fs.stat calls.

**Comment by retorquere** [comment]
That return is an artifact from coffeescript compilation, sorry.

I'm checking existsSync so that the collection gets saved regardless of whether its dirty if the file does not exist. I wasn't sure an empty new collection would be considered dirty.

Otherwise, does it look OK?

**Comment by obeliskos** [comment]
I haven't tested i it look right... if you return object it does not need to be instance of loki since we just graft properties in loadJsonObject

**Comment by retorquere** [comment]
Can I tell in `exportDatabase` whether collections have been removed? I try to minimise saves, so I only save collections when dirty, but if nothing has changed I also don't need to save the non-collection information. I can check on the collections whether they're dirty, but if a collection was removed, that's not available of course.

**Comment by retorquere** [comment]
(Or perhaps there's other things that could have happened that necessitate the saving of the non-collection data)

**Comment by retorquere** [comment]
I've gone over the source code, but `dirty` for a database is inferred from one of its collections being `dirty` -- which means that a collection removal will not not be saved unless forced. I can think of a few monkey-patches that I could do which would mainly wrap `removeCollection` to set a flag, and `saveDatabase` to clear the flag, but I'd prefer to hear your input.

**Comment by obeliskos** [comment]
I think your right, removing a collection won't currently set any dirty flags... 

We could add a dirty flag to the loki class (similar to dirty flag on each collection), and whenever the user makes changes at the (loki) database level such as loki.removeCollection, we set the db level dirty flag.  Then we add a check for that in the isDirty logic, checking loki.dirty and then iterating each collection.dirty flags.

**Comment by retorquere** [comment]
That's what I had been thinking. I can work around it for now by monkey-patching `Loki.prototype.removeCollection`, `Loki.prototype.autosaveDirty` and `Loki.prototype.saveDatabase` to set/return/clear the DB-level dirty flag.

**Comment by retorquere** [comment]
Is the adapter not notified for a `close`? I am persisting my data to a database and I need to close the connection on LokiJS DB close.

**Comment by obeliskos** [comment]
If autosave is enabled, and autosaveDirty() is true we will call the adapters save (or export) method.

loki's close() method also always emits a 'close' event if you need to do insert any logic to

**Comment by retorquere** [comment]
Odd, I thought my tests showed that no save was called during `close`. I'll go test again.

**Comment by retorquere** [comment]
I'm trying to figure out how to use the `close` event to do cleanup and know when it's done. I rely on the callback from the `close` method being called when it's done, so for now I've just done

```
Loki.prototype.close = (function(original) {
  debug('Loki::close', this.filename);
  return function(callback) {
    var self;
    self = this;
    original.apply(this, function(err) {
      if (err) {
        return callback(err);
      }
      if (self.persistenceAdapter && self.persistenceAdapter.close) {
        debug('Loki::close adapter');
        self.persistenceAdapter.close(self.filename, function(err) {
          return callback(err);
        });
      } else {
        callback(null);
      }
    });
  };
})(Loki.prototype.close);
```

and that seems to work

**Comment by retorquere** [comment]
After a bit of tweaking, this is what I ended up with:

```
Loki.prototype.close = (function(original) {
  return function(callback) {
    return original.call(this, (function(_this) {
      return function(errClose) {
        if (_this.persistenceAdapter && typeof _this.persistenceAdapter.close === 'function') {
          return _this.persistenceAdapter.close(_this.filename, function(errCloseAdapter) {
            return callback(errClose || errCloseAdapter);
          });
        } else {
          return callback(errClose);
        }
      };
    })(this));
  };
})(Loki.prototype.close);
```
I realize I could have achieved similar results with a `close` event handler, but I wanted this to work for all Loki databases I used.

Interested in a pull request (which wouldn't use the wrapping method of course)?
