### ISSUE TITLE
autosave without autosaveInterval

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#597]
Is it possible to have `autosave` enabled so that the database gets saved on `close`, but no `autosaveInterval`? I want to save the DB only when idle (which I have a idle handler for which calls `saveDatabase`), or when it's `close`d, but for the latter, I need `autosave` to be on.

**Comment by retorquere** [comment]
I'm asking because `autosaveInterval` is set to `5000` unless overridden, and there's no way to override it with a value that says "don't enable interval saves"

**Comment by obeliskos** [comment]
Maybe either tap into the 'close' event like : 
```javascript
db.on("close", function() {
  db.saveDatabase(function(err) {
     console.log(err?"error saving":"saved");
  });
});
```
Or set the autosaveInterval really high like [Math.pow(2,31) - 1](https://stackoverflow.com/a/12633556)

**Comment by retorquere** [comment]
I'll go toy with the close event.

**Comment by thw0rted** [comment]
This is super old, but if anybody is looking for this today, I think you can just use `Number.MAX_VALUE` or `Infinity` for the interval value.

Note that I'm writing up an issue now about saving and the `close` event.  The short version is that if you call `process.exit` during an event listener for `close`, your database won't save, but it will if you call it from a callback passed to the `db.close()` call instead.
