### ISSUE TITLE
Fix removeWhere()

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [techfort/LokiJS#599]
I have commented on closed issue #64 already. I'm opening another issue in case it is the preferred thing to do. I would like to say that the removeWhere() function needs "while (this.filter(query).length)" or even maybe  "while (this.where(query).length)" rather than the way it is written. It is GUILTY AS CHARGED when it comes to the capital offense of removing items in FOR loops. Thank you!

**Comment by Viatorus** [comment]
Thanks for your input. Feel free to send us a pull request with a unit test of the problem. :)

**Comment by obeliskos** [comment]
I believe we are doing this the correct way as we create a separate array of document results and it is that array we iterate, while removing from separate internal collection array.

**Comment by ssimo3lsuhsc** [comment]
I believe that mutating the collection may also mutate the results. I have an array where I wanted to remove all entries with a certain value greater than 2. Which ones does it ACTUALLY remove? The ones whose values are 1 and 3. The ones whose values are 4, 5, 6, etc., remain in the heap.

**Comment by obeliskos** [comment]
[example](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/c78627d1cbdc51408e5d30e24cc3b5eb/raw/e5161db7b3d29d3a160ddc0215be7116cc95f59a/removeWhere)
