### ISSUE TITLE
How can i implement rest calls to lokijs?

### ISSUE THREAD

**Issue by eggzon** [techfort/LokiJS#601]
Can someone help me how can i implement my rest calls to lokijs, for example i have this rest: https://address-book-demo.herokuapp.com/api/contacts and what i want here is passing all the data to LokiJs and then fetch it from Lokijs.

Or at least if i have any option to import my db or load it from my directory

**Comment by hasahmad** [comment]
I haven't used Loki.js for a while so I'm not sure if they've added a bulk insert functionality.
But you can do a for loop to insert to database.
For example:

```
    var db = new loki('contacts.json');
    var collection = db.addCollection('contacts');
    var data = data_fetched_from_api;
    for (var i=0; i<data.length; i++) {
        var contact = data[i];
        collection.insert(contact);
      }
```
