### ISSUE TITLE
Metadata for collections

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#602]
Is there a safe way to add (and persist) collection metadata? I can of course add any property to the collection object, but I want to make sure I'm not scribbling over data that LokiJS needs.

**Comment by obeliskos** [comment]
So if you want to attach your meta onto the collection itself (and not objects within the collection), your choices are limited.

The only changes which will survive across persistence cycles (save/load) are the properties we [explicity re-attach](https://github.com/techfort/LokiJS/blob/a2950436186fafec2a6b434e5c51cc125a42b2eb/src/lokijs.js#L1538-L1627) in our loki.loadJSONObject() method.

If it were me i would probably a specifically named collection transform to cover this such as : 
```javascript
coll.addTransform("my meta", [{ 
  type: 'my collection metadata',
  value : {
    someMetaProp1 : "stuff",
    someMetaProp2: "more stuff",
    someOtherMetaProp : "another"
  }
}]);
```

Then later, you might look that up with : 
```javascript
var tx = coll.getTransform("my meta");
if (tx) {
  var myMeta = tx[0].value;
  console.log(myMeta.someMetaProp1);
}
```

Collection Transforms can be similtaneously used for its [original purpose](https://github.com/techfort/LokiJS/wiki/Collection-Transforms) by ensuring the 'type' is not an existing transform step type.... 'meta' should be fine.

You 'could' create multiple 'named' meta transforms if you wanted to, or you 'could' create multiple steps within a single meta transform, but like the example above shows, you only need 1 transform and 1 step, and your value object can hold everything.

**Comment by retorquere** [comment]
Works perfectly -- thanks!
