### ISSUE TITLE
deflate as a counterpart to inflate?

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#607]
I need to save `Date` objects to the database; currently I just allow dates to be serialized to a string by the JSON serializer and I call `Date.parse` on them in an `inflate` function. I'd prefer to store them as timestamps though -- would it be possible to add a `deflate` option where I could turn `Date` objects into timestamps, which would be faster to both `inflate` and `deflate` later (plus the storage size benefit).

**Comment by obeliskos** [comment]
Are the objects in your collection prototyped?  If so you could override toJson() like [https://github.com/techfort/LokiJS/blob/a2950436186fafec2a6b434e5c51cc125a42b2eb/src/lokijs.js#L1105-L1121](like loki does).

Not sure what 'storing them as timestamps' is.  I usually store the epoch time like : 
```javascript
coll.insert({ a: 1, b: 2, dt: (new Date()).getTime() });
```

And in the above example, if you have binary indices defined on 'dt', lokijs will (by default) automatically convert dt to epoch time so it can be safely serialized and maintain valid binary index across serializations... but it is up to you to reconvert/inflate back to js object if that is what you want.

So, knowing you will be saving your database, can you clarify what is your preferred format for it always to be in (before -and- after serialization) ?  Was your 'timestamp' referring to js data object, string, or epoch?

**Comment by retorquere** [comment]
They're currently not prototyped but it's possible to have them be; I'll look into that.

I'm looking to do the same thing with epoch times, but during runtime I need my equivalent of the `dt` field to be `Date` objects, so I'd prefer to keep the change between epoch time and Date object to be during inflate/deflate.

You're right, `timestamp` wasn't really descriptive enough; I want my objects during runtime (that is after inflate and as I insert them during normal operations on the DB) to be `Date` objects; on-disk (so after serialization), I prefer them to be stored as epoch time.

**Comment by retorquere** [comment]
(to expand on that -- I do have a `proto` set on the collection I have in mind, but it's currently just `Object` -- I don't need any other behavior on the inflated object except the field inflation)

**Comment by obeliskos** [comment]
yep, you could always run a coll.chain().update(yourConvertBackToDateFunction); after each load but that's probably not clean solution for most uses.

Do you know ahead of time what the property names are of the dates that will need to be converted or are they in meta or are they external user driven?

**Comment by retorquere** [comment]
I know ahead of time, at collection creation time. If I could retrieve the `proto` from the collection, that would help, as I could make sure I create the proper object at the point of `insert` (where I may only have a pointer to the collection, not the DB)
