### ISSUE TITLE
db file should be created by default in load()

### ISSUE THREAD

**Issue by techfort** [techfort/LokiJS#61]
In a node env, load should create a file if it doesn't exist, so as to avoid err 34, especially when autoload is true.

**Comment by estvmachine** [comment]
If you created the file, give you an alert like

**TypeError: Cannot read property 'length' of undefined'

**Comment by techfort** [comment]
could you create a gist for it so i understand exactly what you mean? Thank you!

**Comment by estvmachine** [comment]
Of course. Im ussing NodeJS v0.10:

```javascript
var db = new loki('random.json',{autosave: true,
						       autosaveInterval: 1000* 20 * 1 ,
						      autoload: true,
						      persistenceAdapter: 'fs'});

			db.addCollection('advances', { indices: ['advanceid'] });
```

If i dont create the 'random.json' i got error because doesn't find the file, but if i a create a random.json like that, i got that alert: **TypeError: Cannot read property 'length' of undefined'**

```json 
{}
```

**Comment by techfort** [comment]
Ok - this is still an open issue so i'll make sure it is addressed asap!

**Comment by estvmachine** [comment]
Haha, thanks that would be great

**Comment by Alex-Werner** [comment]
Hello, 

Hi, 
Thank you for your wonderful lib. But I'm actually having the same problem : 
```javascript
 /**
     * @property financialDbPath Path where we want to set the db
     * @final
     */
    financialDbPath : 'nodules/mib/db/financial.json',
    /**
     * @property loaded Is the db loaded yet ? Avoid get object on db not launched.
     */
    loaded:false,
    /**
     * Used for loading or created Db
     * @method initDb
     * @return *
     */
    initDb:function(){
        this.financialDb = new this.loki(this.financialDbPath,
            {
            autosave:true,
            autosaveInterval:5000,
            autoload:true,
            autoloadCallback: function(){
                if(MIB.financialDb.getCollection('internal.markets')){
                    MIB.InternalMarkets = MIB.financialDb.getCollection('internal.markets');
                    console.log("[Nodule : MIB] has found Collection internal.markets");

                }
                else{
                    MIB.createDb();
                    MIB.InternalMarkets = MIB.financialDb.getCollection('internal.markets');
                    console.log("[Nodule : MIB] has created DB");

                }

                MIB.loaded=true;
                console.log("[Nodule : MIB] has fully loaded database 'financial.json'");
            }
        });

    },
```
If I don't create the file I got a  Cannot read property 'length' of un
defined]
If I create it with fs and "{}" inside I got a SyntaxError: Unexpected end of input

If Also tried to saveDB in autoloadCallback but same errors. What should I initiates with FS in my financial.json before asking lokiJS to get it ? 

P.S : A huge pint of the finest beer for the one in charges of names (Eostre, Loki).

**Comment by techfort** [comment]
This is going to the top of my list as it is quite blocking. And thanks for the beer - next release is Brach :)

**Comment by estvmachine** [comment]
Its look this its resolved doesnt?

**Comment by techfort** [comment]
yes - feel free to reopen if it's not.

**Comment by estvmachine** [comment]
I got an error:

![image](https://cloud.githubusercontent.com/assets/2062668/8600635/dc8c411e-2634-11e5-8a69-c60ebf01f3f4.png)

**Comment by Alex-Werner** [comment]
Did you updates your package ?

**Comment by estvmachine** [comment]
Ah im still using 1.2.5, im gonne try with 1.3. Sorry i dont check that.

**Comment by estvmachine** [comment]
Ok im try with 1.3.7 and i have the same issue.

**Comment by techfort** [comment]
@stevmachine what OS are you experiencing this on?

**Comment by Alex-Werner** [comment]
@estvmachine : Create a .json text file with "{}" inside your directory that you name : random.json. 
It should "solve" the problem. 
But that's weird. Did you try on a classic repertory ? (Like desktop) because i'm not sure if NodeJS have full right to create/erase file on %AppData%

**Comment by estvmachine** [comment]
Im using Windows 7 64 bits. I create a text file with "{}" this way:

```javascript
//Create the file with '{}', but doesnt save the db, give me error of 'undefined'
if(!fs.existsSync(dir+'/random.json')){
        fs.writeFileSync("file.txt", 'Text', "UTF-8",{'flags': 'w+'});
}

//If only create empty file, says [SyntaxError: Unexpected end of input]

if(!fs.existsSync(dir+'/random.json')){
           fs.closeSync(fs.openSync (dir+'/random.json','w'));
}
```

Im using fs.Sync methods, but maybe i have problems with the callbacks? or maybe im doing something wrong

**Comment by techfort** [comment]
hey @stevmachine, I suggest you create a gist with the whole code so I can
examine the problem with a complete view on things.

**Comment by estvmachine** [comment]
Of course

```javascript
var localPath= process.env.HOME+  '\\RandomStack' ,
localDbFile = localPath +'\\random.json'; 

//Check if exist folder
	if (!fs.existsSync(localPath)){
	     fs.mkdirSync(localPath);
  }

  // Init the db file
	if(!fs.existsSync(localDbFile)){
                  var fhandler = fs.openSync (localDbFile, 'w');
		  fs.writeFileSync(current, '{}', "UTF-8",{'flags': 'w'});
                 console.log("Create db file in: "+localDbFile);
                fs.closeSync(fhandler);
	}


	var db = new loki( localDbFile,{autosave: true,
						           autosaveInterval: 1000* 20 * 1 ,
				                          autoload: true,
							   persistenceAdapter: 'fs',
						         autoloadCallback: function(){
							    if( ! db.getCollection('avances'))
							         db.addCollection('avances', { indices: ['ordenid'] });
                                                             if(! db.getCollection('preferencias'))
                                                                db.addCollection('preferencias', { indices: ['module','userid'] });
						          
                                      console.log("[LokiDB] collections have been loaded in "+localDbFile);
});

....

//later

var app = require('./config/express')(db, localPath);


```

**Comment by obeliskos** [comment]
I can understand why you want to check the existence of the directory and create it if it does not exist, but you should not need to do that with the database file itself. 

I was able to adjust your sample to this and have it run without errors (after removing the empty random.json which the above code generated) : 
```javascript
var loki = require("./src/lokijs.js");
var fs = require("fs");

var localPath= '.' ,
localDbFile = localPath +'\\random.json'; 

var db = new loki( localDbFile,
{
  autosave: true,
  autosaveInterval: 1000* 20 * 1 ,
  autoload: true,
  persistenceAdapter: 'fs',
  autoloadCallback: function() {
    if( ! db.getCollection('avances'))
      db.addCollection('avances', { indices: ['ordenid'] });
    if(! db.getCollection('preferencias'))
      db.addCollection('preferencias', { indices: ['module','userid'] });

    console.log("[LokiDB] collections have been loaded in "+localDbFile);
  }
});

```

Because of your interval, it takes about 20 seconds to save the first time but it does save.

**Comment by estvmachine** [comment]
Well works for me, but i have to create the file if not exists. I have error for other reason not relationated with LokiJS, so sorry for that. :D thanks for the atention
