### ISSUE TITLE
Rename Collection

### ISSUE THREAD

**Issue by brunaaanayara** [techfort/LokiJS#611]
Its possible to rename a collection?
Suppose I have two collection: C1 and C2
I want C2 to have the name of C1
The solution till now do the following
First I remove all the Data of C1 
Then I copy all the Data of C2 in C1
Next I remove C2

That way I do 2 times the work cuz I could just remove C1 and rename C2 to C1

**Comment by obeliskos** [comment]
Are you looking for quick fix or best practice?

Ideally we could add loki method to rename collection and maybe update any custom inflaters which may be keyed off name, but if you just want to 'fix' some data you could probably just update the name property on a collection.  That won't flag collection as dirty though so you might need to manually save.

**Comment by brunaaanayara** [comment]
I think only a method to rename a collection will solve my problem cause I need to replace all data of c1 with all data of c2 and not just 'fix' some data. I'm looking for best practice but at the meantime a quick fix can solve it. What do you suggest for me to do?

**Comment by obeliskos** [comment]
ok I added a [renameCollection](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html#renameCollection) method to Loki

may take a while to hit npm but you can grab off master (here)

**Comment by brunaaanayara** [comment]
It worked, thanks!
