### ISSUE TITLE
findAndRemove query removes all documents

### ISSUE THREAD

**Issue by zofskeez** [techfort/LokiJS#612]
Suppose I have a collection of documents:
`[ { a: 1 }, { a: 2 }, { a: 3 }, { a: 4 }]`

If I were to do a find({ a: { $lte: 3 }}) it correctly returns the first 3 documents.

However, if I do a findAndRemove({ a: {$lte: 3}}) all of the documents are removed. 

I have simplified the example but in real world I am performing the query on 1 property of type integer. Any ideas as to why this is occurring. I am using this method in many places throughout the program as I understood it was faster than removeWhere but I'm concerned that the results will be inaccurate.

**Comment by obeliskos** [comment]
Your example [works when i tested](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/41cc6123fb6dcc9e60c528daccc2669f/raw/b719c08eb49f256b5b261cf61c678b24a9f67e29/findAndRemove). what options did you pass to addCollection when you created it?  Are there any nulls?  In dirty data scenarios (mixed types, possibly missing values) you should be able to do simplesort on that property and verify the records are sorted as expected.

**Comment by zofskeez** [comment]
Thanks for looking into it. I'm setting unique, indices, and autoupdate when creating the collection. I'm getting unexpected behaviour if a do a find with the same query so it's likely something with the data set. The documents have a utc value and I am doing a query for $lte the utc at the time of the operation.

Is there a way to set the ttl dynamically? That would be ideal for this situation if the utc field in the document could serve as the ttl.

**Comment by zofskeez** [comment]
After more testing I'm even more puzzled. Perhaps this will shed more light.

`const slots = coll.find({ utc: { $lte: { 636407316000000000 } });`

`slots.forEach((slot) => {`
`    // the collection is quite big so I focus on data for 1 service`
`    // when I log the results they are indeed the correct documents that I wish to remove`
`    if (slot.service === 3348) console.log(slot);`
`    coll.remove(slot);`
`});`

`console.log(coll.find({ service: 3348 }));`

Here I find that this log returns an empty array. An initial find shows documents with utc greater than the query value so there should be documents in the collection after the remove.

**Comment by zofskeez** [comment]
After listening to the error event on the collection I have some more information and it appears there is a problem with updating an index:

TypeError: Cannot read property 'available' of undefined
    at LokiEventEmitter.Collection.calculateRange (/node_modules/lokijs/src/lokijs.js:5689:35)
    at LokiEventEmitter.Collection.getBinaryIndexPosition (/node_modules/lokijs/src/lokijs.js:5459:24)
    at LokiEventEmitter.Collection.adaptiveBinaryIndexRemove (/node_modules/lokijs/src/lokijs.js:5531:25)
    at LokiEventEmitter.Collection.remove (/node_modules/lokijs/src/lokijs.js:5371:18)
    at LokiEventEmitter.Collection.remove (/node_modules/lokijs/src/lokijs.js:5340:16)

**Comment by obeliskos** [comment]
collection has [setTTL](https://github.com/techfort/LokiJS/blob/59e575986ab156d9378657833feb2c531a06816e/src/lokijs.js#L4806-L4814) method which apparently did not get jsdoc comments.

not sure what utc (date?) format would have a number that high... looks like a 'find everything' filter.

show what options you are passing to collection constructor for diagnosing index

**Comment by zofskeez** [comment]
I had a look at setTTL and I would need a different expiration value for each document in the collection. The utc value is actually the .NET utc ticks which is unfortunately the date time format the API I am interacting with expects. Here are the options I am passing when creating this collection:
```
const loki = require('lokijs');
const db = new loki();
const coll = db.addCollection('foo', {
    unique: [ ],
    indices: [ 'service', 'utc', 'location', 'available' ],
    autoupdate: true
});
```
I am inserting all of the documents with a default object that is returned from a function so all keys are present. For the available property that has the index, it's possible that the value can be 0. Otherwise, there are no null values.

**Comment by obeliskos** [comment]
collection ttl uses same settings for all docs, maybe that would be a LokiJS2 feature request.

.net ticks, ah.. i usually convert with something like : 
```csharp
        public long ConvertDateToUnix(string date)
        {
            DateTime dt = DateTime.Parse(date);
            TimeSpan ts = dt - new DateTime(1970, 1, 1);
            return (long) ts.TotalMilliseconds;
        }
```
Not sure about javascript using numbers that high, according to this [stackoverflow search result](https://stackoverflow.com/questions/307179) : 
```
console.log(Number.MAX_SAFE_INTEGER);
// 9007199254740991
// your value was :
// 636407316000000000
console.log(636407316000000000 - 60)
// shows 636407316000000000
console.log(636407316000000000 - 70)
// shows 636407315999999900
```
so looks like odd overflow behavior with numbers that high.

The binary index error is odd, i am not sure why that might be happening... are you using latest npm or newer github version?  Could you supply the line of code that  line 5689 reads for you?  

Also autoupdate depends on Object.observe which has been deprecated and may at some point now or in the future be dropped.  I would recommend explicitly calling update and not using that option unless you are aware of this potential coverage or use some kind of polyfill.  Your objects should be native javascript objects that you can do a JSON.stringify() on and they appear as expected (without property getter/setter functionality wrapped around them).
