### ISSUE TITLE
Bad performance on find()

### ISSUE THREAD

**Issue by Redsandro** [techfort/LokiJS#613]
This is probably my own fault, but I am hoping someone can point me in the right direction.

I have a collection of about 3000 medium-big objects in node.js. Now when I do:

```
collection.chain().find({
	"attributes.ai": false, 
	"attributes.score": {
		"$lte": 2200
	}, 
	"transport.digital": true, 
	"transport.rating": {
		"$in": [
			4, 
			5
		]
	}
}).data()
```

It takes about 10 seconds on my laptop (and yields 800 results).

Any idea why this is so slow?

**Comment by Redsandro** [comment]
Holy... it's caused by the `node.js` debugging mode. Even when no debugger is attached, running with `--debug` causes this. Without debugging it's less than a second.

I wonder how this is with the newer `--inspect`. I will investigate.

**Comment by obeliskos** [comment]
interesting, not sure why --debug flag with no debugger attached would do that.

on my machine i had 8.0.0 installed which i just upgraded to 8.5.0 and neither had major performance differences when running : 
```
node --inspect benchmark/benchmark
```
using --debug option instead yields (apparently fatal) DeprecationWarning and does not run script at all

**Comment by Redsandro** [comment]
Ok, it seems to only happen when there's a breakpoint within the scope where a large collection is generated. I cannot reproduce it without debugger attached, so I'm afraid I made a mistake.

I'm using node 4 LTS. It turns out this is not an issue in any production environment. I will keep an eye on this and next time I see weird timings, I will take a closer look.
