### ISSUE TITLE
Memory issue - NativeScript with Lokijs

### ISSUE THREAD

**Issue by bnbs** [techfort/LokiJS#615]
We're writing a mobile sales application using NativeScript + Angular and we want to be possible to use it without internet connection,
so for that we have to download all data like products, clients, among others and save it on the application. Because it is a big volume of data we decide to
use lokijs due to performance, however we're facing the following problem: because all data/collections is load in memory, sometimes the application
reaches 500MB of RAM. Is there a way to unload data from memory? Is there anything we can do to solve it?

**Comment by obeliskos** [comment]
So, as you mentioned, the lokijs will load all data into memory.  In addition, the act of loading and saving adds temporary memory pressure due to javascript's serialization.  By default this may (temporarily) multiply memory usage twofold or possibly threefold.  So i assume you are saving this and using loki nativescript adapter?  Do you have a way to determine how large the saved file(s) are?

So if a big chunk of your memory use is coming from serialization, using the partitioning adapter along with the (nativescript?) adapter might help.  That serializes each collection to separate files, reducing overall memory pressure to that amount required to serialize your largest collection. 

A paging option on the LokiPartitioningAdapter could reduce the size of chunks serialized (and accumulated) even more but if your inner adapter offers transactional rollback on errors, the scope would be per page possibly leaving it in an inconsistent state.  For large data, if it is just for caching data that may be acceptable though.

For nodejs, we have LokiFsStructuredAdapter which can utilize node file streams to serialize one object at a time which would be ideal but I do not know if such asynchronous file stream functionality is available in Nativescript to consider if the adapter could be modified to act similarly.

**Comment by brunaaanayara** [comment]
Yes, I'm using LokiNativescriptAdapter and by now the clients file, for example, have 55mb. 
So, I tried to use the LokiPartitioningAdapter along with LokiNativescript adapter but no success. I was following this [link](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#an-example-using-the-lokipartitioningadapter-along-with-lokiindexedadapter-might-appear-as-) and I got an error saying  "Cannot read property 'adapter' of undefined at getENV" 
I don't know if I'm doing correctly or I'm missing something.

My code:

```
let nativeScriptAdapter = new LokiNativeScriptAdapter();
let partitionAdapter = new Loki.LokiPartitioningAdapter(nativeScriptAdapter, { paging: true });
this.db = new Loki(this.path, {adapter: partitionAdapter}); 
```

**Comment by obeliskos** [comment]
I think the commit I just made would fix that error.  If you'd like to try the latest github version, let me know if it fixes.

**Comment by brunaaanayara** [comment]
The commit fixed that error, but I still cannot make it work. The problem now occurs when I try to load the database, when I was using just LokiNativeScriptAdapter the code below works but when I try to use along with LokiPartitioningAdapter the code throw an error:  Unexpected end of JSON input
JS: at JSON.parse (<anonymous>) line 1908; 
When using LokiPartitioningAdapter along with LokiNativescript adapter the loadDatabase method works differently?

```
import { Injectable } from '@angular/core';
import * as LokiNativeScriptAdapter from 'loki-nativescript-adapter';
import * as Loki from 'lokijs';

var fs = require("file-system");
@Injectable()
export class Database{

    private path: any;
    private db: any;
    private isInstantiated: boolean;

    public constructor(){        
        this.path = fs.path.join(fs.knownFolders.currentApp().path, "database.db");       
        if(!this.isInstantiated){

            let nativeScriptAdapter = new LokiNativeScriptAdapter();
            let partitionAdapter = new Loki.LokiPartitioningAdapter(nativeScriptAdapter, { paging: true });
            this.db = new Loki(this.path, {adapter: partitionAdapter});
            //this.db = new Loki(this.path, {adapter: new LokiNativeScriptAdapter()}); 

            this.isInstantiated = true;                               
        }
    }

    public loadDatabase(){        
        let loadDatabase: any;
        let _db = this.db;
        return new Promise<boolean>(function(resolve, rejected){
            _db.loadDatabase({}, function(){
                resolve(true);
            });
        });
    }    
}
```

**Comment by obeliskos** [comment]
Did you delete the old (non-partitioned) database first?  If you need to upgrade, let me know and I'll describe how that might work.

**Comment by brunaaanayara** [comment]
Yes, I deleted the old database.

**Comment by obeliskos** [comment]
This sounds very similar to #552.

I believe in that thread the solution was to override the default delimeter by passing a 'delimiter' option to the LokiPartitioningAdapter such as : 

```javascript
var nsa = new LokiNativescriptAdapter();
var paOptions = {
  paging: true, 
  pageSize: 5 * 1024 * 1024, 
  delimiter:'$<-|->$'
};
var pa = new LokiPartitioningAdapter(nsa, paOptions);
```

**Comment by brunaaanayara** [comment]
So I followed #552 and made it work but I'm still facing one problem: 
First of all I download all data and save into loki.
Next I list all collections just to make sure that my data was saved.

JS: {"name":"TipoPagamento","type":"TipoPagamento_NEW","count":11}
JS: {"name":"TipoFrete","type":"TipoFrete_NEW","count":4}
JS: {"name":"Fornecedor","type":"Fornecedor_NEW","count":101120}
JS: {"name":"CondicaoParcelamento","type":"CondicaoParcelamento_NEW","count":79}
JS: {"name":"ClienteListaPrecoVenda","type":"ClienteListaPrecoVenda_NEW","count":0}
JS: {"name":"ListaPrecoItem","type":"ListaPrecoItem_NEW","count":9}
JS: {"name":"ListaPreco","type":"ListaPreco_NEW","count":1}
JS: {"name":"ClasseCliente","type":"ClasseCliente_NEW","count":6}
JS: {"name":"Cliente","type":"Cliente_NEW","count":102636}
JS: {"name":"Produto","type":"Produto_NEW","count":206937}
JS: {"name":"Configuracao","type":"Configuracao","count":1}
JS: {"name":"usuario","type":"usuario","count":1}

So I close the application, open it again and list all collection

JS: {"name":"TipoPagamento","type":"TipoPagamento","count":11}
JS: {"name":"TipoFrete","type":"TipoFrete","count":4}
JS: {"name":"Fornecedor","type":"Fornecedor","count":101120}
JS: {"name":"CondicaoParcelamento","type":"CondicaoParcelamento","count":79}
JS: {"name":"ClienteListaPrecoVenda","type":"ClienteListaPrecoVenda","count":0}
JS: {"name":"ListaPrecoItem","type":"ListaPrecoItem","count":9}
JS: {"name":"ListaPreco","type":"ListaPreco","count":1}
JS: {"name":"ClasseCliente","type":"ClasseCliente","count":6}
JS: {"name":"Cliente","type":"Cliente","count":0}
JS: {"name":"Produto","type":"Produto","count":0}
JS: {"name":"Configuracao","type":"Configuracao","count":1}
JS: {"name":"usuario","type":"usuario","count":1}

As you can see "Produto" and "Cliente" are empty and I'm not understanding why. Any clues?
