### ISSUE TITLE
LokiNativeScriptAdapter saveDatabase not working

### ISSUE THREAD

**Issue by brunaaanayara** [techfort/LokiJS#616]
First of all I'm writing a mobile application using NativeScript so because of that I'm using LokiNativeScriptAdapter. I'm trying to download some data and save into loki database but the application stopped working and I didn't understand why that happened cause nativescript write file is async. So after some debug I found that the LokiNativeScriptAdapter saveDatabase was never hit and the persistence adapter is type of LokiFsSystemAdapter and not of LokiNativeScriptAdapter. Should this happen?

**Comment by obeliskos** [comment]
No, so is this using partitioning adapter or just nativescript adapter alone?  If you pass in adapter to loki constructor options it should use that and not reassign the adapter... at least for the loki instance you are constructing.  

Since this is opened as new issue, please post your call to loki constructor and adapter instantiations.

**Comment by brunaaanayara** [comment]
Now I'm using just nativescript adapter.

My code:
```
this.path = fs.path.join(fs.knownFolders.currentApp().path, "database.db");
this.db = new Loki(this.path, {adapter: new LokiNativeScriptAdapter()}); 
```

**Comment by obeliskos** [comment]
That looks right, so if you add something like this to the next line(s) : 
```javascript
console.log("Adapter class : " + this.db.persistenceAdapter.constructor.name);
console.log("Environment: " + this.db.ENV);
```
what does it output?

**Comment by brunaaanayara** [comment]
JS: Adapter class : LokiFsSystemAdapter
JS: Environment: NATIVESCRIPT

**Comment by obeliskos** [comment]
That looks wrong, so if you do this : 
```javascript
this.path = fs.path.join(fs.knownFolders.currentApp().path, "database.db");
var nsa = new LokiNativeScriptAdapter();
this.db = new Loki(this.path, {adapter: nsa}); 
console.log("nsa class : " + nsa.constructor.name);
console.log("Adapter class : " + this.db.persistenceAdapter.constructor.name);
```

**Comment by brunaaanayara** [comment]
JS: nsa class : LokiFsSystemAdapter
JS: Adapter class : LokiFsSystemAdapter

**Comment by obeliskos** [comment]
wtf

ok how about just : 
```javascript
var nsa = new LokiNativeScriptAdapter();
console.log("nsa class : " + nsa.constructor.name);
```

If that's the same, I'd say maybe you are requiring it incorrectly?

**Comment by brunaaanayara** [comment]
ow I realized that I was requiring it incorrectly.
