### ISSUE TITLE
Memory - Loki

### ISSUE THREAD

**Issue by bnbs** [techfort/LokiJS#617]
I'm writing a mobile application and for saving data I'm using LokiNativeScriptAdapter along with LokiPartitioningAdapter. I'm saving like 500 thousands of documents and for a mobile application I think this is a lot.  So the problem is: I call load database when application is initializing so as loki is an in-memory database the application take a long time to initialize like more than 10 seconds.
Is there a way to load just a part of the database with only 2 collections or do I have to load the database with all collections?

**Comment by obeliskos** [comment]
Yes this isn't too clean right now, we could probably add logic within partitioning adapter to configure what collections to use.  'hotloading' and handling 'partial saves' would need to be handled.

Until such logic is added, you would have to do something like this (which would load only first and third collections) : 
```javascript
function runPartialLoad() {
  // load the 'shell/container' db partition using inner adapter
  db2 = new loki('sandbox.db', { adapter: mem });
  db2.loadDatabase({}, function(err) {
    // load first collection using inner adapter
    mem.loadDatabase('sandbox.db.0', function(result) {
      var data = db2.deserializeCollection(result, { delimited: true });
      db2.collections[0].data = data;
      
      // now load third collection using inner adapter
      mem.loadDatabase('sandbox.db.2', function(result) {
        data = db2.deserializeCollection(result, { delimited: true });
        db2.collections[2].data = data;
        
        inspectObject(db2);
      });
    });
  });
}
```
