### ISSUE TITLE
Database files become zero size when they are opened at the same time

### ISSUE THREAD

**Issue by joehui** [techfort/LokiJS#619]
In my project, I have 4 database files.  The users database file is about 1MB big, the projectDocs database is about 100K, the other two are really tiny.

In my code, I have them opened in sequence.  I suspect that after the first few functions are called, they are not really done yet when the subsequent openDb() functions are called.  The simultaneous execution of these calls (combined with the autoload & autosave options) seem to have caused the database files to somehow be reset to zero size and die.

I am running this on Windows platform.  The node version is 6.10.1.

Following is roughly the code I have.  If I use setTimeout to delay the 2nd, 3rd & 4th call so that they will no chance of running simultaneously, everything is fine.

```
usersDb = openDb("users");
groupsDb = openDb("groups");
languagesDb = openDb("languages");
projectDocsDb = openDb("projectDocs");


function openDb(dbName) {
	var dbFilePath = basedir + "/" + dbName + ".json",
	var myDb = new loki(dbFilePath, {
			"autosave" : true,
			"autoload" : true,
			"autoloadCallback" : function() {
				// In our use, collection name is the same as db file name
				collections[dbName + "Collection"] = myDb.getCollection(dbName);
			},
			"autosaveInterval" : 20000
		});
	console.log("DB " + dbName + " opened");
	return myDb;
}
```

**Comment by obeliskos** [comment]
That shouldn't be a problem as long as you wait until they are loaded before using them.  The default adapter on nodejs is the LokiFsAdapter which is asynchronous.   Make sure you don't immediately try to read from those databases until loading is complete.   Typically you also use the autoloadCallback to add the collections if they do not already exist in the database (to initialize new database) and to trigger any code which needs to use that data immediately after loading.

Is there a reason why you aren't using the loki-fs-structured-adapter.js adapter which partitions each collection out into its own file?  While that adapter is more for high performance, it would simplify initialization/callback.  Or even partitioning adapter + LokiFsAdapter?  If you need examples let me know I have tons floating around :)

**Comment by joehui** [comment]
About async nature of LokFsAdapter, what is the best way to know when loading is done after "new loki()".  Should I put the callback inside "autoloadCallback" after the collection is assigned?

About loki-fs-structured-adapter.js adapter, since the project was done a couple years ago, we probably wouldn't want to spend time changing the adapter now.

Thanks for your help!

**Comment by obeliskos** [comment]
Ok, so what version of lokijs are you using?  What changed?

If your not worried about simulatenous requests and need to leave as separate requests might either : 

keep counter and when last collection loads, trigger code to run after data is loaded, like : 
```javascript
var collectionsToLoad=4;
...
function autoloadCallback() {
  // ...
  if (--collectionsToLoad === 0) {
    runProgramLogic();
  }
}
```

or you could force one load at a time like : 
```javascript
loadCollectionSequence(['users', 'groups', 'languages', 'projectDocs']);
function loadCollectionSequence(remaining) {
  var next = remaining.shift();
  var db = new loki(next, { autoloadCallback : function() {
    collections[next] = db.getCollection(next);

    if (loadCollectionSequence.length > 0) {
      loadCollectionSequence(remaining);
    }
    else {
      // runPostLoadLogic();
    }
  });,
}

Examples obviously skip alot of your fixup logic but for flow control either of those might work.

**Comment by joehui** [comment]
Thanks for your detailed response and code samples.

The Db json files become zero size seems to be caused by simultaneous calls to "new loki()".  It was okay at the very beginning.  But, as the sizes of the db files grow, this problem seems to occur more often.  The other change is that the node version is upgraded from 0.x to 6.10.1 now.  The lokijs version is 1.5.0.  Server is on windows platform using "iisnode".

You may want to investigate how simultaneous opening of the db files could have caused these files to become zero size.

For our use, to avoid this problem, I think we will make sure that we do not call the next "new loki()" call before the previous one is completely loaded.

Your 2nd example seems to be exactly what I am looking for.  It is essentially the same as the code that I am about to change to as below.


```
usersDb = openDb("users", function() {
	groupsDb = openDb("groups", function() {
		languagesDb = openDb("languages", function(){
			projectDocsDb = openDb("projectDocs", function() {
				<continue other program logic...>
			});
		});
	});
});

function openDb(dbName, callback) {
	var dbFilePath = basedir + "/" + dbName + ".json",
	var myDb = new loki(dbFilePath, {
			"autosave" : true,
			"autoload" : true,
			"autoloadCallback" : function() {
				// In our use, collection name is the same as db file name
				collections[dbName + "Collection"] = myDb.getCollection(dbName);
				if (callback)
					callback();
			},
			"autosaveInterval" : 20000
		});
	console.log("DB " + dbName + " opened");
	return myDb;
}
```

**Comment by joehui** [comment]
The above solution seems to work for me so far.  I think this issue can be closed now.
