### ISSUE TITLE
Document which MongoDB compatible queries

### ISSUE THREAD

**Issue by vdininski** [techfort/LokiJS#62]
Given the interest in lokijs' MongoDB compatibility it seems odd that there is no mention in the documentation as to what exactly is supported in terms of queries/methods.

Is there a one place where I can find all the currently supported queries?

**Comment by techfort** [comment]
Hi Vasil,
thank you for raising the issue.
MongoDB compatibility is an ongoing work, LokiJS didn't start with the intent of being MongoDB api compatible, but many users found this would be useful for many reasons, so we're gradually introducing this feature. I will explicitly specify whatever feature is MongoDB compatible in the next release.

**Comment by obeliskos** [comment]
The best current source for this is at techfort's website here : 
http://lokijs.org/#/docs

It mentions the operators we currently support are : 
- $eq: equal to
- $gt: greater than
- $gte: greater than or equal to
- $lt: less than
- $lte: less than or equal to
- $ne: not equal to
- $contains: contains
- $regex: use a regex pattern for matching

Each mongo-expression currently supports 1 field/operation for now, blended with javascript 'where' filters and Resultset and DynamicViews to allow chaining multiple 'and' style filters.  

As @techfort mentioned, we will be determining features for next release so feel free to request or inquire about specific issues.

**Comment by vdininski** [comment]
Thanks for the list! :)
However I'd like to ask whether you are planning on introducing support for $update operators (think **$set**, **$push**, **$inc**, etc) even though from what I see the operations are synchronous

**Comment by techfort** [comment]
@vdininski $update operators are not going to be supported in the short term, but we are going to implement a merge method which allows to merge a plain js object into a loki one and update the record in the collection. If you need any further help let me know, meanwhile I'm closing this.

**Comment by xeoshow** [comment]
Hello,

I am new to LokiJS, since it is 2018 now, how about the status for MongoDB API compatibility currently?

Thanks a lot.

Best regards, Jason
