### ISSUE TITLE
IndexedDB massive storage use

### ISSUE THREAD

**Issue by sondreb** [techfort/LokiJS#620]
We are experiencing on some devices that IndexedDB takes up a massive amount of storage, even though the total size of the LokiJS entities are just a few megabytes. Here is a screenshot from a Windows 10 PC with latest version of Chrome (61), as shown in the screenshot the amount of storage reported by .getCatalogSummary() is **3.5 MB**. The usage reported by Chrome for IndexedDB, is a massive **2944 MB**.

![image](https://user-images.githubusercontent.com/309938/31436063-f9d9abbc-ae81-11e7-83bd-f35946446171.png)

This is a web app that is also embedded into a Cordova app for Android and iOS. On iOS devices, the used storage is growing at a rapid pace and reporting gigabytes of used storage after some usage of the app.

LokiJS version: 1.5.0
Angular: 4.3.6

The app uses Web Sockets between app and services, and receives many updates to entities stored in LokiJS. So the total storage is not a lot, but the entities are updated many times each minute (some of the entities are).

We use the LokiIndexedAdapter, with autosave and autoload, but .saveDatabase() is also called a lot on individual updates that are received over Web Sockets.

This happens on just a few desktop PC devices, but appears to be consistent behavior on iOS devices. Same behavior on both iOS 10 and iOS 11.

There are unfortunately few tools and APIs available to debug what is happening within IndexedDB, does anyone knows any tools or tricks to debug such an issue?

I'm building a new Cordova app to test a comparison between LokiJS and direct IndexedDB API, to see if many updates will increase the used storage on iOS.

Additional comment:

Normally the reported size used by IndexedDB are **10-20MB**.

**Comment by sondreb** [comment]
Made a small app that verify the behavior and it appears to be a case of increasing storage usage when updating a lot of items over and over again.

The code is basically like this:

```js
    var idbAdapter = new LokiIndexedAdapter('DATABASETEST');

    db = new loki('test.db', {
        autosave: true,
        autoload: true,
        adapter: idbAdapter,
        autoloadCallback: databaseInitialize,
        autosaveInterval: 1000
    });
```

Then the callback:

```js
    function databaseInitialize() {

        if (!db.getCollection("users")) {
            db.addCollection("users");
        }
    }
```

Then create the initial entities:

```js
    if (!user) {
        log('Creating 5 entities in "users" collection.');
        users.insert({ id: '28a01183-6787-402a-a83d-d63613685d9d', name: 'Firstname1 Lastname', age: 20, modified: null, address: { street: 'Elm Street', zip: '4700', country: 'Norway' } });
        users.insert({ id: '027bfe3e-a3b0-408d-8cb2-5b9f1872654e', name: 'Firstname2 Lastname', age: 21, modified: null, address: { street: 'Elm Street', zip: '4700', country: 'Norway' } });
        users.insert({ id: '72d94d67-3a99-493a-ac13-c95906ba337a', name: 'Firstname3 Lastname', age: 22, modified: null, address: { street: 'Elm Street', zip: '4700', country: 'Norway' } });
        users.insert({ id: '5fdb1fad-2900-4e01-961a-4e872069a6c3', name: 'Firstname4 Lastname', age: 23, modified: null, address: { street: 'Elm Street', zip: '4700', country: 'Norway' } });
        users.insert({ id: '8092ef62-c8df-4f70-a686-645e0af6aa5f', name: 'Firstname5 Lastname', age: 24, modified: null, address: { street: 'Elm Street', zip: '4700', country: 'Norway' } });
        db.saveDatabase();
    }
```

Then a function that I loop many times doing a simple query, update entities and save:

```js
    var users = db.getCollection('users');

    for (var i = 0; i < 10000; i++) {

        var results = users.where(function (obj) {
            return (obj.age < 35);
        });

        for (var j = 0; j < results.length; j++) {
            var user = results[j];
            user.modified = new Date();

            users.update(user);
            db.saveDatabase();
        }
    }
```

This code will continuously increase the IndexedDB usage size on Chrome on the PC, and it will increase the "Data" size on Android and "Doucments & Data" on iOS.

The increase in usage is not as bad on Android and Chrome, but on iOS it grows much, much faster. Even though on the iPhone, it runs the loop a lot slower than the Samsung phone.

After ~20 minutes on an iPhone 6 with iOS 11.0.2 the size the  app uses is **22 MB**
After ~30 minutes on Samsung Galaxy S8 the size reported is **5 MB**
After ~15 minutes on Chrome it reports **2-3 MB**

db.persistenceAdapter.getCatalogSummary() returns size as 2672, which should be 2KB of data.

**Comment by sondreb** [comment]
The Android app have recycled its storage usage, and now reports less, **1.50MB** and increasing as the app is running.

**Comment by sondreb** [comment]
Wrote an update to the test app by using IndexedDB API directly, currently only testing that on the desktop and seeing similar behavior, but needs to run the testing a bit more as it's way slower. Tomorrow I'll update the Cordova test app by using IndexedDB directly and investigating if the same problem happens then.

One solution that comes to mind is reducing the amount of database saves, doing it on intervals that happens rarely and on application close. The app can receive thousands of entity updates a day so it's a lot of writes to IndexedDB.

**Comment by sondreb** [comment]
After my test app ran for a little short of a day, it takes up **1.36 GB** of data on iOS. So writing **2 KB** of data and persisting that to IndexedDB many many times, is not handled very well by iOS.

**Comment by sondreb** [comment]
Running Chrome on both OS X and Windows, normally recycle the storage. But as shown in the original post, sometimes even Chrome on desktop goes "rouge" and use massive storage that it never recycles.

Made a short little screen capture that shows how a simulation increase storage, but is cleaned up by Chrome once in a while.

![indexeddb](https://user-images.githubusercontent.com/309938/31487378-b36799f0-af3a-11e7-9c24-0186acadabfe.gif)

But as mentioned above, the same issue occurs when running IndexedDB API directly, so not an issue directly caused by LokiJS, but I will investigate further if using LokiJS have impact on the storage growth. I'm sure it will be valuable information for anyone using or considering using IndexedDB for app storage.

**Comment by sondreb** [comment]
Reported a bug at the WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=178204

**Comment by sondreb** [comment]
@obeliskos Thanks for the comment, regarding the autosave delay that was only for my test-app.

We had a look at the AppData for Chrome on a few computers, there are a couple of folders for a machine where Chrome on desktop has taken up a lot of storage, and those are "indexeddb.leveldb" and "indexeddb.blob". Computers with no storage increase, only has the .leveldb folders. Had a look at the files within the blob folder, and it is the content of the Loki-database, but sometimes it is written as often as 6-7 times a minute, and taking up a total of a couple of gigabytes.

Any idea when or what happens when Chrome outputs what appears to perhaps be a backup, into the .blob folder? Is it when binaries files are written to IndexedDB? That's not something we intentionally would be using, as mentioned this only happens in rare cases for the desktop (but always for iOS).

From what I experience now, it appears that the compact issues that was previously reported for Chrome, is no longer a problem, looks like it keeps truncating most of the time, but a few times it goes "rouge" and by the looks of it, creates an additional folder called .blob.

**Comment by sondreb** [comment]
We previously dropped using IndexedDB on devices, but will do another attempt after some testing with Safari on iOS. It appears that the storage usage increases as long as the database connection is open, and when closed, it goes back to using the actual stored data size.

I don't know if this perhaps is the way we used LokiJS, or perhaps this is something that should be changed in the library, making sure that the connection is not kept open all the time?

Updated the bug report here with some details: https://bugs.webkit.org/show_bug.cgi?id=178204

**Comment by mohshraim** [comment]
@nishanthvincent 
I think you should support the open case https://bugs.webkit.org/show_bug.cgi?id=178204#c3 by adding comment confirm the exist of bug.
And for now the only workaround is to delete the file on iOS native that keep increasing application data size..
we found the source of increment on the following file; IndexedDB.sqlite3-wal
and this was the location of file at container:
AppData/Library/WebKit/WebsiteData/IndexedDB/file__0/dbName/IndexedDB.sqlite3-wal
**Please note when you delete this file which suppose to have only transactional log you will lose your data saved at client device.**

**Comment by obeliskos** [comment]
Well I believe it was suggested at one time that we issue a close database and that should be easy enough to implement.  When your app shuts down, you might try calling that adapter method (manually for now) to see if (over time) that reduces the allocated growth which is apparently not reclaimed.

Hardest part would be having a test environment/test case which can easily verify whether a fix helps or not.

**Comment by nishanthvincent** [comment]
@mohshraim 
Thankyou somuch for the workaround. I will try to implement it and update.

**Comment by mohshraim** [comment]
@nishanthvincent 
Please add your comment also on webkit bug  -> https://bugs.webkit.org/show_bug.cgi?id=178204
More people adding comments will push them to find a solution for this bug.

**Comment by obeliskos** [comment]
Thanks all for pursuing correcting this...

@nishanthvincent : my last comment was misleading i meant 'we should add'... I just looked into this and added a 'closeDatabase' method to the adapter as well as a new options object with 'closeAfterSave' option to automatically close after every save.

To close manually (when no saves or autosaves are occurring) : 
```
adapter.closeDatabase();
```

To have the adapter close itself after every save (subsequent adapter activity will have to reopen the database) : 
```javascript
var idbAdapter = new LokiIndexedAdapter("myapp", { closeAfterSave: true });
```

If you want to try those methods out for diagnostic purposes they are checked into this main github branch.

**Comment by nishanthvincent** [comment]
@obeliskos Thank you so much!

**Comment by nishanthvincent** [comment]
@mohshraim deleting AppData/Library/WebKit/WebsiteData/IndexedDB/file__0/dbName/IndexedDB.sqlite3-wal
and reinitializing indexed db through Loki does not create the wal file anymore. Any ideas ?

**Comment by mohshraim** [comment]
@nishanthvincent  
In my case i am working on Firestore from Firebase, which use indexDB, 
What i do is deleting file beforeTerminate...  
so reopen my iOS app and my app start normally and create the - wal file...
I think Firestore handle this issue!!! 

I think this a LokJS issue
Try delete the whole folder AppData/Library/WebKit/WebsiteData/IndexedDB/file__0/dbName
In both scenario you will lose the stored data on mobile.

**Comment by nishanthvincent** [comment]
@obeliskos Here is my scenario. As Mohshraim suggested, I am watching the indexed db wal in the following location
*AppData/Library/WebKit/WebsiteData/IndexedDB/LokiCatalog/http_localhost_8080/*.wal
as soon as it hits 200MB My logic is to forcefully recycle

At first I deleted the wal file... that did not regenerate the wal file in the same folder.

Second, I deleted all the files in the http_localhost_8080/ directory that also caused weird behavior

Is there a way to delete the whole lokicatalog and reinitialize every thing while you are still in the app ?

**Comment by obeliskos** [comment]
Have you tried the (potential) fix i checked into main branch and shown about 5 posts above?

If you have the ability to test that newer version of the adapter, along with using the new settings described above, and see if your database size allocation is reset after saving. 

Also, roughly how large is your database's actual size (not counting duplicates)?

**Comment by nishanthvincent** [comment]
@obeliskos I tried your solution but that didn't work as it did not clear the wal file despite setting the catalog and db to null. is there a way to completely delete lokicatalog and reinitialize ??

**Comment by obeliskos** [comment]
As a temporary workaround, you should be able to delete the whole catalog directly from indexeddb from F12 console by running (warning this will delete the whole catalog, not just a single database/key within it) : 
```
indexedDB.deleteDatabase("LokiCatalog")
```

You should be doing that within console, viewing webpage within the domain which the indexedb is hosted.

Usually, when saving, the save is transactional so that if it fails it can revert to previous state.  Deleting in between saves would circumvent than behavior so it is not ideal long term... but neither is having a 30mb database take up all your device storage.

Chrome still seems to have the behavior of it continuously increasing size, i might experiment with that or try safari or ffq.

**Comment by nishanthvincent** [comment]
The platform I have issue with is on IOS running a hybrid mobile app. .
ionic1, cordova, lokijs

I did try this solution 
indexedDB.deleteDatabase("LokiCatalog")
this would never produce a success event for me rather a block event is fired

Here is my logic

 if (ionic.Platform.isIOS()) {
        $window.resolveLocalFileSystemURL(ConfigService.getIosIndexedDbStorageDirectory(), (fileSystem) => {
          let reader = fileSystem.createReader();
          reader.readEntries((entries) => {
            let wal = entries.find((entry) => entry.name.match(/wal$/i)); // looking for IndexedDB.sqlite3-wal
            if (wal) {
              wal.file((fileObj) => {
                console.log("Size = " + fileObj.size);
                if (fileObj.size > 524288000) { // 500 Mb   some threshold
                  console.log("File size is greater than thresold");
                       //   LokiService.indexedDbAdapter.catalog.db.close();
                      // LokiService.indexedDbAdapter.catalog.db = null;
                      indexedDB.deleteDatabase("LokiCatalog")

                  }
            }
    })
}

I think 'LokiService.indexedDbAdapter.catalog.db.close();' fires a close event and reinitializes lokicatalog or something like that
