### ISSUE TITLE
Is it possible to unlink a result from Loki?

### ISSUE THREAD

**Issue by cepm-nate** [techfort/LokiJS#621]
I'm not sure if this is supposed to happen, but it seems that modifying the returned object from a .find (or .findOne) actually modifies the result in Loki.js as well. This is NOT what I want.

Is there any way to "unlink" the result from Loki so that I can modify it without modifying the LokiJS record?

Example on jsFiddle https://jsfiddle.net/12wu8mm8/19/

(In my case, I'm modifying the results and striping out Loki Specific fields, then saving them into PouchDB (which then has a trigger to upsert it the new revision into Loki based on the _id field)). This means LokiJS is simply acting as a 'query tool' with an always-fresh copy of the PouchDB data. This works quite well as PouchDB is AWESOME for syncing between devices, and LokiJS is awesome at query speed.

But this little issue of 'update Loki without doing a .update' is getting in the way.

Any solutions outside of writing a custom CLONE function?

**Comment by obeliskos** [comment]
Using a 'built in' clone option?  By default lokijs does no cloning for optimal speeds, however you can select to do shallow or deep cloning, either everywhere or explicity on calls to data().

Default clone method (if cloning is turned on) is deep 'parse-stringify', if you only need 'shallow' cloning of top level properties that would be faster.

For defining cloning at the collection level (clones on inserts, update, find, where) see 'clone' and 'cloneMethod' options in [collection constructor docs](https://rawgit.com/techfort/LokiJS/master/jsdoc/Collection.html).

For cloning only on chained data() calls, see its [method options](https://rawgit.com/techfort/LokiJS/master/jsdoc/Resultset.html#data).

**Comment by cepm-nate** [comment]
Thanks! For some reason I didn't spot that when searching the documentation earlier.
