### ISSUE TITLE
Consider using JSDoc templates in Loki's JSDoc blocks

### ISSUE THREAD

**Issue by G-Rath** [techfort/LokiJS#622]
JSDoc supports `@template`.

You could use this with collections to aid autocompletion.

I've had a quick try around, and it seems to work in WebStorm.

By adding `@template CollectionType` to the JSDoc of `function Collection`, I can define a collection of type:

```
/** @type {Collection<Recipe>} */
const recipes = this._theDB.getCollection('recipes') || this._theDB.addCollection('recipes');
```

By then adding/changing `Collection.prototype.find`s return type to `Array.<CollectionType>`, WebStorm starts providing autocompletion:

![ss 2017-10-19 at 08 12 17](https://user-images.githubusercontent.com/3151613/31737859-49b2a69c-b4a5-11e7-88e7-f25750e52b8d.png)

I'd be happy to make a PR for this myself when I get the time.

Two minor side effects that would be a result from this is that I'd have to change the JSDoc return type from `array` to `Array` as while both are valid, [WebStorm currently only accepts `Array`](https://youtrack.jetbrains.com/issue/WEB-15815) as the Array type.

Also, I'd use long template names, instead of the usual single letter `T`, `K`, etc because WebStorm seems to have scoping issues and [gets confused when a template is already used in another class](https://youtrack.jetbrains.com/issue/WEB-7522#comment=27-2451012). I think using self-descriptive template names is fine anyway, and would aid documentation.

**Comment by obeliskos** [comment]
Interesting... so do you know if WebStorm's autocompletion supports this functionality to support typescript or just regular javascript prototypal classes?  Are some of your annotations / code in typescript?   

As long as its concise syntax and doesn't mess up actual jsdocs or other editors which do clever 'introspecting', I don't see why not.  I would like to take a moment to consider all options, but some of that would depend on how much this depends on actual type system like typescript or its annotations or what may be vendor specific.  I know we have some aged typescript annotations on definatelytyped, not sure if that would be worth updating just for the code completion.

**Comment by G-Rath** [comment]
My understanding is that this functionality exists for both JavaScript and TypeScript.

It's a fair bit [undocumented](https://stackoverflow.com/questions/16017627/document-generic-type-parameters-in-jsdoc), but JSDoc / Google closure compiler do [support generics](https://github.com/google/closure-compiler/wiki/Generic-Types).

Personally with my usage of LokiJS, WebStorm tends to mostly ignore the TypeScript - for some reason it prefers the JSDoc comments. In saying that, I think this is the only library I've used that's actually had detailed JSDoc comments; most others rely on the TypeScript index.d.ts file.
