### ISSUE TITLE
LokiNativeScriptAdapter is not saving database

### ISSUE THREAD

**Issue by Sharique-Hasan** [techfort/LokiJS#625]
LokiNativeScriptAdapter is not saving database and every time I get a new database whenever I open my app.

```
import * as Loki from 'lokijs';
import * as LokiNativeScriptAdapter from 'loki-nativescript-adapter';

this.db = new Loki(this.dbPath, {
            adapter: new LokiNativeScriptAdapter(),
            autoload: true,
            autosave: true,
            persistenceMethod: 'adapter',
            autosaveInterval: 1000
        });
        this.addLiveNewsCollection();
        this.addMetaDataCollections();
        this.db.saveDatabase();
```

**Comment by Sharique-Hasan** [comment]
JS: Adapter class : LokiNativescriptAdapter
JS: Environment: NATIVESCRIPT

**Comment by Sharique-Hasan** [comment]
I am doing this while adding my collection but still I get same 0 data

```
let collectionExist = this.db.getCollection('liveNews');
        console.log(collectionExist);
        if(!collectionExist) {
            this._liveNews = this.db.addCollection('liveNews');
        }
```

**Comment by obeliskos** [comment]
The database is loaded asynchronously, so you need to move any logic which initializes or reads contents into autoloadCallback.  The [wiki page](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#example-constructing-loki-for-autoloadautosave-with-default-localstorage-adapter-) should have examples.

**Comment by Sharique-Hasan** [comment]
Closing the issue as this was an error due to not loading the getting async after loadingDatabase
