### ISSUE TITLE
TTL options of Collections do not persist

### ISSUE THREAD

**Issue by AleCaste** [techfort/LokiJS#626]
Hello,
This is a very important issue for us since we are using Loki to store user sessions that obviously have an expiration time and we are using the TTL capabilities of loki collections.

The problem is that if we addCollection from scratch specifying the ttl (age) and ttlInterval (check-interval) options then the collection is added and the ttl daemon is started without any problems. Everything works perfectly.

But... if we restart the server, Loki loads the DB (in our case we are using the default json file adapter) and the problem is that collections ttl options are missing in the json file (if we open the file manually we can see the ttl property for our collection is null !!!!!)
So the ttl daemon is NOT started and the sessions expiration cycle becomes useless.

**Comment by AleCaste** [comment]
By the way, we can see that the ```Loki.prototype.serializeReplacer``` method prevents the ttl options from being serialized. Why????

**Comment by AleCaste** [comment]
Hmmmm... I know how to fix this.

In the ```function Collection``` the lines that say:
```
      this.ttl = {
        age: null,
        ttlInterval: null,
        daemon: null
      };
      this.setTTL(options.ttl || -1, options.ttlInterval);
```
... should be replaced with something like:
```
      this.ttl = options.hasOwnProperty('ttl') ? options.ttl : -1;
      this.ttlInterval = options.hasOwnProperty('ttlInterval') ? options.ttlInterval : null;
      this.ttlDaemon = {
        age: this.ttlAge,
        ttlInterval: this.ttlInterval,
        daemon: null
      };
      this.setTTL(this.ttl, this.ttlInterval);
```
This way we rename the collection.ttl object to collection.ttlDaemon while keeping the ttl and ttlInterval options.

Make sure to refactor the code to the new ttlDaemon name (in ```Loki.prototype.copy```, ```Loki.prototype.serializeReplacer```, and ```Collection.prototype.setTTL``` you will need to modify some lines to adapt to the new nomenclature.

**Comment by Codelica** [comment]
Ouch...  this seems like a pretty import issue for anyone hoping to combine ttl w/ persistence.  It will function correctly on a fresh initial run, but never again once persistent data is loaded.  Any chance to re-open ?

**Comment by ThomasSwolfs** [comment]
> Hmmmm... I know how to fix this.
> 
> In the `function Collection` the lines that say:
> 
> ```
>       this.ttl = {
>         age: null,
>         ttlInterval: null,
>         daemon: null
>       };
>       this.setTTL(options.ttl || -1, options.ttlInterval);
> ```
> 
> ... should be replaced with something like:
> 
> ```
>       this.ttl = options.hasOwnProperty('ttl') ? options.ttl : -1;
>       this.ttlInterval = options.hasOwnProperty('ttlInterval') ? options.ttlInterval : null;
>       this.ttlDaemon = {
>         age: this.ttl,
>         ttlInterval: this.ttlInterval,
>         daemon: null
>       };
>       this.setTTL(this.ttl, this.ttlInterval);
> ```
> 
> This way we rename the collection.ttl object to collection.ttlDaemon while keeping the ttl and ttlInterval options.
> 
> Make sure to refactor the code to the new ttlDaemon name (in `Loki.prototype.copy`, `Loki.prototype.serializeReplacer`, and `Collection.prototype.setTTL` you will need to modify some lines to adapt to the new nomenclature.
> 
> ... Last and not least, in the `Collection.prototype.ttlDaemonFuncGen` the line that returns... `return age < diff;` ... should actually be: `return (age!=null && age < diff);` ... due to the fact that in javascript expressions like (null<2500) returns true ! Likewise on the `Collection.prototype.setTTL` method you must replace the `(age<0)` condition with `(age==null || age<0)`

@AleCaste Is there a reason why you didn't create a pull request for this fix?
