### ISSUE TITLE
When updating record, inconsistency in update method

### ISSUE THREAD

**Issue by szmarci** [techfort/LokiJS#627]
When I retrieve a record from a collection:
```
    var record = this.collection.findOne({"id": someid});
```
And update it:
```
    record.prop  = "change";
    this.collection.update(record);
```
Then I jump to the sourcecode of `Collection.prototype.update` method, the `oldInternal`, `newInternal` reference would point to the same object.

Whereas if I retrieve the record like this:
```
    var record = Object.assign({},this.collection.findOne({"id": someid}));
```
`oldInternal` would point to the old object, and `newInternal` to the updated (new) object.
I don't know if it makes a difference, I was just scrolling through the source code and I noticed, but the last one seems to be the correct one, right? 
Don't get me wrong, I know the 'why', retrieval returns a reference not a copy, but then why the distinction of old and new?
Maybe I am missing something.

Thanks for the answer.

**Comment by obeliskos** [comment]
So your object assign is basically a shallow clone, right?  oldInternal and newInternal distinction only really matters if you turn on 'clone' option on for collections.  You do have a choice to choose 'cloneMethod' of 'shallow-assign' if you want to duplicate that behavior.

By default cloning is turned off by default for peak performance, but 'shallow-assign' should very fast shallow clone method -vs- a 'parse-stringify' implementation which is the default clone method.
