### ISSUE TITLE
LokiFSStructuredAdapter: deleteDatabase is not a function

### ISSUE THREAD

**Issue by krishnagopinath** [techfort/LokiJS#628]
First of all, thank you for making this blazing fast DB! 

I have a question about an error I'm encountering with the `LokiFSStructuredAdapter`: 

```
 TypeError: this.persistenceAdapter.deleteDatabase is not a function
      
      at Loki.deleteDatabase (node_modules/lokijs/src/lokijs.js:2615:33)
      at Loki.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Loki.ret (eval at makeNodePromisifiedEval (node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
      at Object.destroyDatabase (server/utils/dbHelper.js:85:47)
     ........
```

I'm trying to run `deleteDatabase` after every integration test (sure, I could just clear the collections, but I'm just starting this side project and did not want to get too granular with details)

It would be great if you could point out the error in my ways! 

Thank you so much :smiley: 

Also, here's how my code looks like:

```
// dbHelper.js
const LokiFSStructuredAdapter = require("lokijs/src/loki-fs-structured-adapter");

// Init DB with FS adapter and some options
const db = new Loki(`${config.DB_NAME}.db`, {
  adapter: new LokiFSStructuredAdapter(),
  autosave: false,
  autoload: false
});

// further down
db.loadDatabase({}, () => {
   // The function that gets called by the tests
  function destroyDatabase() {
   return new Promise((resolve, reject) => {
     if (db === null) return reject("No DB to delete!");

     // Goes further in and tries the delete
     db.deleteDatabase(err => {
       if (err) reject(err);

       resolve(null);
     });
   });
 } 
});
```

### Update

This problem does not occur with the default node FS adapter, so I've been using that for now, I would love to use the `LokiFSStructuredAdapter`, so I'll keep this issue open! :)

**Comment by obeliskos** [comment]
This could probably be easily added to LokiFsStructuredAdapter, using node fs module wildcard pathnames to find and delete any collections, both currently in the database and possibly leftover persisted collections which might have been deleted from loki db but left on disk.  

If anyone wants to submit a p.r. that would be great, otherwise I can probably look into that sometime later next week.

**Comment by krishnagopinath** [comment]
I would love to give it a try, if that is OK :) 

I might be able to get to it only by weekend, I hope that timeline is OK..

**Comment by obeliskos** [comment]
Sure, no problem...

I re-familiarized myself with node fs and wildcards don't seem to be in native libraries.  We would probably need a solution which does not add other external library dependencies and is not operating system dependent.  

So if I had to guess, if it were me I would probably use node 'path.dirname' to get directory name of filename passed in (or work out directory if relative path) and then either get list of all files and then delete those that start with filename or just increment until the file no longer exists ('test.db', 'test.db.0', 'test.db.1', 'test.db.2'...)  Rough logic, not sure if I am describing well or missing better solution but let me know if you are uncertain about how these filenames are structured.

**Comment by krishnagopinath** [comment]
Alrighty @obeliskos , thanks! I plan to get this working today.
