### ISSUE TITLE
Auto-save not triggered when performing insert on custom adapter

### ISSUE THREAD

**Issue by sondreb** [techfort/LokiJS#629]
Made a custom adapter which apparantly is not always called to autosave when items are inserted. Is this normal behavior, or is this a bug? What other operation should be done on insert to trigger save being called on the adapter?

Here is a screenshot that shows the output of the source below:

![image](https://user-images.githubusercontent.com/309938/32385850-aa8ef0c6-c0bf-11e7-81cc-ed3a8fe9984c.png)

I made the repo quickly based on the sample code in the LokiJS documentation. It simply creates a simple adapter, creates a database, a couple of items, then saves and executes an interval that performs inserts every 3 seconds.

Auto-save is configured to be 5 seconds, but never occurs in this sample. The collection grows every 3 second, but after a reload, it is reset back to the initial save that was run on load.

```
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lokijs/1.5.1/lokijs.min.js"></script>
    <script>
        class MyLokiAdapter {
            constructor() { }

            saveDatabase(dbname, dbstring, callback) {
                console.log('SAVE DATABASE: ' + dbname);
                console.log(dbstring);
                localStorage[dbname] = dbstring;
                callback(null);
            }

            loadDatabase(dbname, callback) {
                var serializedDb = localStorage[dbname];
                console.log('LOAD DATABASE:' + dbname);
                console.log(serializedDb);
                callback(serializedDb);
            }
        }

        var db = new loki(this.databaseName, {
            autosave: true,
            autosaveInterval: 5000,
            autoload: true,
            adapter: new MyLokiAdapter()
        });

        var users = db.addCollection('users');

        users.insert({
            name: 'Odin',
            age: 50,
            address: 'Asgard'
        });

        var results = users.find({ age: { '$gte': 35 } });
        var odin = users.findOne({ name: 'Odin' });

        console.log(results);
        console.log(odin);

        db.saveDatabase();

        setInterval(() => {
            users.insert({
                name: 'Thor',
                age: 51,
                address: 'Asgard Road'
            });

            console.log('INSERTED!');
            var results = users.find({ age: { '$gte': 35 } });
            console.log(results);

        }, 3000);
    </script>
</head>

<body>
</body>

</html>
```

**Comment by obeliskos** [comment]
When using autoload, you should pass an autoloadCallback function as well, and use your database initialization logic in there.  You shouldn't manually call loadDatabase when using autoload.

Similarly, when using autosave you do not need to manually call saveDatabase.

We have many examples in the examples folder (like [quickstart3](https://github.com/techfort/LokiJS/blob/master/examples/quickstart3.js) or if you load [LokiSandbox](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm) you can pick examples from the 'Github sample gists' dropdown (like 'Quickstart 3').

**Comment by sondreb** [comment]
Thanks! The issue is reading (and adding) a collection before "autoloadCallback" is raised. If one does that, the adapter won't be called unless explicit calling "saveDatabase". It was only during a change of adapters (going away from IndexedDb) this become a problem, as the new adapter takes a bit longer to initialize.

Using saveDatabase can make sense together with autosave, in a scenario where one don't want to persist too often when data arrives from a service, but want to persist immediately when user edits data locally. This way, if the app crashes any changes made by the user is persisted, but data that come from services might be a few minute stale.

Refactored some code and changed initialization process, works fine again =) Thanks!

**Comment by obeliskos** [comment]
Yes, the persistence adapter might have been synchronous before and asynchronous now... best to just deal with initialization asynchronously unless you need that fine grained synchronicity when using synchronous adapter.

Yep, I can see that being useful to use both autosave and manual calls when used correctly and not (for example) in loops.  I guess my advice was in general... and throttled saves should debounce to some extent so it's let's likely now to accidentally mess anything up with overlapping saves.

Glad to hear your working again :)
