### ISSUE TITLE
Fork Info - TypeScript and lokijs-collections

### ISSUE THREAD

**Issue by TeamworkGuy2** [techfort/LokiJS#630]
Not an issue, just FYI, I've ported a light-weight version of lokiJS to TypeScript:
I was the original writer of the [TypeScript](http://www.typescriptlang.org/) definition for lokijs (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lokijs). 
I've been looking for time to update the definition, but the projects I work on day-to-day have taken me in another direction. 

As a result, I've ported/forked lokijs@1.3.0 and integrated it directly into [lokijs-collections](https://github.com/TeamworkGuy2/lokijs-collections).  Both lokiJS and lokijs-collections are MIT licensed.  @obeliskos and @techfort, let me know if you have any issue or request related to my port of lokiJS code in lokijs-collections.

**Comment by Viatorus** [comment]
Well, I just do a similar thing with the official LokiJS version 2. Please have a look at https://github.com/LokiJS-Forge/LokiJS2 - especially the branch "move_to_typescript". 

I use and used some of your types definition from DefinitelyTyped. Maybe we can combine our work/gain from each other.

**Comment by TeamworkGuy2** [comment]
@Viatorus I like it, I'm always excited to see projects move toward typescript!  My goals with lokijs-collections depart from lokijs on two major points, which may make it somewhat incompatible with LokiJS2:
1. I haven't found strong uses for Resultsets and DynamicViews, I see how they'd be useful in complex server side apps, but most of my work is client side apps that don't benefit from these tools.  So lokijs-collections moves away from the extra complexity and also modularizes the main 'loki' file into separate pieces for persistence, change tracking, etc.
2. Type safety is of paramount important to me, so classes like DynamicView have a generic type, so function definition like: `applySimplSort(propname: string)` in [LokiJS2/.../dynamic_view.ts#L267](https://github.com/LokiJS-Forge/LokiJS2/blob/move_to_typescript/packages/loki/src/dynamic_view.ts#L267) is `applySimpleSort(propname: keyof T)` in [lokijs-collections/.../DynamicView.ts#L173](https://github.com/TeamworkGuy2/lokijs-collections/blob/master/db-collections/DynamicView.ts#L173).

Awesome work, thanks for letting me know :)

**Comment by obeliskos** [comment]
That's great, I can see a lot of possibilities with strongly typed loki as I have done similar (experiments) to concrete mapping layer between loki and dotnetcore node services using generics.  Typescript is really evolving to having that versatility, at compile/transpile time, within js vm itself.

Hope to have time to learn ts more and maybe help out.  Thanks guys, great to see loki evolve... I'm sure @techfort would agree.
