### ISSUE TITLE
Find document with missing property

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#631]
Is there a way to find documents that (do not) have a property set to any value? I need to find documents that are missing a required field so I can add it. I was looking at `undefinedin` but I don't really understand whether what the docs say relates to my use-case. I could user `where` of course, but if I don't have to I'd rather not.

**Comment by obeliskos** [comment]
Yes those query ops like keyin/nkeyin and definedin/undefinedin are a little confusing.  If anyone knows better, feel free to chime in but this is my understanding :

I would say that if you do not need to distinguish between { a: 1 }, { a:2, b: undefined } then you could just call the following (which will return both) : 
```javascript
  coll.find({ b: undefined });
```

If you wanted to widen that to include null values (in addition to undefined), you might use : 
```javascript
  coll.find({ b: { $aeq: undefined } });
```

I don't think any of our ops currently pass in a whole object (from data array) , so the op can't do a hasOwnProperty test. 

If you do not want any results where object has the property defined and equal to undefined, then you would need to use a filter function such as either : 
```javascript
// if not indexed, might as well use the simpler syntax with full array scan
var results = coll.where(function(obj) { return obj.hasOwnProperty("b") });

// if indexed, might want to use two phase to filter for just undefined vals first, 
// and then do hasOwnProperty
results = coll.chain().find({b : undefined}).where(function(obj) { return !obj.hasOwnProperty("b") }).data();
```

**Comment by retorquere** [comment]
I do not need to distinguish between `{ a: 1 }` and `{ a:2, b: undefined }`, and there really shouldn't be `null` values in that field, but it's good to know that I can do this.
