### ISSUE TITLE
How do I handle property transformations before/after storing?

### ISSUE THREAD

**Issue by thasmo** [techfort/LokiJS#634]
Document `D` holds a complex object `O`, which should not get stored directly in the database, but only the identifier `I` (which is a property of object `O`) of object `O` should get stored in the database.

How would I transform the identifier `I` to object `O` when reading from the database, and transform object `O` to it's identifier `I` when storing the document `D`?

Also, how would this work with the auto-update feature? In the best case I just want to assign the object `O` and have only it's identifier `I` persisted,

```js
const document = {
  object: new ComplexObject('unique-identifier-123')
};

collection.insert(document); // Does not store the ComplexObject object, but only it's identifier.
```

Is there a simple way to make LokiJS transform the property on insert/update/find, etc.?

Thanks a lot!

**Comment by obeliskos** [comment]
This is not a specific use case lokijs is designed to make simple, but there are features in lokijs and native javascript that you might be able to employ to accomplish what you are looking to do.

I guess you would need to decide if you want the 'in-memory' representation storing full object with persisted storing only identifier.... or both representations storing identifier.

Collections emit a 'pre-insert' event which you could write a handler for to fix-up your object into an identifier if you want the 'in-memory' representation (as well as persisted representation) to use the identifier.

Attaching a 'toJson' method at any level within your object should also allow you to control how the object will be serialized if you don't mind the 'in-memory' representation containing full object.

You can also utilize collection 'proto' options to define a custom javascript class to inflate from (which incidentally may also contain a toJson method, thus closing the deflate/inflate rountrip).  Collection proto's are slightly less documented but are rather easy and you can probably figure out its usage by looking at our [unit tests here](https://github.com/techfort/LokiJS/blob/master/spec/generic/typed.spec.js).
