### ISSUE TITLE
For-looping collection.remove(obj) weird behavior

### ISSUE THREAD

**Issue by dnfpili** [techfort/LokiJS#64]
Whenever I use a for-loop to remove objects from a collection, loki skips every other reference and ends up deleting only half of the objects in the result array.

Although when I reverse the loop, it works as expected.
Using Node-webkit and lokijs 1.1.14

````
        var loki = require("lokijs")
        var db = new loki("test3");

        var folders = db.addCollection("folders");

        folders.insert({name : "data", type: "system"});
        folders.insert({name : "images", type: "user"});
        folders.insert({name : "datacache", type: "system"});
        folders.insert({name : "imagecache", type: "system"});
        folders.insert({name : "sample", type: "user"});
        folders.insert({name : "documents", type: "user"});
        folders.insert({name : "feeds", type: "user"});
        folders.insert({name : "site", type: "user"});

        db.saveDatabase();
        console.log(folders);


        // Load the database

        db2 = new loki("test3");
        db2.loadDatabase({}, function(){

            var folders = db2.getCollection("folders");
            console.log(folders);
            var list = folders.find();

            for(var i = 0; i < list.length; i++) {
                console.log(i);
                console.log(list[i]);

                folders.remove(list[i]);
            }


            // Reverse loop works fine though

            /*for(var z = list.length -1; z >= 0; z--) {
                console.log(z);
                console.log(list[z]);

                folders.remove(list[z]);
            }*/


        });
````

**Comment by techfort** [comment]
Could I make a suggestion before checking if there is a bug in lokijs? In
your first for loop you're not caching the length of the array you're
iteratinng (list.length). Problem is, you're changing the array length in
the loop by removing an element, which means that list.length is
re-computed. This can definitely lead to weird behaviour. May i suggest you
place a simple `var len = list.length` and change the signature of the loop
to `for (var i = 0; i < len; i++)` and see if it works? On a sidenote, Loki
should probably implement a removeAll() method which uses a solid logic so
you don't have to do that operation yourself.

**Comment by dnfpili** [comment]
Based from your suggestion, I assigned the length to a variable like this

````
var length = list.length;

            for(var i = 0; i < length; i++) {
                console.log(i);
                console.log(list[i]);

                folders.remove(list[i]);
            }
````

I throws me an error instead

````
Uncaught node.js Error 

Error: Parameter is not an object
    at LokiEventEmitter.Collection.remove (X:\nginx146\html\spark-desktop\node_modules\lokijs\src\lokijs.js:2692:15)
    at file:///X:/nginx146/html/spark-desktop/test3.html:50:25
    at readFileCallback (X:\nginx146\html\spark-desktop\node_modules\lokijs\src\lokijs.js:726:11)
    at fs.js:289:14
    at Object.oncomplete (fs.js:97:15)

````
A removeAll() would be nice too, or something that works like:

var list = folders.find({ hidden : true }); 
list.remove(); //removes the results from the query

**Comment by techfort** [comment]
Ok let's separate the issues. I'll create an improvement issue to implement a remove(queryObject) and a remove(func) (where you can pass a filter function).

As for the current issue, Loki thinks you're not passing an object to the remove function so what's the output of that console.log(list[i]) ? It may help understand what's going on.

**Comment by obeliskos** [comment]
Yea best way is to reverse iterate so you are not changing the array index locations of any of the remaining documents.

Issue #65 opened by @techfort should provide simpler methods of doing this but per your existing examples, that is what's causing odd behavior/errors.

**Comment by techfort** [comment]
To clarify on why the forward for loop behaves weirdly: using array.length in the for loop means the counter `i` is checked against the `array.length`. If an `array` has 3 elements, and you remove element `0`, then set `i` to 1,  two problems arise: 1. `i` will now be checked against 2 (the new array length) and 2. loki does a `splice` removing the elements in the data and effectively reorganizing the rest of the array so you'll end up skipping one element per iteration in which you perform a remove.

Purely from an optimiziation point of view, it is always better to cache the length so the for loop doesn't have to recompute the array length at each iteration.

**Comment by dnfpili** [comment]
Thanks @techfort and @obeliskos,

I was working on the assumption that _var list = folders.find()_ actually cached the data to the list variable. Turns out that loki updates the folders.find() reference every time I called remove() resulting in an error halfway through the cached list.length loop. 

I think I understand better how loki works now.

**Comment by techfort** [comment]
Good to know things are working out for you @dnfpili . Can we close this? I'm counting on implementing remove() and removeAll() in the next few days, see #65

**Comment by ssimo3lsuhsc** [comment]
Can I please point out that the code of the removeWhere() function itself is guilty of this behavior? I would fix it myself, but I've had problems on another project with testing asynchronous code, even with Mocha installed. I don't completely understand how it works.
