### ISSUE TITLE
How can I implement a InsertOrReplace over a Unique index?

### ISSUE THREAD

**Issue by danielg2002** [techfort/LokiJS#640]
Hi,
I need something like this http://www.sqlitetutorial.net/sqlite-replace-statement
In a performant way.

Obviously I can do an insert and catch the error, or do a find 'by' first, any other way?

**Comment by Viatorus** [comment]
You could do also an updateWhere/findAndUpdate call.

An [upsert](https://github.com/techfort/LokiJS/issues/158) (update/insert function) is currently not implemented but tracked for LokiJS2.

**Comment by danielg2002** [comment]
thanks @Viatorus 

I suggest include an optional parameter to implement the "object merge" logic (ie. ObjectAssign, custom function).

thanks,
Daniel.
