### ISSUE TITLE
Sort issue in IOS version below 11

### ISSUE THREAD

**Issue by shashankdevp** [techfort/LokiJS#641]
We have a issue where normal sort is not working as excepted in IOS with version below 11. 

In version below 11, when a sort method is called it does not return proper sorted values. But in version 11 it works fine. 

Similarly it works fine in Android phones.

Sample code is below

     var timeStampCollection = localDb.getCollection('TimeStampDetails');
     var timeStamps = timeStampCollection.find({ 'loggedInTimeStamp': { '$gt': 0 } }).sort(function (a, b) { 
         return (a.loggedInTimeStamp < b.loggedInTimeStamp); });
     return timeStamps;

We have created a sample code pen [Sort issue](https://codepen.io/shashankHS/pen/BJJJRb), Please open the code pen in both Google chrome and Safari browser and open Javascript console for the sorted string.  

You can edit the loggedInTimeStamp fields for the sort issue.

**Comment by Viatorus** [comment]
Hello @shashankdevp,

I don't have any Apple device - what is the console output of the Safari sort function? Is there any error message in the console?

**Comment by shashankdevp** [comment]
Hello @Viatorus ,

We were able to reproduce this issue in safari browser installed in Windows machine.

The problem which we are facing is that normal sort function does not return the desired value where as simpleSort method returns proper sorted value in Safari browser. But the same normal sort and simple sort function works fine in Chrome browser.

Steps to reproduce

1. Open the the codepen in both Chrome and Safari browser
2. Open the console and check the sort order (for both normal sort and simple sort methods)
3. Edit one of the value (loggedInTimeStamp) in the list, and check the console for the sorted list.

Console output in **Chrome browser**

![image](https://user-images.githubusercontent.com/12233051/34708520-2ffeebbe-f539-11e7-8a94-46b792a2fea5.png)

Console output in **Safari browser**

![image](https://user-images.githubusercontent.com/12233051/34708645-b9205ff4-f539-11e7-89d8-c931468bf7fb.png)

Thanks & Regards,
Shashank

**Comment by Viatorus** [comment]
Could you give me a link / the version of the safari browser for Windows? With the one I found (Safari 5.1.7) the page does not even load probably:

![a pen by shashank_2018-01-09_10-01-28](https://user-images.githubusercontent.com/3637911/34712979-0aadb7fa-f525-11e7-8297-fde9fb688166.png)

But I found this related issue:
https://stackoverflow.com/questions/15507729/safari-doesnt-sort-array-of-objects-like-others-browsers

Use: a - b instead of a < b

**Comment by shashankdevp** [comment]
Hello @Viatorus ,

I had also installed the same version of Safari browser and the codepen renders similarly, What I did is opened javascript console which opens properly :)

**Comment by Viatorus** [comment]
But now the sort work for you?

Using: 

```js

var timeStampCollection = localDb.getCollection('TimeStampDetails');
 var timeStamps = timeStampCollection.find({ 'loggedInTimeStamp': { '$gt': 0 } }).sort(function (a, b) { 
     return (a.loggedInTimeStamp - b.loggedInTimeStamp); }); // minus, not <
 return timeStamps;

```

**Comment by obeliskos** [comment]
So your results are accurate for your 'simplesort' and 'stackoverflow' results on all browsers?

The stackoverflow example which @Viatorus linked and your codepen (now) shows looks correct... 

To be clear, your example is directly calling javascript sort method on the array of docs returned by (non-chained) collection.find().  (not a loki sort)

Javascript sort expects function returning number value of -1 (a is less than b), 0 (a is equal to b), or 1 (a is greater than b).  That is why our [chained sort example](https://rawgit.com/techfort/LokiJS/master/jsdoc/Resultset.html#sort) demonstrates the same expectation (as we use it within loki as well).

**Comment by shashankdevp** [comment]
Hi @Viatorus @obeliskos ,

Yes with the stackoverflow link provided by @Viatorus it works fine in the Safari browser. We have to verify in the app (IOS build) once. It should work fine, but will update you once we have tested.

Thanks for the help. 👍
