### ISSUE TITLE
How to get list of collections? 

### ISSUE THREAD

**Issue by umutozdemir97** [techfort/LokiJS#647]
I am using Map types to store collections in a Map object of databases. But being able to get the list of collection names and directly creating references to those collections like dbInsance.collection('collectionName') would be great. Or is there? I searched through documents and couldn't find it.

**Comment by obeliskos** [comment]
Yea, theres db.listCollections() which we should add jsdocs for... it returns array of objects with 'name', 'type', and 'count' properties.

**Comment by obeliskos** [comment]
Very [basic jsdoc](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html#listCollections) docs have been added, hopefully in the future people will at least be aware of the existence of the method.
