### ISSUE TITLE
Update is not creating a new one and throwing an error

### ISSUE THREAD

**Issue by umutozdemir97** [techfort/LokiJS#649]
I use update to add/update to sync a bulk of documents in a collection. But it throws an error: 

Error: Trying to update unsynced document. Please save the document first by using insert() or addMany()

I get a huge data and assign this data to a specific collection. I use collection.update() method to do this. Problem is, if not found, is not creating a new one. Is there a way to do this? Or is there a known workaround?

**Comment by obeliskos** [comment]
If your docs have not yet been inserted into loki database and do not have a $loki id, you need to insert them first.

Loki does not (yet?) have upserts but this has been requested in #158.  I suppose any upsert functionality (in LokiJS or LokiJS2) could allow keying off $loki or unique indices.

**Comment by umutozdemir97** [comment]
Maybe we can define a function in collection about how to increment and decrement the key we defined with _unique_ and _indices_. For an integer, decrementer returns key minus one, incrementer returns key plus one. Because my keys are hex values and to increment and decrement first I parse, add one, then turn it to hex value again and use it for next item. Passing incrementer and decrementer in options object in Collection creation would be a good idea. Adding it in Loki2 doesn't look like a good idea because upsert functionality is an important functionality for a NoSQL database.
