### ISSUE TITLE
create a removeWhere(queryObject), a removeWhere(func)

### ISSUE THREAD

**Issue by techfort** [techfort/LokiJS#65]
Optimize removal of multiple records with the above methods.

**Comment by dnfpili** [comment]
Looking forward to this.

**Comment by techfort** [comment]
Ok this is checked in, if you want to try the latest source. removeWhere() takes either a query object (same syntax as find() ) or a filter function. As for removeAll(), there is already a clear() that does just that. I also added support for remove (id: number) which deletes by id rather than passing the entire object.

**Comment by dnfpili** [comment]
Nice, I'll take a look at this as soon as I get back.

**Comment by techfort** [comment]
This is done and reflected in the docs.
