### ISSUE TITLE
Cannot TS2304: Cannot find name "LokiCollection"

### ISSUE THREAD

**Issue by sfaessler** [techfort/LokiJS#652]
After couple of weeks coming back to my NativeScript Application, the system does no longer start:

In console I get the following error:

Found peer TypeScript 2.5.3
app/services/database/database.service.ts(55,19): error TS2304: Cannot find name 'LokiCollection'.

app/services/database/database.service.ts(55,42): error TS2304: Cannot find name 'LokiCollection'.

app/services/database/database.service.ts(61,17): error TS2304: Cannot find name 'LokiCollection'.
app/services/diary/diary.service.ts(20,19): error TS2304: Cannot find name 'LokiCollection'.

TypeScript compiler failed with exit code 1

Code from database.service.ts:

```js
//------------------------------------------------------------------------------------------------------
getCollectionWithName(name: string): LokiCollection<any>
//------------------------------------------------------------------------------------------------------
{
    let coll: LokiCollection<any> = <LokiCollection<any>>this._db.getCollection(name); // this is line 55

     if (coll) {
        return coll;
    }

    return <LokiCollection<any>>this._db.addCollection(name);
}
```

I spent hours looking for a solution, debugging and pulling my hair. Unfortunately, I am currently running out of ideas, does someone have the same problem and can help?

Thanks for any help!

Regards,
Sven

**Comment by obeliskos** [comment]
Sorry I have not had time to respond, and others might be able to help you out better... if you are still looking for a solution.

So you are saying this worked for you at some point but stopped working?

At first glance, I would guess that the following syntax might work for you : 
```typescript
import * as Loki from 'lokijs';

// ...

function getCollectionWithName(name: string): Loki.Collection
{
let coll: Loki.Collection = <Loki.Collection>this._db.getCollection(name); // this is line 55
    if (coll) {
        return coll;
    }

    return <Loki.Collection<any>>this._db.addCollection(name);
}
```
