### ISSUE TITLE
Binary indices occasionally corrupt

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#654]
(continuation from #47)

I have users where the lokijs binary indices occasionally corrupt. It's hard to find out how this happens -- it happens infrequently, and a long-running log to catch is would generate *very* large files for all users. I can't reproduce this at will. Right now I'd be happy to see 1.3.5 drop which has detect and repair functions.

**Comment by obeliskos** [comment]
Great I will work over the next few days/weekend to get things prepared for a 1.5.3 release.  When that is done I will see if @techfort can publish an out-of-band release.

We can continue discussions during diagnosis here.

**Comment by retorquere** [comment]
I have `clone` on for all collections, so it's not an object being modified without an `update` being called.

**Comment by obeliskos** [comment]
Yea weird... so what is the datatype of the property whos binary index is becoming corrupt?   Do I recall that you convert DateTimes from our stored numbers back to a date data type?  If so maybe we should focus there.  

You also might look at disabling the adaptiveIndices so that they revert to our original 'lazy' indices.  So whenever we insert/update/remove we would flag index as dirty and it would stay dirty until an indexed find occurred on that index, at which point we would do a full (expensive) rebuild of index which will stay good until the next time they insert/update/remove.  That is controlled by adaptiveBinaryIndices: false constructor option or passing to collection.configureOptions().

**Comment by retorquere** [comment]
The datatype of the property is 'number' (more specifically, an integer).

I did convert DateTimes from strings to JS Dates, but that was for a field in the doc, not the LokiJS metadata, and I've since removed that field since with cloning on, the results from searches weren't re-inflated, so I got strings where I expected Date objects.

How do I disable adaptiveIndices for existing DBs? By calling collection.configureOptions() on the loaded collection? Or can I do this during load in the store object?

**Comment by obeliskos** [comment]
Yes you can call [configureOptions](https://rawgit.com/techfort/LokiJS/master/jsdoc/Collection.html#configureOptions) after db has loaded to switch back and forth.

That method currently only supports that one option but it might be expanded in the future to allow switching other config options.

**Comment by retorquere** [comment]
Diagnostics are going to be hard in my case, as I can't trigger it, it doesn't occur often (only two known cases in all the time I've used LokiJS), and when I do get to hear about it, there is no history. I have no idea how long I'd have to wait for nonoccurence of the problem before I could decide that disabling adaptiveBinaryIndices would have any effect.

A 10 minute test with logging will easily produce several megabytes of logging; the host application also generates debug logging, so I can't easily whittle this down. To have logging running by default would consume a *lot* of memory (the host application collects the log in RAM) and disk space (where I'd have to accumulate the logs) over the course of even just a week, so I really can't just enable this for everyone in the hopes of catching the problem as it happens.

**Comment by obeliskos** [comment]
Right, and disabling adaptive binary indices may just hide the problem since we forcibly rebuild the index all the time but it the performance is adequate, it might calm things down your main branch to use while you test out diagnostic builds possibly on others (or behind options/flags).

So one thought is that we enable loki changes api along with timer (in your code)... we might set the timer to 1 minute and do full index validation and if it is valid we clear changes and wait for next timer.  Only if it is invalid might we save the changes to a file for subsequent diagnosis.  That would definitely run slower but for a diagnostic build that could be expected.

**Comment by retorquere** [comment]
The typical DB won't be so big to make this a problem I'd guess. 30k items is considered very big, 500k is actively recommended against for the host application with or without my plugin, and most people will have only about 1k-5k docs in their DB.

Diagnostic builds can be as slow as they need to be; the multi-megabyte logs certainly slow things down quite a bit. But the problem is people only notice the problem when the corruption has already happened on a non-diagnostic build. I'm OK with putting out production builds that do background index validation (I have existing infrastructure to trigger activity when the host app is idle), but that would get us the state of things soon after it happened, but not the lead-up.

**Comment by retorquere** [comment]
(also, detect-and-fix is sufficient workaround for my use-case as the problem will most likely manifest itself to the user during startup. If I can detect-and-fix during startup, I'm likely good to go from a pragmatic perspective).

**Comment by retorquere** [comment]
Oh yeah this is perhaps relevant -- I haven't seen complaints that point to this problem during runtime of the app, just in the access I do *directly* after loading the DB. This could well be however because users have gotten into the habit of restarting when they experience problems, and the index corruption would prevent successful startup, forcing them to seek support.

**Comment by obeliskos** [comment]
I might very well be to initial and/or final load/save.

So the life of your plugin / session is (roughly) the same as the life of the browser instance?  This is an add in that loads with browser and is shutdown with browser?  What about multiple browser instances running separate copies, saving to the same database?  That might cause problems if two loki instances are competing with the same database.  I would assume multiple tabs within the same browser would use the same loki instance but multiple browsers would run multiple loki instances?

I have been working to get [typescript definitions updated](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23752) with 1.5.3 changes and that looks like it should be done soon, so I can go ahead and ask for a publish of 1.5.3.

**Comment by retorquere** [comment]
The lifetime of my plugin is the same as the run time of the Zotero instance. Zotero uses firefox as a base but isn't really a browser, and only one can be running at any time. Even when it still lived entirely in FF, Zotero and my plugin run in what's known as Firefox "chrome mode" javascript (not to be confused with running in the Chrome browser) which means it runs in the global browser scope, not any page scope, wholly separate from what tabs may or may not be doing.

The lokijs database in question is also loaded from and saved to sqlite transactionally, so I currently see no route where the save could corrupt the index -- the collection goes to disk, indexes and all, or it doesn't. Even if there *were* multiple copies of Zotero running, Zotero locks the sqlite database on startup, so it's not even possible to change the DB from the command line while Zotero is running.

**Comment by obeliskos** [comment]
Oh, good... one less thing to worry about.   So having settled that, if multiple instances of loki pointing to -different- database names should be perfectly acceptable.  I wonder if it might be useful to set up a 'metadata' / diagnostic database where we might store lightweight summary information.  On shutdown we might store some kind of record of shutdown and possibly all collection counts at the time of shutdown, and possibly index lengths.  We could do the same on startup.  I am just thinking about how we might start adding structured diagnostic info to maintain control over diagnostics.  Let me know if that would add additional complexities as i am not sure how that meta db could be submitted to you for diagnostics.

**Comment by retorquere** [comment]
I'd love to see that. I already have a facility to deliver debug data to me, adding a new section to the submission package is trivial.

**Comment by obeliskos** [comment]
Looks like @techfort has already published 1.5.3. Feel free to go ahead and try it out :smile:

**Comment by retorquere** [comment]
Alright, I've put out a new release with 1.5.3.

**Comment by retorquere** [comment]
I have a user that has this error:

```
this.data[biv[1]] is undefined
["../node_modules/lokijs/src/lokijs.js"]/</</Collection.prototype.checkIndex
["../node_modules/lokijs/src/lokijs.js"]/</</Collection.prototype.checkAllIndexes
```

I'm getting around this uwing the following for now:

```
try {
      coll.checkAllIndexes({ repair: true })
    } catch (err) {
      coll.ensureAllIndexes(true)
    }
```

I have the DB that triggers it, but as before, not the lead-up.

**Comment by obeliskos** [comment]
There may have been only one document / one index value in the array and I think I wasn't handling that correctly.  I have checked in a fix to that.

So you have a copy of the database which contains this corruption?  If so, you might loading into [LokiSandbox](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm) and then run the autocreated script which dumps contents to log and inspector.  Browse the database with the object inspector and see if you can find anything out of the ordinary.  You can also modify the script to query against or run the checkIndex methods to recreate the error and hopefully narrow down the collection containing the index which is invalid.  So long as you don't redefine the 'db' object it will continue to exist across script runs.

**Comment by retorquere** [comment]
I do have a copy of the database, and the collection that triggered the error does indeed have one record.

**Comment by obeliskos** [comment]
Ok well a collection with one record will always throw an exception when calling checkIndex so your checkAllIndexes will throw exception if any one of the indexes has only one value (this should be fixed in the next release with the above commit).

Until the next release, you might try iterating collections and calling checkIndex on each of them... either with a try catch or not calling at all if collection.count() < 2.

**Comment by retorquere** [comment]
This would also work correct?

```
try {
  coll.checkAllIndexes({ repair: true })
} catch (err) {
  coll.ensureAllIndexes(true)
}
```

**Comment by obeliskos** [comment]
As I mentioned if any one of the collections has one document you will be rebuilding all indexes.  It would be safe to do the above but possibly excessively time consuming.

I would do something like : 
```javascript
db.collections.forEach(functioni(coll) {
  if (coll.count !== 1) {
    coll.checkIndex({ repair: true});
  }
});
```

**Comment by retorquere** [comment]
I don't understand. My code calls `ensureAllIndexes` on the specific collection that fails -- how does that affect other collections?

**Comment by obeliskos** [comment]
Ah your right that should work... was thinking of need to check all collections but we don't have a db level method.
