### ISSUE TITLE
Is loadDatabase synchronous?

### ISSUE THREAD

**Issue by ohenepee** [techfort/LokiJS#657]
We have production-facing app that is currently using `autoloadCallback` which is asynchronous... I would prefer something synchronous which would block and load the database before moving onto the next line of code. I'm also using **Loki FS Structured Adapter**.

**Comment by obeliskos** [comment]
We don't currently have a node.js adapter which is synchronous but it should be easy to create one based on the LokiFsAdapter (except using synchronous calls).  How large is your database?

**Comment by ohenepee** [comment]
Currently heading to 1MB... I've got 2 collections... one is around 400kB... the other around 600kB.

**Comment by obeliskos** [comment]
I created a stress test and i cannot replicate any problems with our throttled save functionality but (when using an async adapter) you still need to use async patterns when loading and initializing the database before actually using the database.  Once you bootstrap the database you can use synchronous code patterns and the throttledSave functionality could potentially provide significant performance increases by removing unneccessary saves.

I also created a synchronous adapter, if you decide you prefer totally synchronous behavior.  It needs to be required/imported separatly as the 'LokiFsSyncAdapter' in the 'loki-fs-sync-adapter.js' module.

**Comment by retorquere** [comment]
This may get you going:

var FileStore = {
  mode: 'reference',

  loadDatabase: function(name, callback) {
    var data = require(`./${name}`)

    callback(data)
  }
}

var db = new loki('db.json', { adapter: FileStore })
db.loadDatabase()

**Comment by joshuaquek** [comment]
I quickly made a library that might be able to resolve this:

https://www.npmjs.com/package/lokijs-promise

**Comment by retorquere** [comment]
I don't understand the approach taken in that library. It looks like you can have only one loki DB, and getCollection is async? getCollection is after the DB is loaded; db.loadDatabase with an async adapter is the issue to solve I think.

**Comment by retorquere** [comment]
which I've done using

```
Loki.prototype.loadDatabaseAsync = function(options) {
  return new Promise((resolve, reject) => this.loadDatabase(options, err => err ? reject(err) : resolve(null)))
}

Loki.prototype.saveDatabaseAsync = function() {
  return new Promise((resolve, reject) => this.saveDatabase(err => err ? reject(err) : resolve(null)))
}

Loki.prototype.closeAsync = function() {
  return new Promise((resolve, reject) => this.close(err => err ? reject(err) : resolve(null)))
}
```

**Comment by tomkennedy22** [comment]
Adding deleteDatabase as well - 

```
Loki.prototype.deleteDatabaseAsync = function() {
      return new Promise((resolve, reject) => this.deleteDatabase(err => err ? reject(err) : resolve(null)))
    }
```

**Comment by malshoff** [comment]
> which I've done using
> 
> ```
> Loki.prototype.loadDatabaseAsync = function(options) {
>   return new Promise((resolve, reject) => this.loadDatabase(options, err => err ? reject(err) : resolve(null)))
> }
> 
> Loki.prototype.saveDatabaseAsync = function() {
>   return new Promise((resolve, reject) => this.saveDatabase(err => err ? reject(err) : resolve(null)))
> }
> 
> Loki.prototype.closeAsync = function() {
>   return new Promise((resolve, reject) => this.close(err => err ? reject(err) : resolve(null)))
> }
> ```

I'm getting the error `Property 'loadDatabaseAsync' does not exist on type 'LokiConstructor'. Did you mean 'loadDatabase'?` How do I fix that?
