### ISSUE TITLE
LokiJS sensible defaults thinks application is running in node-webkit (react + babel + webpack project)

### ISSUE THREAD

**Issue by G-Rath** [techfort/LokiJS#659]
This issue was originally about LokiJS having a call to `require('fs')`, but then I found that was actually not the issue, so I've refactored the issue. Sorry about all the confusion (and notifications)

-----

We've got a React web application being built using Webpack (with Babel 6), with the Webpack CDN plugin.

For some reason, `global.window` is set, causing LokiJS to think it's running in a node-webkit env (due to [line 829](https://github.com/techfort/LokiJS/issues/659#L829)), and thus trying to use the fs adapter. 

https://github.com/techfort/LokiJS/blob/71139c9fb8ae35a5a03a5d2fdc55678fcad9f255/src/lokijs.js#L819-L840

I've not used node-webkit, so I can't try and compare the two Window objects to try and find a consistent difference that can be used for comparison. 

I did find this [babel issue](https://github.com/babel/babel/issues/6227) however, that suggests checking if `process` is defined, which should be defined if you're using node-webkit, but not in the browser (if I'm understanding node-webkit correctly).

For now, I'm just going to specify the environment explicitly.

**Comment by G-Rath** [comment]
Ugh as soon as I posted this i went back and saw that it's actually because it's trying to use that adapter (if it wasn't, it wouldn't hit the require call, and so not have a problem).

Still, this might mean that the sensible defaults are not properly detecting the browser?

I'll come back once I've adjusted the defaults on my end :)

**Comment by G-Rath** [comment]
So LokiJS figures out what it's running in using this logic:

https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L819-L840

The problem seems to be that for some reason `global.window` is defined, making LokiJS think it's running in a node-webkit environment? 

I'm trying to figure out what defines global.window, and for possible workarounds. This project is using React, React-DOM, React-Redux, Webpack and Babel, so there are some major players it could be coming from.

**Comment by obeliskos** [comment]
Your suggestion make sense so I have updated environment detection as recommended.  Eventually this will make it into a 1.5.4 release but probably not too soon.  Until then it is on main branch.

Thanks!
