### ISSUE TITLE
Collection.prototype.get('1') fails

### ISSUE THREAD

**Issue by plievone** [techfort/LokiJS#66]
If one accidentally tries to get using string id it does not throw but fails to find the document. This is due to `isNaN` returning false for string id so it is not cast to number, but later strict equality `===` causes id not to be found.

**Comment by techfort** [comment]
Good catch! Will fix this asap.

**Comment by techfort** [comment]
Hi, I applied a quick fix to this, but I was only able to do very superficial tests due to lack of time, would you be able to check the latest source out and see if this works for you?

**Comment by plievone** [comment]
Looks good to me!  (isNaN won't catch non-integer numeric inputs such as Infinity, -1 or decimals, but that's ok, that string id is the most common case and it failed silently before.)
