### ISSUE TITLE
"Trying to update a document not in collection"

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#660]
I have a database I try to update that gives me "Trying to update a document not in collection", but I'm getting the objects out of the DB right before I update them:

```
var loki = require('lokijs')

var FileStore = {
  mode: 'reference',

  loadDatabase: function(name, callback) {
    callback(require('./db.json'))
  }
}

var db = new loki('db.json', { adapter: FileStore })
db.loadDatabase()

console.log(db.collections.map(coll => coll.name))

function probe(name) {
  var coll = db.getCollection(name)
  console.log(`${name}: ${coll.data.length} records`)

  for (const ae of coll.find()) {
    if (ae.updated) {
      delete ae.updated;
      coll.update(ae);
    }
  }
}

probe('autoexport')
```

outputs:

```
[ 'citekey', 'autoexport' ]
autoexport: 3 records
/home/emile/github/better-bibtex/node_modules/lokijs/src/lokijs.js:5743
        throw (err); // re-throw error so user does not think it succeeded
        ^

Error: Trying to update a document not in collection.
    at Collection.update (/home/emile/github/better-bibtex/node_modules/lokijs/src/lokijs.js:5691:17)
    at probe (/home/emile/github/better-bibtex/db.js:23:12)
    at Object.<anonymous> (/home/emile/github/better-bibtex/db.js:28:1)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
```

**Comment by retorquere** [comment]
Changing the script to this resolves the problem, but I'd rather not handle it in the loader:

```
var loki = require('lokijs')

var FileStore = {
  mode: 'reference',

  loadDatabase: function(name, callback) {
    var data = require('./db.json')

    var ae = data.collections.find(coll => coll.name === 'autoexport')
    if (ae) {
      for (const elt of ae.data) {
        delete elt.updated
      }
    }

    callback(data)
  }
}

var db = new loki('db.json', { adapter: FileStore })
db.loadDatabase()

console.log(db.collections.map(coll => coll.name))

function probe(name) {
  var coll = db.getCollection(name)
  console.log(`${name}: ${coll.data.length} records`)

  for (const ae of coll.find()) {
    if (ae.updated) {
      delete ae.updated;
      coll.update(ae);
    }
  }
}

probe('autoexport')
```

**Comment by retorquere** [comment]
This also fixes it in the MWE, but I think this may leave the indexes b0rked:

```
var loki = require('lokijs')

var FileStore = {
  mode: 'reference',

  loadDatabase: function(name, callback) {
    var data = require('./db.json')

    callback(data)
  }
}

var db = new loki('db.json', { adapter: FileStore })
db.loadDatabase()

console.log(db.collections.map(coll => coll.name))

function probe(name) {
  var coll = db.getCollection(name)
  for (const ae of coll.data) {
    delete ae.updated
  }

  console.log(`${name}: ${coll.data.length} records`)

  for (const ae of coll.find()) {
    if (ae.updated) {
      delete ae.updated;
      coll.update(ae);
    }
  }
}

probe('autoexport')
// probe('citekey')
```

**Comment by obeliskos** [comment]
Are you able to create a loki sandbox gist demonstrating a problem?  As long as your updated object has a valid $loki property matching an object in the collection, the update should work.  That code path should be well tested and unit tested. 

You might try (before calling update on the object), doing a console.log on ae.$loki and coll.get(ae.$loki) to make sure both resolve to valid number and object.

**Comment by retorquere** [comment]
Wait, I think I have it: https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/anonymous/772e5647c6a4dfd2f43e326e2479a028/raw/b30f3dc477b0cd50dbedfc4ac46bec50b2ded47d/db.js

**Comment by obeliskos** [comment]
Thank you... important lines from your gist would seem to be : 
line 31 : that one of the documents is missing its $loki property 
line 59 : which shows that the collection 'idIndex'  has one value that is null... this is causing the error   
line 150 : which shows that the maxId issued by the collection is 13

So you would need data surgery to fix that since I doubt you can call remove() on a document not in the collection.  The idIndex is not using the same binary index logic as the binary indices since documents will always be ordered in the data array according to their collection issued $loki id which will be coll.maxId+1.

Detection of this can be done by iterating all documents returned by find() and seeing if they have a $loki property.  Did you generate this data yourself or did it come in from the wild?

**Comment by retorquere** [comment]
This comes from the wild. I have no idea how it got into this state. This collection like the others is saved transactionally using sqlite so I'm fairly sure it's not save-time corruption. I've gone over my sources and I really can't find any place where I mess with the data array directly. Object cloning has been on for a while now, so that should exclude direct manipulation.

**Comment by obeliskos** [comment]
So it looks like the last 2 docs are supposed by the same (1 doc that got split into 2)? Did you add the 'updated' property or could that have come from the meta of the second doc with id of 2? The only other differences are the 'exportNotes' and 'useJournalAbbreviation'... perhaps the code path that sets those might be causing?

**Comment by retorquere** [comment]
The "updated" property was added by me in the past, I don't add it anymore. The objects in that collection are changed in one of two ways:

If a user adds a new doc, any existing doc with the same "path" is removed first ("path" is unique in the collection),

If a one of the objects in another (sqlite) database described by "type"/"id" changes, I just update this document (so fetch-update).

Can I safely remove the $loki-less documents and reindex the collection? Or must the $loki ids be consecutive?

**Comment by retorquere** [comment]
Doesn't look like it. Doing this doesn't make the error go away:

```
  var coll = db.getCollection(name)

  coll.data = coll.data.filter(doc => typeof doc.$loki !== 'undefined')
  coll.ensureAllIndexes(true)

  console.log(`${name}: ${coll.data.length} records`)

  for (const ae of coll.find()) {
    console.log(ae.$loki)
    console.log(coll.get(ae.$loki))
    if (ae.updated) {
      delete ae.updated;
      coll.update(ae);
    }
  }
```

**Comment by retorquere** [comment]
This repairs the error for me:

```
  coll.data = coll.data.filter(doc => typeof doc.$loki === 'number' && typeof doc.meta === 'object')
  coll.ensureId();
  coll.ensureAllIndexes(true);
```

**Comment by retorquere** [comment]
Still no idea how the problem document showed up, but I think it's likely that it's an old database from the pre-cloneObjects days.

**Comment by 1nstinct** [comment]
Your get by id function has a bug. It can't find the existed document and returns null
![image](https://user-images.githubusercontent.com/1754655/164872898-77a47a2b-97a7-4c2f-afd3-dd00aab4b9bb.png)
![image](https://user-images.githubusercontent.com/1754655/164872965-878c4b87-cc2d-4d58-b831-e026b4a89841.png)
