### ISSUE TITLE
Custom Operators

### ISSUE THREAD

**Issue by gadgetman2016** [techfort/LokiJS#662]
Can custom query operators be added like the following:

Loki.addOperator('$_custom', (a,b) => {
    return fib(a) > b;
});

var results = coll.find({
  '$and': [{ 
      'age' : {  '$gt': 30 }
    },{
      'age' : { '$_custom': 50 }
    }]
});

**Comment by obeliskos** [comment]
That type of custom operator would be similar to a where() filter function...  its logic would not be able to be persisted into the database so every time you reload the database you would have to re-register your custom operator.

What we have now are where() functions/chain ops and transforms.  

So you might use chained query using a where chained operation such as : 

```javascript
function $fib50(obj) {
  return fib(obj) > 50;
}

function $fibDynamic(value) {
  return function(obj) {
    return fib(obj) > value;
  }();
}

var results = coll.chain().find({ age: { $gt: 30 } }).where($fib50).data();
// -- or --
results = coll.chain().find({ age: { $gt: 30 } }).where($fibDynamic(50)).data();

```

We also might be able to easily add an optional 'data' parameter to the where() chain op which could be passed to your filter function.... but as of now you would need to use a factory-like function similar to $fibDynamic above if you wanted to parameterize the op.

That can even be persisted into the database using -parameterized- collection transforms... although when you actually invoke the transform you will need to pass your filter function.

So in the above example (using $fibDynamic) you could use parameterized transform such as : 
```javascript
coll.addTransform("age30fib",  = [
  {
    type: 'find',
    value: { $age: { $gt: 30 } }
  },
  {
    type: 'where',
    value: '[%lktxp]FibFilter'
  }
]);

var results = coll.chain("age30fib", { FibFilter : $fib(50) }).data();
// -- or --
results = coll.chain().transform("age30fib", { FibFilter: $fib(50) }).data();
```

The advantage of the above is that you can save the transform to the database and invoke it on your collection by name, passing in your function(s).  If you were to try to use that within a dynamic view however you would need to rebuild/reattach the transform after every load.

**Comment by gadgetman2016** [comment]
The reason why I asked was because I wrote a custom pegjs grammar that transforms a simple query language into the syntax used by the find function. I needed to add 2 custom operators in order for it to work with my project.

**Comment by obeliskos** [comment]
We do export LokiOps so I suppose  you could attach your own ops to that if you want... if you persist your database with any of those queries embedded in a transform or dynamic view you will need to reattach them on every program initialization.

```javascript
loki.LokiOps.$_custom = (a,b) => {
  return fib(a) > b;
});
```

**Comment by gadgetman2016** [comment]
Using the export is sufficient.
