### ISSUE TITLE
The loadDatabase function doesn't throw an error when trying to load a non-existant file

### ISSUE THREAD

**Issue by metaa** [techfort/LokiJS#664]
See title.

So yeah, I'm trying to make some code fool-proof. The docs say, that `loadDatabase` throws an error when trying to load from an empy file, but instead on my side it just loads an empty database.

I'm on NodeJS v9.

I tried using autoloading:
```js
const Loki = require('lokijs')
	, loadHandler = _ => {
		console.log(db.toJson())
	},
	db = new Loki('random.json', {
		autoload: true,
		autoloadCallback: loadHandler,
		serializationMethod: 'pretty'
	})
```
... which gives me a perfectly fine empty database:
```json
{
  "filename": "random.json",
  "collections": [],
  "databaseVersion": 1.5,
  "engineVersion": 1.5,
  "autosave": false,
  "autosaveInterval": 5000,
  "autosaveHandle": null,
  "throttledSaves": true,
  "options": {
    "autoload": true,
    "serializationMethod": "pretty",
    "destructureDelimiter": "$<\n",
    "recursiveWait": true,
    "recursiveWaitLimit": false,
    "recursiveWaitLimitDuration": 2000,
    "started": 1522606652341
  },
  "persistenceMethod": "fs",
  "persistenceAdapter": null,
  "verbose": false,
  "events": {
    "init": [
      null
    ],
    "loaded": [],
    "flushChanges": [],
    "close": [],
    "changes": [],
    "warning": []
  },
  "ENV": "NODEJS"
}
```

... and also manual loading:
```js
const Loki = require('lokijs')
	, db = new Loki('random.json')

db.loadDatabase({}, err => {
	if(err) throw err
	console.log('ok')
})
```
... which just prints "ok".

In both cases for some reason it doesn't throw errors 🤔

Am I missing something?

**Comment by obeliskos** [comment]
No, you aren't missing anything...  

We went that route a while back for autoload/autosave purposes... so that you could set up your autoload callback to initialize the database on first load with collections, dynamic views, transforms, data, etc.  You could always register an autoloadCallback to the constructor and check : 
```javascript
var db = new loki('test.db', {
  autoload: true,
  autoloadCallback: dbInitialize
});
function dbInitialize() {
  if (db.listCollections().length === 0) {
    throw new ('database does not exist');
  }
}
```

We could also start adding options to persistence adapters to allow you to specify whether an exception should be raised when the file does not exist but it has not been much of any issue.

**Comment by metaa** [comment]
Hmmm, I figured I could do that, but still the docs say it would raise an exception 😦
I guess I'll just check for the collection array's size then.

Thanks for letting me know!

**Comment by obeliskos** [comment]
I will close this but mention that if you want to write your own persistence adapter that throws an exception when loading non-existent database, it should be pretty easy.
