### ISSUE TITLE
Bug in average calculation

### ISSUE THREAD

**Issue by thirstyfish** [techfort/LokiJS#665]
The extractNumerical function and hence the average calculation logic uses Number() to filter the resultset on numerical values. 

```
Collection.prototype.extractNumerical = function (field) {
      return this.extract(field).map(parseBase10).filter(Number).filter(function (n) {
        return !(isNaN(n));
      });
};
```

The problem is that 0 values are excluded from the resultset this way.
Using isFinite instead of Number would alleviate this problem:

```
Collection.prototype.extractNumerical = function (field) {
      return this.extract(field).map(parseBase10).filter(isFinite).filter(function (n) {
        return !(isNaN(n));
      });
};
```

**Comment by obeliskos** [comment]
Good catch, yes that sounds like a good fix.  I am thinking we probably should have at least a simple unit test which covers all the statistical methods (like those which depend on extractNumerical).  

Feel free to submit a p.r. or I will add this to eventually look into fixing with coverage.
