### ISSUE TITLE
Object meta is not saved to storage after update.

### ISSUE THREAD

**Issue by ypanshin** [techfort/LokiJS#666]
I used 1.4.1 version of LokiJS, when I updated the version to 1.5.3 my code stopped to work.
In my code, I use "meta.updated" parameter to check when the object was updated.
The parameter was updated correctly in version 1.4.1, however, in the version 1.5.3, the parameter updated by the method "function updateMeta(obj)" however, not saved to storage.
All objects that have been updated, those do not have properties "updated" and "revision".

**Comment by ypanshin** [comment]
The issue in the code of Collection.update method. In the version 1.4.1 you have:
```
Collection.prototype.update = function (doc) {

       ...

        // operate the update
        this.data[position] = doc;

       ...

        this.emit('update', doc);

       ...
    };
```
In the version 1.5.3 you have:
```
  Collection.prototype.update = function (doc) {
     ...

        // if configured to clone, do so now... otherwise just use same obj reference
        newInternal = this.cloneObjects || !this.disableDeltaChangesApi ? clone(doc, this.cloneMethod) : doc;

       ...

        // operate the update
        this.data[position] = newInternal;
 
        ...

        this.emit('update', doc, this.cloneObjects || !this.disableDeltaChangesApi ? clone(oldInternal, this.cloneMethod) : null);
       
       ...
    };
```
In the previous version you did not lose the object reference, so all changes on the object were saved. However in the latest version, the object in storage is a clone, so all changes on original arent saved.

**Comment by obeliskos** [comment]
This bug fix request 666 was made on Friday the 13th 😈 

The way we applied metadata previously was done via listening to the same events we emit to users.  I have extracted meta and changes logic from events so that I can pass internal references while emitting clones to users if cloning is enabled.

I believe I have fixed and added coverage for relevant scenarios... feel free to try out master and see if that works for you.  If you run into any issues, also provide which collection options are set for 'clone', 'disableChangesApi', and 'disableDeltaChangesApi'.

Thanks @Viatorus for always cheering on when bugs are found 😉

**Comment by Viatorus** [comment]
@obeliskos 
Well, maybe this is not the correct reaction - Github should add all available emoji reaction ever made. :joy: 
My intention was more: Thank you for using this software and for writing the issue.

Nevertheless, thank you for fixing this issue! I will port this to LokiDB as soon as possible.

BTW:
Did you checked your emails at  _admin [at] obeliskos (dot) com_?

**Comment by ypanshin** [comment]
@obeliskos Yeah, it works fine :) Thanks.

**Comment by obeliskos** [comment]
Thanks guys, after fixing a typo that @Viatorus pointed out I think this bug fix is complete.  It should eventually make it into a future 1.5.4 release.

@Viatorus, hah I was kidding but yea we need more emojis ✅

**Comment by mrb1090** [comment]
I'm having this very same problem today (04/20) after upgrading to 1.5.3.  Meta data not being saved after updating a document.  Has this been fixed?  If so, what is the incremental version with the fix?

Thanks,

Mike B.
