### ISSUE TITLE
lokijs.org >> This site can’t be reached lokijs.org refused to connect.

### ISSUE THREAD

**Issue by omnsium** [techfort/LokiJS#668]
lokijs.org website not reachable, am I missing some update?

This site can’t be reached
lokijs.org refused to connect.
Search Google for lokijs org
ERR_CONNECTION_REFUSED

**Comment by obeliskos** [comment]
@techfort has your domain been obsoleted or just need to fix?

**Comment by techfort** [comment]
hey @omnsium and @obeliskos - lokijs.org is hosted on digital ocean, the droplet is fine, the website is being served, the domain is active, the nameservers are correctly configured. I have no idea what is going on but i will try to get to the bottom of it, i'll start with an instance reboot.

**Comment by omnsium** [comment]
@techfort thanks. That's helpful.
