### ISSUE TITLE
I can't get started from tutorial

### ISSUE THREAD

**Issue by Smolations** [techfort/LokiJS#669]
I really must be doing something wrong. I have the latest version (1.5.3) and there seem to be some file system issues, but i can't figure it out.
```javascript
// test.js
const Loki = require('lokijs');
const LokiFsStructuredAdapter = require('lokijs/src/loki-fs-structured-adapter.js');

const adapter = new LokiFsStructuredAdapter();
const db = new Loki('sandbox.db', {
  adapter : adapter,
  autoload: true,
  autoloadCallback : databaseInitialize,
  autosave: true,
  autosaveInterval: 5 * 1000
});

function databaseInitialize() {
  let log = db.getCollection("log");

  if (log === null) {
    log = db.addCollection("log");
  }

  // log some random event data as part of our example
  log.insert({ event: 'dbinit', dt: (new Date()).getTime() });
}
```

And when I run node (8.10.0) I get an error:
```
$ node test.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'sandbox.db.0'
```

**Comment by obeliskos** [comment]
Your example works for me, maybe you interrupted the save last time by killing process after it created sandbox.db but before it could save sandbox.db.0?  If deleted any saved database files and rerunning fixes the problem, you may want to intercept SIGKILL : 

https://github.com/techfort/LokiJS/blob/cc49b614c52e4c171ca450fcc46cbaa21cd8f9cc/examples/quickstart3.js#L20-L26

Also (In case it is relevant) the LokiFsStructured adapter used a partitioned output format which is different that the LokiFsAdapter which stores everything in one file.  You would not be able to load a database saved with one of those adapters the another.

**Comment by Smolations** [comment]
Ahh for some reason the db file wasn't showing up in my sublime text sidebar. Listing all files from terminal revealed the file and that solved the problem. Thanks for the additional tip, too!
