### ISSUE TITLE
Error with findOne special caractere "²"

### ISSUE THREAD

**Issue by gkotnik** [techfort/LokiJS#671]
Hello,

I have a problem with me project i use LokiJs and it might be a bug.
it seem lokiJS under IE11 have a problem to find attribute containing special character like '²'.
every other item in the database work but those with those seem to return null every time (yet it work well on chrome and firefox).

Anyone encounter the same problem ? is it a known bug or a mistake on my end?

**Comment by obeliskos** [comment]
I can't recreate this error using our [LokiSandbox](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm) in IE11.  (Oddly though the following code block doesn't render preview correctly in github markdown editor on edge on 1803).

For example, this works : 

```javascript
var db = new loki('sandbox.db');
var items = db.addCollection('items');

items.insert({ name : 'mjolnir', owner: 'thor', maker: 'dwarves' });
items.insert({ name : 'gungnir', owner: 'odin', maker: 'elves' });
items.insert({ name : 'draupnir', owner: 'odin', maker: 'elves²' });

var result = items.find({ 'maker': 'elves²' });
logObject(result);
```

Can you use [LokiSandbox](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm) to find a repro case and post it here ?

**Comment by gkotnik** [comment]
after some test it appear that the error wasn't related to LokiJS but rather a strange IE choice regarding value return from 'select' which make the value different from the one registered by lokiJS.
Sorry for the false issue.
