### ISSUE TITLE
Find record where a property startsWith a given value

### ISSUE THREAD

**Issue by Elisabetta-Ramilli** [techfort/LokiJS#673]
Hello,
I have to do a find query that returns records where a certain property starts with a given value.  Here's an example of what I have to do:

_var record = collection.find({ 
                {'id': {'$startsWith': '123'}}
            })_

Is there something like "$startsWith" in Loki.js that allows me to find records where 'id' starts with the given value '123'? I know the existence of $contains operator but in my case the property must start with the given value and not only contain it.

Thanks in advance for you advice.
Best regards

**Comment by Viatorus** [comment]
You could use a custom filter function with `coll.where(function (a){
return a.startsWith(...);})`.

If it is a string value and not a numerical value, LokiDB's full-text
search has the query startsWith.

>

**Comment by obeliskos** [comment]
$regex should also work … ([Examples here](https://github.com/techfort/LokiJS/wiki/Query-Examples)).

$between: ['123', '124'] might work and it can leverage binary indices if you have defined them.

If your query is performance sensistive, I would use $between to constrain results and if needed do $regex or where() filter (as suggested above) to linear scan only those contrained results (faster).

As @Viatorus mentioned he has done alot of work on fts search for [LokiDB](https://github.com/LokiJS-Forge/LokiDB) if you start needing even more fine grained text searching :)
