### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by gimox** [techfort/LokiJS#674]
I know this is a old problem with a response.. .add fs as empty in webpack config.
Ok! but what about if you can't do this like angular cli project (i don't wan't do a angular eject).
So i run my project in a browser and "fs" module is not require. 

My proposal is to make this line safe `this.fs = require('fs');`

**Comment by obeliskos** [comment]
Is this a runtime error or a error such as during scaffolding?  If error occurs at runtime, what persistence adapter do you expect to use (or do you not need to persist database)?

**Comment by gimox** [comment]
it's  during scaffolding, i'm using indexdDB and it working great. So this fix generate a warning but now it  can serve and build with angular cli.

**Comment by obeliskos** [comment]
ok, i think if we had to do it again we would have extracted -all- persistence adapters out into their own modules.

wait, we are doing it all again with LokiDB, and we did :)

**Comment by obeliskos** [comment]
Thanks for pr!

**Comment by gimox** [comment]
👍👍

**Comment by gdpelican** [comment]
Version bump please? :D

**Comment by obeliskos** [comment]
I will work on updating the changelog and ask @techfort to update maybe around the weekend.

If anyone finds any issues before then, post them so we can fix before version bump.
