### ISSUE TITLE
Unnecessary dependencies?

### ISSUE THREAD

**Issue by plievone** [techfort/LokiJS#68]
Gordian, Istanbul and Mocha are already listed in devDependencies, so they could be removed from ordinary dependencies? Now those dependencies bring in 10MB extra to ordinary install...

**Comment by techfort** [comment]
Good point. The point of devDependencies is that those dependencies are necessary to develop a library, but they are not necessary to run.
LokiJS itself does not depend on anything to run, so there should be nothing in dependencies, while it depends on a few libs for running tests in case you want to develop new features which you need to create tests for. So I suppose "dependencies" could just be empty as we even provide a minified build, so not even gulp is needed. Does this sound right?

**Comment by plievone** [comment]
That sounds right. One can always install devDependencies via npm install on the package root.

At the same time, one could consider adding docs/lokijs.odp and docs/lokijs.pptx to .npmignore, perhaps benchmarks too? Many npm packages keep their install small and clean and let people clone the rest from github repo if needed?

**Comment by techfort** [comment]
That's also a good point. I will clean address those asap.

**Comment by techfort** [comment]
This is done, including the .npmignore
