### ISSUE TITLE
Question - synchronization with server using ChangesApi

### ISSUE THREAD

**Issue by ramasa** [techfort/LokiJS#680]
Using angular 6, lokijs:^1.5.4, @types/lokijs:^1.5.2
Trying to implement two way sync between lokijs and server using changesApi.

How do I prevent changes done to collection as part of handling updates from server ending up again in db.serializeChanges().

1. device1 - db.serializeChanges() , push to server , db.clearChanges() 
2. server - send device1 changes to all devices except device1
3. device2 - pull changes from server, update lokijs collection without the change ending up in serializeChanges()

I tried to setChangesApi(false) in the sync code , but it disables changesApi globally.

**Comment by Viatorus** [comment]
Did you try setting the member variable `disableChangesApi` to true/false
manual?

Maybe this is not fully supported.

>

**Comment by obeliskos** [comment]
I think @Viatorus suggestion will work : 
https://github.com/techfort/LokiJS/blob/cbd8294b9dd5ea855e2f36a99b2ea56977fe685f/src/lokijs.js#L5604-L5611

So you might set : 
```javascript
coll.disableChangesApi = true;
// apply changes from server...
coll.disableChangesApi = false;
```

In the future we should probably add support for that option in our collection.configureOptions() method.
