### ISSUE TITLE
Question - How can I use Vue v-model with collection autoupdate?

### ISSUE THREAD

**Issue by braivre** [techfort/LokiJS#682]
```html
<template>
    <input v-model="note.title" />
</template>
```
```javascript
export default {
    data() {
        return {
            note: {
                title: ''
            } 
        }
    },
    created() {
        let notes_collection = this.$db.getCollection('notes')
        this.note = notes_collection.insert({title: 'New Note'})
    }
}
```
The note title isn't updated when I type in the input. Is this a expected behavior?
I set the autoupdate prop in the collection:
```javascript
function databaseInitialize() {
    let notes = db.getCollection("notes")
    if (notes === null) {
        db.addCollection("notes", {
            autoupdate: true
        })
        notes = db.getCollection('notes')
    }
    notes.on('insert', (value) => {
        value.id = value.$loki
    })
}
```

P.D. Amazing database

**Comment by obeliskos** [comment]
Autoupdate feature is/was based on object.observe and is deprecated in most environments.  For LokiJS we will / should likely remove that feature. See #655, #455 

LokiDB is considering adding a similar feature using proxy, feel free to [chime in over there](https://github.com/LokiJS-Forge/LokiDB/issues/110) if this is of interest to you.
