### ISSUE TITLE
Query by timestamp and upgrade path

### ISSUE THREAD

**Issue by ShiroiKuma** [techfort/LokiJS#683]
I'm starting a new cross-platform project and looking for a JSON DocumentStore, is LokiJS supported on Node 10.x officially?

Is it possible to provide examples on how to query for items in a collection that are older than x days/hours etc? i.e. I'm looking to auto-purge old data

And what would the upgrade path from LokiJS to LokiDB look like in the future? Would it require a complete rewrite of my application or just a few changes?

**Comment by obeliskos** [comment]
Support for Node 10.x? Of course.  

We do have one feature 'autoupdate' which is deprecated though, we should probably go ahead and remove that.  It is not enabled by default so don't turn on that option in collection constructor and expect it to work.

We have TTL functionality which should be able to do what you are requesting, automatically.  You can either look into the 'ttl' and 'ttlInterval' options on the [Collection constructor](https://rawgit.com/techfort/LokiJS/master/jsdoc/Collection.html) or you could manually search and remove based on our built-in 'meta' object properties, such as : 
```javascript
var dt = new Date("1/1/2018").getTime();
coll.findAndRemove({ "meta.created": { $lte: dt });
//or
coll.findAndRemove({ "meta.updated": { $lte: dt });
```

Upgrade from LokiJS to LokiDB is being [worked on right now](https://github.com/LokiJS-Forge/LokiDB/issues/53) ... feel free to chime in over there.

**Comment by ShiroiKuma** [comment]
Thanks ever so much for the clear and concise answers. I don't believe I will need the autoupdate feature myself so I should be safe.

Keep up the good work, and really appreciate the online sandbox for testing.
