### ISSUE TITLE
Feature - ContainsAll filter

### ISSUE THREAD

**Issue by grmpfhmbl** [techfort/LokiJS#686]
I added a $containsAll filter to determine if an array/string contains all of the searched items in an array. Works exactly like $containsAny just wants to match all of the items. If you want to include the feature, I'd create a PR. All changes are in this branch https://github.com/grmpfhmbl/LokiJS/tree/feature-containsAll. I wrote documentation and a test and hopefully did not forget anything.

**Comment by Viatorus** [comment]
Well... there is a $contains filter which does exactly the same.
The wording can be sometimes confusing, sorry.

**Comment by grmpfhmbl** [comment]
Damn... I put the exact same code above $contains. I was kinda blind there. Sorry :-( May I ask, if you could extent / correct the documentation of $contains. At this time it's not mentioned that you can also provide an array. Especially the "Use this..." sentence is very misleading. Suggestion:

- - - -

**$contains** - filter for document(s) with property containing the provided value. ( [commit](https://github.com/techfort/LokiJS/pull/120/commits/1f08433203554ccf00b381cbea4e72e25e62d5da), [#205](https://github.com/techfort/LokiJS/issues/205) ).  ~~Use this when your property contains an array but your compare value is not an array.~~ Use this when you property contains an array, object, or string and your search value is either a single value, or an array containing values. Result will be the document whose property contains _all_ of the search array values.

>When typeof property is : 
>- string: it will do a substring match for your string (indexOf) (see `results1` below) or all of the provided strings (see `results2`)
>- array:  it will check for 'value' existence in that array (indexOf) or all of the 'values' in the provided array. (see `results3`, `results4`, and `results5`)
>- object: it will check to see if your 'value' is a defined property of that object (see `results6`)

```javascript
users.insert({ name : 'odin', weapons : ['gungnir', 'draupnir'], relationship: {wife: 'Frigg'}});
users.insert({ name : 'thor', weapons : ['mjolnir'], relationship: {wife: 'Sif', lover: 'Járnsaxa'}});
users.insert({ name : 'svafrlami', weapons : ['tyrfing', 'draupnir'], relationship: {}});
users.insert({ name : 'arngrim', weapons : ['tyrfing'], relationship: {}});
users.insert({ name : 'thordin', weapons : ['gungnir', 'draupnir', 'mjolnir']});

// returns 'thordin' and 'thor' documents
var results1 = users.find({ 'name' : { '$contains' : 'tho' } });

// returns 'thordin' document
var results2 = users.find({ 'name' : { '$contains' : ['tho', 'din'] } });

// returns 'svafrlami' and 'arngrim' documents
// both are logically equivalent, the first one probably faster 
var results3 = users.find({ 'weapons' : { '$contains' : 'tyrfing' } });
var results4 = users.find({ 'weapons' : { '$contains' : ['tyrfing'] } });

// returns 'svafrlami' document
var results5 = users.find({ 'weapons' : { '$contains' : ['tyrfing', 'draupnir'] } });


// return 'thor' and 'thordin' document.
// IMPORTANT: if the property does not exist, the document will be returned - see Thordin result. Bug?
var results6 = users.find({ 'relationship' : { '$contains' : ['wife', 'lover'] } });
```
