### ISSUE TITLE
Question - Where can I find Staging API documentation?

### ISSUE THREAD

**Issue by michael-felden** [techfort/LokiJS#687]
Staging API is mentioned several times in the collection API.
In my current project I'd like to build a sync service between Loki and MySQL.
So I guess staging could help me with that.

**Comment by obeliskos** [comment]
I believe that falls under 'ChangesAPI' which has high level info in our [ChangesAPI wiki page](https://github.com/techfort/LokiJS/wiki/Changes-API).

If you need more info, you might examine the unit tests which @techfort wrote : 
https://github.com/techfort/LokiJS/blob/master/spec/generic/changesApi.spec.js
https://github.com/techfort/LokiJS/blob/master/spec/generic/stage.spec.js

If after reading those, if you run into any specific questions feel free to ask specific questions you think should be in our documentation.

**Comment by michael-felden** [comment]
thanks for the quick answer

stage(stageName, obj))
getStage(name)

Naming the function arguments would improve the documentation

**Comment by Viatorus** [comment]
@michael-felden Thank you. I will track the naming issue for LokiDB.
