### ISSUE TITLE
LokiJS and Google Sheets?

### ISSUE THREAD

**Issue by gerfnitauthor** [techfort/LokiJS#689]
Could a Google Sheet be the persistent storage for a LokiJS database? How difficult would it be to develop load and save extensions? Would the entire database need to be written when closed, or could only updated records/rows be modified in the Sheet?

**Comment by obeliskos** [comment]
Loki persistence can be adapted to save to any store which can store raw strings in its 'basic' adapter modes.  Add to that partitioning and you can save each collection independently (to separate files) only if they are 'dirty' (pending changes needing to be saved).

Using the [Partitioning Adapter](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#lokipartitioningadapter) along with custom adapter you would write, if you only add 1 record to a database containing 10 collections, then we will save the 1 entire collection only.

To get more granular, you would need to employ our [Changes API](https://github.com/techfort/LokiJS/wiki/Changes-API) to create 'differential changesets' which can be played back on a baseline database.
