### ISSUE TITLE
Collection option defaults vs. docs

### ISSUE THREAD

**Issue by plievone** [techfort/LokiJS#69]
[Docs](http://lokijs.org/#/docs#addCollection) say that collection `asyncListeners` defaults to `false`, but in code it defaults to `true` (even though comment there says otherwise). I was wondering why inserting a new doc results in its `meta.created` being 0 if inspected in the same control flow right after insert, this explains why.

Also collection option `disableChangesApi` defaults to `true` in code, which is a good default I guess, but is said to default to `false` in docs.

**Comment by techfort** [comment]
Thanks for catching that! Yes the intention is to have sync listeners and disabled changes API by default, so in the listeners case i will change the code, and in the changes case I will change the docs.

**Comment by techfort** [comment]
Ok, fixed these too.
