### ISSUE TITLE
Changes API serialization

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#696]
I see in the changes API docs that it stores a serialized copy of the changed object, but I see in the example that it says it would store `{ name: 'users', obj: { name: 'joe' }, `. Should that not be something like `{ name: 'users', obj: "{ name: 'joe' }", `? And can I get the changes without the object serialization? I suspect there's some overhead in the serialization and I only need to know the ID of the objects that have changed.

**Comment by retorquere** [comment]
Wait, the serialized result is not an array of serialized objects, it's a serialized array of objects. Is there a way to get at the pre-serialized changes? I just end up doing a JSON.parse on them, that seems like double work.

**Comment by obeliskos** [comment]
Your custom adapter is standard/basic and not reference right?  

If so, you should be able to serialize coll.getChanges() and pass that to your adapter... you would have to come up with your own file naming convention and you would have to scan files to see what you should reapply/playback.  If you have cloning turned on, you might be able to use deltaChanges to limited persisted objects to only deltas.

**Comment by retorquere** [comment]
I currently have a reference adapter but I could change to standard/basic if that helps. I don't know how to pass things to the adapter -- with my current setup, the adapter seems to get invoked automatically.

this seems to work:

```
var loki = require('lokijs')
  
function YourAdapter() {
   this.mode = "reference";
}

YourAdapter.prototype.exportDatabase = function(dbname, dbref, callback) {
  var success = true; // make your own determinations

  // start transaction
  for (const coll of dbref.collections) {
    for (const change of coll.getChanges()) {
      console.log(change)
      // async save happens here
    }
  }
  // only remove those changes from coll.
  // end transaction

  if (success) {
    callback(null);
  }
  else {
    callback(new Error("some error occurred."));
  }
}

var db = new loki('Example', { adapter: new YourAdapter() });

var users = db.addCollection('users', { indices: ['email'] });
users.setChangesApi(true)

var odin = users.insert( { name : 'odin', email: 'odin.soap@lokijs.org', age: 38 } );
var thor = users.insert( { name : 'thor', email : 'thor.soap@lokijs.org', age: 25 } );
var stan = users.insert( { name : 'stan', email : 'stan.soap@lokijs.org', age: 29 } );
var oliver = users.insert( { name : 'oliver', email : 'oliver.soap@lokijs.org', age: 31 } );
var hector = users.insert( { name : 'hector', email : 'hector.soap@lokijs.org', age: 15} );
var achilles = users.insert( { name : 'achilles', email : 'achilles.soap@lokijs.org', age: 31 } );

stan.name = 'Stan Laurel';
users.update(stan);

users.remove(hector);

db.saveDatabase(console.log)
```

but I'm currently stuck with the transactionality of it. The actual saves are async so it's not inconceivable that new changes are added to the changes feed while the transaction runs, so I can't flush at the end of the transaction because those new changes would be lost, but I don't want to flush at the start of the transaction because the transaction might fail and than all those changes are lost.

**Comment by obeliskos** [comment]
So this sounds like differential backup for purpose of reducing time it takes to save?  How many changesets do you expect to save in between full backups/saves?

It may be best to devise your own method for saving those 'differential' changesets (strings) for later iteration and playback since loki really does not have any orchestration logic for that process.   Serializing the current changes should give you a single string which you can save as a single file.  No real need to use an adapter unless you want to reuse logic elsewhere.  

Generation of changes is sync, at which point you can clear changes sync, before beginning an async save.  Are you intending this process to run on shutdown?  And during shutdown you expect new records to be added?

**Comment by retorquere** [comment]
I'm not yet sure how many changesets will be, but the DB has grown beyond my expected use for some users; I save my loki DB to sqlite (one row per collection) every 5 seconds; I save the collections only when they're dirty. But one of the collections has grown to 6MB serialized for that user, and while it doesn't change every 5 seconds, it's certainly not uncommon for there to be changes at least every minute.

I also run the save at sync, but I don't want to lose everything should Firefox crash, so the once every 5 secs is a compromise between save-every-change and only-at-shutdown.
