### ISSUE TITLE
"$where" query operator is not documented

### ISSUE THREAD

**Issue by mnasyrov** [techfort/LokiJS#697]
There is `$where` query operator, I found it by looking through the sources. It seems like the operator is not documented on the web site. `$where` allows to specify a predicate for a document field and it is used by `Resultset.find()` method.

**Comment by obeliskos** [comment]
I do not recall that being added... by documentation are you referring to query examples page or type definitions?

**Comment by mnasyrov** [comment]
"Query examples" page. As I see typescript's typings have a definition for `$where`.
