### ISSUE TITLE
How Loki handles updates via say Indexeddb or LocalStorage from different webpage instances

### ISSUE THREAD

**Issue by arvind-agarwal** [techfort/LokiJS#698]
I am very new to Loki and trying to understand the persistence mechanism. Let's say, I have a webpage where I am using Loki with indexeddb as the persistence layer. Now for some reason, a copy of that web page is opened, and some writes happen in that webpage (copy). And user comes back to the original webpage, in this case, how the changes done in copy webpage will reflect here? Is it like we need to completely reload Loki, or there is some sort of refresh method can be called to reflect the changes from the underlying adapter? 

I can work out a mechanism to alert the other webpage via websockets, however not sure what is the efficient way of reflecting the change, since I might be using something like DynamicView in the page and indexeddb is common between the webpages.

Maybe I am approaching this in a completely wrong way but some clarification will help.

**Comment by obeliskos** [comment]
LokiJS is not really built to have multiple competing loki instances to be simulatenously updating the same database, however this might be done having a single 'server' to handle all pages via a webworker.  If you are just transacting small amounts of data you should be able to devise simple messaging for inserts, updates, removes which involves serialization/deserialization for messages and have service worker handle all saves, autosaves and collection inserts/updates/removes.

I have yet to experiment with -serviceworkers- and loki, so i am not sure current browsers support that level of 'availability' for running ongoing processes.  If it only supports on-demand pattern you would have to spin up database, make changes, and save after every 'transaction'.  If your database is small enough, you could use localStorage either with loki or directly but it might be able to 'coordinate' multiple overlapping requests.
