### ISSUE TITLE
Using Loki indexed adapter with vuex/redux - removing items isn't reactive

### ISSUE THREAD

**Issue by chasebank** [techfort/LokiJS#700]
This is entirely support and most certainly not an issue with Loki, so I apologize for that.

I'm using Loki, the indexed adapter, and Vuex, which is Vue's version of Redux.

I had this setup working perfectly in an older project, but now I'm having an issue where any sort of removal of items aren't reflected until there's a page refresh. By removal I'm referring to `findAndRemove()` on an item, and `removeDataOnly()` on a collection. If there's better ways to handle deletions I'm also open to that advise, but as far as I can tell, I'm executing this exactly as I did in my older project, where things worked fine, but now they're not.

The loki collection is updated successfully, and the adapter maintains the data, but the Vuex store does not update. I may need to seek help in the Vue community, but I'm trying here first hoping I've made some mistake in setting up loki/the adapter?

I have a Codepen showing the issue [https://codepen.io/chasebank/pen/pZVOMq](https://codepen.io/chasebank/pen/pZVOMq)

Loki and adapter are created
```
var fsAdapter = new LokiIndexedAdapter("HelloWorld");

var db = new loki("people_db", {
  autoload: true,
  autoloadCallback: databaseInitialize,
  autosave: true,
  autosaveInterval: 1500,
  adapter: fsAdapter
});
```

Database is initialized and dummy data is inserted
```
function databaseInitialize() {
  // including this to make resetting db easier
  // db.removeCollection("people")
  
  if (!db.getCollection('people')) {
    db.addCollection('people');

    db.getCollection('people').insert([
      { name: "Daenerys Targaryen", boolean: false },
      { name: "John Targaryen", boolean: false },
      { name: "Tyrion Targaryen", boolean: false },
      { name: "Varys Blackfyre", boolean: false }
    ]);
  }
  
  runProgramLogic();
}
```
app is created
```
function runProgramLogic() {
  let peopleData = db.getCollection('people');
  
  const store = new Vuex.Store({
    state: {
      people: peopleData.data
    },
    mutations: {
      ADD_PERSON(state,payload) {
        peopleData.insert({
          name: payload,
          boolean: false
        })
      },
      
      TOGGLE(state,payload) {
        let thisPerson = peopleData.findOne({
          $loki: payload
        });

        thisPerson.boolean = !thisPerson.boolean

        peopleData.update(thisPerson);
      },
      
      DELETE_PERSON(state,payload) {
        peopleData.findAndRemove({
          $loki: payload
        })
      }
    },
  });
  
  Vue.use(Vuex);
    
  new Vue({
    el: '#app',
    store,
    data() {
      return {
        newPersonName: ''
      }
    },
    computed: {
      people() {
        return this.$store.state.people
      }
    },
    methods: {
      addPerson() {
        this.$store.commit('ADD_PERSON', this.newPersonName)
        
        this.newPersonName = ''
      },
      
      toggle(key) {
        this.$store.commit('TOGGLE', key)
      },
      
      deletePerson(key) {
        this.$store.commit('DELETE_PERSON', key)
      }
    }
  });
}
```
You can add a new person, which is reactive and updates as expected, you can toggle the true/false value and see the prop update in the data. You can refresh the page and see the adapter maintains persistence. But deleting a person appears to do nothing. Until a refresh shows that the person was in fact deleted.

Any ideas?

**Comment by Viatorus** [comment]
Hi @chasebank,

I never used Vuex/Redux but your Codepen helped me to understand what the problem could be.

Direct changes of Collection.data and changes to new properties of documents of Collection.data[i] will not be observed. I don't know anything about the observe mechanism Vuex is using but the following code does not get monitored:

```js
peopleData.data = [];
peopleData.data[0].newer = 1;
```
---

So why did it worked with a previous version of LokiJS? Well, the following code has been changed:

from:
```js
/// Collection.prototype.remove()
this.data.splice(position, 1);
```

to:
```js
///  Collection.prototype.removeBatchByPositions
this.data = this.data.filter(function(obj) {
  return !xo[obj.$loki];
});
```

So instead of modifing the data array, we create a new one. And the observer from Vuex is gone.

**Comment by chasebank** [comment]
Thanks for the reply @Viatorus!

Sure enough, it hadn't occurred to me to check the Loki version of my old project and try downgrading. The old project used 1.5.0

I forked the Codepen and tried the older Loki and it works! https://codepen.io/chasebank/pen/yqjrEq/

I appreciate you giving it a look, even though you may be unfamiliar with Vuex. I'm still learning myself. I'm sure there's a built in feature to solve this very issue.

But in the mean time, is there any serious concerns with me just using the older Loki for now?
