### ISSUE TITLE
Data Loss with Indexed DB adapter

### ISSUE THREAD

**Issue by babysparks** [techfort/LokiJS#704]
We have an app with 200K monthly active users. All with LokiJS and Indexed DB for persistence. The app is a Cordova/PhoneGap Hybrid.

0.5% of users loose all the data, and the app opens like if it was just installed. It's a very small number of users, making it very hard to replicate.

What I discovered so far:
- Only 0.5% of our users are experiencing this issue
- When the user kills the app and opens it again, everything works.
- When the users stops using the app, and comes back couple of hours later, all data was lost
- It happen mostly on iOS, but some Android devices apear to have the same issue
- Not happening due to very low memory (Many have 1gb available or more)
- No apparent correlation with the iOS version or Phone model
- No apparent correlation with country or region
- Re-installing does not correct the problem

Anybody else having a similar issue? Any ideas? Suggestions?

Thanks, JP

**Comment by Viatorus** [comment]
Well, I assume this is not a LokiJS issue. More an issue of storage persistent lifetime.

IndexedDB and LocalStorage are not guaranteed to be persistent.

> From Google Web Development:
> When storage on the local machine is running tight (“under storage pressure”), user agents automatically clear storage to make more available space. 

Please check out the following links:
* https://developers.google.com/web/updates/2016/06/persistent-storage
* https://www.w3.org/TR/quota-api/
* https://storage.spec.whatwg.org/#persistence
* https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria

**Comment by babysparks** [comment]
Is there a guaranteed persistence option?

The majority of my cases are iOS. Are you aware of cases where the iOS will clear an Indexed DB?

**Comment by Viatorus** [comment]
I don't have any knowledge about IndexedDB and iOS (or others).

But what I just read:
> Under certain events in iOS (so far, we have found: low storage, certain iOS upgrades) the data is wiped.

* https://forums.developer.apple.com/thread/75918 
* https://stackoverflow.com/questions/47659352/cordova-apps-localstorage-wiped-after-appstore-update

I am sorry. I don't know any HTML 5 storage on iOS which is guarantees persistence.

**Comment by obeliskos** [comment]
How large does the database grow to, on average and for the .5%?  Are you using autosave, or more specifically, how often does the database get re-saved?  You are using 'just' indexedDB right (not including PartitionAdapter)?
