### ISSUE TITLE
Ionic 3 typescript persistent storage not working

### ISSUE THREAD

**Issue by shraddha1112** [techfort/LokiJS#705]
Hello,
We are trying to persist the data and read it on relaunch for hybrid app  Android and iOS. We have done multiple trials but it is not working.

> ` var FSStorageadapter = { adapter: new FSStorage() }
  var lfAdapter = new LokiLocalForageAdapter("lokidb");
 this.db = new Loki( "databaseDB", 
        { adapter:lfAdapter,
            autosave: true,
        autosaveInterval: 1000,autoload: true, autoloadCallback : this.loadDatabase(),
        }
    );
    this.db.loadDatabase({}, function() {
      console.log('done loading lokidb');
      var collection = this.db.getCollection("BASECOLLECTION");
      if(!collection){
          collection =   this.db.addCollection("BASECOLLECTION");
  
      }
  });`

Any help is appreciated.

**Comment by obeliskos** [comment]
Does it work on desktop?

Couple things i see wrong : 
- Your autoloadCallback should be set to function 'reference' (remove parens from loadDatabase)
- The method 'loadDatabase' doesn't appear in example
- Immediately after instantiating a loki instance with 'autoload' set to true, you are manually loading in the very next (synchronous) statement... i would suggest either manually load or autoload but not both
- Without seeing how you import loki, the Loki constructor may be lowercase

**Comment by shraddha1112** [comment]
Hello,
Thank you for ur reply.
We are working for IONIC 3 Typescript Hybrid Mobile App.
And we dont use it for desktop. We use it for Mobile only.
Following is my complete file.
`import { Injectable } from '@angular/core';
import 'rxjs/add/operator/map';
declare var require: any;

var fs = require("file-system");
const { Loki } = require('@lokidb/loki');
import { File } from '@ionic-native/file';
import { random } from 'd3';
const { FSStorage } = require('@lokidb/fs-storage');
const LokiCordovaFs = require('LokiCordovaFSAdapter');


/*
  Generated class for the DatabaseProvider provider.

  See https://angular.io/docs/ts/latest/guide/dependency-injection.html
  for more info on providers and Angular DI.
*/
@Injectable()
export class CustomOfflineProvider {
   db: any;                        // LokiJS database
  static  value:any;
  userName;

  constructor() {
    console.log('Hello StorageProvider Provider constructor');
    CustomOfflineProvider.value = 0;
   // console.log("value "+this.value);
  }
 
init(userNameIn){
  FSStorage.register();

    var lfsadapter = new LokiCordovaFSAdapter({ prefix: 'loki' });
    
    this.db = new Loki( "databaseDB", 
        { adapter:lfsadapter,
            autosave: true,
        autosaveInterval: 1000,autoload: true, autoloadCallback : this.loadDatabase(),
        }
    );
    this.db.loadDatabase({}, function() {
      console.log('done loading lokidb');
      var collection = this.db.getCollection("LMCOLLECTION");
      if(!collection){
          collection =   this.db.addCollection("LMCOLLECTION");
      }
  });
   

    this.userName = userNameIn;

}
loadDatabase(){
  if(this.db){
  var collection = this.db.getCollection("LMCOLLECTION");
  if(!collection){
      collection =   this.db.addCollection("LMCOLLECTION");
   // collection = CustomOfflineProvider.db.getCollection("LMCOLLECTION");
  }
}
}
  getValue(){
   
    if(this.db){
        var collection = this.db.getCollection("LMCOLLECTION");
        if(!collection){
            collection =   this.db.addCollection("LMCOLLECTION");
         // collection = CustomOfflineProvider.db.getCollection("LMCOLLECTION");
        }
    }else{
        console.log("DB IS NULLL ");
    }
      console.log("GetValue");
      var collection = this.db.getCollection("LMCOLLECTION")|| this.db.addCollection("LMCOLLECTION");;
      /*if(collection == null){
        CustomOfflineProvider.db.addCollection("LMCOLLECTION");
        collection = CustomOfflineProvider.db.getCollection("LMCOLLECTION");
      }*/
        var results =  collection.find();
        console.log(JSON.stringify(results));
      return true;
  }

  setValue(){
    
   // CustomOfflineProvider.db.addCollection("LMCOLLECTION");
   console.log("SetValue");
   var number =Math.random();
   console.log("THis time it s" +number);
   var stringksadj = "test"+Math.random();
   var testObject = {id:number,"name":stringksadj};
  // var collection = this.db.getCollection("LMCOLLECTION");
   var collection = this.db.getCollection("LMCOLLECTION")|| this.db.addCollection("LMCOLLECTION");;

    if(collection!=null){
    collection.insert(testObject);
    console.log("Inserted");
    this.db.saveDatabase();
    }else{
        this.db.addCollection("LMCOLLECTION");
        collection.insert(testObject);
        console.log("Inserted");
        this.db.saveDatabase();
    }
    var results =  collection.find();
    console.log(JSON.stringify(results));
    //CustomOfflineProvider.value++;
  }
  storeChartData(data){
    console.log("STORE CHART DATA");
    console.log("STORE CHART DATA1");
    var chartData = JSON.parse(JSON.stringify(data));
    console.log("STORE CHART DATA2");

  var chartDataResponse = chartData;
 //   console.log("STORE CHART DATA2"+chartDataResponse.length);
 console.log(chartDataResponse);
 var collection = this.db.getCollection("LMCOLLECTION")|| this.db.addCollection("LMCOLLECTION");;
 if(collection!=null){
   console.log("SaVE START")
  collection.insert(chartDataResponse);
    this.db.saveDatabase();
    console.log("SaVE END")
 }
    console.log("STORE CHART DATA3");

   // console.log(JSON.stringify(this.db));
    //var results =  this.db.find();
    //console.log(JSON.stringify(results));

  }

}

`
