### ISSUE TITLE
How could I combine the loki-crypted-file-adapter and loki-fs-structured-adapter?

### ISSUE THREAD

**Issue by xeoshow** [techfort/LokiJS#707]
Hello,

I am now using loki-fs-structured-adapter, and would like to integrate the crypt feature from loki-crypted-file-adapter, how should I do?

Thanks a lot.

Best regards, Jason

**Comment by obeliskos** [comment]
Sorry I missed this earlier, but for future reference I would think this would not be very difficult.

The fs structured adapter serialized each object independently and send that to node fs stream as 'lines'.  

You'd need to pass in a password to the constructor and during saving and loading you would need to encrypt and decrypt the lines as they are written or read.

**Comment by xeoshow** [comment]
Thank you so much for kind reply. I am new to LokiJS, hopefully there could be a demo code for this ... 

Thanks so much again.


Best regards, Jason
