### ISSUE TITLE
React app shows wrong environment and fails persisting DB

### ISSUE THREAD

**Issue by TravelingTechGuy** [techfort/LokiJS#714]
I used `create-react-app` to spin a new app template and then added LokiJS (`yarn add lokijs`).
I tried using the `autosave` and `autoload` so I can persist the DB between sessions:

```
let db = new loki('packages.db', {
      autoload: true,
      autoloadCallback: dbInitialize,
      autosave: true,
      autosaveInterval: 5000,
});
```
I get an error that `fs.stat` is not supported, and `dbInitialize` is never called (andtherefore, my component's state is not set).

After reading the documentation, I added `adapter: new loki.LokiLocalStorageAdapter()` to the settings, and it started working. However, this was supposed to be the default adapter in a browser, so I looked at the string saved into LocalStorage and it says `env: NODEJS`. Apparently, despite running in the browser (Chrome 69), Loki misidentifies the environment.

As a final step, I added `env: BROWSER` to the settings, and it now works without the adapter setting.

I believe there's a bug in the environment detection logic.

**Comment by obeliskos** [comment]
For some reason, the react libraries must be establishing variables in the global namespace which mimic node or node-webkit.  Can you verify if the following evaluates to true in your environment?

https://github.com/techfort/LokiJS/blob/7a050b60537f6da0b94269f405dd724878288ede/src/lokijs.js#L842-L844

**Comment by TravelingTechGuy** [comment]
I had to remove the `env` property to get the `getENV` function called. I put a breakpoint at line 842 (or what corresponded to it in the bundled code) and I can verify that it does return 'NODEJS', that is, all 3 objects (`global`, `global.window` and `process`) are defined in the browser's development tools.

**Comment by TravelingTechGuy** [comment]
Ok, found something more: turns out webpack injects the `process` object into JavaScript. There's a [Medium article about doing it yourself](https://medium.com/@trekinbami/using-environment-variables-in-react-6b0a99d83cf5), but turns out, if you use `create-react-app`, the webpack script does it for you (check out `node_modules/react-scripts/config/webpack.config.web.js`.

Bottom line, either find a better way to find the environment, or just make the `env` property a mandatory parameter when instantiating a new DB object.
