### ISSUE TITLE
Support for React-Native (?)

### ISSUE THREAD

**Issue by killerchip** [techfort/LokiJS#716]
It seems that currently LokiJS does not support React-Native (or I'm doing something terribly wrong).

I have installed performed `npm install --save lokijs` in my project.
Then inside a file I just do:

`const db = require('lokijs');`

Nothing more... the above is enough to brake the app.

When I'm performing `react-native run-android`, I get the error:

```
error: bundling failed: Error: Unable to resolve module `fs` from `<**my project**>/node_modules/lokijs/src/lokijs.js`: Module `fs` does not exist in the Haste module map
```

So, is LokiJS supporting react-native?
If yes, can someone help me out, what am I doing wrong?

Thank you in advance.
Costas

**Comment by muescha** [comment]
for a first step - maybe look at this changes:

https://github.com/techfort/LokiJS/compare/master...cawfree:master
