### ISSUE TITLE
Some small documentation discrepancies

### ISSUE THREAD

**Issue by simonvizzini** [techfort/LokiJS#72]
* [Collection.insert()](http://lokijs.org/#/docs#collection)
  * Documentation and example is talking about the `document(obj)` function, which seems to have been renamed to `insert(obj)`. At first I didn't realise that and I was wondering why I couldn't call the  document function so I looked at the source and the [comment here](https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L2655-L2657) is rather confusing, especially the last line :-)

* [Loki.loadDatabase()](http://lokijs.org/#/docs#load)
  * Documentation is missing the `inflate` option (btw "inflate" is a rather confusing word in this context, "loader" like in the source seems clearer imho)

**Comment by techfort** [comment]
These are fixed, thank you.
