### ISSUE TITLE
"Cannot read property '1' of undefined" at line 535

### ISSUE THREAD

**Issue by Badisi** [techfort/LokiJS#73]
The variable 'obj' declared at line 546 is overlapping the one declared at line 511.

**Explanation**
First time you crossed the line 535 everything is fine but then the second time you got the error "Cannot read property '1' of undefined" which is due to the fact that 'obj' has changed and is now the one that was declared at line 511.

**How to reproduce**
Try to load a database file with 2 collections and give 2 proto as options.
``` db.loadDatabase({collA:{proto:A}, collB:{proto:B}}; ```

**Comment by techfort** [comment]
Thanks for catching this bug!
