### ISSUE TITLE
Add listener on Dynamic View

### ISSUE THREAD

**Issue by DawnImpulse** [techfort/LokiJS#731]
How can I add a listener to a dynamic view result?

What I want is that whenever a data is added to collection & if it matched the dynamic view queries then an event should be triggered to notify of the new changes.

**Comment by obeliskos** [comment]
so it seems dynamic view supports one event "rebuild" and the idea was that it would fire (at least if the view was persistent) when changes to results occur.  Looking through the code I am not positive that is how it actually works... it seems to fire only if sort criteria is specified on the dynamic view.

If I get time, I will experiment... or you could try experimenting yourself in LokiSandbox or elsewhere and let me know your results.

The general syntax I think would be : 
```javascript
let dv = coll.getDynamicView("test");
dv.on("rebuild", () => {
  console.log("rebuild");
});
```

**Comment by DawnImpulse** [comment]
@obeliskosI will experiment a bit and will let you know if I reach on anything conclusive.
