### ISSUE TITLE
`lokijs.min.js` references non-existent `./loki-indexed-adapter.js`

### ISSUE THREAD

**Issue by mike-ward** [techfort/LokiJS#733]
In 'lokijs.min.js` from npmjs.org 

`{adapter=require("./loki-indexed-adapter.js")}return adapter}`

Should it not be;

`{adapter=require("./loki-indexed-adapter.min.js")}return adapter}`

**Comment by obeliskos** [comment]
so when I install lokijs from npm, its package.json's 'main' setting points to the 'src' folder which is non-minified.  How are you importing lokijs itself?

**Comment by mike-ward** [comment]
I've moved on and honestly, I don't recall the details. I typically `npm i -D` to install stuff. I also use Typescript so maybe there's an issue there.
