### ISSUE TITLE
Mention LokiDB in readme...?

### ISSUE THREAD

**Issue by ViggoV** [techfort/LokiJS#737]
Is there any reason why [LokiDB](https://github.com/LokiJS-Forge/LokiDB) isn't mentioned in the readme? It presents itself as the official successor to LokiJS, so I wonder why I had to dig deep into old issues to randomly stumble upon it's existance. It would have been nice to know before I spent a whole day integrating LokiJS into a project..

**Comment by Viatorus** [comment]
LokiDB is not ready yet. That's why I didn't want any bigger announcement.

But at the moment I don't have much time for LokiDB, so I don't know when it will be officially released.

**Comment by ViggoV** [comment]
Ah okay. Thank you. I got pretty confused there for a moment, since the readme for LokiDB make it look like it's up and running..

**Comment by franck34** [comment]
@Viatorus hi, does LokiDB will have the same API as LokiJS ? I'm working hard on a lokijs server and client https://github.com/sloki-project/sloki

**Comment by patarapolw** [comment]
It would be nice if one compares between the two, and why you might consider switching (i.e. using prerelease TypeScript version).

What problems do it tried to solve, anyway, beyond full control over `@types/lokijs`?
