### ISSUE TITLE
Non-blocking loading of large databases

### ISSUE THREAD

**Issue by alexgreenland** [techfort/LokiJS#740]
With a large JSON database, it loads the file asynchronously but blocks the process in the `JSON.parse` step, blocking on the order of 10s of seconds.

https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L2515

https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L1622

Could we move to a non-blocking JSON parser, like [yieldable-json](https://github.com/ibmruntimes/yieldable-json)?

**Comment by obeliskos** [comment]
our (node-based) es6 loki-fs-structured-adapter uses a generator iterator approach with individual JSON.parse calls for each object which sounds similar to what you describe.

I had thought about bringing our iterator approach internal to loki but decided against it as it has always been es5 and we are shifting development focus to lokidb which will likely see such a feature.

So if loki-fs-structured-adapter does not fit your needs, you should be able to create your own "reference mode" persistence adapter to utilize any method such as you describe, even if that requires your dependencies.
