### ISSUE TITLE
Greater Than search returns empty array if there are null values

### ISSUE THREAD

**Issue by IrosTheBeggar** [techfort/LokiJS#745]
I'm writing a script that searches for ratings:

```
    var results = fileCollection.chain().find({
      '$and': [
        { 'path': { '$eq': user.path] } }
        , {
          'rating': { '$gt': 0 }
        }]
    }).simplesort('rating', true).data();
```

As long as all the ratings are integers, this works fine. If just one rating gets set to null then it returns en empty array.

**Comment by franck34** [comment]
null is an object, not 0.

If you were using a SQL database, you would define a default value : 0, when you try to insert a record without rating. So, not sure it's a lokijs bug. 

Suggestion: find null rating value and replace them by 0, and fix your initial insert with -1 or 0 as you want ?

**Comment by obeliskos** [comment]
Well a basic $gt filter seems to work just fine with nulls and undefines as shown in [this LokiSandbox gist](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/a3ad883fe3437d943362f103c0a621cd/raw/ab9f4d8058a20a582f96d93a026cb3f896d29e5a/lokijs-030519)

If i were to change that to a $lt it would still find the relevant docs but would also include the null and undefined records.  LokiJS has unified ranges that say nulls/undefines are always less than numbers.

If you were to remove the $and and $eq ops and just have the $gt and simplesort does it return values correctly?
