### ISSUE TITLE
memory leak for removeCollection

### ISSUE THREAD

**Issue by franck34** [techfort/LokiJS#746]
Hi

While benchmarking lokijs in a nodejs context (see https://github.com/sloki-project/sloki), i can see using heapdump and gc that the collection stay in memory.

If i replace the code below

https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L1212

```
/**
     * Removes a collection from the database.
     * @param {string} collectionName - name of collection to remove
     * @memberof Loki
     */
    Loki.prototype.removeCollection = function (collectionName) {
      var i,
        len = this.collections.length;

      for (i = 0; i < len; i += 1) {
        if (this.collections[i].name === collectionName) {
          var tmpcol = new Collection(collectionName, {});
          var curcol = this.collections[i];
          for (var prop in curcol) {
            if (curcol.hasOwnProperty(prop) && tmpcol.hasOwnProperty(prop)) {
              curcol[prop] = tmpcol[prop];
            }
          }
          this.collections.splice(i, 1);
          return;
        }
      }
    };
```

with just

```
Loki.prototype.removeCollection = function (collectionName) {
      var i,
        len = this.collections.length;

      for (i = 0; i < len; i += 1) {
        if (this.collections[i].name === collectionName) {
          this.collections.splice(i, 1);
          return;
        }
      }
    };
```

no more mem leak, heapdump show that the collection is really removed from nodejs memory (after gc, of course)

Do you have an idea why the removeCollection is implemented like this today ? perhaps there is a good reason to 
```
 if (curcol.hasOwnProperty(prop) && tmpcol.hasOwnProperty(prop)) {
    curcol[prop] = tmpcol[prop];
}
```
but i didn't catch it.

**Comment by obeliskos** [comment]
git blame shows it came from PR #349 but I admit I don't entirely understand why the v8 engine can't automatically gc this from the splice.  The PR does seem to indicate nulling data, binaryIndices, and flushbuffer might be areas preventing gc though.

it sounds like heapdump is really useful for making reliable diagnostics on this, so if you get time to look into this maybe you can load up a (large-ish) sample collection with binary indices and see if there is more of a leak with your method than existing method.  Maybe try unique indices as well.  I should have some random data population in 'benchmarks' folder if you need it.

Although he probably doesn't remember this, if @alexandernst has any recollection he can provide it here otherwise I am open for any experimentation and measured instrumentation based changes if they lower lokijs memory footprint.

**Comment by alexandernst** [comment]
Hmmm... this is quite strange 🤔 Can you add `del tmpcol;` at the end, right before the `return` and check if the memory leak is still there?

**Comment by franck34** [comment]
already tried, you can not del tmpcol; in strict mode

**Comment by alexandernst** [comment]
What about `tmpcol = null;`?

**Comment by franck34** [comment]
let me try, i'm busy right now, give you needs in a few hours thx

**Comment by franck34** [comment]
No memory leak in fact, i was wrong. My benchmark test was wrong.

But, can i suggest this code perhaps ?

```
Loki.prototype.removeCollection = function (collectionName) {
      var i,
        len = this.collections.length;

      for (i = 0; i < len; i += 1) {
        if (this.collections[i].name === collectionName) {

          // get new collection attribute
          var tmpcol = new Collection(collectionName, {});

          // get current collection attribute
          var curcol = this.collections[i];

          // delete current collection attributes
          for (var prop in curcol) {
            if (curcol.hasOwnProperty(prop)) {
              curcol[prop] = null;
            }
          }

          // remove new collection attributes if needed
          for (var prop in tmpcol) {
            curcol[prop] = null;
          }

          this.collections.splice(i, 1);
          tmpcol = null;
          curcol = null;
          return true;
        }
      }
      return false;
    };
```

**Comment by franck34** [comment]
it return true when the collection has been found and removed, false if not

**Comment by obeliskos** [comment]
No memory leak in existing code?  What about the simplified first version you suggested... does simply performing a slice not manage to free up memory as well as the current implementation?

I am hesitant to make this method any more complicated without a measured understanding of if or where the v8 GC might be getting confused with our data structure object references.  

Maybe I can experiment with heapdump this weekend sometime so I can observe the behavior as well.

**Comment by cyclux** [comment]
@obeliskos I don't know if it is directly related but I also discovered a memory leak of LokiJS (nodeJS):

`heapsnapshot` taken every 90 minutes:
![image](https://user-images.githubusercontent.com/5097913/56863405-3115fe00-69b6-11e9-9640-6dd1034f27d1.png)
So the heap rises steadily in around 3 - 5 MB every 90 minutes. 

When I analyze the delta of those heapsnapshots I get a huge amount of objects which are originating from LokiJS processing and are responsible for this leak:

![image](https://user-images.githubusercontent.com/5097913/56863460-c913e780-69b6-11e9-8d00-75ac975b0837.png)

My use case is, that I have a collection with unique index with around 50000 entries. Items get added and removed up to hundreds of times per second. But the collection is steadily hold at ~ 50000 items like a capped collection, known from MongoDB.

Do you know where this leak might be coming from? Is it maybe that the unique index is recalculated on every insert() ? But the old index is kept in memory? However when looking into the heapsnapshot I see the full object:

![image](https://user-images.githubusercontent.com/5097913/56863532-94ecf680-69b7-11e9-9933-d3e56e11e503.png)

Would be happy to get a hint in any direction to solve this, thanks! :)
