### ISSUE TITLE
Nested "or" find fails

### ISSUE THREAD

**Issue by RobertGary1** [techfort/LokiJS#747]
Notice in this unit test below the only difference between the test that passes and the test that fails is the order of the values under OR.

it('Test cache patches', () => {
  expect.assertions(2);

  const queryFails = {'$or': [{'state': 'STATE_FAILED'}, {'$or': [{'state': 'STATE_DEGRADED'}, {'state': 'STATE_NORMAL'}]}]}
  const queryWorks = {'$or': [{'state': 'STATE_NORMAL'}, {'$or': [{'state': 'STATE_DEGRADED'}, {'state': 'STATE_FAILED'}]}]}

  const superSlim = [{
    "uri": "/api/v3/disks/bfe8c919c2a3df669b9e0291795e488f",
    "state": "STATE_NORMAL"
  }, {
    "uri": "/api/v3/disks/bc3f751ee02ae613ed42c667fb57de75",
    "state": "STATE_NORMAL"
  }, {
    "uri": "/api/v3/disks/710466edfdc6609ea23e17eb0719ea74",
    "state": "STATE_NORMAL"
  }];

  const Loki = require('lokijs');

  const db = new Loki('ssmc.db');

  const lokiTable = db.addCollection('bobTest', {unique: ['uri']});

  lokiTable.clear();
  lokiTable.insert(superSlim);

  const resultsSet = lokiTable.chain();

  const result = resultsSet.find(queryWorks).data({removeMeta: true});
  expect(result.length).toEqual(3);

const resultsSet2 = lokiTable.chain();

  const result2 = resultsSet2.find(queryFails).data({removeMeta: true});
  expect(result2.length).toEqual(3); //<<=== THIS FAILS WITH result2.length actually 0

});

**Comment by RobertGary1** [comment]
This bug is very frustrating.

**Comment by obeliskos** [comment]
I don't know where your bug may lie but I adapted your sample and it seems to [run fine for me in Loki Sandbox](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/b7f955e12d1d36616590e0ec49b2d1de/raw/411dc1d804af0e043a786756134505dafa73a122/NestedOrSampleTest).

**Comment by obeliskos** [comment]
I think I have a [LokiSandbox gist](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/b7f955e12d1d36616590e0ec49b2d1de/raw/89f04f29b8a6fad90e31539247cc5e6ab82b9932/NestedOrSampleTest) which can reproduce your issue.

I'll try to look into this over the next few days.

**Comment by obeliskos** [comment]
Ok, I believe I have found the problematic code and removed it... 

I think someone had added an optimization to otherwise straightforward code and it introduced this bug.

Please let me know if you are still encountering any issues with this, but I added your unit test so this nested $or code path should be covered should there be any future changes.

Sorry I missed this, I have not had much time lately to monitor loki issues.

**Comment by RobertGary1** [comment]
Thank you!

**Comment by RobertGary1** [comment]
Are there plans to cut another release to expose this fix?
