### ISSUE TITLE
Does LokiJS support WKWebview in Cordova-ios?

### ISSUE THREAD

**Issue by mesqueeb** [techfort/LokiJS#748]
I need to create a Cordova-ios app that stores data.
From my googling I found DexieJS and LokiJS, and now need to choose what I will use.

LokiJS says it supports Cordova out of the box, but does it support WKWebview?

I was really confused about @dpogue 's post here:
https://github.com/dfahlander/Dexie.js/issues/170#issuecomment-182496050

He says:
> cordova-ios with the WKWebView plugin out-of-the-box supports neither IndexedDB nor WebSQL. This is a WKWebView limitation, not a Cordova problem. You need to install the local web server plugin to allow IndexedDB support.

Does that mean that I need to install:
1. cordova-ios
2. WKWebView cordova plugin
3. lokiJS
4. **ALSO a local web server plugin?**

If anyone can point me in the right direction, I'd be really grateful!

**Comment by mesqueeb** [comment]
I want to correct my original post after [receiving a comment](https://github.com/dfahlander/Dexie.js/issues/170#issuecomment-474187666) by dpogue:

> IndexedDB is properly supported in WKWebView as of iOS 10, with support on iOS 10.3 and newer being quite good.

So we know **WKWebView supports indexedDB**.

Can I automatically assume that LokiJS also supports WKWebView out of the box in this case?

**Comment by Viatorus** [comment]
If WKWebView supports IndexedDB you need LokiJS and and the tiny lokijs-indexeddb-adapter.

**Comment by mesqueeb** [comment]
Ok, I'll close this issue for now and be back if I run into actual problems! 🌝

**Comment by mesqueeb** [comment]
@Viatorus  Is there a difference between `loki-cordova-fs-adapter` and `lokijs-indexeddb-adapter` ?
I'm using cordova, which one should I opt for?

**Comment by Viatorus** [comment]
IndexedDB.

Also check out https://github.com/LokiJS-Forge/LokiDB (successor of LokiJS).

**Comment by mesqueeb** [comment]
@Viatorus I didn't know LokiJS had a successor!!!?!? 

This should also be announced on the official website!! 😅

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Viatorus** [comment]
It's still in under development, but not very active, sorry
