### ISSUE TITLE
meaning of "in-memory"

### ISSUE THREAD

**Issue by mesqueeb** [techfort/LokiJS#749]
I usually don't open the same issue twice, but I'm afraid it might go unnoticed on StackOverflow, so here goes:

LokiJS says it's an:
> In-memory JavaScript Datastore with Persistence

But I don't understand what "in-memory" means. How is "in-memory" indexedDB different from regular indexedDB? 🧐

As I'm under the impression that usually **"in-memory" means non-persistent**.
But LokiJS is **"in-memory with persistence"**. 😃

**Comment by Viatorus** [comment]
Operate (insert/modify/query...) in-memory (RAM).
Save/load a backup from disk (persistent) using LocalStorage/IndexDB/FS....

**Comment by mesqueeb** [comment]
So you mean to say instead of writing and reading directly from the indexedDB Loki would first load the DB into RAM and work from there? Then sometimes push changes back to the actual indexedDB?

Is this better to how a library like Dexie works? I’m trying to choose which one to learn and use. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Viatorus** [comment]
Yes. You can manual trigger `saveDatabase` or use the autosave functionality.

Dexie is limited to IndexedDB and its options. I would prefer learning LokiJS. because it is more flexible.

**Comment by mesqueeb** [comment]
Thanks a lot! ☀️

**Comment by mesqueeb** [comment]
For anyone come looking for extra information on this. The introduction on YouTube is also helpful:
https://youtu.be/jgW23Uo-XZ8
