### ISSUE TITLE
Simple way for removing all items from collection

### ISSUE THREAD

**Issue by mprokopowicz** [techfort/LokiJS#75]
I need simple way to remove all items from collection, but keep all dynamic views on this collection.

What i tried to do is:
```
      while(collection.data[0]) {
        collection.remove(collection.data[0]);
      }
```
It works good for collection itself, but does not updates my dynamic views.
I also feel that it should be some cleaner way to do this.

**Comment by techfort** [comment]
Good point, I am going to include this in the imminent release. If you're working off the latest npm version you could call `collection.removeWhere(func)` and pass a dummy filter like `function (obj) { return true; }`, and if that works all I would need to do is to create a clean wrapper like `collection.removeData()` which curries `removeWhere` in the above fashion.

**Comment by techfort** [comment]
Hi Michal,

I pushed a commit just there with a method in `Collection` called `removeDataOnly()`, which clears all the collection data but keeps everything else intact (indexes, views etc.)
There's a quick test in `tests/testRemove.js` which passes so it should be fine, let me know if this is does what you wanted Loki to do.

**Comment by obeliskos** [comment]
Thanks for spotting that... that was kind of an ugly bug.  Let me know if dynamic views get confused again.

**Comment by obeliskos** [comment]
Also collection.chain().remove() should work as well.

Or dynview.resultset.remove() should remove all documents in the dynamic view's resultset.

**Comment by techfort** [comment]
Closing this as there are multiple ways to do this safely.
