### ISSUE TITLE
SaveDatabase / LoadDatabase Issue

### ISSUE THREAD

**Issue by bugrakolcak** [techfort/LokiJS#753]
Hello i am trying to use lokijs for large collections.

For demo i used LokiIndexedAdapter;
In android everything is working perfectly fine. But in IOS when i try to savedatabase operation it breaks the app.

After reading documentation, i used LokiPartitioningAdapter along with LokiIndexedAdapter after that in IOS breaking app has stopped. But this time after loading and parsing database, data is empty.

Here is my code;

       function getToBeInsertedData(max) {

                var arr = [];
                var count = 0;
                while (count< max) {

                    var obj = {
                        _id: "test",
                        field1: 'Test',
                        field2: 'Test'
                    };
                    arr.push(obj);
                    count = coun + 1;
                }                
                return arr;
          }

         function testLokiJs() {

                var idbAdapter = new LokiIndexedAdapter('tester');

                var pa = new loki.LokiPartitioningAdapter(idbAdapter, { paging: true });

                var db = new loki('test', {
                    adapter: pa,
                    autosave: true,
                    autosaveInterval: 4000
                });

                var coll = db.addCollection('testColl');

                var toBeInsertedData = getToBeInsertedData(5);
                coll.insert(toBeInsertedData);

                db.saveDatabase();

                idbAdapter.loadDatabase('test', function (result) {
                    var parsedJson = JSON.parse(result);
                    //in here parsedJson.collections[0].data is empty
                });
           }

if i remove LokiPartitioningAdapter and use only LokiIndexedAdapter saveDatabase() breaks app with larger data. With smaller data example saveDatabase() and loadDatabase() operations are working.
else if i use LokiPartitioningAdapter along with LokiIndexedAdapter saveDatabase() does not breaks app but after loading database, collections[0].data is empty.

Any ideas...

**Comment by thomaschampagne** [comment]
Did you solve this issue. I'm experiencing the same thing on an electron app
