### ISSUE TITLE
Inserting a document in 2 different collections throws an error

### ISSUE THREAD

**Issue by willaaam** [techfort/LokiJS#756]
Hi Everyone,

I was just trying out LokiJS for a project and found something that feels like a bug. If it isn't - sorry for wasting your time.

I was (for fun) going to benchmark the difference between a unique constraint and an index. When inserting the same document in two different collections, I get an error. 
>         throw new Error('Document is already in collection, please use update()');

How can my collections know of each other? To me it makes intuitive sense for them to be completely separated, unless joined.

Please see the code below:

```
var loki = require('lokijs')
var fs = require('fs')

var db = new loki('testBench');

//We create two collections - one with a unique constraint and one with an index
var nodesUnique = db.addCollection('nodesUnique', { unique: ['technicalPath'] });
var nodesIndex = db.addCollection('nodesIndex', { indices: ['technicalPath'] });
console.log(db.listCollections());

var doc = JSON.parse(fs.readFileSync('./cfr.json', 'utf8'));

// Get rid of the root node to just insert the records
var docDeeper = doc.nodes;

//Insert records in our unique index way of working
var readCfr = nodesUnique.insert(docDeeper);
nodesUnique.update(readCfr);
console.log(db.listCollections());
console.log(nodesUnique.by("technicalPath", "/2/1/1/1/"));

//Insert records in our binary index way of working
var readCfr2 = nodesIndex.insert(docDeeper);
nodesIndex.update(readCfr2);
console.log(db.listCollections());
console.log(nodesIndex.find({technicalPath: "/2/1/1/1/" }));
```

**Comment by RobertGary1** [comment]
When you insert the object a field is added called something like $loki (I can’t remember the exact name but similar to this). This meta data field is used internally to keep track of the object. If you try to insert the same object elsewhere in Loki you get this error.

**Comment by willaaam** [comment]
> When you insert the object a field is added called something like $loki (I can’t remember the exact name but similar to this). This meta data field is used internally to keep track of the object. If you try to insert the same object elsewhere in Loki you get this error.

Thanks for the reply, but that doesn't seem to be the case. $loki is being maintained in readCfr or readCfr2. When adjusting the code to create a separate document, it's still showing the same behavior.

```
var loki = require('lokijs')
var fs = require('fs')

var db = new loki('testBench');

//We create two collections - one with a unique constraint and one with an index
var nodesUnique = db.addCollection('nodesUnique', { unique: ['technicalPath'] });
var nodesIndex = db.addCollection('nodesIndex', { indices: ['technicalPath'] });
console.log(db.listCollections());

var doc = JSON.parse(fs.readFileSync('./cfr.json', 'utf8'));
//Debug code to check if this worked
//for (var exKey in doc) { console.log("key:" + exKey + ", value:" + doc[exKey]); }

// Get rid of the root node and just insert the records
var docDeeper = doc.nodes;
var docDeeper2 = doc.nodes;

//Insert records in our unique index way of working
var readCfr = nodesUnique.insert(docDeeper);
nodesUnique.update(readCfr);
console.log(db.listCollections());
console.log(nodesUnique.by("technicalPath", "/2/1/1/1/"));

//Insert records in our index way of working
var readCfr2 = nodesIndex.insert(docDeeper2);
nodesIndex.update(readCfr2);
console.log(db.listCollections());
console.log(nodesIndex.find({technicalPath: "/2/1/1/1/" }));
```

It does work if I go all the way back and read it again from Disk, but if I check the length of the document (docDeeper), nothing has changed after insert.

```
var loki = require('lokijs')
var fs = require('fs')

var db = new loki('testBench');

//We create two collections - one with a unique constraint and one with an index
var nodesUnique = db.addCollection('nodesUnique', { unique: ['technicalPath'] });
var nodesIndex = db.addCollection('nodesIndex', { indices: ['technicalPath'] });
console.log(db.listCollections());

var doc = JSON.parse(fs.readFileSync('./cfr.json', 'utf8'));
var doc2 = JSON.parse(fs.readFileSync('./cfr.json', 'utf8'));
//Debug code to check if this worked
//for (var exKey in doc) { console.log("key:" + exKey + ", value:" + doc[exKey]); }

// Get rid of the root node and just insert the records
var docDeeper = doc.nodes;
var docDeeper2 = doc2.nodes;

//Insert records in our unique index way of working
var readCfr = nodesUnique.insert(docDeeper);
nodesUnique.update(readCfr);
console.log(db.listCollections());
console.log(nodesUnique.by("technicalPath", "/2/1/1/1/"));

//Insert records in our index way of working
var readCfr2 = nodesIndex.insert(docDeeper2);
nodesIndex.update(readCfr2);
console.log(db.listCollections());
console.log(nodesIndex.find({technicalPath: "/2/1/1/1/" }));
```

**Comment by tvald** [comment]
It seems that `insert()` injects metadata directly into the object you provide to it, without creating an internal copy. (@willaaam In your first example, try `var docDeeper2 = Object.assign({}, docDeeper);`.)

Sounds like a bug to me. If there are performance reasons why `insert()` doesn't shallow clone, documentation should warn about the side effects.

Relatedly, are the results from `by()` / `find()` / etc... shallow-cloned? If not, it would be possible to directly modify values (including internal fields like `$loki`) without an `insert()`.

**Comment by RobertGary1** [comment]
When you create the collection it’s a documented option if you want to clone the inserts and results. 
Similar when you call data() on your results set there is an option to clone and an option to remove metadata.

**Comment by tvald** [comment]
@RobertGary1 Thanks, you're correct.

https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html#addCollection

> Name | Type | Attributes | Default | Description
> -- | -- | -- | -- | --
> clone | boolean | <optional> | false | specify whether inserts and queries clone to/from user
> cloneMethod | string | <optional> | 'parse-stringify' | 'parse-stringify', 'jquery-extend-deep', 'shallow, 'shallow-assign'

@willaaam try
```
var nodesUnique = db.addCollection('nodesUnique', { unique: ['technicalPath'], clone: true, cloneMethod: 'shallow' });
var nodesIndex = db.addCollection('nodesIndex', { indices: ['technicalPath'], clone: true, cloneMethod: 'shallow' });
```

**Comment by tvald** [comment]
Don't want to stray too far off topic, but I think only `collection.chain()` has the option of cloning retrieved data? It looks like `collection.by()` and `collection.where()` will always return direct references to internal objects.

(Probably intended, but unexpected to API consumers and perhaps worth documenting more clearly?)
