### ISSUE TITLE
$loki id

### ISSUE THREAD

**Issue by manuwall** [techfort/LokiJS#760]
Is there a possibility to select the $loki -id and pass it into a variable?

Best regards
Manu

**Comment by cyclux** [comment]
Yes, if you mean to query the collection by $loki and pass the result:
```
var users = db.addCollection("users");
var resultObj = users.insert({username:"Heimdallr"});

// now that our object has been inserted, it will have a $loki property added onto it
var heimdallr = users.get(resultObj.$loki);
```

See https://github.com/techfort/LokiJS/wiki/Indexing-and-Query-Performance
