### ISSUE TITLE
lokijs find equivalent of oracle %

### ISSUE THREAD

**Issue by informvisu** [techfort/LokiJS#761]
http://127.0.0.1:8000/list/device/d/*/*/*/*

[{"name":"device1","make":"cisco","model":"ME-3400","os":"12.*","path":"root","jumpHost":"1.2.3.4","meta":{"revision":0,"created":1556057124787,"version":0},"$loki":1}]

It is returning the above where it suppose not to. How to wildcard search for asterisk. 

```
app.get('/list/device/:name(*)/:make(*)/:model(*)/:os(*)/:path(*)',(req, res) => {
	var name = req.params.name.replace('*', '.*');
	var make = req.params.make.replace('*', '.*');
	var model = req.params.model.replace('*', '.*');
	var os = req.params.os.replace('*', '.*');
	var path = req.params.path.replace('*', '.*');
	var neColl = networkDb.getCollection('network_element');
	var docs = neColl.find({
		'$and': [
			{name: {'$regex': name}},
			{make: {'$regex': make}},
			{model: {'$regex': model}},
			{os: {'$regex': os}},
			{path: {'$regex': path}}
		]
	});
	res.send(JSON.stringify(docs));
});
```

**Comment by obeliskos** [comment]
Sorry for the delay, that would likely be the $regex operator. Info on operators [available here](https://github.com/techfort/LokiJS/wiki/Query-Examples).
