### ISSUE TITLE
In-Memory database

### ISSUE THREAD

**Issue by manuwall** [techfort/LokiJS#762]
Hello

are there any examples of how creating a in-memory database, creating collections for it, inserting data to the collections?

At the moment I have created a database in which I insert all my data into a json-file. But that's not my goal. I want the data to disappear after the browser got closed.

Thanks for any replies.
Best regards

**Comment by obeliskos** [comment]
This should work :
```javascript
var db = new loki("temp", { 'env': 'MEMORY' });
```
