### ISSUE TITLE
Insert class instances and deserialize/ inflate objects into class instances

### ISSUE THREAD

**Issue by boedy** [techfort/LokiJS#772]
In the feature summary on lokijs.org is mentionend:
> Insert class instances and deserialize/ inflate objects into class instances

What is meant by this exactly and how would it work? Based on that line I'm assuming one can store class instances. If so how does the object hydration work?

If someone could provide an example, that would be really helpful!

**Comment by obeliskos** [comment]
@techfort originally created that capability and, while there is no formal documentation that I know of, there is [his unit tests for it](https://github.com/techfort/LokiJS/blob/master/spec/generic/typed.spec.js) which may help you.  If not let me know and I can try to clarify.
