### ISSUE TITLE
findOne

### ISSUE THREAD

**Issue by mprokopowicz** [techfort/LokiJS#78]
Why does the findOne returns Ruleset, not found document or null if not found?

**Comment by techfort** [comment]
It's probably worth considering returning the record directly instead of the resultset. I'll have a quick conversation with @obeliskos  about this.

**Comment by obeliskos** [comment]
findOne should return the first document matching your criteria, or null if none exist.  If it is returning a resultset for you, it is a bug so please provide test case.

I just ran a quick test and it seems to work as I described above for me.

**Comment by Badisi** [comment]
I've made a plunker to reproduce this issue.
('findOne' is returning a Resultset instead of a document)

Plunker: http://plnkr.co/edit/an4zfquYf6kl1hWPRMcX

**Comment by techfort** [comment]
I can't load the plunker, is it possible it's private or the url is wrong?

**Comment by Badisi** [comment]
Is this one better: http://plnkr.co/edit/LgcaKd?p=info ?

**Comment by techfort** [comment]
Yes, perfect. Now that's weird, will investigate asap.

**Comment by obeliskos** [comment]
I ran the test case and yea there was a bug when doing findOne on indexed property which is now fixed.

Thanks!

**Comment by techfort** [comment]
Thanks @obeliskos ! closing this.
