### ISSUE TITLE
Can we cut a new release?

### ISSUE THREAD

**Issue by RobertGary1** [techfort/LokiJS#784]
We've had some important fixes since January. Can we cut a new release?

**Comment by CaitlinWeb** [comment]
@techfort @stefanprobst @obeliskos Is master currently production-ready? As OP said, can a new release be published?

**Comment by techfort** [comment]
i can prepare a new release if @obeliskos is also ok with it

**Comment by RobertGary1** [comment]
bump

**Comment by techfort** [comment]
i released 1.5.7 - let me know if all went well

**Comment by stefanprobst** [comment]
looks like npm is still at 1.5.6

**Comment by stefanprobst** [comment]
thanks! all :+1:

**Comment by RobertGary1** [comment]
Thanks. This works great. I see the update in npm although it doesn't show up under releases in github. Not sure if that's normal..
https://github.com/techfort/LokiJS/releases

**Comment by techfort** [comment]
@RobertGary1 yes you are right, i tagged the release but never pushed it. It's up now, thanks for flagging that. Boy what a day i had.
