### ISSUE TITLE
collection.clear() does not emit an event?

### ISSUE THREAD

**Issue by sp00x** [techfort/LokiJS#785]
After eventually figuring out had to enable change tracking to get the events working, I noticed that while .remove(), .insert() and .update() emits events you can listen to with .on() - the collection.clear() method does not appear to emit any events? Shouldn't it?

**Comment by devleaf-matt** [comment]
Hi @sp00x,

Sorry I can't be of help to your question, I'm just curious how you got the `.on()` method working as my current code of: `this.db.on(['delete', 'insert', 'update'], event => console.log(event));` currently doesn't emit any output. Would it be possible to provide a sample of how you got this working here, as the docs aren't really the best. A big thanks for your help in advance!

**Comment by sp00x** [comment]
@devleaf-matt As mentioned in the ticket I had to enable change tracking to get it working, i.e. you add the collection with `{ disableChangesApi: false }` or something like that as described on https://github.com/techfort/LokiJS/wiki/Changes-API .. But of course that adds a whole bunch of other stuff going on

**Comment by sp00x** [comment]
Closing the ticket still didn't fix the issue :P
