### ISSUE TITLE
TS typings error?

### ISSUE THREAD

**Issue by cafeoh** [techfort/LokiJS#787]
There seem to be some TS typing error. I frequently hit a wall where the methods/members/return values don't match what's actually sent. I only remember of a couple instances, but it seems to happen fairly frequently, so I'm left wondering if perhaps pebkac.

For example the `listCollections` method returns an object containing `{name, type, count}`, but typescript says that it returns a list of collections (`Collection<any>[]`)

Another issue (that might or might not be related, not sure) I've found is that adding items into a collection fails unless `"disableMeta"` is set to `true`, otherwise it tries to write `obj.meta.version` directly into the object, which fails since `obj.meta` isn't defined in the object that I pass it. Perhaps another method is to be used, or I'm meant to create another object, but the typings indicate `any`, and the manual creation of an object isn't detailed anywhere that I saw.

So I'm wondering, am I using the wrong typings? Are they not up to date? Am I doing something wrong?

With Love,
Cafe

**Comment by erik-helmers** [comment]
+1, you're right about the `Loki.listCollections` (just checked) but I don't know if it's more of a DefinitelyTyped issue.

However, about the `obj.meta.version` error : you're probably using the`Collection.add()` method, which name is a bit misleading... you should use `Collection.insert()` instead.

**Comment by erik-helmers** [comment]
Also there's a problem : every interface is exported without a namespace, so the types pollute the global namespace in violation of general best practices. But fixing this may be breaking changes. How do we do ?

**Comment by nmocruz** [comment]
I have a problem with branchResultset() om the DynamicView, it doesn't set the first parameter as optional
