### ISSUE TITLE
Reuse existing id instead of $loki

### ISSUE THREAD

**Issue by mprokopowicz** [techfort/LokiJS#79]
My use case for LokiJS is to gather lot of messages in browser coming from server over websocket and apply dynamic views for this messages.

All of messages coming from server has their unique id. It will be great to have an option to tell Loki to use existing ids instead of creating new $loki id.

Now if i want to get doucment by my existing id, i have to do this way:

```
var item = collection.find({myId: 99})[0];
if(item) {
   //do something with found document
}
```

if I understand the documentation good, the Collection#get method is faster in such case.
Also if use Collection#find, then Loki have to check whole collection even, when it already found first document.

**Comment by techfort** [comment]
get() would be faster but if you index a field the performance hit will be on building the index and after that it should be nearly as fast as get() (*nearly*). As LokiJS is capable of upwards of 300k ops/s on indexed find you should be absolutely fine. Let me know if this is the case. If find() is not as fast as you'd like it to be then I have a solution in mind which will take me a few days to implement though.

**Comment by mprokopowicz** [comment]
I mentioned performance, but it's really abut syntax / code style.

Lets assume that my server sends me to browser following message:

```
{
  msgId: 1,
  name: "loki"
}
```

and 

```
{
  msgId: 2,
  name: "thor"
}
```

Later, when some name has been changed server sends:

```
{
  msgId: 1,
  name: "Sigyn"
}
```
So on every message I have to check if it already exists and i should just update the document or its a new messege and I should insert it to collection:

```
    function insertOrUpdate(incomingMessage) {
      var existingState = collection.find({stateId: incomingMessage.stateId})[0];
      if (existingState) {
        angular.extend(existingState, incomingMessage);
        collection.update(existingState);
      } else {
        collection.insert(incomingMessage);
      }
    }
```

I don't feel very good with this piece of code: ` collection.find({stateId: incomingMessage.stateId})[0]`

I saw in code, that loki checks $loki property to check if document was already inserted to collection, so if I can reuse my `stateId` the above insertOrUpdate function could be simpler?

**Comment by techfort** [comment]
Ok that's a very precise use-case which I can analyze and see if there's a case for implementing a library change (as it would be useful to everybody using LokiJS). I will include it in the 1.2.0 milestone so it's addressed in the next few days. Straight off the top of my head i can see a mongodb-like `upsert` forming.

**Comment by obeliskos** [comment]
You could use findOne() which will return first object matching that criteria or null if none exists.

Possibly the general use case you are describing might fit in with a cache mode feature we have considered.  Cache might normally might be age based or mru based, but maybe we could also allow it to enforce uniqueness of a user column and kick out any old values.

For performance purposes user supplied id can never replace loki id internally for get() since we guarantee linear order for get() binary search without needing to sort (data is already sorted by $loki).

**Comment by techfort** [comment]
We had a quick conversation about this particular feature. The implications of fiddling with indexes are heavy, as they affect performance and stability of Loki. So we will keep this issue open and defer it to the 1.3.0 Milestone, which is tentatively due in April. We are working on the caching features that @obeliskos  mentioned, so this discussion will come up again.

**Comment by techfort** [comment]
@mprokopowicz we're about to release 1.3.0, which include UniqueIndex. A unique index allows faster retrieval, and works as a constraint (you cannot insert an object with the same unique value or update an object to have the same value of another one). Effectively, it makes every field you index as unique as fast as a primary key. This to me resolves this issue (in that you can use your own custom key as unique, and get up to 1.1M ops/s according to benchmarks). Let me know if this is not the case, meanwhile I am closing this, thanks for bringing it up!

**Comment by mingfang** [comment]
I found this issue by searching for ```upsert```.
Are there plans to implement upsert?

**Comment by techfort** [comment]
There are, I'll create an issue for it and include it in v1.4

**Comment by scorpnode** [comment]
any news on upserts
