### ISSUE TITLE
Web interface for LokiJS

### ISSUE THREAD

**Issue by pixari** [techfort/LokiJS#793]
Hello everybody!

Since a web interface for LokiJS is missing, I thought it could be a good idea to start working on it.

The stack will be: 
- VueJS (front-end)
- Vuetify (component library for VueJs)
- Jest (unit test)

I have in mind something like PhpMyAdmin, but for LokiJs obviously. :)

In the next days I'll prepare and share the project.

In the meantime feel free to add issues and/or contribute to the documentation.

The brand new repository is here: https://github.com/pixari/LokiJSAdmin 

Thanks and best regards!

**Comment by mauriciovalencia** [comment]
I saw your init project, by the way, you'll use Vue-Cli base tool?.

**Comment by pixari** [comment]
Hi @mauriciovalencia!

Yes, I pushed right now a draft. => https://github.com/pixari/LokiJSAdmin

I will use the vue-cli 3. 

I am wondering if it would be better to write a LokiJS plugin for Vuex before proceeding (or just as part of the project). 

It would be nice to have kind of interface between Loki and the store.

**Comment by techfort** [comment]
hey @pixari you've got all my encouragement! this is an awesome idea. I saw some implementation of lokijs as backend for a vuex store and it seemed really nice, there's even an ORM i just discovered: https://www.npmjs.com/package/@atlascity/vuex-orm-plugin-lokijs 
In any case, i'm here for questions if you need me, although my time is very limited.
