### ISSUE TITLE
Documentation does not list emitted events

### ISSUE THREAD

**Issue by thw0rted** [techfort/LokiJS#795]
BLUF: I had to dig around in the source to find out what values are valid to pass to `db.on()`.

For example, I have a singleton database instance that I use in several modules.  The singleton loads the database from file at startup, but if I try to read a collection immediately in a consuming module, there's no data, because the load isn't finished.  Since I'm not in the module that's calling `loadDatabase()`, I can't pass a callback to that method.

This is easy to solve by listening to the "loaded" event, but nowhere in [the docs](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html) does it say that this event exists.  We see that `Loki` implements `LokiEventEmitter` so it has an `on()` method, but we don't know what events it will emit.

The [JSDoc usage notes](https://devdocs.io/jsdoc/tags-event) give this example of an `@event` tag:

````js
    /**
     * Snowball event.
     *
     * @event Hurl#snowball
     * @type {object}
     * @property {boolean} isPacked - Indicates whether the snowball is tightly packed.
     */
````

You can also use `@fires` / `@emits` to annotate methods that (sometimes) cause those events to be emitted.

**Comment by Pictor13** [comment]
Nice suggestion.
I just had the same problem, with finding documentation about the available events.

**Comment by thw0rted** [comment]
Gah, I was on vacation and just got back to find this was flagged a day or two after I left, then closed halfway through.  Is there a way to get this issue re-opened or do I need to file a new one?  @techfort ?

**Comment by techfort** [comment]
i am up the walls but i will try to get this done asap

**Comment by thw0rted** [comment]
"Activity"!  (Still relevant.)

**Comment by techfort** [comment]
gotta find time to address this, damn

**Comment by thw0rted** [comment]
Marco?

**Comment by thw0rted** [comment]
Polo!

**Comment by Grewer** [comment]
I only found 2 events: `loaded` and `close`, luckily we can add custom events

You can also use the collection event:
```
close
delete
error
flushbuffer
insert
pre-insert
pre-update
update
warning
```

use like:
```
coll.on('update', (event) => {
        console.log('coll change', event)
})
```

**Comment by thw0rted** [comment]
Guess it's just a "more activity" kind of day?

**Comment by bendavis78** [comment]
@Grewer there are quite a few events emitted in loki, just grep for `emit(` in `lokijs.js`:

```

      this.emit('warning', 'collection ' + collectionName + ' not found');
      this.emit('close');
              self.emit('loaded', 'database ' + self.filename + ' loaded');
              self.emit('loaded', 'empty database ' + self.filename + ' loaded');
              self.emit('loaded', 'database ' + self.filename + ' loaded');
      this.emit('rebuild', this);
        this.emit('filter');
      this.emit('sort');
      this.emit('sort');
      this.emit('sort');
        this.emit('rebuild', this);
      this.emit('filter');
      this.emit('filter');
          self.emit('rebuild', self);
        this.emit('rebuild', this);
        this.emit('pre-insert', doc);
      this.emit('insert', results);
        this.emit('error', err);
        this.emit('pre-insert', obj);
        this.emit('insert', returnObj);
        this.emit('pre-update', doc);
        this.emit('update', returnObj, oldInternal);
        this.emit('error', err);
        this.emit('error', err);
            this.emit('delete', this.data[positions[idx]]);
        this.emit('error', err);
        this.emit('delete', arr[0]);
        this.emit('error', err);
```
