### ISSUE TITLE
Is Lokijs.org website gone?

### ISSUE THREAD

**Issue by RobertGary1** [techfort/LokiJS#797]
Tried on a couple networks and get a message that it no longer resolved. Is it just on my end?

**Comment by diomed** [comment]
not just on your end. it's gone. 

maybe they forgot to renew hosting or smth??

**Comment by chitombo** [comment]
@techfort could you migrate the Lokijs.org code to Github? Or open a Patreon for Lokijs? 
I really enjoy using Lokijs and found the website very useful as a quick reference. I am willing help pay for its hosting :) and I am sure others who find it useful would be interested in helping as well.

**Comment by RobertGary1** [comment]
The website is on github. I download it and am running it locally now.

**Comment by chitombo** [comment]
I had not noticed that it was already on github, downloaded it now as well and will run locally for now, but I am still willing to help get it hosted online again 👍

**Comment by techfort** [comment]
sorry guys, had to cut that expense because i was running it on digital ocean and having no income from lokijs it has cost me 6euro a month for the last 5 years. That's at least 70 beers. If you want to get it up and running i'm more than willing to help, I was thinking of setting it up as a github pages thing, seeing as it's free.

**Comment by samrat-bhandari** [comment]
@techfort Firebase Hosting is a great free option to host static content like documentation etc. Is it possible to host the front-end code from digital ocean in a free firebase project?

**Comment by benoror** [comment]
@techfort Github pages is free, also Netlify, happy to help if needed

Also, you should consider https://github.com/sponsors to fund your work pal!

**Comment by txxia** [comment]
This works fine for me https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html

**Comment by JohnMunsch** [comment]
I've rearranged a couple of things in the root of the project and submitted a pull request so the old site can be redeployed on GitHub Pages with almost no effort.

**Comment by Bandito11** [comment]
> sorry guys, had to cut that expense because i was running it on digital ocean and having no income from lokijs it has cost me 6euro a month for the last 5 years. That's at least 70 beers. If you want to get it up and running i'm more than willing to help, I was thinking of setting it up as a github pages thing, seeing as it's free.

I don't see why you shouldn't do this lmao. I forgot this was a thing. I may move my app from Firebase to github hosting because I don't think I will get that much traffic anyways.

**Comment by techfort** [comment]
Hey guys, i moved the docs to github pages thanks to @JohnMunsch 's work.
Edited the link in the tagline, i think we're good now. The website itself
did not really add anything to the docs, and the sandbox is still linked in
the read me.
