### ISSUE TITLE
Make "meta" optional

### ISSUE THREAD

**Issue by mprokopowicz** [techfort/LokiJS#80]
Is adding "meta" properties essential to LokiJS?
If not - it will be great to make it optional.

**Comment by techfort** [comment]
That's a nice idea. I will inspect if there are features that heavily rely on meta, and if a quick work-around can be done to achieve this.

**Comment by techfort** [comment]
There's quite a few features relying on meta at the moment. We will definitely look into the feasibility of this but for now it will have to be postponed to 1.3.0.

**Comment by KimSchneider** [comment]
Meta, or any other additions that loki does, should reside under the $loki property. Would be cool for the next version.
{
 $loki : { id : 1, meta : {  } },
 name : 'Hugo',
 meta : 'He is awesome'
}

**Comment by techfort** [comment]
@KimSchneider  @mprokopowicz sorry for addressing this a bit late but i have been very busy. So here's the thing: as @KimSchneider points out, the whole meta should be under $loki. In fact, the plan for LokiJS v2.0 is to only have the $loki id in the object itself and store meta for the object in a sort of parallel collection, so not to pollute the original object beyond the simple id. However, this would be too much of  a breaking change for LokiJS users, as many users are using the `updated` property of `meta` to apply a last-write-wins logic in distributed applications. I suppose it wasn't the best design decision at the time, but I am afraid this will have to wait for v2.0 which is a complete rewrite.
