### ISSUE TITLE
"in" / "oneOf" operator 

### ISSUE THREAD

**Issue by mprokopowicz** [techfort/LokiJS#81]
I would really like operator, that checks if document property matches one of provided array value.

For example for document 
```
{
 int: 5
}
```

I want to do `collection.find({int: {$in: [3,4,5,6]})`

**Comment by techfort** [comment]
That's also a good idea. You can definitely do that with a Resultset at the
moment, by doing something like
```javascript
messages.chain().where(function (obj) { return [3,4,5,6].indexOf(obj.int)
!= -1; }).data()
```
but yeah a utility method would come in handy.

**Comment by obeliskos** [comment]
We already have $in operator.    Maybe i am missing something but have you tried your example above?

**Comment by techfort** [comment]
You know- I did think that! It was a very recent addition. I've got to get
more sleep. Closing this, feel free to re-open if it's not what you wanted
exactly.

**Comment by mprokopowicz** [comment]
I seed it in code :)
Needs to be documented.
