### ISSUE TITLE
Dot notation in idicies

### ISSUE THREAD

**Issue by mprokopowicz** [techfort/LokiJS#82]
It's not clear for me if it is legal to use dot notation in indices?

```
 var collection = new loki.Collection('HMStatesCollection', {
      indices: ['stateId', 'cellAddress.elementId', 'categoryId']
    });
```

**Comment by obeliskos** [comment]
Dot notation is not currently supported in indices.  Could consider adding it at some point in the future once we prioritize roadmap.

**Comment by techfort** [comment]
A good idea - will create a 1.3.0 Milestone and add it in there. I don't want to rush anything that deals with indexes, there are always performance implications as well as functionality ones involved when working with indexes.
