### ISSUE TITLE
Bug on removeWhere

### ISSUE THREAD

**Issue by techfort** [techfort/LokiJS#83]
In reference to this, the dynamic view seems to keep a zombie "undefined" document in it after its removal.

**Comment by techfort** [comment]
This is quite weird. The underlying collection is intact, so is the view, but instead of removing the element from the view an "undefined" zombie element is left in. I need to revise the mechanism to remove documents, especially in a loop where they may cause strange behaviour.

**Comment by obeliskos** [comment]
is your removeWhere invoking the DynamicView.removeDocument() which -is- raised from collection.remove() ?

**Comment by techfort** [comment]
Ok - this was a headwrecker. The bug was not with lokijs, it was with the fact that i copied the latest minified version of lokijs, which had a couple of important bug fixes missing and a different (broken) implementation of removeWhere.
The plunker now works correctly: http://plnkr.co/edit/rye2uw1rhncOmNxbMfnh?p=preview sorry about that. Closing this.
