### ISSUE TITLE
Question: is there paging support?

### ISSUE THREAD

**Issue by caligo-erik** [techfort/LokiJS#830]
I would like to display a limited number of lines, e.g. 100.
Is there any support of returning query results "page by page"?

Or do you have any suggestions on how to implement this 'manually' with LokiJS?

**Comment by aboltunov-r7** [comment]
Something like this should handle what you want.
`yourCollection.chain().find().offset(itemsPerPage * (currentPage - 1)).limit(itemsPerPage).data(),`

**Comment by caligo-erik** [comment]
> Something like this should be doing what you want.
> `yourCollection.chain().find().offset(itemsPerPage * (currentPage - 1)).limit(itemsPerPage).data()`

Something like this should work, my problem with this approach is the memory consumption. In case of very large collections, the first result set returned by chain().find() might still be very large.
For multi-user-environments, this won't scale really well.

A built-in linear index would resolve this, hence my question in the first place.
