### ISSUE TITLE
Collection got empty after refresh browser

### ISSUE THREAD

**Issue by dohoangn** [techfort/LokiJS#838]
I have Lokijs in an Vuejs app in Chrome browser.
I just use standard way to create  db
```
let db = new Loki("test", {
      autoload: true,
      autosave: true,
      autosaveInterval: 10,
      adapter: new LokiIndexedAdapter()});
```

Creating a collection, inserting item into collection, everything working fine. However when refreshing browser, all records in collection get lost even I wait few minutes after saving

**Comment by dohoangn** [comment]
Having these options seem to persist data 
autosaveInterval: 1000,
throttledSaves: false,

**Comment by balain** [comment]
Same problem here! Any idea?
