### ISSUE TITLE
Using DynamicView.resultdata

### ISSUE THREAD

**Issue by mprokopowicz** [techfort/LokiJS#84]
I'm using undocumented "resultdata" property of DynamicView, because it fits very good my needs (One reference to always up-to-date array).

DynamicView.data() returns always a new array.

I've got 2 questions:
1. It is safe to relay on resultdata in persistent views?
2. Why does the resultdata it's not sorted? (I've got simplesort applied on my DynamicView)

**Comment by obeliskos** [comment]
Currently, persistent views only sort on data() call to avoid thrashing the view when many inserts/updates are being performed.

I will be revisiting dynamic views and should make improvements to them within the next release timeframe.  This might be accomplished using a throttled resort timer as option and/or new events to tap into.

**Comment by mprokopowicz** [comment]
@obeliskos Thx!
What about using resultdata? It's safe or am i touching loki internals which may change?

**Comment by techfort** [comment]
For now I wouldn't do it unless you don't care so much for sorted data. And yes if you apply changes to resultdata you'll get a big sign saying "At your own peril" :)

**Comment by mprokopowicz** [comment]
Got it. 
I will switch to data() for now.
