### ISSUE TITLE
findOne failing in a particular scenario

### ISSUE THREAD

**Issue by Badisi** [techfort/LokiJS#85]
I have a scenario where I'm dynamically trying to create and update documents while looping through an array of objects.
In this scenario, findOne is working fine the first time it is called but next it will always return the document from the previous call.

I've tried to make a very simple example available here: http://plnkr.co/edit/fD6vnv

I did not investigate much but it seems that the issue is within the **calculateRange** method.

Thanks

**Comment by techfort** [comment]
I'm sorry if this sounds stupid but i would have thought you would do this:
`var result = brandCollection.findOne({'brand':car.brand});` instead of 
`var result = brandCollection.findOne({'id':car.brand});`, as far as i can see ids are completely different from brands.
Again sorry if i misunderstood the issue.

**Comment by Badisi** [comment]
I'm sorry, I agree that 'id' could be misleading (it was just meant for the example).
I've updated the plunker and replaced 'id' by 'brand' as you suggested.

Now, as you can see in the log, after we successfully retrieve a document with findOne, the next calls will not always return the objects we were looking for.

**Comment by techfort** [comment]
Ok I'll look into this
/cc @obeliskos

**Comment by obeliskos** [comment]
I think its a bug he found. 

loki.js, line 1583 should be : 
return t[index.values[seg[0]];

I will update later today or you can try updating and see if that fixes it for you.  If that's not it let me know.

Problem exists in edge case where doing findOne on indexed column.

Thanks for reporting.

**Comment by Badisi** [comment]
Thanks for your prompt reply.
This seems to have fix both the issue in the plunker and in my personal use case.
Again thanks for your hard work to both of you !

**Comment by techfort** [comment]
@obeliskos thanks a lot for squashing that bug. And thanks @Badisi for the kind words. Closing this.
