### ISSUE TITLE
 Loki IndexedDb adapter is not exported

### ISSUE THREAD

**Issue by ajmas** [techfort/LokiJS#851]
Looking at `src/lokijs.js` I see that the  Loki IndexedDb adapter is not exported. At the moment in ES6 code I can do:

```
import Loki, { LokiLocalStorageAdapter } from 'lokijs';
```

but I can't do the same for `LokiIndexedDbAdapter`. This would need a change so that in `src/lokijs.js`:

```
  Loki.LokiMemoryAdapter = LokiMemoryAdapter;
  Loki.LokiPartitioningAdapter = LokiPartitioningAdapter;
  Loki.LokiLocalStorageAdapter = LokiLocalStorageAdapter;
  Loki.LokiIndexedDbAdapter = LokiIndexedDbAdapter;
  Loki.LokiFsAdapter = LokiFsAdapter;
```

Though given the code structure, that would mean bring in the code from `src/loki-indexed-adapter.js`.  One question here, is whether there is any reason why there is no importing of functionality via a `require`?

**Comment by ajmas** [comment]
Actually it turns out that we can do this instead:

```
import LokidIndexedAdapter from 'lokijs/src/loki-indexed-adapter';
```

**Comment by thomaschampagne** [comment]
+1

**Comment by patarapolw** [comment]
+1
