### ISSUE TITLE
How to check if a database exists?

### ISSUE THREAD

**Issue by mikelgmh** [techfort/LokiJS#868]
What's the way to check if a database exists?

**Comment by thomasdingemanse** [comment]
I have a similar issue: I've created a database with `new Loki('filename.db')`, but the file does not appear when I run my server and there is no error output either, even with `verbose: true`.

```js
const path = require('path')
const Loki = require('lokijs')

const filename = path.join(__dirname, 'filename.db')

const datastore = new Loki(filename, {
  verbose: true,
  autoload: true,
  autosave: true,
  autosaveInterval: 1
})

const test = datastore.addCollection('test')

test.insert({ key: 'value' })
```

I've added `autosave` and `autosaveInterval` in case LokiJS only writes to the file when collections are modified, but without those options it doesn't work either. Inserting data into the in-memory collection works fine, it's just the persistence part that does not.
