### ISSUE TITLE
question: proper way to read whole collection's data

### ISSUE THREAD

**Issue by work67** [techfort/LokiJS#871]
Hi,
which is better:

1. var array_of_all_items = collection.data

or

2. var array_of_all_items = collection.find()

?

I need to know the proper way to load ALL items from a collection into a variable.
The lokijs docs explain how to query a collection, but what is the best query for "getAll" ?

**Comment by robertdavid010** [comment]
> Hi,
> which is better:
> 
>     1. var array_of_all_items = collection.data
> 
> 
> or
> 
>     1. var array_of_all_items = collection.find()
> 
> 
> ?
> 
> I need to know the proper way to load ALL items from a collection into a variable.
> The lokijs docs explain how to query a collection, but what is the best query for "getAll" ?

If the data is equivalent, then wouldn't the first case to directly access the data be more computationally efficient then calling a method to get the same data?
