### ISSUE TITLE
loadJSON error

### ISSUE THREAD

**Issue by LzMiguel** [techfort/LokiJS#880]
I can't load my database.

`var read = require('read-file-utf8');
var loki = require('lokijs');
var db = new loki('db.json');
var data = read(__dirname+'/db.json');
db.loadJSON(data);
console.log(db);`

![image](https://user-images.githubusercontent.com/58833404/106187284-2e949980-6184-11eb-89da-f6872d5bcb8d.png)

My 63 is "db.loadJSON(data);"

**Comment by StudentESE** [comment]
what about the JSON-File ?
