### ISSUE TITLE
LokiFSStructuredAdapter autosave not working

### ISSUE THREAD

**Issue by StudentESE** [techfort/LokiJS#883]
> @Mika83AC
> ```js
> const loki = require('lokijs');
> const path = require('path');
> const LokiFSStructuredAdapter = require('lokijs/src/loki-fs-structured-adapter');
> 
> let dbFile = path.resolve(__dirname, './test-data.json');
> 
> let Db = new loki(dbFile, 
>   { 
>     verbose: true,
>     autosave: true, 
>     // autoload: true,
>     autosaveInterval: 1000,
>     adapter: new LokiFSStructuredAdapter(),
>     // autoloadCallback: databaseInitialize,
>     autosaveCallback: () => { 
>       console.log('autosaved db'); 
>     }
>   }
> );
> 
> loadDb(({Db, test})=> {
>   console.log('db loaded', Db);
>   console.log('entries in db collection test', test.find());
> });
> ```

```console.log(Db);``` shows  autosave: false

```
persistenceMethod: 'adapter',
  persistenceAdapter: LokiFsStructuredAdapter {
    mode: 'reference',
    dbref: {
      filename: 'db.json',
      collections: [Array],
      databaseVersion: 1.5,
      engineVersion: 1.5,
      autosave: false,
      autosaveInterval: 5000,
      autosaveHandle: null,
      throttledSaves: true,
      options: [Object],
      persistenceAdapter: null,
      verbose: false,
      events: [Object],
      ENV: 'NA'
    },

```
How do I get it enabled ?
is there a path I can change the value of options (switching autosave on/off) while running?
like ...
```db.persistenceAdaper['LokiFsStructuredAdapter'].dbref['autosave] = true;```
also manually save the collection doesn't trigger the ```autosaveCallback``` ... but showing the content of the memory db says it gots new entries.

I like to autosave to json. Please help :-)

_Originally posted by @StudentESE in https://github.com/techfort/LokiJS/issues/563#issuecomment-818819120_

**Comment by GabrielGab** [comment]
Hi  there , I am doing some testing to get this library into a project, have you received some answer for this issue or got some workaround by yourself ?
Thanks !

**Comment by StudentESE** [comment]
no, seams like there is no further support for this project.
