### ISSUE TITLE
Is there any way to wait for an insert to complete?

### ISSUE THREAD

**Issue by nabils** [techfort/LokiJS#886]
Insert is currently async but it does not return a promise. As far as I can see there is no way to know when an insert of multiple records to a collection has completed? Is this possible?

Thanks

**Comment by nabils** [comment]
It does seem to be sync actually. Closing this

**Comment by jaandrle** [comment]
@nabils Exactly operations above [Collections](http://techfort.github.io/LokiJS/Collection.html) are synchronous. Saving function [`saveDatabase`](http://techfort.github.io/LokiJS/Loki.html#saveDatabase) can be asynchronous and accepts callback.
