### ISSUE TITLE
[Question] Where is data stored when using LokiIndexedDBAdapter?

### ISSUE THREAD

**Issue by robertdavid010** [techfort/LokiJS#888]
I am using this adapter to persist data from a browser extension/plugin instance of LokiJS. There is only 1 table in the indexedDB "LokiCatalog" when I explore it using dev tools (Application/Storage/IndexedDB. There records are the instance configuration within which the first key/value pair is `"filename": "loki.db"` which leads me to think that the data (which I can still persist/query using the adapted db) is still being stored in a file?

### Application tab in Devtools

![image](https://user-images.githubusercontent.com/2262763/123769454-9da82280-d8c9-11eb-9fc1-f9209b001ca7.png)

### Showing persisted record in console

![image](https://user-images.githubusercontent.com/2262763/123769501-a7ca2100-d8c9-11eb-82fb-f5234fb313d7.png)

What should I expect to see when inspecting the Application -> Storage -> IndexedDB when using the IndexedDB adapter to persist data using LokiJS?

**Comment by cepm-nate** [comment]
In your first screenshot it should be within the 'val' field. Here's what my paged storage looks like:
![image](https://user-images.githubusercontent.com/10284464/141214004-e77872e8-bf4e-46c4-bac4-4a993866e49a.png)
