### ISSUE TITLE
{} and getAll

### ISSUE THREAD

**Issue by KimSchneider** [techfort/LokiJS#90]
Hey,

it would be much easier to handle programatically generated find objects if a {} would result in a getAll. At the moment this seems to be the case if you pass null to find only.

I wanted to fix the code myself but was not sure if that would break anything.

Regards,
Kim

**Comment by obeliskos** [comment]
No problem, I believe the change I just committed should perform as described.  If not you can submit pull request or describe further.

Thanks,
Dave

**Comment by KimSchneider** [comment]
Alright, thanks! :)
