### ISSUE TITLE
File system persistence issue (Node.js)

### ISSUE THREAD

**Issue by MatiasFito** [techfort/LokiJS#92]
I'm running a little node.js server that creates a little LokiJS database and then loads it back. My problem is that when i try to load the database from the file, the collections attribute is empty even though i can see the file created and the collection and it's data is there, i have screens of my code, so you can see if something is wrong but the process is very simple.

![Image of save method](http://puu.sh/gupBZ/68675f4b16.png)

![Image of load method](http://puu.sh/gupCG/11918d1323.png)

This is the loki.json file that is in the same directory and is created by the save method

![Image of loki.json](http://puu.sh/gusLW/fd4688a5e3.png)

The console.log(lokiDatabase) shows collections: []. Curiously the loki.json shows "persistenceMethod":null,"persistenceAdapter":null in that same file where everything is actually saved.

![Image of loki.json 2](http://puu.sh/gusMU/f95fe79bb8.png)

 I'm sure i have a syntax error somewhere but i couldn't find any examples of "saving to file system" and then "loading from that same file". Thanks in advance and sorry if this is too noob.

**Comment by techfort** [comment]
Hey Matias,

can you take a look at this :
https://gist.github.com/techfort/66898d95ac8ff133720d
As node,js does i/o asynchronously you may be trying to log before the
database is loaded
If not let me know and i'll look into the issue.
Joe

**Comment by MatiasFito** [comment]
Hi Joe, thanks for taking the time to help me. I tried with the Gist you sent me, i had to change saveToDisk() to saveDatabase() couse it said it didn't have souch method.

The console output was not the expected, it showed only the console.log(users.data) but the console.log(users2.data) didn't output anything (like it was empty). I took a screenshot of it:

![Image1](http://puu.sh/guGXB/265bccfac4.png)

I did a console.log(db2) to see how it was loaded, this was the output maybe it helps to solve the mistery:

![Image2](http://puu.sh/guH2n/0558a88ee2.png)

The test.json is fine just like the last time it hold the collection and documents.

I'm running node.js on a windows 8 64 bits. Hope we can solve it together, I told everyone at my work that this is incredible awesome and we should totally use it, and i stand by it but i need to be able to do this for the demonstration :)

**Comment by techfort** [comment]
Hi Matias,
sorry, the gist is actually a bit outdated, but I didn't have much time earlier to inspect the issue. I'll work on this asap. And don't worry, persistence works just fine, we have plenty apps using loki to persist data so i'm sure we'll get to the bottom of this.

**Comment by MatiasFito** [comment]
Thanks a lot!, I'll help you in anything you need just say the word :).

**Comment by obeliskos** [comment]
I think in your first post you should change your second code sample to look like : 

```javascript
var lokiDatabase = new loki('loki.json');

lokiDatabase.loadDatabase({}, function() {
  console.log(lokiDatabase.getCollection('movies').data);
});
```
first param should be options but you can pass empty object, and then callback because (as Techfort mentioned) is async.

This worked for me in node and node webkit, let me know if that doesn't work in your case.

**Comment by MatiasFito** [comment]
It worked!, as long as I'm inside the callback function i can access all the data retrieved from the data base. Thank you both for your help you can close this issue, but maybe test and really look into it to document this behaviour couse not everybody knows about the "async nature" of node and how it could be affecting this particular scenario. Thanks again!

**Comment by obeliskos** [comment]
Great, yes the node filesystem object provides synchronous and asynchronous methods... loki uses asynchronous versions.  Indexeddb for web users requires async and localstorage is generally synchronous.  To accommodate all persistenceMethods with similar interface we use that callback.

Hopefully we will document this better in the future.  Will close this issue now.
Thanks!
