### ISSUE TITLE
'pre-insert' event not firing or found. 

### ISSUE THREAD

**Issue by wilblack** [techfort/LokiJS#93]
Hi.
I have been using LokiJS for about 3 months now in the browser. The IndexedDB adapter is great. I am having a few problems however. 

In reading the docs for LokiJs you mention a `pre-insert`  and `pre-udate` events. I am trying to use these to insert UUID's into my collection objects when created to no avail. Looking in the code on the master branch these do not appear to exist. Is the documentation out of sync or are they on a different branch.
 
Also what is up with versioning? The docs talk about version 1.1 and 1.2 but I can only see some references to 1.0 and 1.1 in the repo branches and there are no versions in bower (i'm using this in the broswer).

**Comment by techfort** [comment]
Hi,
I'll look into why the events are not fired, and revert as soon as possible. Hopefully it's just a matter of sticking in an emit('pre-insert', obj) before inserting the object. Same for the update.

As for versioning...  yeah - i need to tidy things up a bit on that side. Let me see what i can do in the short term.

**Comment by techfort** [comment]
Hi Wil,

i have applied the `pre-insert

**Comment by techfort** [comment]
hey @wilblack any update on this? Thanks!

**Comment by techfort** [comment]
Closing this.
