### ISSUE TITLE
findOne() return type is not consistent

### ISSUE THREAD

**Issue by miketahani** [techfort/LokiJS#95]
I haven't extensively tested this, but it appears that findOne() returns different types based on the query.

`collection.findOne({'attr1': attr1});` returns the document object.

`collection.findOne({'$and': [{'attr1': attr1}, {'attr2': attr2}]});` returns an array containing the single document object.

The expected behavior is findOne() returning either an array containing the document *or* the document object itself, but not both.

**Comment by techfort** [comment]
Hey Mike, thanks for flagging this. @obeliskos worked a lot on findOne so he might have a good idea of how to resolve this straight away.

**Comment by miketahani** [comment]
I think what's happening is unrelated to the query and instead has to do with indexed/unindexed fields. These are the offending lines, where findOne returns a Resultset array and findOneUnindexed returns a document:

[findOne](https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L3015)
[findOneUnindexed](https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L3050)

I'd submit a pull request but I haven't had a chance to dig through the Resultset internals and it seems wrong to just wrap the returned findOneUnindexed doc in an array.

**Comment by obeliskos** [comment]
Yea could be the new $and and $or paths which I just added didn't consider findone.  I'll take a look at that tonight.

**Comment by obeliskos** [comment]
Thanks for letting me know about this, I think I have fixed it.  Feel free to try out and let me know your results.   

I will try to add some test cases for this over the next week so I don't forget about these paths (findOne with $and $or ops).

**Comment by obeliskos** [comment]
I have added test cases which verify this code path works (and will continue to work)

**Comment by miketahani** [comment]
Thanks!
