### ISSUE TITLE
persistence question/idea

### ISSUE THREAD

**Issue by seriousme** [techfort/LokiJS#98]
hi,

while looking at the persistence code in lokijs.js I noticed some double code.

e.g.
```
  this.fs.readFile(this.filename, {
            encoding: 'utf8'
          }, function readFileCallback(err, data) {
            if (err) {
              return cFun(err, null);
            }
            self.loadJSON(data, options || {});
            cFun(null, data);
          });
```

occurs twice

Would it be an idea to create the default persistenceMethods as adapters inside lokijs.js
And then on init bind an instance of the relevant adapter to the loki instance.

e.g. something along the lines of : https://gist.github.com/seriousme/fb1690a99e8b15ec42a9

Then the persistence methods loadDatabase and saveDatabase could skip all the checks and just call the adapter. You could wrap the adapter call of saveDB in a try/catch and call  this.autosaveClearFlags() based on the outcome ;-)

If you think this is the right direction I'm happy to give the refactoring a try, however it is your project and I'm just a passing by ;-)

Cheers,
Hans

**Comment by techfort** [comment]
Hi Hans,
that sounds good! Yeah there's a bit of cleanup to be done on the entire codebase, so if you notice stuff like code repetition by all means go ahead and refactor.
your encrypted storage piece of work was great, so whenever you have ideas feel free to submit PR's, i don't need further confirmation of your great coding skills :)

**Comment by seriousme** [comment]
Thx for merging the PR.
